### ISSUE TITLE
Micromenu conflict

### ISSUE THREAD

**Issue by mspykerez** [tullamods/Dominos#166]
Hi, Dominos micro menu feature is interfering with this other great addon http://www.wowinterface.com/downloads/info18329-MicroMenu.html making it not show anything! Can this be fixed? Or also allow dominos to put the micromenu on the Titanbar addon.

**Comment by Tuller** [comment]
In the next version, you can do this via lua:
```lua
/run Dominos.db.profile.modules.MenuBar = false
```
