### ISSUE TITLE
Rework the profiles UI

### ISSUE THREAD

**Issue by Tuller** [tullamods/Dominos#174]
Make it easier to understand, and make it easier to find.

**Comment by Tuller** [comment]
The UI is now easier to find (all panels of the main options menu are now in a tabbed interface, so there's no hidden panels to expand anymore).  

Next up: I need to make copying profiles a bit easier to find (maybe, not sure how frequently people do so), and integrate per spec profiles.

**Comment by jcai1** [comment]
Can't this just use AceDBOptions and LibDualSpec?

**Comment by Tuller** [comment]
I don't like the look & feel of the AceDBOptions menu.

**Comment by jcai1** [comment]
bump - please consider adding a way to automatically switch profiles when spec swapping.

**Comment by Tuller** [comment]
Closing, as Dominos uses the ace UI for this now. will remember to create one for spec swaps
