### ISSUE TITLE
Scrollable Quest Tracker

### ISSUE THREAD

**Issue by jgillich** [tullamods/Dominos#184]
I like my UI simple and just cover the bottom of the screen, however the quest tracker behaves really weird when there's not enough screen space. Dominos Quest did have the ability to scroll the Quest Tracker earlier, but [as you said](http://www.curse.com/addons/wow/dominos_quest#c41) Blizzard made some changes in WoD so it doesn't support it anymore.

I would really like to have this again, is there anything I can help with? I don't have any experience with Lua or the WoW API, but learning these things shouldn't be too hard. Since I couldn't find the repository for the Quest addon here on GitHub, would you mind creating one?

**Comment by Goranaws** [comment]
Dominos_Quest is my creation. Tuller, the author of Dominos, allows me to make my own sub-addons to go with Dominos.. 

I plan to restore scrolling soon. I need to go over and learn the new code before I can do so.

**Comment by Goranaws** [comment]
Also, https://github.com/Goranaws/Dominos_Quest

**Comment by jgillich** [comment]
Aww I'm sorry, I somehow assumed all Dominos addons would be in the tullamods org. Anyway, thanks for your work on Dominos_Quest, let me know if I can help in any way!

**Comment by Goranaws** [comment]
I would love any help you can give! I often test my addons on my own.. Any feedback or help with coding would be GREATLY appreciated!
