### ISSUE TITLE
Dominos & Masque

### ISSUE THREAD

**Issue by NickSavior** [tullamods/Dominos#185]
Hello,

There's a bug that causes icons to look different when Masque is installed but it's disabled for Dominos. I made a ticket on Masque's bug tracker, they replied that it's Dominos' code that causes that. More details there: http://www.wowace.com/addons/masque/tickets/156-dominos-masque/

**Comment by Tuller** [comment]
Looks like I need to do the following:
* Detect when a group is disabled or not.  
* Register the Masque callback and update when a group is disabled/enabled

**Comment by Tuller** [comment]
It appears one of my adjustments caused issues:

There seems to be some incompatibility with the latest version of Dominos and Masque.  A couple of the action bars will not show the Masque artwork every time I log into a character.  I have to go into Masque's settings to re-enable the artwork.  It seems to be a problem on Dominos as I installed Bartender as a test and the Masque artwork displays with no issue.

http://www.curse.com/addons/wow/dominos?comment=5837

To clarify Darkhelmet's point:  Dominos' MultiBars are having their "Grid" state set to "disabled" regardless of the settings value in Dominos' options.  With the grid disabled, Masque's "Background" texture is hidden.

http://www.curse.com/addons/wow/dominos?comment=5853

**Comment by Tuller** [comment]
This is now resolved in the 6.2.x branch
