### ISSUE TITLE
[CURSE BETA] Micromenu

### ISSUE THREAD

**Issue by samyonair** [tullamods/Dominos#188]
Hi, have installed your beta version and have Issues with Micromenu if I run it under 6.0.3 no LFG Tools and some other are missing no lua error only if disabling it within config 

3x Dominos\bars\menuBar.lua:172: attempt to index local 'button' (a nil value)
Dominos\bars\menuBar.lua:172: in function `IsMenuButtonDisabled'
Dominos\bars\menuBar.lua:326: in function <Dominos\bars\menuBar.lua:323>
[C]: in function `Show'
Dominos_Config\menu.lua:110: in function `ShowPanel'
Dominos_Config\menu.lua:191: in function `func'
FrameXML\UIDropDownMenu.lua:748: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
self = DominosFrameMenumenuDisable ButtonsSammlungen {
 0 = <userdata>
 Text = DominosFrameMenumenuDisable ButtonsSammlungenText {
 }
}
owner = DominosFramemenu {
 0 = <userdata>
 header = <unnamed> {
 }
 buttons = <table> {
 }
 id = "menu"
 sets = <table> {
 }
 menu = DominosFrameMenumenu {
 }
 activeButtons = <table> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = DominosFrameMenumenuDisable ButtonsSammlungen {
 0 = <userdata>
 Text = DominosFrameMenumenuDisable ButtonsSammlungenText {
 }
}
button = nil

Greetings Samyonair

**Comment by Tuller** [comment]
The beta version of Dominos is meant only to run on the PTR.

**Comment by lunaskyrise** [comment]
6.1.0 has been published on live (wow 6.0.3 via curse client) and it has this bug.

**Comment by Tuller** [comment]
Your curse client is set to use beta versions, which is the issue here

**Comment by samyonair** [comment]
I Know that I’ve set my curse client to alpha version, I use them to find incompatibilities to carbonite (helping there) and to give early feedback if something goes wrong, first time this is an Issue with a patch in working by blizz.

 

Thank you for your help and clarifaction

 

Greetings Samyonair

 

Von: Jason Greer [mailto:notifications@github.com] 
Gesendet: Dienstag, 10. Februar 2015 13:50
An: tullamods/Dominos
Cc: Lars Christian
Betreff: Re: [Dominos] [CURSE BETA] Micromenu (#188)

 

Your curse client is set to use beta versions, which is the issue here
