### ISSUE TITLE
No class bar in 6.1.2

### ISSUE THREAD

**Issue by missakins** [tullamods/Dominos#196]
Hi, I updated to 6.1.2 today and I no longer have a class bar on my druid.

My other PC has a class bar on 6.1.1 though.

**Comment by missakins** [comment]
Reverting to 6.1.1 got it back for me. Must be a beta thing...

**Comment by Tuller** [comment]
I had a feeling something would break, hence the beta tag :)

**Comment by Aingealfire** [comment]
Ran into similar, my bags bar vanished :)
