### ISSUE TITLE
Bags order changed from 6.1.1 to 6.1.4

### ISSUE THREAD

**Issue by b-morgan** [tullamods/Dominos#199]
Can we please have an option to return to the old order (which is the same order as the default Blizzard UI)?

The backpack is the one that moved and changing the options to get the backpack where it used to be messes with the order of the other four bags.

**Comment by Tuller** [comment]
That's actually a bug on my end






On Tue, Mar 3, 2015 at 11:36 AM -0800, "b-morgan" <notifications@github.com> wrote:












Can we please have an option to return to the old order (which is the same order as the default Blizzard UI)?



The backpack is the one that moved and changing the options to get the backpack where it used to be messes with the order of the other four bags.
