### ISSUE TITLE
Doing Darkmoon Faire, accessing the mini-games

### ISSUE THREAD

**Issue by Striding** [tullamods/Dominos#201]
Date: 2015-03-04 12:16:50
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Dominos\bars\menuBar.lua line 133:
   bad argument #1 to 'wipe' (table expected, got nil)
Debug:
   [C]: wipe()
   Dominos\bars\menuBar.lua:133: UpdateOverrideBarButtons()
   Dominos\bars\menuBar.lua:252: FixButtonPositions()
   Dominos\bars\menuBar.lua:248: LayoutOverrideUI()
   Dominos\bars\menuBar.lua:183: Layout()
   Dominos\bars\menuBar.lua:68:
      Dominos\bars\menuBar.lua:66
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

AddOns:
  QuestItemButtonFix, v
  Swatter, v5.0.0 (<%codename%>)
  NPCScan, v6.1.0.2
  NPCScanOverlay, v6.1.0.1
  AchieveIt, v
  AckisRecipeList, v3.0.17
  Altoholic, vr155
  AuraFrames, v1.2.4
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v6.1.4
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  BonusRollPreview, v60000.23-Release
  ButtonFacade, v5.3.394
  Configator, v5.1.DEV.376(/embedded)
  DataStore, vr53
  DataStoreAchievements, vr39
  DataStoreAgenda, vr21
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr31
  DataStoreContainers, vr49
  DataStoreCrafts, vr65
  DataStoreCurrencies, vr28
  DataStoreGarrisons, vr9
  DataStoreInventory, vr42
  DataStoreMails, vr42
  DataStorePets, vr37
  DataStoreQuests, vr34
  DataStoreReputations, vr35
  DataStoreSpells, vr25
  DataStoreStats, vr24
  DataStoreTalents, vr50
  DBMCore, v
  DBMDefaultSkin, v
  DBMDMF, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Dominos, v6.1.6
  DominosEncounter, v
  DominosRoll, v
  ErrorFilter, v2.12
  FixRaidTaint, v0.2
  FlightMap, v6.0.3.0
  FramesResized, v2.6.0-59
  Gatherer, v5.0.0
  GatherMate2, v1.33.5
  GatherNotify, v1.51
  Grail, v068
  GrailAchievements, v011
  GrailReputations, v007
  GrailWhen, v001
  Grid, v6.0.3.1710
  GridSideIndicators, v6.0.0-beta
  GridStatusDungeonRole, v1.2.4
  GridStatusRole, v1.8.4
  HandyNotes, vv1.3.3
  HandyNotesWellRead, v6.1.0.4
  HealersHaveToDie, v2.3.5
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LegacyQuest, vv1.0
  LibExtraTip, v5.12.DEV.363(/embedded)
  LibStrataFix, v1.3.0
  Mapster, v1.6.2
  Masque, v6.1.0
  MasqueCainyx, v4.3.00
  MikScrollingBattleText, v5.7.140
  MogIt, v3.4.0
  NeedToKnow, v4.0.19
  OmniCC, v6.1.0
  Overachiever, v0.82
  Postal, v3.5.4
  QuestGuru, v2.3.10
  SavedInstances, v6.1.1
  SexyMap, v2.4.23
  Skada, v1.4-29
  SlideBar, v5.0.0 (<%codename%>)
  StrataFix, v3.5.0
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TabardAddict, v2.28
  TidyPlates, v6.15.3
  TidyPlatesNeon, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.351(/embedded)
  TipTac, v15.03.04
  TipTacItemRef, v15.03.04
  TipTacTalents, v15.03.04
  Titan, v5.5.3.60100
  TitanBag, v5.5.3.60100
  TitanClock, v5.5.3.60100
  TitanGold, v5.5.3.60100
  TitanPerformance, v5.5.3.60100
  TitanRepair, v5.5.3.60100
  TitanVolume, v5.5.3.60100
  TomTom, vv60000-1.1.1
  TooltipItemIcon, v1.67
  tullaRange, v6.0.4
  Wholly, v050
  XLoot, v6.1-1
  XLootGroup, v6.1-1
  XLootMaster, v6.1-1
  XLootMonitor, v6.1-1
  ZoneLevelInfo, v2.1.2
  ZPerl, vr937
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_ptBR v6.1.0.60100 <none>
  (ck=b20)

**Comment by Tuller** [comment]
I think this is fixed now.

**Comment by Striding** [comment]
Yes it is! Thank you Tuller, that was annoying xD
