### ISSUE TITLE
 "filling" messed up

### ISSUE THREAD

**Issue by Guema** [tullamods/Dominos#205]
Hello, since last version Dominos do not compute "filling" well. in fact, the atempted result is that the bar is supposed to be at the center of the bar filling and leaving the rest as spacing. but since 6.1.8, there is a wried offset and the bar is not at the middle.

Thank you for your work !

**Comment by Tuller** [comment]
Can you provide a screenshot?

**Comment by Guema** [comment]
I will provide a screen tomorrow. (It's 0h00 here). Thanks for this fast answer.

**Comment by Guema** [comment]
I was going to upload a screen but i noticed an update, and updated it.
The new update fixed the bug.

thanks for your amazing addon and work.
Closed
