### ISSUE TITLE
Duplicated bars 

### ISSUE THREAD

**Issue by CapDiva** [tullamods/Dominos#211]
For some reason some of my bars get duplicated in my monk and some others toons.
It's completely random and just make the game annoying to play.
The worst char is my monk, when I change stance, it duplicate 2 out of the 10 action bars, in other words anything i do in bar one will be done in another randon bar 
I did everything I could to make it work (Keybinding/change config/reload the game)

**Comment by Tuller** [comment]
In config mode, you can right click the bar and mess with your paging settings.  Try playing around with those.
