### ISSUE TITLE
No Actionbars (in & out of configmode) + not able to switch profile

### ISSUE THREAD

**Issue by mumsford** [tullamods/Dominos#212]
Hi,

I'm using Dominos on all of my chars except for one.

When i log on to my shaman, dominos will show no actionbars, not even in config mode. Then i tried to change the profile to my main -> nothing happens and the profile is still set on "Shaman" (by default).

When i try to change the profile due to /dominos set default, Dominos wont accept my command.

(Deleting the shaman, and creating a new char with an other name changed nothing. So I'm forced to use Bartender on my Shaman =(

**Comment by Tuller** [comment]
Try running with just dominos + dominos_config and enabling the rest from
there

**Comment by mumsford** [comment]
hey, thank you very much. Sorry for the late answer, but it worked perfectly :+1:
