### ISSUE TITLE
Lua error when reloading UI in certain vehicles

### ISSUE THREAD

**Issue by Radipon** [tullamods/Dominos#213]
This can be reproduced by /reloading while under an override-bar invoking transformation. In particular, I noticed it while doing [Song of Wind and Water](http://www.wowhead.com/quest=12726/song-of-wind-and-water). Steps were tested with no other addons loaded, but whether this occurs in other vehicle ui states is uncertain.

`Message: Interface\FrameXML\RestrictedExecution.lua:397: Call failed: Interface\FrameXML\RestrictedExecution.lua:397: Call failed: Interface\FrameXML\RestrictedExecution.lua:397: Call failed: [string "			local state = message..."]:6: attempt to perform arithmetic on a nil value
Time: 02/04/16 20:15:55
Count: 1
Stack: [C]: ?
Interface\FrameXML\RestrictedExecution.lua:397: in function <Interface\FrameXML\RestrictedExecution.lua:390>
(tail call): ?
(tail call): ?
Interface\FrameXML\SecureHandlers.lua:113: in function <Interface\FrameXML\SecureHandlers.lua:108>
[C]: in function 'SetAttribute'
Interface\AddOns\Dominos\bars\actionBar.lua:248: in function `UpdateOverrideBar'
Interface\AddOns\Dominos\bars\actionBar.lua:238: in function `LoadStateController'
Interface\AddOns\Dominos\bars\actionBar.lua:80: in function `New'
Interface\AddOns\Dominos\bars\actionBar.lua:567: in function `Load'
Interface\AddOns\Dominos\Dominos.lua:117: in function `Load'
Interface\AddOns\Dominos\Dominos.lua:53: in function <Interface\AddOns\Dominos\Dominos.lua:51>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ce\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ce\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:343: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:422: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:923: in function <Interface\FrameXML\UIParent.lua:825>

Locals: (*temporary) = "Call failed: Interface\FrameXML\RestrictedExecution.lua:397: Call failed: Interface\FrameXML\RestrictedExecution.lua:397: Call failed: [string "			local state = message..."]:6: attempt to perform arithmetic on a nil value"
`

**Comment by Tuller** [comment]
Can you try 6.2.9 once it's up?
http://www.wowinterface.com/downloads/info9085-Dominos.html

**Comment by ceylina** [comment]
I just did a test in a siege engine in ulduar

6.2.9 and got the same error. Even checking to use the blizzard override bar doesn't help.


Error attached for reference:

`4x FrameXML\RestrictedExecution.lua:397: Call failed: FrameXML\RestrictedExecution.lua:397: Call failed: FrameXML\RestrictedExecution.lua:397: Call failed: [string "			local state = message..."]:6: attempt to perform arithmetic on a nil value
[C]: ?
FrameXML\RestrictedExecution.lua:397: in function <FrameXML\RestrictedExecution.lua:390>
(tail call): ?
(tail call): ?
FrameXML\SecureHandlers.lua:113: in function <FrameXML\SecureHandlers.lua:108>
[C]: in function `SetAttribute'
Dominos\bars\actionBar.lua:250: in function `UpdateOverrideBar'
Dominos\bars\actionBar.lua:240: in function `LoadStateController'
Dominos\bars\actionBar.lua:80: in function `New'
Dominos\bars\actionBar.lua:569: in function `Load'
Dominos\Dominos-6.2.9.lua:117: in function `Load'
Dominos\Dominos-6.2.9.lua:53: in function <Dominos\Dominos.lua:51>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:343: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:366: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:925: in function <FrameXML\UIParent.lua:825>

Locals:
workingEnv = <userdata>
ctrlHandle = <userdata>
pcallFlag = false
LOCAL_Function_Environment_Manager = <function> defined @FrameXML\RestrictedExecution.lua:209
error = <function> defined =[C]:-1
tostring = <function> defined =[C]:-1`

**Comment by ceylina** [comment]
Pretty sure this is what is causing the conflict or at least the start of a cascade.

self.header:SetAttribute('state-overridebar', isOverrideBar)

Just to test, I commented out the above with the "use blizzard override action bar " check in options and was able to reload. Now I understand this isn't the solutione because if you uncheck that, it does not swap actionbar 1 to the vehicle ui action buttons but thought I would share this. I'm using this change with the option checked until you find a fix so I don't accidentally reload and throw an error.

**Comment by Tuller** [comment]
I bet it probably works better now :P

**Comment by ceylina** [comment]
I may or may not have forgot to mention it is working now oops :o

Much better thanks ;)

**Comment by Tuller** [comment]
Hurray :)
