### ISSUE TITLE
Using action_sets module system with multiple alts of same class causes issue on intial setup...

### ISSUE THREAD

**Issue by ceylina** [tullamods/Dominos#214]
Note: This is with action sets enabled and using a single set profile and only when setting up an alt of a class that already has been setup using the same saved and set profile.

Tried to figure out what was going on but here is what has happened:

Using 6.2.8 (6.2.9 isn't on curse btw)

So I have around 20 alts. Many of the same class. 

I am using a set profile for all alts. When I setup a new alt, I "set" the saved profile".

It worked great until I went to my second alt of the same class. In this case it was a warrior.

When I set up the first warrior, everything went smooth.

When I went to the second warrior and clicked to set the saved profile, All my icons from my bars went to my mouse cursor then rearranged on my bars to try and recreate the settings on my first warrior. Since that first warrior is my bank alt, I had very few abilities and items on bars. 

so pretty much everything got wiped out on my second warrior.

I figured this was a fluke until I went on my second monk. Same issue. The first monk setup just fine but the second one went bonkers again and everything went to the mouse cursor (as in how you move icons off or around bars) and tried to recreate my first monk's bar.

So there is a bug in the profile system that when you have multiple alts (mine are mostly across two connected realms) of the same class and use one set profile for everyone, it will try and rearrange everything on the action bars to recreate that first alt's bar settings. By settings I mean spells, ability,etc icons.

Now the good thing Is once you go back and reset all the icon placement on bars it stays put and doesn't readjust when swapping alts but that first setup freaked me out.

It's rather troublesome and I wonder if it is something that can be sorted out so you don't have to fumble with layout profiles?

**Comment by ceylina** [comment]
Perhaps instead of defaulting to the class such as WARRIOR, you default to the character name-server? This would prevent maybe the issue with the class name saving spell icon locations and going crazy on the second alt of the same class when using a single set custom named profile across all alts.

**Comment by Tuller** [comment]
Yep, that's a reasonable change.  I didn't think of the scenario of a user playing many of the same class when I setup the defaults for action sets.

**Comment by Tuller** [comment]
The latest commit to ActionSets should fix this:
https://github.com/tullamods/Dominos_ActionSets/commit/997ec1379077b251a5fdf00a998e9ccdeb1d59c0
