### ISSUE TITLE
Possible to add in ability to hide hotkey name and macro text per bar?

### ISSUE THREAD

**Issue by ceylina** [tullamods/Dominos#215]
Would you be interested in adding the option to hide the name (i.e.hotkey) and macro text on a per bar basis? It would add a ton of cosmetic appeal I believe to the UI allowing the ability to hide say pet hotkey names instead of removing the hotkey assignment itself.

I've added this in myself but it's not efficient enough to post here as it is pretty much static assignments and doesn't have interface setting support or profile support

Perhaps in the advanced bar settings in configuration mode you can add a check for hide hotkey and hide macro text?

**Comment by Tuller** [comment]
Yes. I need to make a milestone and start adding features for dominos 7.0
