### ISSUE TITLE
[Legion] Faded Opacity error

### ISSUE THREAD

**Issue by kaedys** [tullamods/Dominos#216]
When a menu bar is set to have a faded opacity less than 100, mousing over the bar triggers an error:

```
Date: 2016-05-15 18:27:02
ID: 9
Error occured in: Global
Count: 1
Message: ..\AddOns\Dominos\core\frame.lua line 396:
   attempt to call method 'SetChange' (a nil value)
Debug:
   Dominos\core\frame.lua:396: ?()
   Dominos\core\frame.lua:420: Fade()
   Dominos\core\fadeManager.lua:16: Update()
   Dominos\core\fadeManager.lua:35:
      Dominos\core\fadeManager.lua:33
Locals:
targetAlpha = 1
duration = 0.1
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 1
(*temporary) = "attempt to call method 'SetChange' (a nil value)"
fadeGroup = <unnamed> {
 0 = <userdata>
 targetAlpha = 1
}
parent = DominosFramebags {
 0 = <userdata>
 header = <unnamed> {
 }
 buttons = <table> {
 }
 id = "bags"
 sets = <table> {
 }
 focused = true
 docked = <table> {
 }
}
fade = <unnamed> {
 0 = <userdata>
}

AddOns:
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  AutoVendor, v29
  DejaCharacterStats, v7.0.3 b1
  Dominos, v6.2.8
  DominosActionSets, v
  DominosEncounter, v
  DominosXP, v
  Prat30, v3.6.8      
  Prat30Libraries, v
  Quartz, v3.2.7
  Skada, v1.4-33
  SkadaAvoidanceMitigation, v1.3.3
  SkadaPlayerScore, v1.04
  TellMeWhen, v8.0.0
  TellMeWhenOptions, v
  TipTac, v15.12.07
  TipTacExtraTip, v1.0
  TipTacItemRef, v15.12.07
  TipTacTalents, v15.07.02
  WeakAuras, v2.1.0.26
  WowLua, vv60200-1.0.0 
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=221)
```

In addition, the bar in question is invisible (though still interactable) both before and after this error.  If one opens that bar's options and changes the faded opacity (to any other value), the bar becomes visible, but is locked at 100% opacity.  Previous behavior (invisible, error on mouseover) occurs after a reload.

**Comment by kaedys** [comment]
Note that this may in fact be two separate issues.  The behavior where it is invisible until the faded opacity is adjusted, and then is locked at full opacity, I've only observed on my menu bar and my bag icon (which I customarily keep at 0% faded and 100% mouseover).  However, on investigation, they seem to exhibit the same behavior even when set at 100% faded.

The error I listed occurs when any of my bars that is set to sub-100% faded is moused over, but these other bars do not exhibit the invisible behavior (they do not adjust to 100% opacity when moused over, either, however).

**Comment by Tuller** [comment]
They removed that bit of the API in legion, hurray :)

**Comment by Tuller** [comment]
The latest beta version should fix this:
http://www.wowinterface.com/downloads/info19110-DominosBeta.html

**Comment by kaedys** [comment]
Seems to be fixed.
