### ISSUE TITLE
Legion beta - Dominos Cast

### ISSUE THREAD

**Issue by bessiq** [tullamods/Dominos#217]
Originally posted this on Curse before I saw your request to post bugs to github. Anyway, getting a repeating error when Dominos Cast is enabled (along with Dominos' other modules - not including non-Tuller modules like Dominos Quest). This occurred with and without other addons enabled.

> 1627x Dominos_Cast\castBar.lua:164: attempt to index field 'border' (a nil value)
> Dominos_Cast\castBar.lua:164: in function <Dominos_Cast\castBar.lua:147>
> 
> Locals:
> self = DominosFramecast {
>  0 = <userdata>
>  header = <unnamed> {
>  }
>  heightAdjust = 80
>  id = "cast"
>  sets = <table> {
>  }
>  time = <unnamed> {
>  }
>  widthAdjust = 280
> }
> elapsed = 0.010000000707805
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = ""
> (*temporary) = <userdata>
> (*temporary) = <userdata>
> (*temporary) = "attempt to index field 'border' (a nil value)"
>

**Comment by Tuller** [comment]
Yay :)
I'll try and start working on this stuff during the weekend.

**Comment by Tuller** [comment]
The latest beta version fixes this in that I've stripped down the cast bar to simply move around the default one.

**Comment by bessiq** [comment]
Great! Can't wait to try it. I presume you intend to wrangle that new Artifact Power bar at some point, too? Thanks for everything!

**Comment by MetalHeadSix** [comment]
Just tried the update, still getting massive cast bar errors, over 400 in a few seconds.  I'm also wondering about the new Artifact Power bar.

462x Dominos_Cast\castBar.lua:164: attempt to index field 'border' (a nil value)
Dominos_Cast\castBar.lua:164: in function <Dominos_Cast\castBar.lua:147>

Locals:
self = DominosFramecast {
 0 = <userdata>
 header = <unnamed> {
 }
 heightAdjust = 80
 id = "cast"
 sets = <table> {
 }
 time = <unnamed> {
 }
 widthAdjust = 280
}
elapsed = 0.010000000707805
(*temporary) = nil
(*temporary) = nil
(*temporary) = ""
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = "attempt to index field 'border' (a nil value)"

**Comment by bessiq** [comment]
MetalHeadSix, I'm not sure the legion branch on here is complete yet, but I'm sure Tuller is working on it when he can. The version on Curse/Curseforge is still from last year. It works if you disable the Dominos Cast module, but since Dominos doesn't affect the artifact power bar yet, I'm still using Bartender4 for the beta at the moment. Not really fond of how it tries (and kinda fails) to snap/anchor the bars together though.

**Comment by Tuller** [comment]
Curse will be updated probably on the weekend assuming they support the Legion TOC now.  It will be posted as an alpha, though, because too many people auto update to beta versions there :P
