### ISSUE TITLE
Dominos Beta 7.0.4 - Dominos Progress issue

### ISSUE THREAD

**Issue by bessiq** [tullamods/Dominos#218]
Hi Tuller,

On my two characters that have an artifact (both demon hunters), when I click the XP bar to toggle to the Artifact/Rep bars the beta client freezes (Windows says WoW is not responding and I have to close the program). On my characters without an artifact, the XP bar switches normally. I don't have an Honor bar yet as I haven't done any PvP, fwiw.

Tested with only Dominos enabled (deleted Dominos XP module - was disabled anyway). Using non-Blizzard bar texture (Armory), Always Show Text enabled, Segmented disabled. BugSack reports no errors after logging back in after client crash. Non-artifact character (that didn't crash) was in WoD garrison, and demon hunters were in new Dalaran or class hall.

Going to get the artifact for another class just to determine it's not a class-specific bug, which I kinda doubt? Let me know if you want me to provide any further info.

**Comment by Tuller** [comment]
There's probably an infinite loop in there.  My fault for not trying on my person with an artifact :P

**Comment by Tuller** [comment]
7.0.5 should fix this.
