### ISSUE TITLE
Config - Show States updating

### ISSUE THREAD

**Issue by johnsolver** [tullamods/Dominos#222]
Removing [combat]show;hide from Show States, doesn't show the bar until a ui-reload

**Comment by Tuller** [comment]
The expected behavior is that the new setting will apply if you press enter, or if the textbox loses focus.  If I implement a debounce thing, then it'll also auto update when typing.

**Comment by Tuller** [comment]
I've implemented auto updates while you type in 7.0.9.

**Comment by johnsolver** [comment]
Seems like the 'save' part doesn't trigger the bar reload if there is no text in the box, eg. start with setting the show states to '[combat]show;hide' => the bar disappears change the states by deleting the text => the bar isn't updated until a ui reload

**Comment by Tuller** [comment]
This will be fixed in the next release.
