### ISSUE TITLE
Dominos_Progress - reputation bar not updating

### ISSUE THREAD

**Issue by funkjedi** [tullamods/Dominos#227]
Noticed this while rep farming in Lost City of the Tol'vir. None of the rep gains were being reflected until exiting the instance.

The problem seems to stem from the fact that the `UPDATE_FACTION` event isn't sending a value for the unit param it's just `nil`. Commenting out the unit check in the event handler fixes the problem.

```lua
function ProgressBarModule:UPDATE_FACTION(event, unit)
	--if unit ~= 'player' then return end

	self:UpdateAllBars()
end
```

**Comment by Tuller** [comment]
This will be fixed in 7.0.9, thank you.
