### ISSUE TITLE
Exp/Artifact Bar Resize ?

### ISSUE THREAD

**Issue by Amy892** [tullamods/Dominos#230]
Can we resize these bars in the futur ?
Thanks !

**Comment by Tuller** [comment]
![menu](https://cloud.githubusercontent.com/assets/191239/17080134/8c738180-50f2-11e6-9f9d-cb7b51b10fae.png)
Its already there.

**Comment by Amy892** [comment]
What...but all I have is this !
![sans titre](https://cloud.githubusercontent.com/assets/20616796/17083841/b1328dd0-51ac-11e6-9ff5-13d5c0843e1a.png)

**Comment by Tuller** [comment]
This looks like a translation error. It turns out that I should have Disposition as the localized version of Layout instead of what it currently is (feel free to suggest something better).  Will be fixed in 7.0.10
