### ISSUE TITLE
Action bar paging not working as intended

### ISSUE THREAD

**Issue by Tarkumi** [tullamods/Dominos#235]
Since the last version the paging of Action Bar 1 not working with SHIFT+up/down arrow or SHIFT+mousewheel. It only switches between Action page 1 and Action page 2. If I use SHIFT+number the paging is working as intended.

**Comment by Tuller** [comment]
Do you have the extra action bars  enabled on the Blizzard side of interface options?  That can sometimes limit the paging pool.

**Comment by Tarkumi** [comment]
You are right, thank you. Somehow the right actionbars are turned on.
