### ISSUE TITLE
New spells do not display on the vehicle's action bar

### ISSUE THREAD

**Issue by Zireael-N** [tullamods/Dominos#238]
There's a scenario in Legion where you get to play as a different character, but the thing is, you don't have all the spells since the start of the scenario, you get them as you progress through the scenario. I am using Dominos on Beta, and the new spells do not show up on the progress bar until I reset my profile or do a /reload. This is only a visual bug, because these spells do get used when I press keybinds of slots where they are supposed to be. Just to clarify, resetting a profile or doing a /reload only shows spells that you had at that moment; if you get more spells, you have to do that again.

**Comment by Tuller** [comment]
Does this happen if you are using the override action bar too?

**Comment by Zireael-N** [comment]
It's a bit hard to reproduce because I've already completed that scenario and can't recall anything else with a similar mechanic.

**Comment by Zireael-N** [comment]
@Tuller since Legion is live now, I got to do the scenario once again. This does not happen with "Use Blizzard Override Action Bar" toggled on. I left the scenario without completing it this time, so I am up to test any code changes if it's needed.
