### ISSUE TITLE
Error on clicking reputation/exp bar

### ISSUE THREAD

**Issue by ShaunDreclin** [tullamods/Dominos#239]
So clicking on my reputation bar to convert it to an exp bar (on a max level toon if it matters) gives the following error:

Message: Interface\AddOns\Dominos_Progress\progressBar.lua:139: bad argument #1 to 'format' (string expected, got nil)
Time: 08/10/16 22:34:23
Count: 1
Stack: [C]: in function `format'
Interface\AddOns\Dominos_Progress\progressBar.lua:139: in function `UpdateText'
Interface\AddOns\Dominos_Progress\honorBar.lua:17: in function `Update'
Interface\AddOns\Dominos_Progress\honorBar.lua:8: in function `Init'
Interface\AddOns\Dominos_Progress\progressBar.lua:167: in function `OnModeChanged'
Interface\AddOns\Dominos_Progress\progressBar.lua:155: in function `SetMode'
Interface\AddOns\Dominos_Progress\progressBar.lua:210: in function `NextMode'
Interface\AddOns\Dominos_Progress\progressBar.lua:97: in function `OnClick'
Interface\AddOns\Dominos_Progress\progressBar.lua:43: in function <Interface\AddOns\Dominos_Progress\progressBar.lua:43>

Locals: (*temporary) = "(%s)"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Tuller** [comment]
This is fixed in 7.0.13
