### ISSUE TITLE
error with menubar

### ISSUE THREAD

**Issue by Ravenslair38** [tullamods/Dominos#240]
3x CollectionsMicroButton:SetPoint(): EJMicroButton is dependent on this

[C](?): in function `SetPoint'
Dominos\bars\menuBar.lua:240: in function`FixButtonPositions'
Dominos\bars\menuBar.lua:222: in function `LayoutPetBattle'
Dominos\bars\menuBar.lua:201: in function`Layout'
Dominos\bars\menuBar.lua:80: in function <Dominos\bars\menuBar.lua:78>

Locals:
(_temporary) = CollectionsMicroButton {
 0 = <userdata>
 MAParent = MicroButtonsMover {
 }
 newbieText = "View all the mounts and pets you have. Also allows you to manage your pets' abilities if you are a Pet Trainer."
 MAScaled = 1
 Flash = CollectionsMicroButtonFlash {
 }
 MAPoint = <table> {
 }
 MALockPointHook = true
 tooltipText = "Collections"
 SetPoint = <function> defined =[C](?):-1
 EvaluateAlertVisibility = <function> defined @FrameXML\MainMenuBarMicroButtons.lua:494
}
(_temporary) = "BOTTOMLEFT"
(_temporary) = EJMicroButton {
 0 = <userdata>
 MAParent = MicroButtonsMover {
 }
 EvaluateAlertVisibility = <function> defined @FrameXML\MainMenuBarMicroButtons.lua:560
 MAScaled = 1
 Flash = EJMicroButtonFlash {
 }
 MAPoint = <table> {
 }
 MALockPointHook = true
 tooltipText = "Adventure Guide |cffffd200(SHIFT-J)|r"
 newbieText = "View information about Cataclysm dungeon and raid bosses, including their abilities and treasure."
 playerEntered = true
 varsLoaded = true
 SetPoint = <function> defined =[C](?):-1
 NewAdventureNotice = <unnamed> {
 }
}
(_temporary) = "BOTTOMRIGHT"
(_temporary) = -1
(_temporary) = 0

**Comment by Tuller** [comment]
So, from the bug report you're using something called MicroButtonsMover?  I think that's the culprit here.
