### ISSUE TITLE
Show states and mouseover opacity

### ISSUE THREAD

**Issue by ceylina** [tullamods/Dominos#242]
So someone asked on the wow forums how to do combat opacity and mouseover opacity. Now you have in layout a opacity and faded opacity for mousing over. The issue comes when you add a show state, especially for combat.

Here is an example

Images:

![wowscrnshot_081216_160244](https://cloud.githubusercontent.com/assets/9342192/17637010/5da84bf6-60a6-11e6-9b7d-191608430c1a.jpg)

Action bar 1, I set the advanced, Show states to 

[combat]75;25

Now I got and everything is fine. In combat it shows 75% and out of combat it shows 25% alpha( opacity)

So now I want to also have it show 50% when I mouseover out of combat so here is what I need to do to get that going (more issues after this explanation)

In order to set a mouseover opacity I must now set Faded Opacity to any value other than 100 and when I do I can set opacity to a value such as 50 so that I can now mouseover.

Of course now I have the added issue of when I am in combat the bar is 75% opacity unless I mouseover then it is now that 50% opacity. Not a terrible issue because I did after all ask to have the opacity on mouse over to 50%. I can solve this by setting the combat opacity and slider for opacity to the same value.

So do we need to ask to have opacity overridden and faded opacity overridden if a show state entry is placed in advanced? If that is the case we need the ability to have multiple show state entries much like what bartender allows (sorry to name drop them but it is an example of a possible layout for show states)

One more thing and this is a minor bug. If you have a masque set for dominoes (masque addon that is) and it has a gloss setting (sets the gloss of the skin to an opacity), actionbars will override that masque gloss opacity unless set to 0%

See image for what I mean by gloss settings. For some reason dominos is overwriting the masque setting

![wowscrnshot_081216_160136](https://cloud.githubusercontent.com/assets/9342192/17637015/645d1c4c-60a6-11e6-88ad-1f86a973a028.jpg)

**Comment by Tuller** [comment]
I think what you want to do for the first thing is:
[combat]75:show
And an opacity of 50% and a faded opacity of 50%.  That'll make the bar 75% in combat, 50% ooc when hovering over the bar, and 25% otherwise.

**Comment by ceylina** [comment]
Ah so set combat as an opacity in a show state then just show OOC and let the layout handle it. Seems counter intuitive to what most people are used to but it sort of makes sense in an efficient sort of way.

There still is the issue with opacity being overwritten on masque. BTW, I am using this skin

https://mods.curse.com/addons/wow/masque_caith

**Comment by ceylina** [comment]
Ok just tested it and it does not work that way.

It's also very confusing to sort it out trying to use it that way.

[combat]75:show

This does diminish it to 75% in combat but it doesn't then allow opacity or faded opacity to do anything out of combat. Setting show out of combat sets it to opacity of 100%

So basically the only way to get the sliders to work is as I described initially, which seems counter intuitive to what people are used to.


Also it should be [combat]75;show should it not?

**Comment by Tuller** [comment]
I've been testing with [mod]75;show (yes, its ; and not : ).  How it is meant to work is that if you specify a number, then the bar is shown with that opacity when the condition is met, show will just show the bar, using whatever opacity it should normally have, and hide will hide the bar completely.  

I'm debating adding another syntax, [combat]75:25; which would allow overriding both normal and faded opacity values.

For the Masque thing, please create a separate issue.  Its not actually anything that I'm doing, since blizzard code handles button display for the most part.  I just tell masque that the buttons exist.

**Comment by Tuller** [comment]
One bug is fixed in 7.0.13:
Showstate opacity now always takes precedence over mouseover opacity.

**Comment by ceylina** [comment]
So just simply to confirm... You can not have a combat show state (say combat hide or 0)  to hide or "fade" the bars and mouseover opacity at the same time (while in combat)? That's ok if that is the proper limitation

So for example, I set a show state of [combat]10;show and in layout have the opacity of 75 and faded opacity of 45 it will now work out of combat to mouseover and change opacity but in combat it will fade to 10% and not allow mouseover opacity changing. That's a good thing, I just want to know for sure ;)

**Comment by Tuller** [comment]
Yes, if you do [combat]10;show, the bar should stay at only 10% opacity in combat, and use the normal opacity/faded opacity settings outside of combat.

**Comment by ceylina** [comment]
Works for me. Oh and I would consider this one fixed.
