### ISSUE TITLE
Masque opacity changing to 100% when show state condition is added to actionbar

### ISSUE THREAD

**Issue by ceylina** [tullamods/Dominos#243]
Forked off from issue #242 so this is more of an FYI then an "OMG please fix". This is when a state conditional is set to an opacity below 100% (not show/hide) and that state triggers

If you have a masque set for dominoes (masque addon that is) and it has a gloss setting (sets the gloss of the skin to an opacity), actionbars will override that masque gloss opacity unless set to 0%

See image for what I mean by gloss settings. For some reason dominos is overwriting the masque setting

The skin I am seeing the issue on is 

https://mods.curse.com/addons/wow/masque_caith

![645d1c4c-60a6-11e6-88ad-1f86a973a028](https://cloud.githubusercontent.com/assets/9342192/17646247/5d688084-6187-11e6-82b9-887b9eb70b32.jpg)

**Comment by ceylina** [comment]
Playing with this post 7.0.13 fixes I find that it only messes up on the "Gloss Settings" in masque when I have a show state for out of combat set to a percent opacity.

If I have a show state of [combat]75;show for example and have the opacity and faded opacity sliders set then nothing goes wrong but should I set he show state out of combat to like [combat] 70;40, have the sliders at 100 (they are overridden by the show state anyway in this case) and have the gloss setting in masque to anything above 0%, it then goes to 100%

**Comment by Tuller** [comment]
This is probably fixed with masque and dominos updates
