### ISSUE TITLE
When Dominos active, keybind text is missing on the vehicle action bar

### ISSUE THREAD

**Issue by charleslaine** [tullamods/Dominos#244]
I noticed this when both using the SELFIE camera as well as when operating a vehicle during one of the Legion invasion events.  Whenever the normal action bars are replaced by the vehicle action bar, the key bind text is missing.  I  disable Dominos and reload, and the text is visible.  Whenever I reenable Dominos the text is missing again.  So it defintely seems like its something to do with Dominos.

**Comment by Tuller** [comment]
Four years later I verified this is no longer happening
