### ISSUE TITLE
CharacterMicroButton:Hide()

### ISSUE THREAD

**Issue by laric** [tullamods/Dominos#247]
Getting this on my rogue all the ttime.

19x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'CharacterMicroButton:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Hide'
Dominos\bars\menuBar.lua:211: in function`LayoutNormal'
Dominos\bars\menuBar.lua:205: in function `Layout'
Dominos\bars\menuBar.lua:80: in function <Dominos\bars\menuBar.lua:78>

Locals:

**Comment by Tuller** [comment]
Do you have the full trace?

**Comment by laric** [comment]
Soory that is all I am getting in bruggrabber/bugsack.. is there a way to get more information for you then I will gadly assist

**Comment by Tuller** [comment]
Well, roughly i think its due to another addon, can you try with just Dominos + Dominos_Config?
