### ISSUE TITLE
The new custom cast bar fading randomly

### ISSUE THREAD

**Issue by Guema** [tullamods/Dominos#249]
Hi,
Im just here to report a big bug about the new castbar.
At the moment, while casting a spell and seeing progress bar, if you try to cast an other spell who fails (because you cannot cast this spell while casting an other for exemple) the casting bar show a "Failed" indicator, and fade as the spell was cancelled, but in facts, the only spell that failed is the one you cannot launch during casting, not the one already beeing cast. this result in finishing the cast without the castbar showed.

This is a pretty big bug.

I think you should check if the failed spell event or something like this is the same that the one being cast. But i don't exactly know how Wow Api works.

So, i hope i am understandable as im french. (My english sucks, i agree)

Thanks for this wonderful addon

**Comment by Guema** [comment]
Info : 
This bug happend only when the second spell is not available (on Cooldown)

How to reproduce :

- Cast a non-instant spell.
- While casting, try to use a spell that is not available (on cooldown or on global cooldown)

=> Bug : the castbar fade, even if the spell is still being casted.

**Comment by Tuller** [comment]
Hurray for reproducible steps!  This will be fixed in the next release.

**Comment by Guema** [comment]
fast and efficient fix, well done, gg and thanks ^^
