### ISSUE TITLE
Configured textures are not applied

### ISSUE THREAD

**Issue by ckaotik** [tullamods/Dominos#250]
When choosing a texture for supported bars (e.g. Cast, XP, ArtifactXP), the texture is reset to the default Blizzard one on `/reload`. I'm using Dominos 7.0.18 and LibSharedMedia, but am unsure if this also happens without.

![cast_texture](https://cloud.githubusercontent.com/assets/151904/18157114/b0779970-701b-11e6-8c3d-7aa6df215afe.png)

**Comment by Tuller** [comment]
I bet this is a case of the texture being registered sometime after the castbar was created.

**Comment by Tuller** [comment]
This should be fixed in 7.0.19
