### ISSUE TITLE
Artifact xp bar doesn't recognize talent specc change

### ISSUE THREAD

**Issue by enkol** [tullamods/Dominos#251]
If you switch talent specc, i.e. from marksman to beastmaster, your artifact weapon gets automatiaclly swapped, but the artifact expierience bar still shows the rank+xp of the previously equipped one.

Dominos 7.0.18, german language client

**Comment by Tuller** [comment]
This should be fixed in 7.0.19 (I hope)

**Comment by enkol** [comment]
Yes, seems fixed for me with 7.0.19. Thanks for the quick fix!
