### ISSUE TITLE
Possible taint with OverrideActionBar?

### ISSUE THREAD

**Issue by ceylina** [tullamods/Dominos#255]
In the world quest where you go back to the war of the ancients and you get an OverrideActionBar, i got this error. The thing is the addon that got the taint has nothing to do with actionbars at all so it leads me back to here.

1x [ADDON_ACTION_BLOCKED] AddOn 'ColorPickerPlus' tried to call the protected function 'OverrideActionBar:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\ActionBarController.lua:164: in function`BeginActionBarTransition'
FrameXML\ActionBarController.lua:179: in function `ValidateActionBarTransition'
FrameXML\ActionBarController.lua:142: in function`ActionBarController_UpdateAll'
FrameXML\ActionBarController.lua:64: in function <FrameXML\ActionBarController.lua:53>

Locals:

Not sure at all if this started from taint with dominos or if there is some poor coding on Blizzard's end but just wanted to put this here just in case.

**Comment by Tuller** [comment]
The only real way to tell would be to disable everything not Dominos and do the quest.

**Comment by ceylina** [comment]
If I get it again I sure will.

If I remember I can even up my taint log and see if it finds anything.

**Comment by ceylina** [comment]
So got this again doing another world quest. Not even sure what to say about it, something in legion has messed things up

**Comment by Tuller** [comment]
I think that this was fixed via my override bar changes for 8.1
