### ISSUE TITLE
Multiple charges button not grayed out when not at max charges

### ISSUE THREAD

**Issue by johnsolver** [tullamods/Dominos#261]
Not sure if this is a dominos issue but buttons with multiple charge abilities when on cooldown previously were grayed out, with 7.1 they no longer are unless all the charges are depleted.

**Comment by Tuller** [comment]
I believe this is a blizzard adjustment.

**Comment by johnsolver** [comment]
I wonder if this can be modified, perhaps in omni or tullacc
