### ISSUE TITLE
Spell cooldown vanishes on hover

### ISSUE THREAD

**Issue by ckaotik** [tullamods/Dominos#262]
I've set my bars to fade when not in combat/not hovered (`opacity = 100`, `Faded Opacity = 50`, `Show States = "[combat]100;show"`). When hovering an item with an active cooldown, the cooldown disappears and only re-appears randomly. 
Caused me to fall to my death, because I thought the glider was available :(

Illustrated in the following gif:
![cooldown-vanishes](https://cloud.githubusercontent.com/assets/151904/19810589/5bef7b08-9d2e-11e6-9d2c-20417a98dc5d.gif)

**Comment by Tuller** [comment]
I think I fixed this (in tullaCC)

**Comment by ckaotik** [comment]
The update to tullaCC fixed this issue, thanks!

I've been using tullaCC since forever without problems and totally forgot I was using it. Love your addons :)
