### ISSUE TITLE
Bars 7-10 are exact duplicates of druid form main bars

### ISSUE THREAD

**Issue by nohre** [tullamods/Dominos#264]
Action Bars 7-10 are duplicates of the 'Action Bar 1' of different forms. Dragging an ability off of Action Bar 7 will result in the exact same change in the 'Action Bar 1' of cat form.  Removing or adding an ability from Action Bar 1 of cat form has the same effect on Action Bar 7, etc.

Each Action Bar from 7-10 is a duplicate corresponding to the Action Bar 1 of a different form:
Cat - Action Bar 7
Tree - Action Bar 8
Bear - Action Bar 9
Moonkin - Action Bar 10

Most testing was done as a level 110 resto druid acquiring Moonkin form from the level 45 talent Balance Affinity, and acquiring Tree form from the level 75 talent.  Balance spec also shares a duplicate of Action Bar 1 and Action Bar 10, so I suspect that this problem presents on the same bars regardless of specialization. 

Edit: While Restoration spec and selecting Balance affinity, the Tree of Life form uses the stanceless (humanoid/caster form) Action Bar 1 instead of a duplicate of Action Bar 8. A duplicate of Action bar 8 is used for Tree form if Feral Affinity or Guardian Affinity is being used.

**Comment by Tuller** [comment]
So, this isn't actually a bug.  What you're experiencing is bar mirroring, and you can mess with the settings for it via the action bar's right click menu under paging settings.

**Comment by nohre** [comment]
Thanks for taking the time to reply!  I played around with the paging section of the action bars and was not able to find a way to free up any of the bars from mirroring.   My default settings for the druid stances were all 'Disable' to begin with.  I did not see anything regarding 'mirroring' specifically.  Altering the paging settings seemed to only change which bars are mirrors for each other.  Is there a single option to disable bar mirroring altogether?

**Comment by Tuller** [comment]
Are you looking at action bar 1?

**Comment by nohre** [comment]
Some, or perhaps most of the time, the mirrored substitutions were made on action bar one.  But, in a few cases, when I messed with the paging settings, the action bars 7-10? mirrored on action bars other than number 1.  My ultimate goal is to have 6 or more action bars that are truly unique, but I haven't been able to find a a way to achieve that.
