### ISSUE TITLE
When using Masque with 'Pushed' color set, the color stays after the button is released

### ISSUE THREAD

**Issue by bady92** [tullamods/Dominos#267]
Hi there, so I've fount this issue with Dominos and Masque that when you set 'Pushed' color in Maque and then use the ability that has the AoE circle via the mouse scroll it stays 'pushed' all the time untill you click on that button. It has been reported here https://github.com/StormFX/Masque/issues/9

Steps to replicate:
Bind a wheelDown or wheelUp to a button
Put spell with AoE circle targeting on that button
Use the bind

**Comment by bady92** [comment]
Okay so apparently this only happens on DominosFrame2 and doesn't matter if the spell has AoE targetting or not

**Comment by Tuller** [comment]
I be its due to bar 2 being comprised of buttons Dominos has generated itself, and not the standard action bar ones.  Do you experience similar behavior on bar 7, but not on bar 3?

**Comment by bady92** [comment]
I can repro it on bars 2 and 7-10, it works just fine on all the other ones
