### ISSUE TITLE
Dominos tried to call protected function ReportPlayerIsPVPAFK()

### ISSUE THREAD

**Issue by Sipollo** [tullamods/Dominos#268]
In combat I right clicked on a player portrait & selected "Report Player Away" in a battleground.

Got the following LUA error as a result:

`[ADDON_ACTION_FORBIDDEN] AddOn 'Dominos' tried to call the protected function 'ReportPlayerIsPVPAFK()'.`

**Comment by Tuller** [comment]
Does that occur with just Dominos loaded?

**Comment by Sipollo** [comment]
This is odd; tried to re-create the bug and couldn't - either with only Dominos loaded or with all of my usual addons I was running previously. Guess it could've been something about the BG I was in?

Occured in Eye of the Storm I seem to recall.

**Comment by Tuller** [comment]
Likely, this was a misreport due to another addon tainting things that only Blizzard code is allowed to call.
