### ISSUE TITLE
dom_config fails to load after several(many) UI reloads

### ISSUE THREAD

**Issue by Goranaws** [tullamods/Dominos#272]
been working on the arced layout code, and dom_config stops loading after a while. Not sure what's causing it. no errors, right clicking just starts hiding bars instead of bringing up the menu.

**Comment by Tuller** [comment]
Well, shift + rightclick normally does that, maybe a key is getting stuck?

**Comment by Goranaws** [comment]
No keys are stuck. Running a brand new Razer Blade Pro laptop. only fix is to logout and log back in. Not a big issue, nobody else is likely to reload the UI as often as you or I.

**Comment by Goranaws** [comment]
Turns out that this is an issue with Windows 10 "task view". I uhave task view bound to my middle mouse button, to quickly swap between wow and my Lua editor.. so not sure what's going on, but it's not an issue with the add-on.
