### ISSUE TITLE
Bugs / LUA errors seen on 7.2 PTR

### ISSUE THREAD

**Issue by Sipollo** [tullamods/Dominos#273]
Poking the 7.2 PTR I've seen a couple of issues.

The system menu bar - with the character, talents, social, etc buttons - is missing. Likely related to the following LUA error:

27x Dominos\bars\menuBar.lua:211: attempt to index field '?' (a nil value)
Dominos\bars\menuBar.lua:211: in function `LayoutNormal'
Dominos\bars\menuBar.lua:205: in function `Layout'
Dominos\bars\menuBar.lua:80: in function <Dominos\bars\menuBar.lua:78>

Locals:
self = DominosFramemenu {
 0 = <userdata>
 header = <unnamed> {
 }
 buttons = <table> {
 }
 id = "menu"
 activeButtons = <table> {
 }
 overrideButtons = <table> {
 }
 sets = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "CharacterMicroButton"
 2 = "SpellbookMicroButton"
 3 = "TalentMicroButton"
 4 = "AchievementMicroButton"
 5 = "QuestLogMicroButton"
 6 = "GuildMicroButton"
 7 = "LFDMicroButton"
 8 = "EJMicroButton"
 9 = "CollectionsMicroButton"
 10 = "StoreMicroButton"
 11 = "HelpMicroButton"
 12 = "MainMenuMicroButton"
}
(for control) = 11
_ = 11
name = "HelpMicroButton"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
pairs = <function> defined =[C]:-1
MICRO_BUTTONS = <table> {
 1 = "CharacterMicroButton"
 2 = "SpellbookMicroButton"
 3 = "TalentMicroButton"
 4 = "AchievementMicroButton"
 5 = "QuestLogMicroButton"
 6 = "GuildMicroButton"
 7 = "LFDMicroButton"
 8 = "EJMicroButton"
 9 = "CollectionsMicroButton"
 10 = "StoreMicroButton"
 11 = "HelpMicroButton"
 12 = "MainMenuMicroButton"
}

Also seeing the following LUA error:

5x Dominos_Progress\artifactBar.lua:30: Usage: local cost = C_ArtifactUI.GetCostForPointAtRank(rank, tier)
[C]: ?
Dominos_Progress\artifactBar.lua:30: in function `Update'
Dominos_Progress\main.lua:52: in function `UpdateAllBars'
Dominos_Progress\main.lua:93: in function `?'
...nos\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...nos\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...nos\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...ceDominos\libs\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <...ceDominos\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil

**Comment by Tuller** [comment]
For the first one, are you running the 7.2 version of Dominos?

**Comment by Sipollo** [comment]
I'm not; had checked to see if there was an update before posting the above, I obviously missed the 7.2 update - sorry!

**Comment by Tuller** [comment]
I just posted another one to fix the artifact bar as well.

**Comment by Sipollo** [comment]
Cool; with your update above I no longer see load errors from Dominos; thanks!
