### ISSUE TITLE
double cast bar when quest action bar shows

### ISSUE THREAD

**Issue by rakkarage** [tullamods/Dominos#275]
when the quest action bar shows, either blizzard or dominos... the cast bar shows twice?

![2017-04-15 12](https://cloud.githubusercontent.com/assets/962340/25064854/ac28c8a4-21d1-11e7-991f-317677e30c7c.png)
![2017-04-15 13](https://cloud.githubusercontent.com/assets/962340/25064852/ac267158-21d1-11e7-940a-6000d9226825.png)
![2017-04-15](https://cloud.githubusercontent.com/assets/962340/25064853/ac269a34-21d1-11e7-96b1-91ee1edb8049.png)

thanks

**Comment by Guema** [comment]
I think this is related to VehicleCastBar. it must be a different Frame from _G.CastingBarFrame in wow basic UI.

**Comment by Tuller** [comment]
It probably is the separate vehicle one

**Comment by rakkarage** [comment]
/framestack
![2017-04-17 1](https://cloud.githubusercontent.com/assets/962340/25093954/d8bbb060-2362-11e7-8e80-337ec38716a1.png)

**Comment by Tuller** [comment]
/grumbles at blizzard for being inconsistent with how they do quest stuff sometimes.

**Comment by Guema** [comment]
That's the wrong side of huge teams. There is always someone somewhere that will do bad things others will don't see directly.

**Comment by Tuller** [comment]
I think the simple solution to this is:
```_G.PetCastingBarFrame:UnregisterAllEvents()```

From reading the code, the pet bar casting bar is only shown if the pet is possessed.
