### ISSUE TITLE
Pet battle MenuBar anchoring conflict

### ISSUE THREAD

**Issue by joshbooth** [tullamods/Dominos#276]
`31x CollectionsMicroButton:SetPoint(): EJMicroButton is dependent on this
[C]: ?
[C]: in function `SetPoint'
Dominos\bars\menuBar.lua:238: in function `FixButtonPositions'
Dominos\bars\menuBar.lua:220: in function `LayoutPetBattle'
Dominos\bars\menuBar.lua:199: in function `Layout'
Dominos\bars\menuBar.lua:78: in function <Dominos\bars\menuBar.lua:76>`
If there were a way to just disable Dominos entirely while in pet battles, that'd be fine. Not a big deal, obviously, but I like keeping my BugSack icon green.

**Comment by Tuller** [comment]
I have not reproduced this one quite yet.  What does your config look like for the menu bar?
