### ISSUE TITLE
Changing Profiles Does Not Refresh Masque

### ISSUE THREAD

**Issue by StormFX** [tullamods/Dominos#279]
I just thought I'd let you know that while trying to narrow down some issues in Masque, I noticed that if you change Dominos' profile, some of the layers lose their skin settings from Masque. In your profile change/update function, you need to call Group:ReSkin() for each group/subgroup.

**Comment by Tuller** [comment]
This should be fixed in the latest commit

**Comment by StormFX** [comment]
Looks good! Thanks! :)

Closing. ;)
