### ISSUE TITLE
Error Message Upon Login

### ISSUE THREAD

**Issue by teutelquessir** [tullamods/Dominos#280]
Got the following error message upon logging in:

Date: 2017-06-22 16:30:23
ID: 1
Error occured in: Global
Count: 1
Message: ..\FrameXML\SecureHandlers.lua line 673:
   script ran too long
Debug:
   ..\FrameXML\SecureHandlers.lua:673:
      ..\FrameXML\SecureHandlers.lua:659
   (tail call): ?
   Dominos\core\bindingsController.lua:335: UpdateBindings()
   Dominos\core\bindingsController.lua:312:
      Dominos\core\bindingsController.lua:310
Locals:
frame = <unnamed> {
 0 = <userdata>
 Unregister = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:230
 Register = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:215
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:203
 HasSurrogate = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:304
 frames = <table> {
 }
 SetupAttributeMethods = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:110
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:715
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:197
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:699
 RequestUpdateBindings = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:308
 CVAR_UPDATE = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:208
 UPDATE_BINDINGS = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:193
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:704
 RegisterEvents = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:180
 HookBindingMethods = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:169
 __UpdateBindings = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:310
 surrogates = <table> {
 }
 CastingOnKeyPress = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:348
 OnEvent = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:189
 UpdateCastOnKeyPress = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:340
 UpdateBindings = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:323
 __WaitingToUpdateBindings = false
 FreeSurrogate = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:276
 CreateSurrogate = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:244
 Load = <function> defined @Interface\AddOns\Dominos\core\bindingsController.lua:101
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:710
}
body = " self:RunAttribute('LoadBindings') "
(*temporary) = <function> defined =[C]:-1
(*temporary) = SecureHandlersUpdateFrame {
 0 = <userdata>
}
(*temporary) = "_execute"
(*temporary) = "_execute"
(*temporary) = "script ran too long"
IsValidFrame = <function> defined @Interface\FrameXML\SecureHandlers.lua:461
error = <function> defined =[C]:-1
select = <function> defined =[C]:-1
type = <function> defined =[C]:-1
LOCAL_API_Frame = SecureHandlersUpdateFrame {
 0 = <userdata>
}

AddOns:
  Swatter, v7.0.5 (<%codename%>)
  Ace3, v
  Altoholic, vr182
  Ampere, v3.1.0.15
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Auctionator, v4.0.17
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  Clique, vv70200-1.1.0
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr63
  DataStoreAchievements, vr45
  DataStoreAgenda, vr25
  DataStoreAuctions, vr48
  DataStoreCharacters, vr40
  DataStoreContainers, vr56
  DataStoreCrafts, vr77
  DataStoreCurrencies, vr35
  DataStoreGarrisons, vr21
  DataStoreInventory, vr50
  DataStoreMails, vr49
  DataStorePets, vr42
  DataStoreQuests, vr42
  DataStoreReputations, vr40
  DataStoreSpells, vr30
  DataStoreStats, vr29
  DataStoreTalents, vr59
  DBMCore, v7.2.8
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Dominos, v7.2.2
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  EasyMail, v
  Gatherer, v7.0.5
  GatherMate2, v1.40
  GroupCalendar5Clock, v5.2.5
  Incognito, v1.4.1
  Informant, v7.4.5714 (TasmanianThylacine)
  ISBoxer, v1.0
  LibExtraTip, v5.12.DEV.423(/embedded)
  LibQTip10, vr178-release 
  LibSharedMedia30, v3.0-97
  LibSink20, v
  MageNuggets, v5.5.6
  MageNuggetsCooldownMonitor, v1.1.2
  MageNuggetsStatMonitor, v1.2.1
  MarketWatcher, v2.2
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.147
  MogIt, v3.8.1
  MogItMail, v3.8.1
  MogItOneHanded, v3.8.1
  MogItOther, v3.8.1
  MogItRanged, v3.8.1
  MogItTwoHanded, v3.8.1
  MoveAnything, v16.2.0
  Omen, v3.1.12
  oRA3, vv7.2.2
  OreCrusher, v4.1
  Outfitter, v5.19
  Ovale, v7.2.2.0
  PersonalLootHelper, v1.29
  Prat30, vr1054      
  Prat30Libraries, v
  Quartz, v3.3.4
  Recount, vv7.2.0c
  SexyMap, vv7.2.0
  SharedMedia, v3.0.7-188
  SlideBar, v7.0.5 (<%codename%>)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TankWarnings, vv1.3.2
  TargetCharms, v1.6.1 (7/19/2016)
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.12.0.70200
  TitanBag, v5.12.0.70200
  TitanClock, v5.12.0.70200
  TitanCurrency, v7.1
  TitanDurability, v1.24
  TitanGatherer, v4.0.0
  TitanGold, v5.12.0.70200
  TitanLocation, v5.12.0.70200
  TitanLootType, v5.12.0.70200
  TitanMail, v7.01
  TitanPerformance, v5.12.0.70200
  TitanRepair, v5.12.0.70200
  TitanSpec, v4.1
  TitanVolume, v5.12.0.70200
  TitanXP, v5.12.0.70200
  TomTom, vv70200-1.0.0
  totalRP3, v1.2.8.1
  totalRP3Data, v
  totalRP3Extended, v1.0.3.1
  totalRP3ExtendedImpExport, v1.0.3.1
  totalRP3ExtendedTools, v1.0.3.1
  UnlimitedChatMessage, v1.9.8
  WIM, vr524
  WOWScribe, v4.0.3
  ZPerl, v5.3.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=1034)

**Comment by Tuller** [comment]
Have you tested with just Dominos enabled?

**Comment by teutelquessir** [comment]
Just now saw this email and whatever issue there was seems to have gone
away.
