### ISSUE TITLE
Shadow priest conflict

### ISSUE THREAD

**Issue by d0grent** [tullamods/Dominos#283]
dominos crashes my WoW when loading into the game, but only when I'm in shadow spec.

**Comment by d0grent** [comment]
any idea when this will be fixed? I still can't use this addon on shadow spec.

**Comment by Tuller** [comment]
I don't really have anything to go on, as Dominos has nothing special in the code for priests.

**Comment by d0grent** [comment]
could it be non priest specific? Maybe there's an issue with the way
abilities get replaced on the bars when you switch specs? I'm not sure but
I definitely narrowed it down to just dominos and just the 1 spec.

**Comment by Tuller** [comment]
It may be related to the artifact bar, which I just posted a fix for

**Comment by d0grent** [comment]
this fixed the issue thanks. When I first switched to shadow I hadn't used any AP in the weapon, I dumped several hundred million AP in it at once and that's when I first crashed, so that makes perfect sense.
