### ISSUE TITLE
Pet Bar Show State

### ISSUE THREAD

**Issue by Korvus-III** [tullamods/Dominos#284]
I an unable to change the show state of the pet bar.  When i cIick away from the advanced window, and open it back up, the show state defaults back to [@pet,exists,nopossessbar]show;hide.  I don't get an error message when i attempt to do so, is this by design?

**Comment by Tuller** [comment]
Yes, for the most part.

**Comment by TheAthenA714** [comment]
Any chance this could change in the future? I have all my bars set up with the same show/hide conditions, it kinda sucks to have a lonely pet bar staying behind all alone.

**Comment by Tuller** [comment]
Yes, eventually
