### ISSUE TITLE
what the fuck that is that with "chargeable on request" ?

### ISSUE THREAD

**Issue by Roswell51** [tullamods/Dominos#285]
Good me it fucks me on the nerves with this kind of the weird bug. This message who say "chargeable on resquest" I CAN'T CONFIGURE MY ACTION BARS!? FIX IT

**Comment by Guema** [comment]
Can you be more accurate about the problem you encounter ? Loading on demand is not a bug, that's a feature allowing to load addon only when it's useful, in this case, when you want to configure the addon.
Did you disable (uncheck) Dominos config addon in addon panel ? To configure Dominos, this must be checked, and you after have to go in interface > addons tab > Dominos.

**Comment by Roswell51** [comment]
No, it's always chacked, I never uncheck dominos config >:(

**Comment by Guema** [comment]
This is intented if the message is displayed in AddOns menu.

Go in menu (Escape) > Interface > AddOns (tab) > Dominos.

If I remember well, Dominos loads automatically by itself when accessing this menu. Or maybe you have to click a button.

**Comment by Roswell51** [comment]
yes I already on it but, when I tried to type "/dom" or "/dominos", the option windows doesn't display on my screen, instead of it, it's displayed on the chat box -_-, now today, after closed my pc or restart, it's seem work when I type "/dom" the windows display. WTF what is that weird bug like that.

**Comment by Guema** [comment]
Chat command api is really bugged referring to what i tried myself, it means that imo Blizzard is more responsible than the addon maker. As Dominos have a really good Ui, please, access it by menus.

Im not responsible of dominos, but as i can see about your messages, please keep in mind that :
- addon coders are not payed, and do all the work freely for users.
- they work with really bad documented sources, and really minimalistic dev tools, making work even harder.
- receiving message like "this is shit" or "FIX IT" is really annoying. If i was the Dominos coder, i would probably have considered just deleting your ticket, as there is no due for anyone, especially for people that don't know courtesy, plus your message being useless as you basically just agressively say it don't work without any precision.

Remember that addons are fan made for free.

And as im just a user of Dominos myself, my help is also free and unpayed.

**Comment by Roswell51** [comment]
It's not up to you that I'm going to get angry, but the bugs really irritate me, it's like we were unable to configure the action bars or play dirty tricks just to make me confuse more often , I am tired of having millions of addon's problems caused by our worst enemy "Blizzard". Yes for Blizzard, I really do not like his style, they are terrible, I hate their complex code, because it breaks the addons too and this Blizzard's style take up too much of my screen, it irritates me so much.

I have question about the first message : For the "Fix it" at the end from the first message above, can I edit or is it too late to correct if I really want to delete "FIX IT"?

**Comment by Guema** [comment]
Ill try to reproduce myself and see if i can provide precisions.

**Comment by Roswell51** [comment]
Finally the problems disappeared, I am happy to return to normal, but you add a "progress" in the list! O_o
