### ISSUE TITLE
Joining Randon BG's

### ISSUE THREAD

**Issue by Duncan1985** [tullamods/Dominos#287]
Tried to join random bg after installing and setting up Dominos frames to how i like them however it wont let me queue.

Bug report below.

Date: 2017-10-19 11:18:02
ID: 1
Error occured in: AddOn: Dominos_Units
Count: 1
Message: Error: AddOn Dominos_Units attempted to call a forbidden function (JoinBattlefield()) from a tainted execution path.
Debug:
   [C]: JoinBattlefield()
   Blizzard_PVPUI\Blizzard_PVPUI.lua:611: HonorFrame_Queue()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  AucAdvanced, v7.5.5724 (TasmanianThylacine)
  AucFilterBasic, v7.5.5724 (TasmanianThylacine)
  AucFilterOutlier, v7.5.5724.5459(7.5/embedded)
  AucMatchUndercut, v7.5.5724.5585(7.5/embedded)
  AucStatHistogram, v7.5.5724 (TasmanianThylacine)
  AucStatiLevel, v7.5.5724 (TasmanianThylacine)
  AucStatPurchased, v7.5.5724 (TasmanianThylacine)
  AucStatSales, v7.5.5724.5598(7.5/embedded)
  AucStatSimple, v7.5.5724 (TasmanianThylacine)
  AucStatStdDev, v7.5.5724 (TasmanianThylacine)
  AucStatWOWEcon, v7.5.5724.5613(7.5/embedded)
  AucUtilAHWindowControl, v7.5.5724.5575(7.5/embedded)
  AucUtilAppraiser, v7.5.5724.5719(7.5/embedded)
  AucUtilAskPrice, v7.5.5724.5599(7.5/embedded)
  AucUtilAutoMagic, v7.5.5724.5686(7.5/embedded)
  AucUtilCompactUI, v7.5.5724.5715(7.5/embedded)
  AucUtilEasyBuyout, v7.5.5724.5576(7.5/embedded)
  AucUtilFixAH, v7.5.5724 (TasmanianThylacine)
  AucUtilItemSuggest, v7.5.5724.5651(7.5/embedded)
  AucUtilPriceLevel, v7.5.5724.5633(7.5/embedded)
  AucUtilScanButton, v7.5.5724.5631(7.5/embedded)
  AucUtilScanFinish, v7.5.5724.5720(7.5/embedded)
  AucUtilScanProgress, v7.5.5724.4979(7.5/embedded)
  AucUtilScanStart, v7.5.5724.5347(7.5/embedded)
  AucUtilSearchUI, v7.5.5724.5721(7.5/embedded)
  AucUtilSimpleAuction, v7.5.5724.5705(7.5/embedded)
  AucUtilVendMarkup, v7.5.5724.4828(7.5/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.3.2
  BeanCounter, v7.5.5724 (TasmanianThylacine)
  Configator, v5.1.DEV.431(/embedded)
  DBMCore, v7.3.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Dominos, v7.3.1
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  DominosUnits, v4.2.3
  Enchantrix, v7.5.5724 (TasmanianThylacine)
  EnchantrixBarker, v7.5.5724 (TasmanianThylacine)
  Informant, v7.5.5724 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.430(/embedded)
  Recount, vv7.3.0c
  SlideBar, v7.5.5724 (TasmanianThylacine)
  Stubby, v7.5.5724 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=83c)

**Comment by Goranaws** [comment]
This is my bug. Caused by dropdown mene taint. I'm working on it.
