### ISSUE TITLE
Quick-paging suddenly got limited

### ISSUE THREAD

**Issue by Egobyte83** [tullamods/Dominos#288]
So, I have been using dominos for quite some time now and I really like it. Unfortunately, a few weeks ago I was suddenly unable to scroll through all of my action bars when quick-paging and I have no idea why. I don't know if its because I have done something to offset the default settings or whatnot, but now I can only quick-page through two bars, number 1 and number 2; they are the only ones that show up in the number 1 bar when I shift+scroll the mouse; the rest are fixed right next to the first bar and perfectly customizable in regards to making them invisible and all of that, but they never show up in number 1 when quick-paging anymore. I am not really seeing anything in the options on how to correct this. Some help would be appreciated. ^^

**Comment by Egobyte83** [comment]
Which action bars are they? :O

**Comment by Egobyte83** [comment]
And where do you activate them? (in which menu)

**Comment by Tuller** [comment]
These guys:
![image](https://user-images.githubusercontent.com/191239/34182708-691b778c-e4e5-11e7-9bec-50fe30a9fbb8.png)

When checked, they consume quick pages.

**Comment by Egobyte83** [comment]
Wow thank you :) some of them came back when I copied the options in your screenshot
