### ISSUE TITLE
Reputation bar

### ISSUE THREAD

**Issue by cogar328** [tullamods/Dominos#289]
I recently replaced my addons and now Dominos rep bar is no longer automatically changing to active reputation even though i have the option checked.  Any help? Thanks

**Comment by cogar328** [comment]
no response?

**Comment by Tuller** [comment]
I did, on the curse page :P

**Comment by cogar328** [comment]
just to let you know, the Dominos reputation bars are still not responding
properly and I am just using them broken.

**Comment by ckaotik** [comment]
I've added this code to Dominos_Progress' `xpBar.lua` file, might not help exactly with your problem but it disables the xp bar
- for characters that have xp gain turned off
- for characters at "max" level, which should include trial account and purchased expansion limits

```lua
function ExperienceBar:IsModeActive()
	return not IsPlayerAtEffectiveMaxLevel() and not IsXPUserDisabled()
end
```

**Comment by Tuller** [comment]
I could have sworn I actually had that in my code.
