### ISSUE TITLE
Update Dominos on Curse

### ISSUE THREAD

**Issue by AL3x3y0** [tullamods/Dominos#290]
Version 7.3.1 from Curse have bug with cyrillic letters (they showing like "???"), you forgot update LibSharedMedia-3.0 in Dominos_Progress, Dominos_Config and Dominos_Cast:
`elseif locale == "ruRU" then`
`	LOCALE_MASK = lib.LOCALE_BIT_ruRU`
`	SML_MT_font["Arial Narrow"]			= [[Fonts\ARIALN.TTF]]`
`	SML_MT_font["Friz Quadrata TT"]		= [[Fonts\FRIZQT__.TTF]]`
`	SML_MT_font["Morpheus"]				= [[Fonts\MORPHEUS.TTF]]`
`	SML_MT_font["Nimrod MT"]			= [[Fonts\NIM_____.ttf]]`
`	SML_MT_font["Skurri"]				= [[Fonts\SKURRI.TTF]]`

FRIZQT__ -> FRIZQT___CYR
MORPHEUS -> MORPHEUS_CYR
SKURRI -> SKURRI_CYR

But I see that you already fixed it 24 days ago:
https://github.com/tullamods/Dominos/commit/725e37b950928830d282a0a93fd1bf0a7177dd43

Why don't you upload this update to Curse?

**Comment by Tuller** [comment]
Its coming, I've just been away from my computer for a bit.

**Comment by Tuller** [comment]
Its now there.
