### ISSUE TITLE
Showstates

### ISSUE THREAD

**Issue by Fumi24** [tullamods/Dominos#292]
Hi

Can seem to find this on the wiki but how many showstates are there or is there only [combat]?

Im currently trying to make a bar only visible inside raids/instances and when im out of combat.

**Comment by Tuller** [comment]
I still need to get around to finally porting the wiki over to github.  Here's the full list:
https://wow.gamepedia.com/Macro_conditionals

**Comment by Fumi24** [comment]
ah, thx didnt realize showstate was the same as conditinals.
