### ISSUE TITLE
Compat issue with GW2 UI addon

### ISSUE THREAD

**Issue by Boymann** [tullamods/Dominos#293]
Dominos Overrides the 1st actionbar of GW2 UI and overlaps the health indicator of it as a result.
Any fix to this?
GW2UI: 4.21
Dominos: 7.3.2

**Comment by Tuller** [comment]
Its a conflict: you're running two addons that try to modify the same Blizzard action bar parts and only one of them will "win"

**Comment by Boymann** [comment]
Yeah, I know but I thought it could be solved by making the bar parts afflicted "toggleable"? (Just an idea)

**Comment by Tuller** [comment]
It's a bit more complicated than that, especially for action bar 1 which is pulled in from the normal UI.
