### ISSUE TITLE
Vehicle bar stays after I leave pod on M High Command

### ISSUE THREAD

**Issue by napnapnapnap** [tullamods/Dominos#294]
After I leave the pod on Mythic High Command, the vehicle bar stays on the screen (empty) and blocks me from using my ActionBar1 (keybindings too).

I don't know if it's same on heroic mode.

**Comment by Tuller** [comment]
Are you getting any lua errors/addon_action_blocked messages?

**Comment by napnapnapnap** [comment]
I didn't have a logger addon, I will do this boss again Sunday, I'll try to log and sacrifice a wipe in the name of Dominos :p

**Comment by napnapnapnap** [comment]
This time I didn't have the proiblem but I was playing another spec so another config, but I still got some bugs in my logs

OmniCC bug : 1x [ADDON_ACTION_BLOCKED] AddOn 'OmniCC' tried to call the protected function 'CompactRaidFrame6:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:350: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:283: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:117: in function <FrameXML\CompactUnitFrame.lua:53>

Locals:
InCombatSkipped

Dominos bug 1: 

1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton31:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\ActionButton.lua:364: in function `ActionButton_Update'
FrameXML\ActionButton.lua:813: in function `ActionButton_OnEvent'
FrameXML\ActionButton.lua:253: in function <FrameXML\ActionButton.lua:245>

Locals:
InCombatSkipped

Dominos bug 2: 8x CollectionsMicroButton:SetPoint(): EJMicroButton is dependent on this
[C]: ?
[C]: in function `SetPoint'
Dominos\bars\menuBar.lua:238: in function `FixButtonPositions'
Dominos\bars\menuBar.lua:224: in function `LayoutOverrideUI'
Dominos\bars\menuBar.lua:201: in function `Layout'
Dominos\bars\menuBar.lua:78: in function <Dominos\bars\menuBar.lua:76>

Locals:
InCombatSkipped

**Comment by Tuller** [comment]
I'm pretty sure I fixed this one and failed to close the issue.
