### ISSUE TITLE
Some bars are unusable and abilities suddenly are removed from bars

### ISSUE THREAD

**Issue by Rokyy194** [tullamods/Dominos#296]
Hello,
So recently I've noticed that some bars dissapear - I can't put any ability into them, the opacity is in on 100, also they are not hidden. Sometimes it happens when I remove some ablity from the bar - then all abilites dissapear and I can't put any new. 

Also, I have problems with sudden abilities change. I don't know, if some key combination does it, but when I was in dungeon, the abilities suddenly were replaced with some others. When I relogged, everything was fine again. 
These issues are terrible, I wish I could use Dominos, but because of them I just can't :C

**Comment by Tuller** [comment]
Are you pressing shift + mousehweel or shift + number?
