### ISSUE TITLE
Lua Errors

### ISSUE THREAD

**Issue by dreamtheme** [tullamods/Dominos#298]
Hi, i'm getting this error.
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'OverrideActionBarButton3:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\ActionButton.lua:364: in function `ActionButton_Update'
FrameXML\ActionButton.lua:720: in function `ActionButton_OnEvent'
FrameXML\ActionButton.lua:207: in function <FrameXML\ActionButton.lua:204>

Locals:
InCombatSkipped

**Comment by mrbuds** [comment]
I have the same error showing regularly in combat too
```
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'OverrideActionBarButton1:Show()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Show'
FrameXML\ActionButton.lua:364: in function `ActionButton_Update'
FrameXML\ActionButton.lua:720: in function `ActionButton_OnEvent'
FrameXML\ActionButton.lua:207: in function <FrameXML\ActionButton.lua:204>

Locals:
InCombatSkipped
```

**Comment by Tuller** [comment]
So there's good a chance more of these just start disappearing when 8.1 comes out due to blizzard fixing a few bugs on their end.
