### ISSUE TITLE
BFA LUA Issues & Other Misc

### ISSUE THREAD

**Issue by Zen-Karma** [tullamods/Dominos#303]
Upon logging in the following LUA errors pops up. It seems to address the issue I first noticed of it not hiding the default bag bar,default mini menu bar, the default action bar with the two gryphons on the end including thew two progress bars below it. However you can still move everything including bags etc it just leaves the default "background" of the items listed above in their default location.

----------------------------------------------------------------------------

Message: Interface\AddOns\Dominos\plugins\blizzardHider.lua:13: attempt to index global 'Addon' (a nil value)
Time: Sun Apr 22 11:00:44 2018
Count: 1
Stack: Interface\AddOns\Dominos\plugins\blizzardHider.lua:13: attempt to index global 'Addon' (a nil value)
Interface\AddOns\Dominos\plugins\blizzardHider.lua:13: in function `disableFrame'
Interface\AddOns\Dominos\plugins\blizzardHider.lua:39: in main chunk

Locals: frameName = "ArtifactWatchBar"
unregisterEvents = nil
frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'Addon' (a nil value)"
hiddenFrame = <unnamed> {
 0 = <userdata>
}

**Comment by Zen-Karma** [comment]
Message: Interface\AddOns\Dominos_Cast\castBar.lua:519: attempt to perform arithmetic on local 'endTime' (a boolean value)
Time: Mon Apr 23 10:04:49 2018
Count: 1
Stack: Interface\AddOns\Dominos_Cast\castBar.lua:519: attempt to perform arithmetic on local 'endTime' (a boolean value)
Interface\AddOns\Dominos_Cast\castBar.lua:519: in function `UpdateCasting'
Interface\AddOns\Dominos_Cast\castBar.lua:255: in function `func'
Interface\AddOns\Dominos_Cast\castBar.lua:169: in function <Interface\AddOns\Dominos_Cast\castBar.lua:166>

Locals: self = DominosFramecast {
 0 = <userdata>
 border = <unnamed> {
 }
 props = <table> {
 }
 latencyBar = <unnamed> {
 }
 fout = <unnamed> {
 }
 bg = <unnamed> {
 }
 container = <unnamed> {
 }
 statusBar = <unnamed> {
 }
 spark = <unnamed> {
 }
 fin = <unnamed> {
 }
 id = "cast"
 sets = <table> {
 }
 labelText = <unnamed> {
 }
 units = <table> {
 }
 timeText = <unnamed> {
 }
 header = <unnamed> {
 }
 docked = <table> {
 }
 icon = <unnamed> {
 }
}
reset = true
name = "Activating Specialization"
nameSubtext = "Activating Specialization"
text = 236544
texture = 1116064496
startTime = 1116069496
endTime = false
vmin = 0
(*temporary) = DominosFramecast {
 0 = <userdata>
 border = <unnamed> {
 }
 props = <table> {
 }
 latencyBar = <unnamed> {
 }
 fout = <unnamed> {
 }
 bg = <unnamed> {
 }
 container = <unnamed> {
 }
 statusBar = <unnamed> {
 }
 spark = <unnamed> {
 }
 fin = <unnamed> {
 }
 id = "cast"
 sets = <table> {
 }
 labelText = <unnamed> {
 }
 units = <table> {
 }
 timeText = <unnamed> {
 }
 header = <unnamed> {
 }
 docked = <table> {
 }
 icon = <unnamed> {
 }
}
(*temporary) = "spell"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 1116064496
(*temporary) = "attempt to perform arithmetic on local 'endTime' (a boolean value)"
UnitCastingInfo = <function> defined =[C]:-1
GetSpellInfo = <function> defined =[C]:-1
GetTime = <function> defined =[C]:-1
min = <function> defined =[C]:-1

**Comment by Tuller** [comment]
They changed the casting APIs.

**Comment by Tuller** [comment]
Not yet (I've been quite busy with another project).

**Comment by Zen-Karma** [comment]
Ah no worries, was merely checking in. Seems its very operational in BFA anyways except for the above LUA issues at least for me so I've kept it enabled and just dealt with the things not being hidden and disabled the cast bar....I'll keep an eye out for when you do got time to work on this one. ....Thanks!

**Comment by Tuller** [comment]
https://github.com/tullamods/Dominos/releases/tag/8.0.0-alpha2 should be a bit less broken.

**Comment by Zen-Karma** [comment]
Awesome!! Just logged into beta and I'm getting NO LUA errors related to Dominos. Thanks! If any do popup I shall let you know
