### ISSUE TITLE
Bar Frames are not hiding with override or pet battle ui

### ISSUE THREAD

**Issue by DennisJohnsen** [tullamods/Dominos#304]
I'm trying to setup my new UI with Dominos for the actionbars.

I noticed an issue with custom artwork and the Dominos frames. It appears when the Override UI or Pet Battle UI is shown (Having default override ui enabled), the surrounding frame for the buttons is not "hidden". This means any other frames that are set as children to Dominos frames are not hiding with the bars correctly.

The frame is still there, as seen on this screenshot using /framestack to find the frames.
![Framestack issue](https://i.imgur.com/sGJaIN2.jpg)

Even setting changing the opacity for these frames with give the wanted result, but obviously a proper hiding of the frame is better.

Hope it is something you will look at.

Kind Regards
Dennis

**Comment by Tuller** [comment]
In most cases, only one thing is actually directly parented to a DominosFrame, and that's DominosFrame.header. That frame is then hidden automatically when the override ui/pet battle ui are shown.

Now as to why I needed both frames: I don't actually think I do anymore. It was from a much older design when some DominosFrames needed to be secure and some did not.

**Comment by DennisJohnsen** [comment]
I did try to put a child frame inside the ".header" frame, but i could never get my frame to show when using that as a parent, unfortunatly.

Right now i'm just gonna add the same events you're using to check for override bar, and simply hide my artwork frames my self. Obvious, i wont do that if your timeframe for this is sooner rather than later :P Keep me posted.
