### ISSUE TITLE
"spell_activation_overlay_glow_show/hide" not supported correctly

### ISSUE THREAD

**Issue by Enbis-codes** [tullamods/Dominos#305]
I just noticed that Dominos doesn't work with spell overlay glow - at least when it's done through WeakAuras, but probably in any other case as well. 

Here's for example simple weakauras code that hides the default button glow on Pistol Shot when there's already 6 combo points: 
https://pastebin.com/RwP7yWdt
Basically, just 2 triggers: status -> Spell Activation Overlay Glow on Pistol Shot + 6 combo points = action on show: hide the button glow

And here's the result with both Bartender and Dominos side by side (Dominos on the left):
https://image.ibb.co/i4hZao/Wo_WScrn_Shot_052218_200358.jpg
^ with less than 6 points it goes as intended on both, but it's not controlled by the script yet.

https://image.ibb.co/fhiAgT/Wo_WScrn_Shot_052218_200647.jpg
^ and this is where it goes wrong: overlay's correctly hidden on Bartender part, but not on Dominos. 

(note: yes, Dominos and Bartender have different names for action bars, I accounted for that by making 2 coplies directed at both for demonstration)

I suspect it has something to do with LibButtonGlow and/or SPELL_ACTIVATION_OVERLAY_GLOW_HIDE event not mentioned even once through Dominos code, so apparently it just goes by default behavior. 

Any chance this can be supported in the future?

**Comment by Tuller** [comment]
Have you tried on the stock blizzard action buttons for confirmation?

**Comment by Enbis-codes** [comment]
It doesn't work with default blizzard action buttons, though not like I expected it would... which isn't exactly a compliment to default blizz actionbars. >_>
Or at least not with every proc that lights up action buttons - seems like only those with fancy mid-screen animation cause problems. Buuut this line:
`/run ActionButton_HideOverlayGlow(MultiBarBottomRightButton6); ActionButton_Update(MultiBarBottomRightButton6)`
- at least very least it makes the flashy button blink once before the glow returns. 
Also this:
`/run local i = IsSpellOverlayed(185763); print(i);`
- would return true/false if flash's up or not atm.
That's the best I could find so far, but I'm no expert in either lua or wow api, so it's just what I managed to google within few min ( https://us.battle.net/forums/en/wow/topic/20759416925 ) Maybe that'd help in any way...
