### ISSUE TITLE
Disable spell proc flashes on action bars

### ISSUE THREAD

**Issue by mspykerez** [tullamods/Dominos#309]
Add an option to disable spell proc highlight flashes on the action bars.

**Comment by Tuller** [comment]
I don't really have the ability to control this one at the moment. Maybe if I opt to roll my own action button code.

**Comment by jcadduono** [comment]
I've been doing this in my own addons, it's pretty simple actually to just hide the glow.
```
local function DenyOverlayGlow(actionButton)
	if somesettingprofile.hide_glow then
		actionButton.overlay:Hide()
	end
end

hooksecurefunc('ActionButton_ShowOverlayGlow', DenyOverlayGlow) -- Disable Blizzard's built-in action button glowing
```

**Comment by mspykerez** [comment]
Disabling per spell would be optimal.

**Comment by jcadduono** [comment]
You could check the actionButton icon against a list of spells (that you want to disable glow for) icons within that function in order to do that easily.

**Comment by Tuller** [comment]
I think this would be a good candidate for a separate addon, since it could work on things other than just Dominos.
