### ISSUE TITLE
Heart of Azeroth AP bar

### ISSUE THREAD

**Issue by phen00** [tullamods/Dominos#312]
I'm using dominos 8.0 (atleast the version I think is meant for BFA) and there doesn't seem to be a way to get the AP bar for the neck to show up. I tried unequipping my artifact weapons and that didn't work either. Went through the settings and couldn't find anything.

I take it i've probably missed something.

**Comment by Tuller** [comment]
I've not gotten to implementing it yet.

**Comment by Tuller** [comment]
I've now implemented it in the 8.0.1 version:
https://github.com/tullamods/Dominos/releases/tag/v8.0.1-alpha
