### ISSUE TITLE
Config panel "progress" vanished.

### ISSUE THREAD

**Issue by Draugor** [tullamods/Dominos#313]
Hi there,

so i started to revamp my UI and i started checking out Dominos. After some googling i found that apparently there should be a config panel where i can set the color of the progress-bars and check "one bar mode", but for me it wasn't visible.

Deactivating/activating different addons i figured out, that when i have ArkInventory enabled the panel magically disappears.

![dominos_only](https://user-images.githubusercontent.com/6240419/41935546-6074c068-798a-11e8-8190-f95a768a8036.png)
![dominos_plus_ark](https://user-images.githubusercontent.com/6240419/41935559-670e6212-798a-11e8-9e7c-01ebb7c1bcee.png)

edit: i'm using version 7.3.2

Cheers!

**Comment by Tuller** [comment]
Is this still occurring?
