### ISSUE TITLE
True variable length bars

### ISSUE THREAD

**Issue by Goranaws** [tullamods/Dominos#315]
-Would still be limited to a total of 120 buttons.
-instead of hiding buttons from the bars, use them to make more bars.

*example - assume default settings of 10 Bars with 12 buttons each.
If you add 6 extras buttons to only (Bar 5) it would shift the buttons across the bars, to reduce (Bar 10) by 6 buttons. Then if you added 6 extra buttons to (Bar 3), (Bar 10) would disappear. 

You would not directly move buttons from one bar to another. The buttons would just shift across the bars, keeping their proper sequence.

I hope this make some sort of sense, thought it might be a fun idea for added flexibility. This would only conflict with bar paging, though I don't think it would bother any of the override bars(vehicle bars and such)

**Comment by Tuller** [comment]
I actually sort of did this with Bongos3.

**Comment by Goranaws** [comment]
I wasn't playing WoW back then. :-D I'll take a look at the code eventually.

**Comment by Tuller** [comment]
Paging is the real reason I don’t do this. Bars makes sense as a logical unit. 

To implement variable length bars. One would probably want to do instead give each bar a set number of pages, and then start the next bar’s action ID after the previous bar’s start + page count.

In practice, this causes a lot of shuffling in screen, and isn’t super compatible with setting bar 1 to point to the default stance bars (7-10)

**Comment by Tuller** [comment]
Paging is the real reason I don’t do this. Bars makes sense as a logical unit. 

To implement variable length bars. One would probably want to do instead give each bar a set number of pages, and then start the next bar’s action ID after the previous bar’s start + page count.

In practice, this causes a lot of shuffling in screen, and isn’t super compatible with setting bar 1 to point to the default stance bars (7-10)
