### ISSUE TITLE
Cast Bar Failing

### ISSUE THREAD

**Issue by phated1** [tullamods/Dominos#316]
If you press another spell while mid-cast (to queue the next spell), the cast bar shows "failed" and stops displaying the current cast.
GIF: https://puu.sh/AYr5a/786a356e35.gif

No addons other than dominos enabled, error not present with default blizzard cast bar. Also running version 8.0.3

**Comment by trbbs** [comment]
Experiencing the same issue as well. I utilize the 400ms spell queue and have it display on my bar, and I find that the cast bar disappears often or doesn't register when I add my next spell to queue.

https://imgur.com/a/L6kOlqA

**Comment by BBrav** [comment]
Same issue, happens also when the spell is delayed multiple times by melee npc hits. Even without queing the next spell, the castbar dissapeared after more than 10 mobs were melee hitting me.
