### ISSUE TITLE
Error triggered while fighting boss

### ISSUE THREAD

**Issue by Maldark** [tullamods/Dominos#317]
`Message: Interface\AddOns\Dominos_Progress\progressBar.lua:129: Usage: BreakUpLargeNumbers(number[, natural])
Time: Wed Jul 18 21:03:27 2018
Count: 7
Stack: Interface\AddOns\Dominos_Progress\progressBar.lua:129: Usage: BreakUpLargeNumbers(number[, natural])
(tail call): ?
[C]: in function `fn'
Interface\AddOns\Dominos_Progress\progressBar.lua:129: in function `UpdateText'
Interface\AddOns\Dominos_Progress\azeriteBar.lua:22: in function `Update'
Interface\AddOns\Dominos_Progress\main.lua:55: in function `UpdateAllBars'
Interface\AddOns\Dominos_Progress\main.lua:100: in function `?'
...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>`

After killing Professor Putricide in ICC 25HC it is triggered every time I loot. It did not trigger before.

**Comment by Tuller** [comment]
I think this is fixed in current releases.
