### ISSUE TITLE
Faded opacity

### ISSUE THREAD

**Issue by chadmccune** [tullamods/Dominos#319]
I have a utility bar set to faded opacity of 0.  I have my mage portals and mage teleport "flyout buttons" on those bar.  WhenI press the key binding for those buttons, they don't become visible unless I hover over the bar or where the "flyout" is.

Probably "as intended", and I'm ok with that.  If it is, is there a show state I could use to make them visible when active?

**Comment by Tuller** [comment]
There's not a showstate I can use for that bit unfortunately.
