### ISSUE TITLE
Disappearing bars in Dominos

### ISSUE THREAD

**Issue by Rokyy194** [tullamods/Dominos#321]
Hi,
I have an issue with dominos - my bars sometimes automatically disappear and I need to relog to get them back, which is really annoying. It usually hapens to the bar 1, though I never change any bar options and make sure they are not hidden. Sometimes it happens when I pick an ability from the bar - the slot for that ability disappears.

**Comment by Tuller** [comment]
are you pressing shift + number or shift + mousewheel?
