### ISSUE TITLE
Select-State is broken on Action Bar 1

### ISSUE THREAD

**Issue by dethleffson** [tullamods/Dominos#323]
Domnios 8.0.6

Action Bar 1 Buttons cannot be "selected" anymore. The green border is not appearing like there is no real selection. All the other bars are working -> See Screenshot: 
![a2662237e4cba93cfaa4e3bd4b389c98](https://user-images.githubusercontent.com/8402468/44208708-7adcf200-a161-11e8-84a1-0e5db669bc21.gif)

**Comment by Tuller** [comment]
What happens without masque?
