### ISSUE TITLE
Cant see the azerite bar

### ISSUE THREAD

**Issue by Nerweth** [tullamods/Dominos#324]
cant see the azerite bar at all for some reason. it isnt hidden either, in fact i cant see it in the config mode

**Comment by duimech** [comment]
The azerite bar shows as the old artifact bar. 

I had to use my middle mouse (wheel button) click to change the artifact bar to the azerite bar.

This reddit post shows to right click though:
https://www.reddit.com/r/WowUI/comments/97wx9n/help_trying_to_find_azerite_power_bar/
