### ISSUE TITLE
Add current Azerite level to Azerite Bar?

### ISSUE THREAD

**Issue by TanerH** [tullamods/Dominos#326]
Hi there,

I posted this on the WoWInterface forum, but I figured I should (re)post it here, too...

This is a cut/paste from my post there:

Hi Tuller,

I was wondering if you'd consider adding an option to display the current Azerite level in the Azerite Bar?

I looked at your code briefly, and the gross, quick-hack way I did this was to edit Dominos_Progress/azeriteBar.lua and edit the end of the AzeriteBar:Update() function to:
```lua
local current_level = C_AzeriteItem.GetPowerLevel(azeriteItemLocation)
local mylabel = L.Azerite .. ' [' .. current_level .. ']'
 
self:SetValues(value, max)
self:UpdateText(mylabel, value, max
```

Obviously this is a huge hack-job, but it does exactly what I want.
Being able to have this as an actual option (rather than having to hack it in each time) would be awesome :-)

Thanks for considering...

**Comment by Tuller** [comment]
I'm adjusting my end to have:
```lua
function AzeriteBar:Update()
    if not self:IsModeActive() then
        self:SetValues()
        self:UpdateText(L.Azerite, 0, 0, 0)
        return
    end

    local azeriteItemLocation = C_AzeriteItem.FindActiveAzeriteItem()
    local powerLevel = C_AzeriteItem.GetPowerLevel(azeriteItemLocation)
    local value, max = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation)

    self:SetValues(value, max)
    self:UpdateText(L.Azerite, value, max, powerLevel)
end
```

That should allow powerLevel to be visible as an option.
