### ISSUE TITLE
Action bar 1 stuck to bottom of screen

### ISSUE THREAD

**Issue by adonna55** [tullamods/Dominos#327]
Any quest action bars (which are on action bar 1) are stuck to the bottom of my screen. I can move the box all over but the buttons are stuck. Please help? Dominos version is 8.0.7.
![wowscrnshot_091218_193556](https://user-images.githubusercontent.com/43224494/45460629-63434b80-b6c4-11e8-8696-ad1183ba53c7.jpg)
![wowscrnshot_091218_193600](https://user-images.githubusercontent.com/43224494/45460630-63434b80-b6c4-11e8-8dba-43f30fb1704b.jpg)

**Comment by Tuller** [comment]
This is an addon conflict, probably something like MoveAnything.

**Comment by adonna55** [comment]
Thank you for the response - I'll mess around with it.
