### ISSUE TITLE
potion and healthstone CD not shown

### ISSUE THREAD

**Issue by hollo6** [tullamods/Dominos#330]
Battle potions, health potions and Healthstone cooldowns are not being shown on action bars.
They are being shown for other items like invisibility potions though.
Issue can be reproduced while using the potion/HS when only Dominos, Dominos_Config and Arkinventory are enabled. But the latter does not have any action bar or cooldown related setting.
Issue is present only if both addons are enabled, AI in itself does not break it if Dominos is disabled.

**Addon Version**
currently 8.0.7, but it's been like this forever

**Comment by Tuller** [comment]
I've not reproduced this one on my end.
