### ISSUE TITLE
Enhanced Bar Snapping with more points!

### ISSUE THREAD

**Issue by Goranaws** [tullamods/Dominos#332]
Here's the concept code: https://github.com/Goranaws/Dominos/tree/master/Dominos
I was able to increase the number of snappable points, while reducing the over line count of the module by 50 lines. Every point on a moving frame, has three optional points it can snap to on another frame. (example: TopLeft can snap to BottomLeft, BottomCenter or BottomRight. Or: RightCenter could snap to TopLeft, LeftCenter or BottomLeft)

Its fully functional, but I suspect you would apply your own personal touch, before release, if you choose to use it.

**Comment by Tuller** [comment]
Do you have some examples/screenshots of the new anchor points?

**Comment by Goranaws** [comment]
A quick black and white gif should work! Before and after a reload, just to show it's works between games.
![gif-181126_103041](https://user-images.githubusercontent.com/569473/49024068-a7dc7000-f166-11e8-87d8-28087a436607.gif)

**Comment by Tuller** [comment]
I don't like corner to corner anchors as there are too few pixels involved. I do think there's utility in allowing say, the bottom left/right of a bar to anchor to the bottom of the screen.

Also I've gone ahead and LibStub'd flypaper: https://github.com/Tuller/FlyPaper/tree/master

**Comment by Goranaws** [comment]
I'll see what I can do to modify my current design to work as you've described.

**Comment by Goranaws** [comment]
I've made some changes, and added lots of documentation. let me know if I need to explain anything further. :)

**Comment by Goranaws** [comment]
https://github.com/Goranaws/Dominos/blob/master/Dominos/libs/FlyPaper/FlyPaper.lua
