### ISSUE TITLE
Lua error in 8.1 patch

### ISSUE THREAD

**Issue by Vikirnoff** [tullamods/Dominos#334]
I got this Lua error today. 
2x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'MainMenuBar:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearAllPoints'
FrameXML\MainMenuBar.lua:43: in function `SetPositionForStatusBars'
FrameXML\MainMenuBar.lua:8: in function `OnStatusBarsUpdated'
FrameXML\StatusTrackingManager.lua:181: in function `LayoutBars'
FrameXML\StatusTrackingManager.lua:84: in function `UpdateBarsShown'
[string "*:OnEvent"]:4: in function <[string "*:OnEvent"]:1>

Locals:
InCombatSkipped

I'm using dominos version 8.1.1

this error pop up when I was killing some mobs. Thanks for the help! 
![wowscrnshot_121218_101602](https://user-images.githubusercontent.com/11279387/49878980-f50f4180-fdf6-11e8-8aa4-7ed7db8de331.jpg)
 I see my bars and such just this error pops up. I have included a screenshot to show what is up.

**Comment by Precurseurs** [comment]
same error
Dominos: Failed to load ActionBars

**Comment by Tuller** [comment]
Failed to load actionbars is actually #333 and is fixed by installing the addon to the right location, or updating the twitch client.

**Comment by yesitsmeagain** [comment]
same problem here, reinstalling or downloading again the files doesnt fix it.

**Comment by Vikirnoff** [comment]
My twitch client is updated. I even did reinstall by hand to the right location. I'm still getting this error. :(

**Comment by VerstandInvictus** [comment]
Confirmed, restarting Twitch and re-updating fixed it for me. That's a pretty big change for Blizzard to make with absolutely no mention in the patch notes...

**Comment by Precurseurs** [comment]
Bug fixed by twitch app

**Comment by majil41** [comment]
Or by installing into the changed directory location
________________________________
