### ISSUE TITLE
My Errors in Version 8.1.1

### ISSUE THREAD

**Issue by Dephi73** [tullamods/Dominos#336]
12x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' hat versucht die geschützte Funktion 'MainMenuBar:ClearAllPoints()' aufzurufen.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearAllPoints'
FrameXML\MainMenuBar.lua:43: in function `SetPositionForStatusBars'
FrameXML\MainMenuBar.lua:8: in function `OnStatusBarsUpdated'
FrameXML\StatusTrackingManager.lua:179: in function `LayoutBars'
FrameXML\StatusTrackingManager.lua:84: in function `UpdateBarsShown'
FrameXML\StatusTrackingManager.lua:72: in function `SetBarSize'
FrameXML\MainMenuBar.lua:382: in function `ChangeMenuBarSizeAndPosition'
FrameXML\MultiActionBars.lua:49: in function `cb'
FrameXML\MultiActionBars.lua:44: in function <FrameXML\MultiActionBars.lua:34>
FrameXML\MultiActionBars.lua:58: in function `MultiActionBar_Update'
FrameXML\ActionBarController.lua:175: in function `ValidateActionBarTransition'
FrameXML\ActionBarController.lua:143: in function `ActionBarController_UpdateAll'
FrameXML\ActionBarController.lua:62: in function <FrameXML\ActionBarController.lua:51>

Locals:
InCombatSkipped

**Addon Version**
8.1.1

**Comment by Dephi73** [comment]
Getting errors in combat:
Date: 2018-12-12 18:47:30
ID: 7
Error occured in: AddOn: Dominos
Count: 5
Message: Note: AddOn Dominos attempted to call a protected function (MainMenuBar:SetPoint()) during combat lockdown.
Debug:
[C]: SetPoint()
..\FrameXML\UIParent.lua:2981: UIParentManageFramePositions()
..\FrameXML\UIParent.lua:2357:
..\FrameXML\UIParent.lua:2344
[C]: SetAttribute()
..\FrameXML\UIParent.lua:3153:
..\FrameXML\UIParent.lua:3151
[C]: UIParent_ManageFramePositions()
..\FrameXML\MainMenuBar.lua:60: SetPositionForStatusBars()
..\FrameXML\MainMenuBar.lua:122:
..\FrameXML\MainMenuBar.lua:65

**Comment by Dephi73** [comment]
New error Today

1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' hat versucht die geschützte Funktion 'OverrideActionBar:Hide()' aufzurufen.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Hide'
[string "*:OnFinished"]:2: in function <[string "*:OnFinished"]:1>

Locals:
InCombatSkipped

Addon Version 8.1.2

**Comment by Tuller** [comment]
Try again with 8.1.3.

**Comment by Dephi73** [comment]
Thx works fine
