### ISSUE TITLE
8.1: Item stack counts on action bars out of sync

### ISSUE THREAD

**Issue by jcadduono** [tullamods/Dominos#341]
Version: 8.1.3

Since 8.1 I appear to be having issues with item counts, maybe only for conjured items though possibly other items.
Known affected items:
- Mystical Flask (from Cauldron)
- Healthstone

If I use these items, the action button does not update, and sometimes the update is so delayed that I go into combat thinking I have a healthstone but I actually ran out of charges last fight!

**Comment by Tuller** [comment]
I've not reproduced this one.

**Comment by jcadduono** [comment]
Yeah it turns out it's a bug on Blizzard's end. There's a huge forum thread regarding it.
