### ISSUE TITLE
Bars not returning to normal after entering a vehicle

### ISSUE THREAD

**Issue by drxzz** [tullamods/Dominos#344]
Having a bug in King's Rest where my bars get swapped to the coffin vehicle bar upon getting chosen for "Entomb", and upon exiting the coffin my bars do not return to normal. The vehicle bar remains but without any active buttons. The only way I fix this atm is by reloading ui.

I used to have this issue a few months ago but at some point it stopped happening, but with the new patch it started again.

**Dominos Version 8.1.1*

**Comment by Tuller** [comment]
Before I dig into this, try 8.1.3 (it specifically addresses some issues with the override bar)
