### ISSUE TITLE
Perform the action at the touch of the key and not at the release

### ISSUE THREAD

**Issue by Crysto38** [tullamods/Dominos#345]
Hi there, 

I apologize in advance for my English.
I love this addon Dominos since the beginning, but i think we need an option like bartender : 

"Perform the action at the touch of the key and not at the release" because it's important for few players.

I am at your disposal,
Thinking you,

Florian

**Comment by Tuller** [comment]
Dominos obeys the blizzard console variable, ActionButtonUseKeyDown, which actually is set to be enabled by default. This enables the setting:
```/console actionButtonUseKeyDown 1```

This disables it
```/console ActionButtonUseKeyDown 0```

**Comment by Crysto38** [comment]
Thank you for your answer :) 

Indeed we can go through the console but it is not always easy and accessible to everyone.
A single check / uncheck button in the bar menu would be top (general menu or one by one bar) 

Thinks again for your answer

**Comment by Tuller** [comment]
I think for this one, I'll leave it up to people to install AdvancedInterfaceOptions which can adjust this as well as spell queue timing
