### ISSUE TITLE
'AutoCastable' Texture Always Visible

### ISSUE THREAD

**Issue by StormFX** [tullamods/Dominos#347]
**Addon Version**
8.1.3

I seem to remember running into this issue before and I can't remember if we discussed it. Anyhow, the behavior of the default UI is to hide the `AutoCastable` texture when the `AutoCast` state is enabled and its respective frame is shown. _Dominos_ does not currently follow this behavior and the `AutoCastable` texture is always visible. If this is intentional, perhaps it should be optional.

**Comment by Tuller** [comment]
I'm not sure I'm able to verify this one. Here's an auto-cast pet spell on the stock action bars:
![image](https://user-images.githubusercontent.com/191239/56461407-09b1a680-63a2-11e9-8a74-a7319d49e3bd.png)

And here it is on Dominos:
![image](https://user-images.githubusercontent.com/191239/56461420-4087bc80-63a2-11e9-95c5-4cb020d88c4a.png)

**Comment by StormFX** [comment]
I'll check when I get home. I could have swore it hides the `AutoCastable` texture. Maybe my age is catching up with me and my brain went on vacation while I was testing. :p

**Comment by StormFX** [comment]
I looked through the code on my USB and it appears you're correct. I guess that means I'll have to have _Masque_ handle it.
