### ISSUE TITLE
Bar 1 gets locked in corner and won't move in Configure

### ISSUE THREAD

**Issue by Maleroy15** [tullamods/Dominos#348]
Bar won't move and is just locked in the bottom right corner

**Comment by Tuller** [comment]
Are you running the 8.2 version?

**Comment by alexandur92** [comment]
Same issue. I am running 8.2 version of the game.  To reproduce the bug  left click the Dominos icon on the minimap and try to move "action bar 1" . The moment you do that you will get stuck bottom left of the map. After that it completely bugs out

**Comment by DerekWagner** [comment]
Twitch didn't see that there was a new version available.

Went to wowinterface and manually installed 8.2.7 and the issue is resolved.

**Comment by Tuller** [comment]
That was my expectation, hurray :)
