### ISSUE TITLE
Stealth rollbar not being changed to under some circumstances

### ISSUE THREAD

**Issue by Sipollo** [tullamods/Dominos#350]
For several expansions I've been using the following macro on my druid to go into cat form if I'm not in it & then, if not in combat, go into prowl:
```
#showtooltip
/cast [nostance:3] Cat Form(Shapeshift)
/cast [nocombat] Prowl
```
Prior to BfA being released this worked successfully with Dominos - you'd get the right bar selected for going into stealth.

With BfA, the macro works - but only if you start off in human form.

If you're already in cat form, when you hit the button the macro is on the bar ends up going to the default the bar has - which is the caster form one. Not so useful when in cat form!

If you hit prowl directly then the bar correctly changes.

Dominos version: 8.2.7-retail.
Occurs with only Dominos & Dominos-Config as the enabled addons.

**Comment by Tuller** [comment]
Have you tried with the stock action bars?

**Comment by Foxtrek** [comment]
Actually theres an issue with stealthing on the rogue. While in stealth once you use an skill that breaks stealth, dominos takes about 3 seconds to change to the "Out of stealth" bar. Not sure if thats whats causing it but its frustrating because even if you have a separate bar for your out of stealth skills, you still end up using the stealth because the bar hasn't changed.

**Comment by Tuller** [comment]
Can you verify that with just Dominos + Dominos_Config? My quick tests aren't showing a delay.

**Comment by Foxtrek** [comment]
> Can you verify that with just Dominos + Dominos_Config? My quick tests aren't showing a delay.

I will once i get home. I also tried it on feral druid and i got the same issue. So assumed maybe it was related to 8.2 file because it was working perfectly fine before. I'll try and get a clip of the interaction i get regarding it. Thank you for your response.

**Comment by alexgyu** [comment]
> Actually theres an issue with stealthing on the rogue. While in stealth once you use an skill that breaks stealth, dominos takes about 3 seconds to change to the "Out of stealth" bar. Not sure if thats whats causing it but its frustrating because even if you have a separate bar for your out of stealth skills, you still end up using the stealth because the bar hasn't changed.

I noticed this too on my rogue but realized I had the subterfuge talent that enables stealth abilities for 3 secs out of stealth -_-. Not sure if it's the same case for you but might be worth checking since you mentioned the 3 seconds to change bars
