### ISSUE TITLE
One of the bars stuck 

### ISSUE THREAD

**Issue by KasprzykM** [tullamods/Dominos#351]
One of the action bars (Number 1) is stuck to the left side and is not responsive (Cannot move, click or edit). Reseting profile to completely new one makes it move to the middle of the screen, however upon clicking on it once (or trying to move) it bounces back to left corner and stays there unresponsive. The issue is still present after turning all other addons off (I was trying to see if other addons might interfere).

Is this known/unknown bug or is the issue only on mine setup?

Dominos version: 8.1.3

**Comment by DalekOmega** [comment]
I am having the same issue.  I have uninstalled the addon and deleted profiles but whenever I try to move the Number 1 action bar is jumps to the lower left corner of my screen and it wont let me move it anywhere.

**Comment by Tuller** [comment]
You need to install an 8.2 version of Dominos. Curse is frequently bad at updates, so try this one:
https://www.wowinterface.com/downloads/info9085-Dominos.html

**Comment by KasprzykM** [comment]
Confirmed, 8.2.9 version from wow interface and the issue is gone. Thank you so much :)
