### ISSUE TITLE
Action Bar #1 moves

### ISSUE THREAD

**Issue by Nigok** [tullamods/Dominos#352]
when i try to move my #1 bar it goes to the far left corner at the bottom, i cannot move the bar whatsoever 
![Capture](https://user-images.githubusercontent.com/52572337/60724650-56cffe00-9f37-11e9-93c2-69ad06b2211e.PNG)

**Comment by Tuller** [comment]
This is already fixed - make sure you're running the 8.2 version (/dom version can tell you)

**Comment by Drevneus** [comment]
Hello, but bug still here...

**Comment by Drevneus** [comment]
Oh, it turned out that our favorite tweet client did not update the new versions ... And when reinstalling, it installs 8.1.3 (it shows it as the last). Although the file list has new versions and it turned out manually.

Please do something, people suffer =) In the comments on the add-on page too.

**Comment by Nigok** [comment]
The issue issnt there if you just download and I stall it from the curse website then its updated to 8.2

**Comment by Drevneus** [comment]
Yes, i mean that through the application Twitch, version 8.1.3 is installed. For some reason, he doesn`t want to update new versions. I would not have thought that they are =)
