### ISSUE TITLE
Masque: Individual skins for each action bar? 

### ISSUE THREAD

**Issue by xStiven** [tullamods/Dominos#353]
I don't know where else to ask, so i guess its may count as "suggestion" of "enhancement". So, it is possible to have individual skins options of each individual action bar? For example action-bar 1 has Skin №1 and action-bar 2 have Skin№2. In Masque configuration menu, there is subsections for Dominos/RegisteredButtons(or something like that), but it has option to change skins only for ALL actions bars, and some other categories, but not for individual Action-bars. I missing something and there is a way to change skins individually, or it just not possible?

**Comment by Tuller** [comment]
Still working on this. It’s actually surprisingly non trivial to do in Dominos

**Comment by srcesaribeiro** [comment]
Hey Tulles. Thanks for the great add-on. Will this feature ever come to classic? Thank you.

**Comment by Tuller** [comment]
I've gotten to this while working on the 9.0 updates
![image](https://user-images.githubusercontent.com/191239/90345509-b6407e80-e010-11ea-8335-a03c435e9020.png)
