### ISSUE TITLE
One Bar Mode improve

### ISSUE THREAD

**Issue by TheHDX** [tullamods/Dominos#354]
It would be really great if there was an option to disable "old" progress bars. One Bar mode is good feature but i'd like to remove tracking of artifact power, reputation etc. Mainly because it usually switches to XP one even on max level.

Edit: Simple checkbox in Progress tab would be perfect

Thanks.

**Comment by Tuller** [comment]
Since I already have detection for inactive modes built in, I can probably just make it so click cycling skips any modes you don't have yet.

**Comment by TheHDX** [comment]
Would be nice to see!

**Comment by Tuller** [comment]
This is implemented in 8.2.11: When you click on the bar to switch modes, only active ones are taken into account.

**Comment by TheHDX** [comment]
Cool, btw why doesn't twitch app automatically download newest release versions? I have to do it manually on version page everytime..

**Comment by Tuller** [comment]
Curse is bad about handling classic and live builds.

**Comment by Tuller** [comment]
Are you running the same dominos profile on both characters?

**Comment by TheHDX** [comment]
Yes

**Comment by Tuller** [comment]
I've made the mode portion per character instead of per profile.

**Comment by TheHDX** [comment]
Everything looks good now. Thanks!
