### ISSUE TITLE
Option to remove actionbar frame border

### ISSUE THREAD

**Issue by smoothys** [tullamods/Dominos#358]
Please add an option to remove the frame border around each Icon / slot on the action bars for a more puristic visual.

A global setting in config would be nice, but it would be ok to have the setting for each actionbar.

Bartender4 has this feature and I would like to see it here too, since Dominos is the better addon.

**Comment by Tuller** [comment]
Do you have a screenshot of exactly what bit you want to remove? By default, Dominos trims button icons to remove the border from older buttons. If you install Masque, then Dominos relies on that to handle skinning.

**Comment by smoothys** [comment]
![bartendervsdomino](https://user-images.githubusercontent.com/54029787/63106845-06ab7900-bf84-11e9-9957-d4e9d2a6724a.png)
On the top you can see bartender, below is dominos. This is meant for classic client, not sure if I am even correct here

**Comment by Tuller** [comment]
I think your best bet for this one is to use Masque
