### ISSUE TITLE
Reputation/XP bar with multiple character

### ISSUE THREAD

**Issue by Guema** [tullamods/Dominos#359]
**Is your feature request related to a problem? Please describe.**
I'm using a unique profile for all my characters, for many reasons :
- easier to spread a change in profile over all my characters instead of copying on all profiles
- easier to setup for a new character
- I want to keep the same interface for the whole game

But this comes with a problem. When i switch my main XP bar to track reputation on my lvl 120 characters, my 110 chars will also get modified. I know it's take only one click to change, but, i have to do it each time i switch between low level alts and main or max level alt

**Describe the solution you'd like**
Because the XP and reputation bar is really character-bounded info (You don't always track the same reputation, you can play a low level alt etc...) I think it make sense the XP/reputation bar display state should be always stored as character-bounded info, regardless the chosen profile. Letting ppl chose what to show on each of their character.

**Comment by Tuller** [comment]
This should be fixed with the latest version (8.2.13)

**Comment by Guema** [comment]
I tested with the last version, working very well !
Bravo !
Thx for ur attention and all your amazing work
