### ISSUE TITLE
One bag mode does not properly remove the other bag buttons

### ISSUE THREAD

**Issue by ShaunDreclin** [tullamods/Dominos#360]
![Screenshot](https://user-images.githubusercontent.com/5851433/63788366-57e03480-c8c3-11e9-83f4-455903eb5bce.gif)

**Addon Version**
8.2.13-Classic

**Comment by Tuller** [comment]
Are you running any other addons? I'm not seeing the buttons on a quick test

**Comment by arunasliveris** [comment]
Same issue here, it's very annoying.

**Comment by Tuller** [comment]
This should now be fixed

**Comment by ShaunDreclin** [comment]
Confirmed, fixed as of 8.2.14-Classic

Thanks!
