### ISSUE TITLE
Protected function: DominosActionButton30:Show()

### ISSUE THREAD

**Issue by A6GibKm** [tullamods/Dominos#363]
I got a lua error while in combat with the function `DominosActionButtonX:show()`. This is similar to #254, but this is in Classic.

**Addon Version**
8.2.13-Classic

##  Trace

```1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton30:Show()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Show'
FrameXML\ActionButton.lua:357: in function `ActionButton_Update'
FrameXML\ActionButton.lua:695: in function `ActionButton_OnEvent'
FrameXML\ActionButton.lua:207: in function <FrameXML\ActionButton.lua:204>```

Locals:
InCombatSkipped

**Comment by Tuller** [comment]
Under what context did this happen?

**Comment by A6GibKm** [comment]
Playing warrior, combat... I will try to pin it down more precisely, but it seemed more or less random.

**Comment by A6GibKm** [comment]
I have not seen this again since I reported it. Closing it for now.

**Comment by akaij** [comment]
I just got this on my lev19 warrior in The Barrens. I also had a lot of quest objectives shown on the map because, well, it's Barrens, and I think it's related to that. The bug completely disappeared once I finished some quests which I think cleared the displayed icon limit the client was hitting.
