### ISSUE TITLE
Failed to load ProgressBars

### ISSUE THREAD

**Issue by createdbyfran** [tullamods/Dominos#364]
If applicable, try reproducing your issue with just Dominos and Dominos_Config enabled. This helps route out issues that are due to either conflicts with other addons, or Dominos modules that are not part of the core, like Dominos_Units.

**Addon Version**
/dominos version 8.2.16-classic

Interface\AddOns\Dominos_Progress\config.lua:40: attempt to index filed '?' (a string value)

My experience bar not working and the progress bar in the menu not appearing.

**Comment by cyberze** [comment]
http://prntscr.com/p0amnw
