### ISSUE TITLE
Green bar under the options, (question mark / game menu button)

### ISSUE THREAD

**Issue by Navoxctr** [tullamods/Dominos#365]
There is a new green bar that appears under the question mark button (Game Menu) How can we remove this?

**Comment by Tuller** [comment]
Do you have a screenshot?

**Comment by Navoxctr** [comment]
Screenshot https://imgur.com/a/MXpp7Ec

**Comment by Tuller** [comment]
This is now fixed

**Comment by Navoxctr** [comment]
Thank you so much Tuller!
