### ISSUE TITLE
Action bar paging

### ISSUE THREAD

**Issue by GreyFoxGer** [tullamods/Dominos#366]
There is a problem with action bar paging, after unit exited vehicle.

Example: Action Bar #1, switches (shift+arrow) normally one time and back.

After exiting vehicle it starting to switch between all panels.

**Addon Version**
Dominos: 8.2.16-Retail

**Comment by Tuller** [comment]
That may actually be a bug on Blizzard's end. Can you test without Dominos running?

**Comment by cheetahfox** [comment]
I am also having problems with Action bar paging. In my case it's with druid cat form.

I have action paging setup switch to Action bar 7 in cat form but it switches to Action bar 9 (which is shared with bear). Bear form works correctly but in Cat form or when I prowl there is no action bar paging.  Without the Dominos loaded action bar paging works correctly.

**Comment by Tuller** [comment]
Classic or retail?

**Comment by cheetahfox** [comment]
Sorry, in classic (version 1.13.2.31687).

**Comment by Tuller** [comment]
Try again with 8.2.21.

**Comment by cheetahfox** [comment]
Working correctly now with 8.2.23. Thanks!
