### ISSUE TITLE
XP bar is not updating

### ISSUE THREAD

**Issue by Aixler** [tullamods/Dominos#367]
After updating today, my xp bar is no longer updating.
Change its size or something will cause it to update once, but earning xp won't trigger an update.

**Comment by Tuller** [comment]
This should be fixed in the latest release (8.2.17)

**Comment by xenoph** [comment]
Does not update for me with 8.2.17, in Classic.

**Comment by Tuller** [comment]
What about in 8.2.18?

**Comment by xenoph** [comment]
Works for me now with 8.2.18. Thank you for the fix!
