### ISSUE TITLE
Not functioning MacOS

### ISSUE THREAD

**Issue by Vbrorson** [tullamods/Dominos#368]
The addon wont function on my macbook? 
There is no issue putting the file in the addons folder, but the game wont recognize it or show it, in the addons menu (on login).

Addons such as Questie, Auctionator does work.

**Comment by Tuller** [comment]
Are you getting any error messages? I'm assuming you have Dominos + Dominos_Config in your addons folder (at the root that is)

**Comment by Vbrorson** [comment]
There are no errors. The file does contain Dominos_Congif in a subfolder.
It's added correctly in the addon file as well, with other addons, where
the other addons are functioning correctly.

The addon simply doesn't show in the "addons" alternatives.

søn. 1. sep. 2019 kl. 16:44 skrev Jason Greer <notifications@github.com>:

**Comment by Tuller** [comment]
so what you should see in Interface/AddOns folder is something like
* Dominos
* Dominos_Config
* and others

It sounds like you have a single folder, Dominos, and within that is Dominos and Dominos_Config. A screenshot of your finder window might help.

**Comment by Vbrorson** [comment]
Correct. Here is a screenshot of a) Interface/AddOns
and b) interface/AddOns/Dominos

Impressively quick response time, I truly appreciate your help!


fre. 6. sep. 2019 kl. 00:39 skrev Jason Greer <notifications@github.com>:

**Comment by Tuller** [comment]
It does not look like they attached.

**Comment by Vbrorson** [comment]
My mistake. I was replying through my mail application.

fre. 6. sep. 2019 kl. 00:47 skrev Jason Greer <notifications@github.com>:

**Comment by Tuller** [comment]
try moving everything inside of the Dominos folder into the main addons directory. Same with OmniCC

**Comment by Vbrorson** [comment]
Brilliant, it worked! Thanks.

fre. 6. sep. 2019 kl. 01:12 skrev Jason Greer <notifications@github.com>:
