### ISSUE TITLE
(macos) Setting keyboard shortcut with command key doesn't work

### ISSUE THREAD

**Issue by nikgervae** [tullamods/Dominos#371]
**Addon Version**
8.2.13

I tried to set a keybind using the command key; for example, command+s. It didn't work; Dominos instead set the keybind to control+s, which is not what I typed, so if I later press command+s, nothing will happen.

If Dominos cannot actually set a keybind containing the command key, it should not set a keybind and should present an error message to the user.

Note: I did try setting such a keybind in the WoW client keybinds window, and it too failed but in a different way, simply omitting the command key from the bind. Do note that the macos WoW client has an option to treat the command key as a control key, but I do not have that option selected. If it is active, then of course pressing command+s should set the keybind to control+s.

**Comment by Tuller** [comment]
You may want to report this over here, as this is the library that Dominos uses
https://www.wowace.com/projects/libkeybound-1-0

**Comment by nikgervae** [comment]
Thank you, I'll check that out and post appropriately.

**Comment by Tuller** [comment]
In the 9.0 version, I've made two adjustments:
* All Dominos' action buttons are now available via the standard bindings menu in addition to /kb
* Dominos supports the new quick binding mode.

This doesn't fix KeyBound, but it does at least provide an option that you can check out once the patch is released this week.
