### ISSUE TITLE
spells will be placed automatically in actionbar1 in a hidden button

### ISSUE THREAD

**Issue by Sovereign1987** [tullamods/Dominos#372]
Hello

I have found a problem with the dominos actionbar1. I have seen that when I use a spell, the effect on the button when the spell is ready comes outside my actionbar.

I checked that out and found out that I have spells in hidden buttons. My actionbar has a size 8 buttons and 8 columns. Now when I log in, blizzard will be placed automatically spells who I did not have on a actionbar to the actionbar1.

For Dominos self is ok, the spells with not be visible in my bar but the UI thinks this buttons are active and shows the effect from the global spells "ready effect". it then flashes briefly next to the actionbar.
![WoWScrnShot_090619_193520](https://user-images.githubusercontent.com/37331548/64448385-d916a300-d0dd-11e9-81bf-378283663fc8.jpg)

I have to set the actionbar to size 12 and columns 12 and then reduce to 8/8 but when i received new spells I have the problem again.

it looks like the UI ignores the actionbar button size when the character received new spells.

sorry for my bad english, I hope I could explain it reasonably

best regards,
Jan

**Comment by Tuller** [comment]
Can you try with just Dominos + Dominos_Config enabled? I think that maybe another addon at fault.

**Comment by Sovereign1987** [comment]
Hi, have tried with only dominos + config and same problem. I can reproduce it by removing my pvp (war mode) buttons from the bar, unplugging them and logging in again. the pvp talents are automatically added to the action bar1, although this is limited to 8 places. This then creates the effect bug.
here you can see that the talent will be added to hidden button. The size of actionbars are 8. when i now use a spell i can see the effect above on this hidden buttons.
![WoWScrnShot_090719_152507](https://user-images.githubusercontent.com/37331548/64475538-63194700-d184-11e9-88e5-74b63819a75e.jpg)

I do not know since when this is. I noticed it only 2 weeks ago.

**Comment by Tuller** [comment]
Try with 8.2.25 once it is uploaded.

**Comment by Sovereign1987** [comment]
Hello, sorry i had forgot to test with 8.2.25 but now have 8.2.26 and works perfect now.

Thanks for fix it :)
