### ISSUE TITLE
XP-bar missing

### ISSUE THREAD

**Issue by Vbrorson** [tullamods/Dominos#373]
When enabling the dominos addon, my xp-bar goes missing.

How do I enable it?

**Comment by Tuller** [comment]
Is Domimos progress enabled?

**Comment by Vbrorson** [comment]
Can't seem to find it. I only have commands available? /dom etc


lør. 7. sep. 2019 kl. 17:53 skrev Jason Greer <notifications@github.com>:

**Comment by Tuller** [comment]
I mean if you check your installed addons. If not, you may want to reinstall Dominos.
