### ISSUE TITLE
XP Bar Blank on Load

### ISSUE THREAD

**Issue by giannim24** [tullamods/Dominos#374]
After loading, the XP bar does not show any of the filled part. A workaround I have found is to click the bar, which will show the reputation, then click it again which will bring the XP bar back and working correctly.

![image](https://user-images.githubusercontent.com/55122368/64581837-d8ce1000-d348-11e9-8c97-d7c7c4b872dd.png)
After logging in

![image](https://user-images.githubusercontent.com/55122368/64581856-e7b4c280-d348-11e9-8d16-2957eb654ce9.png)
After workaround

**Addon Version**
8.2.24-Classic

**World of Warcraft Version**
Classic

**Comment by Tuller** [comment]
I've not reproduced this one yet.

**Comment by Tuller** [comment]
I think 8.2.27 finally nails this down.
