### ISSUE TITLE
Bug: no background in action bar

### ISSUE THREAD

**Issue by mixMugz** [tullamods/Dominos#375]
Last version. No background with masque.

**Comment by Tuller** [comment]
What Dominos version, what masque version, and what skin?

**Comment by Tuller** [comment]
This is what I see when I do show empty buttons in Dominos with 8.2.25 + masque 8.2.7:
![image](https://user-images.githubusercontent.com/191239/64898789-11872580-d678-11e9-9b4b-8a29021207c6.png)

**Comment by mixMugz** [comment]
Same problem with all other skins. In another plugins (uses masque) problem not exist. Only in Dominos

**Comment by mixMugz** [comment]
Actually i mean no background texture. There is same settings in bagnon
![111](https://user-images.githubusercontent.com/17923916/64992303-485d7580-d8dc-11e9-9236-cfadcbea0ad7.png)

**Comment by mixMugz** [comment]
And this screen from old version. Prior 8.2.24
![222](https://user-images.githubusercontent.com/17923916/64992807-58298980-d8dd-11e9-8a1e-0c5bde28d401.png)

**Comment by Tuller** [comment]
I'm not sure what may be causing that. it is showing up for me with 8.2.7 and Dominos 8.2.26, provided i check the backdrop option for the skin.

**Comment by mixMugz** [comment]
Can you give screen? I have checked backdrop option, but no background texture

**Comment by Tuller** [comment]
Here's what i see, and here are my settings:

![image](https://user-images.githubusercontent.com/191239/65379003-2f174900-dc8f-11e9-86de-43ce206390ca.png)

![image](https://user-images.githubusercontent.com/191239/65379005-38081a80-dc8f-11e9-8a25-3b0a084ca628.png)

**Comment by mixMugz** [comment]
Ok. It's not your fault. I found what backdrop changed in Claith. It's not dominos problem. Sorry
