### ISSUE TITLE
Multiple issues with recent update

### ISSUE THREAD

**Issue by boomslang72** [tullamods/Dominos#377]
1)
The XP and Azerite Bars are showing up blank on character Log In.  On one of my characters, the Azerite Bar keeps changing to the Artifact Bar (and shows blank).  This issue has been posted as a bug already.  The work around is to Click on the bars for them to show correctly again.
2)
Buttons that show stacks are shifted too far over, past the button borders.  On my Balance druid, the Lunar Strike and Solar Wrath stack counts are moved off the button backgrounds.  I had to turn off my Masque skins because using a Skin makes them completely hidden.  Previous to this latest update, the stack counts were centered.
3)
I moved some buttons around on my action bars recently.  During combat, a few of my buttons are resetting back to their old positions.  If I reload my UI or I log out and log back in, they will reset to their proper positions.

Not sure why there are suddenly so many issues with this add on.  This add on was working perfectly for a very long time...

**Comment by Tuller** [comment]
1: Can you try with the latest beta (8.2.26)?
2: Masque recently made some updates that break compatibility with previous versions. Are you having this issue with all skins? Does it happen with Masque disabled?
3: Can you try replicating this one with just Dominos + Dominos_Config?
