### ISSUE TITLE
Warrior Stance Changes

### ISSUE THREAD

**Issue by Zahele** [tullamods/Dominos#378]
If applicable, try reproducing your issue with just Dominos and Dominos_Config enabled. This helps route out issues that are due to either conflicts with other addons, or Dominos modules that are not part of the core, like Dominos_Units.

**Addon Version**
8.2.23

**World of Warcraft Version**
1.13.2.31830

Occassionally (once every 6 hours or so) when changing warrior stances all of the bars will duplicate bar #1 or go completely blank. A simple relog fixes this issue. I've been unable to replicate it reliably. I'll give the Config enabled bit a go and post what I find.

**Comment by Tuller** [comment]
You might be hitting shift + mousewheel or shift + number. Shift + 1 will reset the bar in that case.
