### ISSUE TITLE
Ability to turn of extra addons through lua

### ISSUE THREAD

**Issue by DennisJohnsen** [tullamods/Dominos#381]
I'm missing an ability to turn of the extra addons that Dominos is bundled with, such as roll window and castbar.

The issue with simply deleting the addons, or disabling them will make them appear again when Dominos is updated through the Twitch app.

This would be very beneficial for creating custom UI's that is ment to be shared, so the steps of setting up the UI is easier.

Kind regards
Dennis

**Comment by Tuller** [comment]
I'm adding a new field for enabled modules on a per profile basis, so you can now modules like this:

```lua
Dominos.db.profile.modules.ActionBars = false
Dominos.db.profile.modules.BagBar = false
Dominos.db.profile.modules.CastBar = false
Dominos.db.profile.modules.MenuBar = false
Dominos.db.profile.modules.PetBar = false
Dominos.db.profile.modules.ProgressBars = false
Dominos.db.profile.modules.RollBars = false
Dominos.db.profile.modules.StanceBar = false
Dominos.db.profile.modules.VehicleBar = false
```

This check is done when Dominos calls its Load method. This happens after PLAYER_LOGIN and also after a new profile is loaded.

**Comment by DennisJohnsen** [comment]
And it's already released. My man.. Nice job :) Thank you!
