### ISSUE TITLE
Buff Bar Configuration Disappeared - WoW Classic

### ISSUE THREAD

**Issue by ProteJJ** [tullamods/Dominos#385]
Hello I'm using version: 8.2.30-classic
When I first installed dominos it was possible to move/resize/configure the buffs bar. A while ago, the blue box" which buffs would be present disappeared and now I cannot edit/configure my buffs bar. Whenever I have a buff, the icon is small (approx the size of the dominos button on the minimap) and pushed very close to the minimap which hides the majority of the first buff present. 

Please advise! 

Thank you.

If applicable, try reproducing your issue with just Dominos and Dominos_Config enabled. This helps route out issues that are due to either conflicts with other addons, or Dominos modules that are not part of the core, like Dominos_Units.

**Addon Version**
You can get this via running `/dominos version` in game

**World of Warcraft Version**
Classic, Retail, PTR

**Comment by Tuller** [comment]
That’s a feature of a different addom

**Comment by ProteJJ** [comment]
Think that would be Simple Unit Frames? 
I'm not using a lot of mods I dont think... questie, libclassicmobhealth, bagnon, Simpleunitframes, coordinates by tomcat tours, dominos, leatrix maps. tomcat's tours, leatrix plus. 

All classic version mods of course

**Comment by Tuller** [comment]
It might be yes.
