### ISSUE TITLE
Bar Override

### ISSUE THREAD

**Issue by Vaeltash** [tullamods/Dominos#386]
Got this every time a bar override occours.

2x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'OverrideActionBarButton2:Show()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Show'
FrameXML\ActionButton.lua:368: in function <FrameXML\ActionButton.lua:342>
[C]: in function `ActionButton_Update'
FrameXML\ActionButton.lua:736: in function `ActionButton_OnEvent'
FrameXML\ActionButton.lua:211: in function <FrameXML\ActionButton.lua:208>

Locals:
InCombatSkipped

**Comment by Tuller** [comment]
Closing this one, as I reduced some more possible taint vectors in 9.0
