### ISSUE TITLE
Dominos Cast uninterruptible cast "Gray"

### ISSUE THREAD

**Issue by strickland** [tullamods/Dominos#390]
**Is your feature request related to a problem? Please describe.**

It is not related to a problem, it's just a normal feature within blizzard castbar that I am missing.

**Describe the solution you'd like**

When you are casting and if the enemy cannot interrupt that cast, the castbar should show as gray colored, which indicates that I can keep on casting and it will not be interrupted, Just like the behavior of the default blizzard castbar, try it in nazjatar, there's a spot where you can cast to loot something from the ground and the enemies cannot interrupt that cast, this should look gray, this helps me know that I can keep on casting before killing the mobs etc.

**Describe alternatives you've considered**

**Additional context**

If you go to Nazjatar, around Ashen Strand, there are some lootable small mobs that gives an achievement, if you loot those the cast should be gray, similarly if you are a paladin and you cast the uninterruptable ability, your cast shall be gray too, try it within blizzard castbar, then try it with dominos castbar.

**Comment by Tuller** [comment]
This should actually be implemented n ow.
