### ISSUE TITLE
Artifact Power/Azerite Power

### ISSUE THREAD

**Issue by paradisewoods** [tullamods/Dominos#392]
Can we eliminate the Artifact Power part of the bar? Artifact Power is gone, and every once in a while my bar goes from AzP to ArP. While I admit possible player responsibility (I shouldn't have the bar where I can click on it, assuming that's what's happening), I'm not sure why it's still there (is it something on Blizzard's end preventing its removal?).

**Comment by Tuller** [comment]
I'll prevent artifact from being available as a bar mode for 8.0 clients and later
