### ISSUE TITLE
Soul shards no longer working

### ISSUE THREAD

**Issue by Lohoris** [tullamods/Dominos#396]
Since today's update, the spells requiring soul shards as a component, no longer show their count.

The items in the bar still work as expected, though.

Attaching a screenshot…

<img width="786" alt="Screenshot 2019-12-11 at 15 08 18" src="https://user-images.githubusercontent.com/207821/70638235-6bc06400-1c30-11ea-9fd3-c0033b6486c4.png">

**Comment by Axaion** [comment]
Same for Blind and Vanish

**Comment by Tuller** [comment]
I have a feeling that this was intentional on Blizzard's end.

**Comment by Lohoris** [comment]
> I have a feeling that this was intentional on Blizzard's end.

Do you think we have any other way to access the soul shard count? (like looking at the bags etc)

It's extremely annoying not to have it :/

I mean: it doesn't have to be bound to the specific spell, as soon as I can display that count somewhere in the page (I guess that would basically be a separate addon, but worth pursuing).

**Comment by Dyaxler** [comment]
I think Blizzard broke...
`currentCharges, maxCharges, cooldownStart, cooldownDuration, chargeModRate = GetSpellCharges(spellId or "spellName")`
...this function is no longer returning anything. Not only Soul Shards but any spell that requires a Reagent such as Paladins Greater Blessings, Druids Rebirth, Mage Portals etc.

**Comment by Axaion** [comment]
That would suck fairly hard, as their default actionbar still shows it

**Comment by Lohoris** [comment]
> That would suck fairly hard, as their default actionbar still shows it

In that case I'd assume it's a bug.

Or maybe they renamed that property to something else?

**Comment by Axaion** [comment]
I found something out, it depends on what actionbar you use, as in you have to use the actionbar that would show on default actionbars, to get the reagent count to show.

For example, if i have blind in "Dominos Actionbar 2" it wont show it, because that would not be there for default actionbars, but if i put it in "Dominos Actionbar 5" it will show the reagent count on blind, this bar also shows when you enable it with pure default actionbars

I can only guess this is just blizzard fucking with us.

**Comment by Lohoris** [comment]
> I found something out, it depends on what actionbar you use

Not entirely sure what you mean there: I've just tried to move it to every single action bar, from 1 to 10, and it didn't work in any of them.

**Comment by Axaion** [comment]
Weird.. :\

**Comment by Tuller** [comment]
I've implemented reagent counts in the latest classic version (8.2.33)

**Comment by Axaion** [comment]
> 
> 
> I've implemented reagent counts in the latest classic version (8.2.33)

Unsure if its just me, but with this update it stopped showing numbers of potions, grenades, food and so on

Does show blind/vanish now however

**Comment by Tuller** [comment]
That one was a bug on my end.

**Comment by Axaion** [comment]
Yep, confirmed working after bugfix update!

**Comment by Lohoris** [comment]
That's really awesome, thanks for the fix!
