### ISSUE TITLE
Question: Static action bars in dominos?

### ISSUE THREAD

**Issue by xStiven** [tullamods/Dominos#398]
Hello! Do it possible to make a "static" action bar in dominos? Meaning, the action bar will not change it "content" when you change spec? What is "overide ui" for?

**Comment by Tuller** [comment]
For the first part: right click the main bar in config mode, and turn off the various paging settings.
For the second part: Its's for vehicles and other times when you completely switch from one set of abilities to another during an encounter.

**Comment by Lohoris** [comment]
I also have this problem, and I already tried to disable paging, except it was already disabled.

For me, every single bar is changed if I change spec, despite only bar 1 is set as paged.

**Comment by Lohoris** [comment]
Also, I'm not entirely sure how is paging would be supposed to work anyway.

It would more intuitive for me to just have a flag "page it", "don't page it", but I guess the current implementation is bound to how it works internally in the wow engine?

**Comment by Tuller** [comment]
I think I misread the initial comment. The contents of your action bars is saved per spec on Blizzard’s end and there is no way to disable that behavior that I’m aware of.

Quick paging is for using certain hot keys (called action page) to swap between bars. Prior to 8.0, these defaulted to shift + number and shift + mousewheel.
