### ISSUE TITLE
Error as soon as I enter combat.

### ISSUE THREAD

**Issue by Dirtywiz** [tullamods/Dominos#400]
Hi, 

I get an error every time I'm in combat. All and all, everything seems to be working great.
I can see all my bars and they work as intended, but I get my chat & BugSack filled with the same error message and I can't figure out why.
I have tried to look for the source of it, but I can't seem to figure it out with the limited knowledge and experience I've got with .lua. 

The error occurs with only Dominos + Dominos Config enabled. 

**Addon Version**
Dominos version: 8.2.31-classic

**World of Warcraft Version**
Classic

**Error Message**
123x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton47:Show()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Show'
FrameXML\ActionButton.lua:357: in function `ActionButton_Update'
FrameXML\ActionButton.lua:695: in function `ActionButton_OnEvent'
FrameXML\ActionButton.lua:207: in function <FrameXML\ActionButton.lua:204>

Locals:
InCombatSkipped

Any idea what's going on here? 

Best Regards, 
DirtyWiz

**Comment by Dirtywiz** [comment]
I don't know but it might be worth mentioning that I'm a warrior. However, it doesn't seem to be related to Overpower/Execute/Shield Block as far as my testing goes.

**Comment by Tuller** [comment]
Sounds like a tainting issue, but I'm not sure the source quite yet.

**Comment by Tuller** [comment]
Closing due to 9.0 changes that I’ve made to reduce taint a bit
