### ISSUE TITLE
Bug after game starts

### ISSUE THREAD

**Issue by lulavc** [tullamods/Dominos#401]
After login... that show up.

Using latest version on wow classic.

1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function '<unnamed>:Hide()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Hide'
Dominos\core\configOverlay.lua:563: in function <Dominos\core\configOverlay.lua:562>

**Comment by lulavc** [comment]
It started when i started using the action bar 7 with 4 columns.

**Comment by Tuller** [comment]
I've not reproduced this one.
