### ISSUE TITLE
Horrific Vision Sanity Button

### ISSUE THREAD

**Issue by Talimar** [tullamods/Dominos#404]
Seems Dominos isn't hooking into the extra action button you get in the new horrific visions. 
The button shows up in it's default spot without binding.

**Comment by jlschuncke** [comment]
Confirmed. This cost me a Tier 2 run because my Encounter bar was positioned on top of the unmodified button for Orb Operation Manual. If it had gone to the Extra button (like I suspect it should), no problem.

**Comment by Tuller** [comment]
can you do a /fstack and determine the name of the button?

**Comment by Tuller** [comment]
Please try the beta for this one:
https://github.com/tullamods/Dominos/releases/tag/8.3.1-beta2

**Comment by Talimar** [comment]
Hey. Sorry about the late response. Haven't done any more visions until today.
Does this help? I probably should have moved my weakauras first, but this is holding the mouse directly on the button. Using the beta version.
https://i.imgur.com/iE7KE6a.png

**Comment by Tuller** [comment]
Dominos doesn't actually handle the zone ability frame, so that could be why its in the way at least. Most other reports I had gotten were about PlayerPowerBarAlt, which is what the beta updates the handling for

**Comment by Talimar** [comment]
Yeah, I did some islands today and picked up an on-use item that gave a button in the same spot. And it was draggable to my bars. Just never occurred to me to try the same in visions, being the panic rooms that they are. Closing :)
