### ISSUE TITLE
Cooldown frame for ExtraActionButton is too small

### ISSUE THREAD

**Issue by jcai1** [tullamods/Dominos#405]
The cooldown sweep for the extra action button is too small:
https://i.imgur.com/PJuZ0Yi.png

I verified that this is still an issue with fresh Dominos settings, only changes are: for Extra Bar: Scale = 80, Show Blizzard Texture = Unchecked.

**Addon Version**
8.3.0-retail

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
Does it look like that without Dominos enabled?

**Comment by jcai1** [comment]
Looks okay without Dominos enabled: https://i.imgur.com/O5iYwFC.png

Seems from the Blizzard XML that the cooldown frame has a fixed offset from the extra action button:

    <Cooldown name="$parentCooldown" inherits="CooldownFrameTemplate" parentKey="cooldown">
        <Anchors>
            <Anchor point="TOPLEFT" x="5" y="-4"/>
            <Anchor point="BOTTOMRIGHT" x="-5" y="5"/>
        </Anchors> 
    </Cooldown>

So my current workaround is just:

    ExtraActionButton1Cooldown:ClearAllPoints()
    ExtraActionButton1Cooldown:SetAllPoints()

**Comment by Tuller** [comment]
Try the 8.3.1-beta when its gets built:
https://github.com/tullamods/Dominos/releases/tag/8.3.1-beta

**Comment by jcai1** [comment]
Appears to be fixed. Thanks.
