### ISSUE TITLE
AP Bar missing 

### ISSUE THREAD

**Issue by ocandoe** [tullamods/Dominos#406]
I cant see my AP bar, anyone same?

**Comment by Tuller** [comment]
Is Dominos_Progress enabled? Do you see where it would be in config mode?

**Comment by afterlyfe666** [comment]
also happned to me a few days ago, i get the exp,rep bar just not AP

**Comment by Tuller** [comment]
Also out of curiosity, what version are you running? Its possible that you accidentally got the version for classic.

**Comment by afterlyfe666** [comment]
twitch seepushed a few classic addons onto me, i forced an older dominos intall and it fixed it.

seems to be a twicth issue.  this is not the only addon break when updating through twitch

**Comment by ocandoe** [comment]
Solved ... For any reason twich replace for me the versión of Domino for the domino classic i dont know why
