### ISSUE TITLE
horrific visions the extra action button will not replace the blizzard UI button which is burried undeer my actin bars lol

### ISSUE THREAD

**Issue by Visonea** [tullamods/Dominos#407]
If applicable, try reproducing your issue with just Dominos and Dominos_Config enabled. This helps route out issues that are due to either conflicts with other addons, or Dominos modules that are not part of the core, like Dominos_Units.

**Addon Version**
You can get this via running `/dominos version` in game

**World of Warcraft Version**
Classic, Retail, PTR

**Comment by Tuller** [comment]
Have you tried the beta?

**Comment by Tuller** [comment]
This should be available by the new Zone bar, which defaults to the right side of your screen
