### ISSUE TITLE
Button Macro Function Broken.

### ISSUE THREAD

**Issue by D25527** [tullamods/Dominos#408]
I am having difficulty with certain macro functions in Classic when I use Dominos. One of the ones I have trouble with is: 

#showtooltip
/cast [btn:2] Conjure Water
/use Conjured Spring Water

If I disable the mod it works. If it is enabled it will consume the water, but the button:2 or btn:2 does not. I am not sure what is going on as it worked for a few weeks but stopped. Reinstalling thru twitch does not fix it.

**Comment by Tuller** [comment]
Try
```
#showtooltip
/cast [btn:2]Conjure Water;Conjured Spring Water
```

**Comment by D25527** [comment]
No joy. I have reverted to a mod:shift to conjure water. This is the only button mod I use so its a minor inconvenience.

**Comment by Tuller** [comment]
Im pretty sure I replicated this on the stock action bars too, so it will be an interesting thing to fix
