### ISSUE TITLE
Pet bar doesn't appear

### ISSUE THREAD

**Issue by venzeg** [tullamods/Dominos#410]
**Addon Version**
8.3.1-classic

**World of Warcraft Version**
Classic

I'm a druid and don't have pet bar required for most of the times. But in some encounters it doesn't appear as expected. Currently, can't control a tank in Darkmoon faire. It seems that code

```
function PetBar:GetShowStates()
	return '[@pet,exists,nopossessbar]show;hide'
end
```

is not working correctly thinking that no pet does exist. If I remove "exists" part from the code, pet bar starts to appear properly, but now it always shows pet bar during character login:
![petbar](https://user-images.githubusercontent.com/60940596/74267999-272c7400-4d18-11ea-90ca-12740c5ad995.png)

Would be grateful for a fix.

Regards

**Comment by Tuller** [comment]
The simplest case might be this for classic:
```lua
function PetBar:GetShowStates()
    return '[pet]show;hide'
end
```

**Comment by Tuller** [comment]
This is implemented the beta, in case you've not had a chance to try it.

**Comment by venzeg** [comment]
Soz for a long response, it works fine for me on beta

**Comment by Tuller** [comment]
Yay
