### ISSUE TITLE
Extra Action Button Resets

### ISSUE THREAD

**Issue by Rustyb0y** [tullamods/Dominos#411]
Everytime I load the game up the Extra Action Button position resets to it's default poistion.  In order to fix this I have to open config and right click on the correct buttons position.

**Addon Version**
8.3.1-retail

**World of Warcraft Version**
Retail

![dominos1](https://user-images.githubusercontent.com/54157890/74578597-e9666e80-4fe9-11ea-8683-2b7640e5091a.png)
![dominos2](https://user-images.githubusercontent.com/54157890/74578602-ee2b2280-4fe9-11ea-927c-675135914c7a.png)
![dominos3](https://user-images.githubusercontent.com/54157890/74578608-f2efd680-4fe9-11ea-83aa-649f32811f99.png)
![dominos4](https://user-images.githubusercontent.com/54157890/74578613-f7b48a80-4fe9-11ea-8301-01a38c6a037b.png)

**Comment by Tuller** [comment]
Does this occur with just Dominos enabled?

**Comment by Rustyb0y** [comment]
Ok so I think it's an addon called ExtraQuestButton that lets you use the extra action button for quest items if the action button isn't being used.

There are two lines in it's anchor code, which I have commented out. It now works as intended

ExtraActionButton1:ClearAllPoints()
ExtraActionButton1:SetPoint('CENTER', self)

The funny this is, the author has included code that when you unlock/lock the buttons position from  his addon it checks to see if any other addon has control of its position and will not let you move it.  I would have thought they would have done the same check on load.

I will contact the author and see if he will update his addon
