### ISSUE TITLE
Global Scaling Option

### ISSUE THREAD

**Issue by Xorag** [tullamods/Dominos#415]
Hello,

I'm not sure if this has been requested before but I'd like to request an enhancement for an option where you could have a single slider in the options that would allow you scale all UI elements at once - I use a high DPI display so my default WoW UI elements are pretty large and I'm planning to conserve some screen space by scaling down all of my action bars/roll/alerts etc... and doing them one by one isn't particularly difficult, but having a global option would be fairly user friendly I'd imagine.

Thanks!

**Comment by Tuller** [comment]
For now, this slash command works
```/dom scale all 2```

**Comment by Xorag** [comment]
That's fine then thanks - I just didn't know about :)
