### ISSUE TITLE
GetMirrorTimerProgress("timer") addon action blocked

### ISSUE THREAD

**Issue by speedwaystar** [tullamods/Dominos#416]
**Addon Version**
9.3.2-beta3-retail

**World of Warcraft Version**
Retail

This repeatable error starts getting thrown in a tight loop when engaging in combat underwater, while Dominos is trying to show the Breath meter as one of its MirrorTimer elements.

[ADDON_ACTION_BLOCKED] Addon "Dominos" tried to call the protected function "DominosFramemirrorTimer1.Show()"
[ADDON_ACTION_BLOCKED] Addon "Dominos_Cast" tried to call the protected function "DominosFramemirrorTimer1.Hide()"

![BugSack output](https://i.imgur.com/To2jwgF.png)

2127x Dominos_Cast\mirrorTimer.lua:314: Usage: GetMirrorTimerProgress("timer")
[string "=[C]"]: in function `GetMirrorTimerProgress'
[string "@Dominos_Cast\mirrorTimer.lua"]:314: in function <Dominos_Cast\mirrorTimer.lua:311>

Locals:
(*temporary) = nil

Consequences: (apart from the error proccing 10x per second): the Breath timer doesn't update and doesn't hide until a Reloadui is performed.

**Comment by Tuller** [comment]
This should be fixed in beta4
