### ISSUE TITLE
Disabled bars reappear after logging out and back in to the game.

### ISSUE THREAD

**Issue by Klunkk** [tullamods/Dominos#417]
Something in the new beta version has caused disabled/unused action bars to appear. Specifically for me, it is bars 8, 10, bags, and exp. I can disable them via the in-game options, but they always return to the visible state after logging out and back in again. Disabling Dominos_config has no effect. As far as I can tell, there are no error messages.

EDIT: Tried a different character and bars 7, 10, bags, and exp reappeared. It seems as though any bars that are disabled are the ones that reappear.

**Addon Version**
8.3.2-beta4-retail

**World of Warcraft Version**
Retail

**Comment by Road-block** [comment]
The exact same thing happens for 8.3.2-beta4-classic on the Classic (and Classic PTR) client.

Visibility status on bars (middle or shift-clicked off) does not persist logout or reloadui.

**Comment by Road-block** [comment]
Reverting to beta3 works.

**Comment by Tuller** [comment]
Try with beta5

**Comment by Road-block** [comment]
> Try with beta5

beta5 looks good.

**Comment by Klunkk** [comment]
Can confirm. Beta 5 appears to have fixed it.
