### ISSUE TITLE
Bag Bar/ Dominos

### ISSUE THREAD

**Issue by ClassicmikeFairbanks** [tullamods/Dominos#418]
The Bag Bar in dominos for classic wow has stopped working for me. Whenever I reload, go into a loading screen naturally, or logout and login, the bag bar moves. 

Weather its in an existing profile, or I try making a new one, the bag bar will not save where I put it. 
It also moves it to random spots, so If I move the bag bar to the top right of my UI and reload, or cahnge profiles and then switch back, it will sometimes move it to the bottom right, or slight off center bottom right. 

It makes no sense why this will not save and every other bar does fine. Please help me if you can.
![AfterReloadDominos](https://user-images.githubusercontent.com/62153014/76644304-206a6a00-652d-11ea-9112-0b76825357a7.JPG)
![BeforeReloadDominos](https://user-images.githubusercontent.com/62153014/76644306-21030080-652d-11ea-8b0a-dede79a6acf9.JPG)

**Comment by Tuller** [comment]
Other addons might also try to move the bag bar, move anything is a common example. Can you reproduce the issue with just dominos enabled?

**Comment by ClassicmikeFairbanks** [comment]
I just tested with three different types of reloads after disabling all other addons and the bag will still not save. I also tried making a new profile again to save it but this also did not work. 

It doesn't even move it back to the same spot every time, it is slightly different every time it moves it.

**Comment by Tuller** [comment]
Is this still an issue?

**Comment by ClassicmikeFairbanks** [comment]
I got rid of dominos so to my knowledge yes, but I have no idea. I could
never figure it out. No changes I made to my addons or profiles or anything
fixed it.
