### ISSUE TITLE
[mod:shift]& [nomod] not working as intended with shift paged bar

### ISSUE THREAD

**Issue by itsthatguy** [tullamods/Dominos#419]
**Addon Version**
`8.3.1-classic`

**World of Warcraft Version**
Classic

**Summary**
The macro in question is:
```
#showtooltip
/use [mod:shift] Nightcrawlers
/use [mod:shift] 16
/cast [nomod:shift] Fishing
```

The problem is that using the hotkey to activate the shift version of the macro always tries to `/cast [nomod:shift] Fishing` when clicked, it functions correctly.

**Additional Information**
Key binds are set, and double checked to make sure the hotkey was not bound to anything else.

Tested with only dominos and dominos config enabled.

**Comment by Tuller** [comment]
Did you check the blizzard bindings for shift + number? They should be under Action Page.
