### ISSUE TITLE
Sanity bar moving

### ISSUE THREAD

**Issue by Sooleawa** [tullamods/Dominos#420]
version:latest curse, retail
(did not try only with dominos enabled yet)
started when 8.3 came out

Normally enabled positions for encounter bar and vehicle button:
![1](https://user-images.githubusercontent.com/38173931/77844832-1772cd00-71aa-11ea-8ae7-4c26dafe5014.jpg)

Encounter bar appearing with sanity>
![2](https://user-images.githubusercontent.com/38173931/77844852-48eb9880-71aa-11ea-92ee-710c284d0592.jpg)

As soon as i am in combat, it moves to the middle of my character:
![3](https://user-images.githubusercontent.com/38173931/77844862-615bb300-71aa-11ea-9580-9b6b8d329e21.jpg)

Not just for sanity, so far every time that bar gets used, solo, raid wherever.

(on a side note, also the exit vehicle button does not appear some cases it did before 8.3, but i did not made further tests yet)

**Comment by Tuller** [comment]
Are you testing this with just Dominos + Dominos_Config?

**Comment by Sooleawa** [comment]
said no,  wanted to avoid turning on and off these 3000 addons one by one ,  but will not escape it.
so, after hours or turning things on off:
Seems that **leatrix** overwrites the dominos powerbar position in combat (if it is set to manage frames),  turning off either leatrix frame management or dominos encounter fixes things.

**Comment by Sooleawa** [comment]
vehicle button fixed as of now
