### ISSUE TITLE
[Classic] Right click cast on self not working

### ISSUE THREAD

**Issue by Xorag** [tullamods/Dominos#421]
8.3.1-Classic

Classic WoW

I've noticed with right click cast set to self it does not appear to work. If i have someone targeted and I left click arcane intellect they get it, then if i keep them targeted and right click, the spell is still cast on them.

Thanks

**Comment by Tuller** [comment]
I've not reproduced this one. Tried alt + key and right clicking a spell after making sure that Right Click Target was set to Self.

**Comment by Xorag** [comment]
I'm not sure what I can check - In my vanilla interface settings I have auto self cast turned on and the self cast key is control, but I've used dominos for years and never needed to use the self cast modifier in addition to right clicking in order to self cast.

**Comment by Tuller** [comment]
Check here (/dominos):
![image](https://user-images.githubusercontent.com/191239/78078873-87e04080-739a-11ea-906c-d2ced89d9b57.png)

You shouldn't need to hold down a key, I was just mentioning I tested both alt + key and right clicking the button.

**Comment by Xorag** [comment]
Yup, I've always used that setting and had it set to self. I tried disabling all other addons as well as resetting my dominos profile on my mage where I've been testing it - I'm not sure how I could continue debugging it. I could make a video showing it not working for me but I know that won't have any concrete debugging info.

**Comment by Xorag** [comment]
I'm wondering if you can test on your end with a fresh profile? Maybe a variable isn't being set properly in newer versions, but if you had an older version of the addon with the variable already set you wouldn't experience the issue? Just a guess.

I also tested a fresh install of classic wow and dominos on my laptop and I have the same issue as my main PC

Thanks!

**Comment by Xorag** [comment]
Deleted my previous comments - I figured out the issue.

I use a macro:
<pre>
#showtooltip
/cast Arcane Intellect
</pre>

When using this macro right-click self cast does not work.

When I drag the spell to my bar it DOES work.

The reason I use the macro is to ensure the spell is always cast at the highest rank (helpful when leveling).

Not sure if this is fixable though?

Thanks!

**Comment by Tuller** [comment]
For macros, you may need to do this instead:
```
#showtooltip
/cast [btn:2,@player]Arcane Intellect;Arcane Intellect
```

**Comment by Xorag** [comment]
That works, I had no idea about the mouse button modifier. Thanks!
