### ISSUE TITLE
[bug] reputation bar still use the default UI

### ISSUE THREAD

**Issue by Altoholic** [tullamods/Dominos#422]
**Addon Version**
8.3.1-classic

**World of Warcraft Version**
Classic

**Screenshot**
https://imgur.com/a/sR6icB0

As you can see, if i want to activate the tracking of a reputation, in the  reputation panel (the default keybind is "u"), it put it where the default UI should have it (it's the white bar that don't make any sense here, if i use Dominos).

**Comment by Tuller** [comment]
Have you tried with just Dominos enabled?

**Comment by Altoholic** [comment]
yes.

**Comment by Tuller** [comment]
I've still not managed to reproduce this one

**Comment by Altoholic** [comment]
I don't know what to say...
Fresh install, only Dominos enabled, activate tracking of a reputation in the default reputation panel, and i have the bug.
100% reproducible.
WoW classic.

**Comment by Tuller** [comment]
Yes, its weird that I can't reproduce it. Can you do an /fstack and tell me the frame name?

**Comment by Altoholic** [comment]
/fstack: 
https://imgur.com/a/MpehFpI

I created a new character, and i don't have the bug anymore.
I tried some other characters: no more bug.
But i still have it on my main character, even with only Dominos activated.
So... i don't know what to do. Delete all dominoes config file ? (but i don't want to lose my Dominos config ^^ can i export it ?)

**Comment by Altoholic** [comment]
After "only Dominos activated", i loged out, activated all addons, login in: bug no more here.
I uncheck reputation, check it again: the bug came back.

**Comment by Slivo-fr** [comment]
I experienced the same issue

**Comment by Tuller** [comment]
8.3.8 has a text fix for this. I _still_ have not reproduced it on my end.

**Comment by Altoholic** [comment]
The update only makes things worse: I can't have a reputation bar anymore (also tested with only dominos activated), and the original bar is still there (on my main character, and on no other, which makes me confused).

**Comment by Tuller** [comment]
I usually use Dominos + Dominos_Config as the benchmark for ensuring that no other addons are enabled and causing issues. You can turn on Dominos_Progress (which has the reputation bar) and the rest.

**Comment by Altoholic** [comment]
I created a new character and can confirm : with only Dominos + Dominos Config + Dominos progress, i can't make the xp bar show the reputation anymore.

https://imgur.com/a/YdpVyyX

**Comment by Tuller** [comment]
Is auto switch modes checked?

**Comment by Altoholic** [comment]
What is auto switch ? I can't find it in the options.
But i found "one bar mode" (i don't see any difference with or without it checked) and "skip inactives modes", and after checking/unchecking them, it's working again... except for my main, who still have the original reputation bar if i try to follow one of them.
It really feel like something is corrupted for that peculiar character. I should delete all configurations files, but i don't want to lose my settings... is there a way to export them ?

**Comment by Tuller** [comment]
The option would be on the right click menu for the bar in config mode

Otherwise, you could use the profiles menu on /dominos to switch to a new one and then reset that profile

**Comment by Altoholic** [comment]
Auto switch was unchecked. I checked it. It works on its own, but i still have the strange bug on only one character.
I made a test profile, imported my rogue profile, and switched some characters from rogue to test, and still have the same behavior : only one of my character have the bug, all the other work as intended.

Maybe if i delete everything about dominos (including configuration files), and install it again, that strange bug can go ?
But is there a way to export my configuration first, so i can import it back ?

**Comment by Altoholic** [comment]
Also: on the buggy character, right clicking on the exp bar don't do anything, while on any other character with the same profile, it switch exp/rep.

**Comment by Tuller** [comment]
You could export your saved variables from your WTF folder if you wanted to reset the addon, but there's no option to import something like that back into Dominos.

**Comment by Altoholic** [comment]
RIP.
I'll keep the bug then, it's not game breaking.
TY for your help.
