### ISSUE TITLE
No exit button in Wintergrasp guns and Tortollan world quests

### ISSUE THREAD

**Issue by Ashenblue** [tullamods/Dominos#423]
The exit-vehicle button is missing when in guns in Wintergrasp.  Have to use the option "Use Blizzard Override Action Bar" to get out of tower guns.  The exit should be one of the buttons on the regular bar, not the little exit button.

When in a tank or anything else that uses the little exit button, that works.  It's when the exit button is one of the regular buttons.

Can duplicate this in Wintergrasp by getting into one of the tower guns.  There will be no way to get out of the gun.  If you use /dom and enable the "Use Blizzard Override Action Bar" there will be a gun-exit button in the Blizzard action bar.

**Addon Version**
8.3.2-beta5-retail

**World of Warcraft Version**
Retail

**Comment by Ashenblue** [comment]
Also is in the world quests for the Tortollans.  The "exit" for "Make Loh Go" and such.  Possible that Blizzard has moved the location of that button in their UI?  Normally it would be a button on the Dominoes bar, like button 10 or something.  But it's not there anymore in Dominoes, only in the "Blizzard Override Action Bar".

**Comment by Tuller** [comment]
Do you happen to have a screenshot of this? Blizzard does have a tendency to be inconsistent between patches

**Comment by Ashenblue** [comment]
Look at the bottom row in these images.  One is the "Blizzard Override Action Bar" and it has an exit button.  The other one is Dominoes and there is no exit button.

![WoWScrnShot_042420_172056](https://user-images.githubusercontent.com/63941622/80261621-8da30c00-8650-11ea-8689-01f59109fd61.jpg)
![WoWScrnShot_042420_172109](https://user-images.githubusercontent.com/63941622/80261622-8e3ba280-8650-11ea-94ed-d25ba03e26c4.jpg)

**Comment by Alyred** [comment]
Not only is this button missing, but it appears that the ExtraActionButton bar is missing completely as well, or, I cannot get it to appear.

**Comment by Tuller** [comment]
The vehicle exit button should show up again. Sorry for the delay on the fix, got caught up in other bits first
