### ISSUE TITLE
Flyout Direction on Hunter Pet buttons

### ISSUE THREAD

**Issue by ElaineofShalott** [tullamods/Dominos#424]
Retail WW
Version 8.3.1-retail
Flyout buttons such as call pet and pet utility are flying out downwards and off the screen instead of going upwards. Originally I had this problem on my mage as well, but I exited and re-started the game and it fixed it. It is continuing on my Horde Hunter as well. I turned off all addons except Dominos and Dominos_Config and the problem remains.

![WoWScrnShot_042020_145320](https://user-images.githubusercontent.com/64038904/79790636-0b49dd80-831a-11ea-9607-f8e99e1ea1d4.jpg)

**Comment by Tuller** [comment]
This will probably be best fixed by me adding an option to the frame for this, as it appears my code isn't guessing right for you.

What happens if you move the bar towards the bottom of the screen?

**Comment by obijuann** [comment]
Same issue with my mage portal and teleport menu flyouts. I keep them on the right of the screen. If they're in the rightmost bar, they fly off the screen to the right.
![image](https://user-images.githubusercontent.com/32609170/103447792-ba2e0f80-4c44-11eb-87f2-52077350a278.png)

But if I move them to the leftmost bar, they work as expected:
![image](https://user-images.githubusercontent.com/32609170/103447800-cd40df80-4c44-11eb-9ddf-db434522a202.png)

It would be nice to have an option to dictate which direction the flyout uses.
