### ISSUE TITLE
Castingbar is lagging

### ISSUE THREAD

**Issue by xleeverx** [tullamods/Dominos#426]
The casting bar depends on the use. It no longer runs smoothly and you can see individual stops.

**Addon Version**
8.3.3

**World of Warcraft Version**
Retail

**Comment by Slivo-fr** [comment]
Same issue on classic ! Also it seems a bit different at first look (thinner maybe?)

**Comment by xleeverx** [comment]
Yes, in retail the same. It`s thinner. Other Style included ?
