### ISSUE TITLE
Button cooldown visuals not appearing on bars with a show state of `[combat]show;0`.

### ISSUE THREAD

**Issue by jaf470** [tullamods/Dominos#427]
Cooldown indicators don't seem to be showing in 8.3.6 when the bar has a show state of `[combat]show;0`.

Steps to reproduce:

1. Place a show state of `[combat]show;0` on a bar
2. Reload UI
3. Enter combat and use an ability with a long cooldown

Installing 8.3.5 or removing the show state fixes the issue.

**Addon Version**
8.3.6

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
Looks like I manually need to call setalpha instead of hoping the game would do it for me

**Comment by jaf470** [comment]
Looks to be working properly in 8.3.7.  Thanks!
