### ISSUE TITLE
Action bars covered by Quest Tracker, new in 8.3.6

### ISSUE THREAD

**Issue by Mepheus** [tullamods/Dominos#428]
In WOW Classic, after updating to Dominos-8.3.6-classic from i believe 8.3.1-classic the quest tracker of Questie overlays the action bars.

Before The action bars always were in the foreground.

![Questie over Dominos](https://user-images.githubusercontent.com/64781965/80960774-cb9aef80-8e09-11ea-9788-b228f61e69cb.PNG)

**Comment by Tuller** [comment]
To get slightly technical on this, older versions of Dominos had a frame between the actual action buttons and the Dominos frame itself, and I removed it as it wasn’t actually necessary.

It looks like a side effect of this is that Dominos frames are now one level “lower” and that’s why it is probably showing up behind questie.

**Comment by Mepheus** [comment]
Thanks for the reply!
Do you maybe see a possible workaround from the users side?
Or can this be resolved in future Updates?
Awesome addon by the way, thanks a lot for maintaining it.

**Comment by Mepheus** [comment]
it is fixed perfectly in 8.3.7, thanks a lot!
