### ISSUE TITLE
Cast bar will remain on screen often after a spell cast

### ISSUE THREAD

**Issue by alessandrouw** [tullamods/Dominos#430]
After the latest update, I am noticing that sometimes after I cast something, the cast bar
just stays on screen on "0.0" timer. I got today an screenshot after casting Silas' Sphere of Transmutation:

![CastStuck](https://user-images.githubusercontent.com/43277877/81313870-cda9bc00-905e-11ea-9bc5-d1e22d7f773e.png)

It will disappear if I cast something else, but until I do, it stays there. It does not happen every time, but it's very common. I'm not sure yet how to reproduce. It can also happen to basic spells such as Hearthstone and Solar Wrath. I'm absolutely sure it wasn't an issue before the update.

**Comment by Tuller** [comment]
This should be fixed in 8.3.8
