### ISSUE TITLE
Keyring Icon

### ISSUE THREAD

**Issue by BigBoar** [tullamods/Dominos#431]
no matter what my keyring setting for the addon are, the default keyring icon appears on my screen in the middle right on my toon and wont ever move.

**Addon Version**
8.3.1

**World of Warcraft Version**
Classic

**Comment by Tuller** [comment]
Can you try with the latest version?

**Comment by ManofSteel007** [comment]
This exact same issue is happening with me. It happened after updating to the most recent version. Any solution here?

**Comment by Tuller** [comment]
I would doublecheck with the latest version
