### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Altoholic** [tullamods/Dominos#433]
**Addon Version**
8.3.9-Classic

**World of Warcraft Version**
Classic

80x SharedXML\Util.lua:317: attempt to compare nil with number
SharedXML\Util.lua:317: in function <SharedXML\Util.lua:316>
...faceDominos_Cast\DominosTimerBarTemplate.lua:49: in function `SetValue'
Dominos_Cast\mirrorTimer.lua:30: in function <Dominos_Cast\mirrorTimer.lua:27>

Locals:
value = 0
min = nil
max = nil
(*temporary) = "attempt to compare nil with number"

**Comment by Altoholic** [comment]
It 100% happen when i take suffocation damage (and infinitely repeat - 1105 error in a few seconds).

**Comment by Tuller** [comment]
Can you try reinstalling the addon? I ask because there's specifically this bit in the latest version for th is case that's there to handle the nil value:
`local value = (GetMirrorTimerProgress(self.timerName) or 0) / 1000`

**Comment by Altoholic** [comment]
I did, and no more error.
