### ISSUE TITLE
Possible bug? Opacity stuck on until going over both sets of bars with the mouse, changing zones, and other..

### ISSUE THREAD

**Issue by thatmikeguy2** [tullamods/Dominos#436]
Retail, I have disabled all other addons. I believe this started around two or so updates ago, I also use this [mod:lshift][mod:lalt][@target,exists,harm][combat]80;show

(Layout size 9, columns 9, spacing/padding 0, scale 67) (Opacity 100, delay 0, duration 0.1, faded opacity 12, delay 0, duration 0.1) all else default.

Only one of the two sets of bars, my main set has the advanced settings. I've used this same setup for many years, and I started seeing it getting stuck a few weeks ago. It's not on every say pet battle, but maybe 1 of 3. I had a backup from 3/27/20, so I deleted all the dom* in addons and copied it over, not changing anything in WTF, and went into over 30 pet battles and it did not happen, the opacity went back to how it was set.

Normally I wouldn't go to all this for an addon, but yours is the best and most important. Keep up the good work!

**Comment by Tuller** [comment]
The fader checks on player_entering_world now, so that should cover this.
