### ISSUE TITLE
Extra action button problem

### ISSUE THREAD

**Issue by jhu1234** [tullamods/Dominos#439]
![2020-06-16 (4)_LI](https://user-images.githubusercontent.com/66981701/84723480-a4b30a00-afc0-11ea-9f9e-d22461a157b5.jpg)

As you see, I moved exctra button to the right side, But 'extra action button frame' didnt.
When i play as heal, i set raid frames  just over action bars, that extra frame preventing click or mouseover.

Can you add functions to remove this?

+  i found this script removing extra button frame.
/run local e=ExtraActionBarFrame;e:ClearAllPoints();e:SetPoint("CENTER",UIParent,"CENTER",0,0);e.SetPoint = function() end;e:SetScale(1) 

For temporary, i want to add this script at .lua file, how can i do?

**Comment by Tuller** [comment]
This should be fixed in 8.3.11

**Comment by jhu1234** [comment]
I checked and updated, and 'extra button frame' disappeared.
However, extra button disappeared too.


![2020-06-28](https://user-images.githubusercontent.com/66981701/85937421-5f86c480-b93e-11ea-90e8-87b9758620e9.png)
