### ISSUE TITLE
8.3.11 Extra Action Button 1 Bug Report

### ISSUE THREAD

**Issue by ensidia** [tullamods/Dominos#441]
If applicable, try reproducing your issue with just Dominos and Dominos_Config enabled. This helps route out issues that are due to either conflicts with other addons, or Dominos modules that are not part of the core, like Dominos_Units.

**Addon Version**
8.3.11-Retail

**World of Warcraft Version**
Battle for Azeroth

I report a bug on the 8.3.11 version of Extra Action Button.

![WoWScrnShot_070420_101058](https://user-images.githubusercontent.com/67811537/86502538-56cf3c00-bddf-11ea-8e1d-127df5d89095.jpg)

As shown above, the Extra Action Button is supposed to be in position No.1 but is held in position No.2 and will not move.
If No.1 is moved to another location, but No.2 remains there.
I downgraded Dominos to 8.3.10 version, and it worked normally.
Please let me know how to solve this problem in 8.3.11 version.

**Comment by Tuller** [comment]
Have you verified with just Dominos + Dominos_Config?

**Comment by ensidia** [comment]
> Have you verified with just Dominos + Dominos_Config?

Should I try with all other add-ons disable and only Dominos + Dominos_Config enabled?

**Comment by ensidia** [comment]
> Have you verified with just Dominos + Dominos_Config?

I solved this!

The cause was MoveAnything Add-on.

Thank you for your reply. Have a nice day!
