### ISSUE TITLE
Extra Action Button - Keybind Doesn't Work in Combat

### ISSUE THREAD

**Issue by webdevdave** [tullamods/Dominos#442]
I noticed in the Change Log that you wrote "8.3.11 Recoded the extra action bar frame to work more like the zone bar. The parent frame the bar should stay with the acutal bar position now". Since then it seems the Extra Action Button no longer lets you click the keybind when in combat. I switched back to 8.3.10 and it is working correctly.

**Comment by Tuller** [comment]
When you say click the keybind, are you clicking the button on screen, or pressing a hotkey?

**Comment by webdevdave** [comment]
Pressing the hotkey on my keyboard is what's not working. So I end up having to click the button with my mouse on screen to get it to work.

**Comment by Tuller** [comment]
This is probably fixed in the beta.
