### ISSUE TITLE
When a fade out delay is set, MouseEntering a frame before that delay is finished fails to cancel a pending Fade

### ISSUE THREAD

**Issue by kesava-wow** [tullamods/Dominos#443]
To reproduce, have a bar with:
- Fade in opacity: 100
- Fade out opacity: 0
- Fade out delay: 1 (or whatever)
- (everything else default)

1. Mouse over the bar to fade it in.
2. Mouse out.
3. Mouse over again before the delay is finished.
4. The bar fades out with the mouse over it.

This line prevents the necessary call: https://github.com/tullamods/Dominos/blob/8a77d990c9be687c71eebe7c644915d189c68ab4/Dominos/core/frame.lua#L443

Just removing that line does fix it, obviously, but you probably want to cancel the pending fade out instead of overwriting it with a fade in from 100 to 100.

Dominos: 8.3.12
Game: retail

**Comment by Tuller** [comment]
Thanks for the detailed report, and yeah cancelling the animation then is probably best.

**Comment by Tuller** [comment]
The animation cancellation logic is a bit better in the 9.0.13 version
