### ISSUE TITLE
Dominos_Cast\DominosTimerBarTemplate.lua:249: attempt to call method 'GetBackdrop' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [tullamods/Dominos#445]
**Addon Version**
8.312
**World of Warcraft Version**
Beta  9.0.1.35360

Message: ...face\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:249: attempt to call method 'GetBackdrop' (a nil value)
Time: Fri Jul 31 14:29:08 2020
Count: 4
Stack: ...face\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:249: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua"]:249: in function <...face\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:238>
[string "@Interface\AddOns\Dominos\core\helpers.lua"]:105: in function <Interface\AddOns\Dominos\core\helpers.lua:104>

Locals: self = <unnamed> {
 OnSizeChanged = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:15
 fadeOut = <unnamed> {
 }
 SetFormattedText = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:65
 SetShowSpark = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:94
 SetText = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:61
 SetShowLabel = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:108
 SetPadding = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:157
 OnUpdate = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:19
 statusBar = <unnamed> {
 }
 SetFont = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:73
 SetLatencyPadding = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:136
 countdown = true
 SetShowIcon = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:101
 SetShowLatency = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:129
 Start = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:168
 Pause = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:191
 FadeOut = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:228
 fadeIn = <unnamed> {
 }
 latencyBar = <unnamed> {
 }
 background = <unnamed> {
 }
 SetShowText = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:115
 showLabel = true
 showIcon = false
 SetCountdown = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:164
 showBorder = true
 icon = <unnamed> {
 }
 border = <unnamed> {
 }
 FadeIn = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:218
 SetLabel = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:57
 latencyPadding = 400
 OnLoad = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:10
 SetTexture = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:83
 showText = true
 Layout = <function> defined @Interface\AddOns\Dominos\core\helpers.lua:110
 GetLatency = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:184
 OnValueChanged = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:29
 SetShowBorder = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:122
 0 = <userdata>
 Stop = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:208
 Resume = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:199
 SetIcon = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:69
 padding = 1
 UpdateLatencyPadding = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:142
 SetValue = <function> defined @Interface\AddOns\Dominos_Cast\DominosTimerBarTemplate.lua:48
}
margin = nil
iconSize = nil
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"

**Comment by Tuller** [comment]
I'm aware of this, but don't have beta access yet.

**Comment by Tuller** [comment]
This is fixed in the beta version.
