### ISSUE TITLE
Cannot see EXP bar

### ISSUE THREAD

**Issue by javedbartlett** [tullamods/Dominos#446]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

There is no exp bar, i open the dominos options and bar config mode and there is no exp bar on the screen at all.

**Addon Version**
You can get this via running `/dominos version` in game
8.3.12-retail

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.
Beta

**Comment by Tuller** [comment]
Is Dominos_Progress enabled?

**Comment by javedbartlett** [comment]
@Tuller I do not have dominos_progress. This is all I have:


![image](https://user-images.githubusercontent.com/48427864/90849973-324f0500-e336-11ea-9cc2-6886026c21e4.png)
