### ISSUE TITLE
extra action button losing set position since recode in the most recent update 

### ISSUE THREAD

**Issue by clmcgrath** [tullamods/Dominos#447]
This all worked fine before the last update. now the extra button loses its set position and disjoins from the edit control 
![image](https://user-images.githubusercontent.com/452012/90067332-f45e3b00-dcbc-11ea-8718-b6ab2fb7b9db.png)

resetting the position  sometimes fixes it other times not sometimes entering the right click extra settings fixes it as well ones fixed it seems to work fine for rest of session or /reload 
![image](https://user-images.githubusercontent.com/452012/90067824-adbd1080-dcbd-11ea-88cc-e923e9a9ec50.png)

I do have move anything installed but did not have this issue with the extra action button prior to the recent recode 
**Addon Version**
8.3.12-Retail

**World of Warcraft Version**

Retail

**Comment by Tuller** [comment]
You should check to see if move anything is set for the extra bar. The reason is because we both attempt to move the same frame. Prior to the update, Dominos would only move the button, and not the frame that contains the button.

**Comment by alessandrouw** [comment]
I'm having the exact same issue. I have no idea really how to replicate it, but it happens very often now.
