### ISSUE TITLE
Bugged hidden default action buttons

### ISSUE THREAD

**Issue by d87** [tullamods/Dominos#450]
Hidden default action buttons aren't being initialized or something, they all point to action 1

Steps to reproduce
1. Have something bound to ActionButton12
2. Resize Bar 1 to be 11 buttons or less
3. Reload
4. Key bind isn't working
5. /dump ActionButton12.action says 1

**Addon Version**
9.0.0-beta1 and later, 9.0.0-beta is fine

**World of Warcraft Version**
Beta

**Comment by Tuller** [comment]
In earlier versions of Dominos, if you had a bar with 11 buttons, then Dominos would get and setup the 12th button at all. In beta1+, I initialize every button, even if you're not using them. I've pushed a commit that reverts to the older behavior.

This is currently in in the realm of undefined behavior. Buttons that are beyond a bar's length don't currently get setup for paging, and in the case of  buttons named DominosActionButtonXX, may not exist at all.

**Comment by d87** [comment]
Oh, so before it was falling back to blizzard action buttons when not used
It's fine if DominosActionButtonXX are not created or paging doesn't work, but for MultiBarXXX it's just nice to retain compatibility with default UI and keybindings.
Well it works now, thanks
