### ISSUE TITLE
Action bar 1 relocates to different area whenever leveling up and loading into zones.

### ISSUE THREAD

**Issue by Recaine** [tullamods/Dominos#451]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
You can get this via running `/dominos version` in game

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.

**Comment by Tuller** [comment]
This is typically caused by a different addon, have you tried with just Dominos enabled?

**Comment by Recaine** [comment]
Will try later on and and get back to you.    Thanks for your help.

**Comment by Recaine** [comment]
Yup it was move anything, thanks again.
