### ISSUE TITLE
Macros being run on keydown and keyup

### ISSUE THREAD

**Issue by zarillion** [tullamods/Dominos#452]
New issue discovered after I updated my Dominos on beta today. I use a macro that prints my current map coordinates while placing icons on the map for my addon:

```
/script local m = C_Map.GetBestMapForUnit("player"); local p = C_Map.GetPlayerMapPosition(m, "player"); print(format("%04d",floor(p.x*10000))..tostring(format("%04d",p.y*10000)))
```

I have action bars 1-6 displayed, and when I place the macro in action bar 2 the macro is run on both keydown and keyup and the coordinate is printed twice. This does not occur for any other action bar I have displayed, only #2. Reverting my dominos version back to `9.0.0-beta-Retail` fixes the problem.

**Addon Version**
You can get this via running `/dominos version` in game

9.0.0-beta3-Retail
9.0.0-beta2-Retail
9.0.0-beta1-Retail

**World of Warcraft Version**
Beta

**Comment by Tuller** [comment]
What do your bindings look like for the bar?  Can you try complexly clearing the bindings for the button and then reminding it?

Basically I bet I’m not properly clearing the old binding format yet.

**Comment by zarillion** [comment]
I tried unbinding the keybind a few times with ESC and then rebinding it and the issue persisted. Here are some screenshots of my setup. The macro is under the "E" key.

![image](https://user-images.githubusercontent.com/64381982/91786030-54654480-ebcc-11ea-8d53-e6ea2ab0c7fb.png)

![image](https://user-images.githubusercontent.com/64381982/91786048-5fb87000-ebcc-11ea-9172-07bedf70eee2.png)

**Comment by Tuller** [comment]
Try the latest beta.

**Comment by zarillion** [comment]
The issue appears fixed for me now, it only runs once on key up.

I also tested Action Bar 2 with the "Cast action keybinds on key down" setting (which I don't normally use, but I know others that do). It does not appear to honor that in the newest version, all binds are still key up only.

Closing this issue since my original problem was fixed, thanks!

**Comment by Tuller** [comment]
If you adjust the cvar, you'll need to reload your UI for it to take effect
