### ISSUE TITLE
Retail WOW. Can't key bind dominos bar 10

### ISSUE THREAD

**Issue by begryphon** [tullamods/Dominos#453]
Version 8.3.12 classic
WOW classic

Love Domino. I cannot key bind to Domino bar 10. I've exhausted every thought I have troubleshooting this.
Please explain why this is the case.
Many thanks,
Burt

**Comment by Tuller** [comment]
What happens  in binding mode when you hover over buttons on the bar? (My guess is that there's another frame over it).

**Comment by Tuller** [comment]
With the 9.0 release, you'll have an option for binding buttons via the standard bindings menu. That may resolve this if its still happening.
