### ISSUE TITLE
UI layer for dominos buttons makes them appear over Blizzard Sanctum Screen in Shadowlands beta

### ISSUE THREAD

**Issue by GaryREM** [tullamods/Dominos#454]
Dominos buttons show up over top of Sanctum screen making the Sanctum screen unreadable.

**Addon Version**
9.0.0-beta4-retail

**World of Warcraft Version**
Beta

**Comment by Tuller** [comment]
Do you have a screenshot of this versus what the stock UI does?

**Comment by GaryREM** [comment]
Here is stock UI which has no problems since elements do not overlap.


However, I have element in Dominos which do overlap.




I wish there was an option to move the frame layer backward or forward for each bar.

Thanks...

**Comment by Tuller** [comment]
I don't see any screenshots there

**Comment by GaryREM** [comment]
There are links to images in previous comment now.

**Comment by Tuller** [comment]
Is this still happening for you? I've not yet replicated it.
