### ISSUE TITLE
Offset Aura/Class Bar Key Bind Labels - SL 9.0 Beta 4

### ISSUE THREAD

**Issue by Xorag** [tullamods/Dominos#457]
Running 9.0 Beta 4 in the shadowlands beta and I've configured my auras to have bindings and notice an issue I also see in Classic - the key bind labels extend far off of the smaller buttons.

I play in 4K and have my UI scaled to .85 but changing the scaling to 1 doesn't make a difference, screenshot below. 

The top bar is the default aura bar, the bottom bar is an 80% action bar with reduced spacing and padding to match the aura bar:

![image](https://user-images.githubusercontent.com/42698965/94879329-ebbcf200-042d-11eb-95ce-376dfbcff852.png)

**Comment by Xorag** [comment]
As an update, it looks like the default UI doesn't show, or is incapable of showing the key bind labels on the class bar at all :(

**Comment by Tuller** [comment]
Fixed in beta 5 (along with the pet bar).
