### ISSUE TITLE
Lua errors on shadowlands 9.0.2 when flying and you have a pet.

### ISSUE THREAD

**Issue by GaryREM** [tullamods/Dominos#459]
Lua errors on shadowlands 9.0.2 when flying and you have a pet.
Dominos 9.0.0-beta4-Retail

Message: Interface\FrameXML\PetActionBarFrame.lua:247: attempt to perform arithmetic on a nil value
Time: Sat Oct 10 12:26:26 2020
Count: 48
Stack: Interface\FrameXML\PetActionBarFrame.lua:247: attempt to perform arithmetic on a nil value
[string "@Interface\FrameXML\PetActionBarFrame.lua"]:247: in function `PetActionBar_UpdatePositionValues'
[string "@Interface\FrameXML\UIParent.lua"]:3287: in function `UIParentManageFramePositions'
[string "@Interface\FrameXML\UIParent.lua"]:2601: in function <Interface\FrameXML\UIParent.lua:2588>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3397: in function `UIParent_ManageFramePositions'
[string "@Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetBelowMinimapFrame.lua"]:5: in function `layoutFunc'
[string "@Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:473: in function `UpdateWidgetLayout'
[string "@Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:449: in function `ProcessAllWidgets'
[string "@Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:23: in function <...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:21>

Locals: (*temporary) = nil
(*temporary) = MainMenuBarVehicleLeaveButton {
 0 = <userdata>
 Highlight = <unnamed> {
 }
}
(*temporary) = "attempt to perform arithmetic on a nil value"

**Comment by Tuller** [comment]
I've not reproduced this one. yet. Its an interesting one because there's nothing about Dominos in that stack trace.

**Comment by GaryREM** [comment]
Yeah. I thought this was strictly a Blizzard problem(and maybe it is). However, there is no LUA error when I disable the main Dominos add on. It's something like there is something in Dominos saying there is a pet bar (even though there is none visible).

It does not occur with my mage (no pet).
It did not occur with my hunter (with pet). I had seen it before the character wipe on beta when the hunter had a construct with him.
It did not occur with my warlock (with pet)
However, it does occur with my warlock (with pet) when I also have a specific (Marz, Atticus) construct also with me.
