### ISSUE TITLE
Vehicle bar stopped working in 9.0

### ISSUE THREAD

**Issue by ascott18** [tullamods/Dominos#461]
Upon updating to the 9.0 version, my vehicle override bar (not using the Blizzard one) stopped working. I had to go in the options and change "Override Bar" from "Action Bar 1" (the bar it always has been) to "Action Bar 2" and then back to "Action Bar 1" again for it to start working.

**Addon Version**
9.0.0-Retail

**World of Warcraft Version**
Retail

**Comment by ascott18** [comment]
It seems I have to go through this process of changing the value and changing it back every time I reload my UI or log out.

**Comment by Tuller** [comment]
It should be fixed in 9.0.2. Basically, I added a bunch of lifecycle events to Dominos frames, and then failed to adjust the IsOverrideBar method on action bars to account for it.
