### ISSUE TITLE
Keybindings stopped displaying one one of my bars

### ISSUE THREAD

**Issue by ascott18** [tullamods/Dominos#462]
In the 9.0 version, one of my bars no longer displays keybind text.

Before update (screenshot taken 3 days ago): See the keybind text on the bottom right quadrant of actions (a single action bar)
![image](https://user-images.githubusercontent.com/5017521/95934052-c496e680-0d84-11eb-803a-07471de20fdb.png)

After update: (keybinds missing on bottom right bar - rightwards starting with Intimidation ):
![image](https://user-images.githubusercontent.com/5017521/95934080-db3d3d80-0d84-11eb-82a8-030122f921c1.png)

All 4 bars on the bottom are identical size, scale, Masque config, etc. I have not changed any keybinds since updating or since the patch. The keybinds on these buttons all still work - they just aren't shown on the buttons anymore. The buttons still light up when I press the corresponding bind.

**Addon Version**
9.0.0-Retail

**World of Warcraft Version**
Retail

**Comment by ascott18** [comment]
Rebinding these buttons is restoring the text. Here's the output on screen when I do the rebind: 
![image](https://user-images.githubusercontent.com/5017521/95934599-1db34a00-0d86-11eb-8fec-b6525cb646d0.png)

**Comment by rekcon** [comment]
I have this issue as well. However, instead of the keybinding just missing; I think bar2 is not actually the old bar2. The previous bar2 is hidden and if you do not rebind the keys to the is new bar2 you can still actually use the spells that were bound because the bar exists but is not displayed.

**Comment by rekcon** [comment]
I think this is happening because how Dominos handles the first bar. bar1 I think is unique. The bindings seem to start at bar2 because the keybinds for bar1 are handled by the blizzard actionbar bindings. Starting at bar2 its handled by the dominoes code. I think maybe in the creation of the bars it is skipping dominos bar1 instead of dealing with bar + 1 everywhere. And in skipping that bar it is not displayed.

**Comment by rekcon** [comment]
I just did more testing. The bar is correct. The bar does not display the binding. If I move the spells in bar2 and press the bound keys it casts the new spell. So the bar is visible. The bindings are not.

**Comment by rekcon** [comment]
Found it. Renaming the bindings in bindings-cache.wtf for the character or global (depending on the config) from DominosActionButton#:**LeftButton** to DominosActionButton4:**HOTKEY** restores the functionality. The bindings become visible again.

**Comment by Tuller** [comment]
My migration code was firing too early, it looks like. I've moved it from ADDON_LOADED to PLAYER_LOGIN and that appears to have fixed the issue for me. (I swore I tested this on beta!)

As for why the bindings format changed from ButtonName:LeftButton, to ButtonName:HOTKEY -- This allows me to differentiate keypresses from mouseclicks. I'm then able to use this information to support cast on key press on custom actions (ex any action button named DominosActionButtonXX in a way that actually works better (you should see the UI respond when you press down on a key), and is more efficient (no more creation of extra fake buttons that click the action).

**Comment by rekcon** [comment]
The old binding name :Leftbutton works but just doesn't display on the bar. Some change should be made to prevent the user from having to manually rebind or rename keybindings of the past.
