### ISSUE TITLE
Dominos Keybind Text

### ISSUE THREAD

**Issue by LVNDSCAPE** [tullamods/Dominos#463]
Hello before dominos update for pre-patch

I used to use this 

	_G[self:GetName()..'HotKey']:SetFont("Fonts\\FRIZQT__.ttf", 18, "OUTLINE")

to change the hotkey text in the bindableButton.lua

With the new update , can someone help me with the lua?
Thank you.

**Comment by Tuller** [comment]
Maybe something like this?

```lua
hooksecurefunc(Dominos.BindableButton, "AddQuickBindingSupport", function(button)
    button.HotKey:SetFont("Fonts\\FRIZQT__.ttf", 18, "OUTLINE")
end)
```

**Comment by LVNDSCAPE** [comment]
In which line number should I be inserting the code , Tuller?

I tried inserting the code you provided after line 201 function BindableButton:UpdateHotkeys()

But I am getting attempt to index field 'Hotkey' (a nil value)
![Screenshot_4](https://user-images.githubusercontent.com/23572961/96014348-49a8fb00-0e6c-11eb-8f6d-08a66d10bcd2.png)

**Comment by Tuller** [comment]
Just generally towards the end of the file (or even in a separate addon that's dependent on Dominos). I think the call should actually be:
```lua
hooksecurefunc(Dominos.BindableButton, "AddQuickBindingSupport", function(self, button)
    button.HotKey:SetFont("Fonts\\FRIZQT__.ttf", 18, "OUTLINE")
end)
```

**Comment by LVNDSCAPE** [comment]
Hello Tuller , thank you for the help.
It is working wonderfully.

![Screenshot_6](https://user-images.githubusercontent.com/23572961/96019171-2da85800-0e72-11eb-841c-b306c2e38e3e.png)
