### ISSUE TITLE
Attempt to call global 'InActiveBattlefield'

### ISSUE THREAD

**Issue by Rustyb0y** [tullamods/Dominos#464]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
You can get this via running `/dominos version` in game
9.0.2-Retail

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.
9.0.1 (36230) (Release x64)

honorBar.lua
Line 21
InActiveBattlefield was relocated and renamed C_PvP.IsActiveBattlefield

**Comment by Tuller** [comment]
This should be fixed in the [9.0.3 release](https://github.com/tullamods/Dominos/releases/tag/9.0.3)
