### ISSUE TITLE
Shadowlands: Changed status of the Command key on a Mac

### ISSUE THREAD

**Issue by tflo** [tullamods/Dominos#465]
With Shadowlands, Blizz removed the Mac-specific setting that allowed to map the function of the Ctrl key to the Command (Cmd) key. 

_Short explanation for non-Mac users:_

This setting was useful because the Cmd key on a Mac is way easier to reach than the Ctrl key. Cmd is at the location of the Windows key of a Win keyboard, with the difference that it is a real modifier key. On the Mac it is indeed the main modifier, with or without being combined with Shift/Option/Ctrl.

They removed this setting because with Shadowlands they (finally!) emancipated the Cmd key to a native standalone modifier key, with the same rights as Ctrl, Alt, or Shift. This is of course a great change, because now we have one more modifier we can use in the standard Key Bindings panel, and also for macro conditions as `[mod:cmd]`.

However, this change negatively affects add-ons that work with key bindings: The Cmd key is not available there, and we have to use the awkwardly placed Ctrl key instead (since the former Ctrl-Cmd-key mapping doesn’t exist anymore).

Dominos is one of these add-ons.

I use for example the modifier-key paging functions of Dominos, with many of my CDs and secondary spells on the Cmd-paged bars. The Cmd key can comfortably be pressed with the thumb without moving the other fingers, the Ctrl key not so much.

Besides that, it would simply be a waste if the best modifier key remains unusable for paging.

---

For the moment I could get away with a simple hack:

Changing line 61 in barStates.lua

from
```
addState('modifier', 'ctrl', '[mod:ctrl]', CTRL_KEY)
```
to
```
addState('modifier', 'ctrl', '[mod:cmd]', CTRL_KEY)
```
brought back the Cmd key for me.

I only made a few short tests, and it seems to work fine, for the moment. But it works only for paging, and not, for example, for key bindings for action bar buttons. (I guess these are done by an external library.) 

---
Probably you are not playing on a Mac, and so I would understand if this issue has very low priority for you.

However, it would be great if Dominos – some day – could make “native” use of the modifiers on a Mac.

Thanks in advance for considering, and thanks for this really great add-on.

– Tom

**Comment by Tuller** [comment]
You should see better support in 9.0.4. LibKeyBound was updated and I added the modifier state `[mod:meta]` to barStates.lua. I'll still need to add support for combo key presses, but will need to improve the paging UI a bit before I can do so (otherwise the list is going to be quite large)

**Comment by tflo** [comment]
Wow, great! Thanks!

[I leave the issue open for the combo-key paging.]
