### ISSUE TITLE
Cannot move loot window anymore after latest update

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [tullamods/Dominos#468]
It's now immovable in the middle of my raid frames
![WoWScrnShot_101420_203159](https://user-images.githubusercontent.com/65634313/96059690-9d134d00-0e5c-11eb-851e-f5a1b49ba235.jpg)

**Comment by pedrorafaelpadilla** [comment]
I also have no lua errors from donomios

**Comment by MetalMusicMan** [comment]
I don't have a loot window option in Config Mode either

**Comment by Tuller** [comment]
Added back in 9.0.5
