### ISSUE TITLE
Extra Button Wonkie Behavior

### ISSUE THREAD

**Issue by MetalMusicMan** [tullamods/Dominos#469]
Since WoW 9.0.0 and even on Dominos 9.0.4 my Extra Action button shows a very large extra space around the button when in Config Mode. When out of config mode, the button sometimes jumps about 500 pixels up from its location without warning, then suddenly will jump back. It does this frequently every few seconds sometimes. 
![dominosextraspace](https://user-images.githubusercontent.com/51964348/96079868-757fad00-0e7b-11eb-8412-212dcbaeb162.png)
![dominos jump location](https://user-images.githubusercontent.com/51964348/96079925-92b47b80-0e7b-11eb-9dc0-1cb74f31965f.png)
![dominos normal location](https://user-images.githubusercontent.com/51964348/96079926-934d1200-0e7b-11eb-9571-c2055bbaa29c.png)

**Comment by Tuller** [comment]
Does this happen with just Dominos enabled?

**Comment by MetalMusicMan** [comment]
The extra space around the Extra button in Config mode is still there with only Dominos on.

The jumping up/down is not, and after some trial and error it is Titan Panel and Dominos being on at the same time that causes the jump up/down in the button. No other issues with them both enabled though.

**Comment by Tuller** [comment]
In 9.0, the extra bar now encompasses the ExtraAbilityFrame, and can include multiple abilities. I’ve sized the bar to be the same as that new frame, which is why it is quite a bit larger now.

**Comment by MetalMusicMan** [comment]
Got it, thanks-- any chance for an option to make that Extra Bar "anchor" to a specific corner? The way my UI is, I would want the bar to anchor to the top-left and then fill out from there. I think it will break certain elements depending on how the multiple abilities lay out.

**Comment by Tuller** [comment]
I don't have a huge amount of control over the layout, You could add in negative padding to shrink it for the moment, though.

**Comment by OdessaGrimaldus** [comment]
I'm having roughly the same issues with the Extra Button here myself. ..Even with the Blizz Texture disabled I am still having the texture appearing. ..The button itself at it's 200 scale is much, much smaller than what it was before. ..Also, I'm not sure if this was pointed out yet, but the roll hub/window/button is nolonger accessible to be moved through Dominos.

**Comment by MetalMusicMan** [comment]
I found a fix, in case anyone else is having this issue.

Within Titan Panel configuration, checking the box "Disable Screen Adjust" under the "Top Bars" and "Bottom Bars" section appears to remove the issue.
