### ISSUE TITLE
Unable to change the font via LUA edits after update

### ISSUE THREAD

**Issue by ned406** [tullamods/Dominos#470]
Currently the LUA files cannot be modified to change the font anymore, or at least I cannot find how to do it.

**Comment by Tuller** [comment]
see https://github.com/tullamods/Dominos/issues/463

**Comment by ned406** [comment]
> see #463

This worked perfectly thank you Tuller. For anyone else I couldnt get the command to work in the action button LUA but I stuck it in my masque addon folder and it worked perfectly

**Comment by Tuller** [comment]
For what its worth, you're the second person to ask about styling the fonts this time around, so I may make it easier to work with.
