### ISSUE TITLE
Missing XP Bar Missing Alliance Paladin

### ISSUE THREAD

**Issue by elainedeshalott** [tullamods/Dominos#472]
Dominos Version 9.0.4-Retail

World of Warcraft Vesion - Retail

My XP Bar is missing. So far I have found this problem only on my Alliance Paladin. I Reset the profile to the default and that bar still does not appear in config mode.

I have not checked all 48 of my alts yet, but the problem seems specific to the character. The bar appears both on my main Druid and my Horde Paladin. Both my Paladins use the same bar profile, but the XP bar is missing alliance side. It does seem to appear in the standard UI if dominos is turned off. Pictures are the character with the missing XP bar in config mode. My Horde Paladin with an XP bar showing at the top on the same profile and the character with the default UI and the XP bar showing in the default UI.
![WoWScrnShot_101720_054051](https://user-images.githubusercontent.com/73018751/96334091-2765d780-103c-11eb-9158-812db982b39b.jpg)
![WoWScrnShot_101720_054233](https://user-images.githubusercontent.com/73018751/96334063-ef5e9480-103b-11eb-994b-cc43ea8cf21e.jpg)
![WoWScrnShot_101720_054405](https://user-images.githubusercontent.com/73018751/96334069-f4bbdf00-103b-11eb-8ad0-1f4370d4316c.jpg)

**Comment by Tuller** [comment]
Can you doublecheck that Dominos_Progress is enabled on those characters?

**Comment by elainedeshalott** [comment]
I am not sure what suddenly changed but the bar which was missing through several reboots this morning is now showing on that Character.
