### ISSUE TITLE
Vehicle UI mover and scaling option

### ISSUE THREAD

**Issue by siven80** [tullamods/Dominos#473]
I have always used moveanything to scale down the default Vehicle UI, and now thats its not working, i thought dominos would be a good place for this feature as it is an action bar. 

I have no idea if its actually possible easily tho.

**Comment by Tuller** [comment]
Dominos has an option, "Use Blizzard Override Bar". If you uncheck that, Dominos will just place vehicle abilities on whatever bar you want instead of showing the full Blizzard UI for it. Does that work well enough?

**Comment by siven80** [comment]
It works, tho i wished the other bars would hide so that only bar 1 would show.

Tho i kinda like the blizz vehicle bar. Luckily moveanything has been updated so i can scale that down to 0.8 again.
