### ISSUE TITLE
Can't click ExtraActionButton after fight reset.

### ISSUE THREAD

**Issue by MaximusPM** [tullamods/Dominos#475]
The Extra Action Button seem to be pretty screwed. Have been seen a couple of issues with it.

The one I'm having is that after resetting a raid fight, I can't click it unless I do a /reload first when using Dominos. If I disable it, it works fine.

**Comment by Tuller** [comment]
Does this happen with just Dominos enabled? Other stuff could be messing with the bar too.

**Comment by MaximusPM** [comment]
I disabled all addons, did a reload and tried with no addons on. It works fine. Then I enabled only Dominos, and this happens. Was testing with Demonic Inquisition in the Tomb of Sargeras because it has both the Action Button and the Extra Power Bar.

**Comment by ronin-seven** [comment]
Just had this happen to me this morning.  Was doing a LFD in Shadow Pan Monastery and on the last boss (Taran Zhu), the extra action button worked fine the first time.  We wiped, ran back and tried again.  That's when I realized the button wasn't responsive anymore.

**Comment by Tuller** [comment]
Can you do a /framestack, hover over the frame, and send a screenshot?

**Comment by MaximusPM** [comment]
First pull - all addons loaded.

![WoWScrnShot_101920_153853](https://user-images.githubusercontent.com/73047187/96498452-72d9da80-1222-11eb-8a17-d55d4bbed8ac.jpg)
![WoWScrnShot_101920_153854](https://user-images.githubusercontent.com/73047187/96498456-74a39e00-1222-11eb-9e6b-dc58a3f8da05.jpg)

Second pull - all addons loaded. Framestack doesn't even identify the extra action button.

![WoWScrnShot_101920_153957](https://user-images.githubusercontent.com/73047187/96498466-766d6180-1222-11eb-8a85-8747e2c76c66.jpg)

Then I disabled all addons but Dominos.

First pull - exact same thing.

![WoWScrnShot_101920_154316](https://user-images.githubusercontent.com/73047187/96498470-779e8e80-1222-11eb-92d6-4f5bfb8523e4.jpg)
![WoWScrnShot_101920_154318](https://user-images.githubusercontent.com/73047187/96498472-78372500-1222-11eb-99c3-4041a074a398.jpg)

Second pull - exact same thing. Framestack can't identify any frames.

![WoWScrnShot_101920_154350](https://user-images.githubusercontent.com/73047187/96498476-79685200-1222-11eb-80f3-51295f09cd53.jpg)

When I disable all addons, including Dominos, it shows the frame information for the Extra Action Button every pull.

**Comment by Tuller** [comment]
Please try the https://github.com/tullamods/Dominos/releases/tag/9.0.6-beta beta release  once it appears.

**Comment by MaximusPM** [comment]
It worked!

**Comment by MaximusPM** [comment]
Damn, I'm having the problem again, but this time with quests. Not sure about the behavior here because sometimes it works, sometimes it doesn't.

![WoWScrnShot_102120_004525](https://user-images.githubusercontent.com/73047187/96670957-16b4aa80-1337-11eb-86e3-f6a685ff3e7e.jpg)

**Comment by Tuller** [comment]
Try with 9.0.7 and see if it fixes things up. I think the culprit is some interaction between the ExtraAbilityContainer having toplevel = true and mouse interactions enabled on ExtraActionBarFrame.

**Comment by ronin-seven** [comment]
Just FYI, I took my hunter over to the Demonic Inquisition in the Tomb of Sargeras just now with 9.0.12 and did the same thing MaximusPM did, started the encounter to bring up the EAB and then FD'ed to reset the bosses.  I did this multiple times and each time the EAB was interactable, so hopefully we're good now.

Thanks!
