### ISSUE TITLE
Pet/Stance bar not inheriting correct hotkey info

### ISSUE THREAD

**Issue by ned406** [tullamods/Dominos#478]
For whatever reason the pet/stance bar does not use override fonts when using Masque and I don't know what sort of LUA command would force it to do this. The pics below are of the pet bar and then an action bar with pet abilities and you can see how the fonts and sizes are different.

Pet Bar
![Petbar](https://user-images.githubusercontent.com/41378787/96386131-83da0b80-1190-11eb-8d7a-5ebee48ca2cd.png)

Action Bar
![Normal bar](https://user-images.githubusercontent.com/41378787/96386134-8d637380-1190-11eb-9330-138ce80aa259.png)

**Comment by Tuller** [comment]
This one is likely related to https://github.com/tullamods/Dominos/commit/1daeae9eb5cae5b381d3dcd5bc53da467a50db4c. In that one, I resize the fonts on the pet/stance bars to fit better within the frames.

**Comment by Tuller** [comment]
This should be resolved in 9.0.11. I've changed the behavior so that the pet button/stance button text is only resized when not using a masque skin.
