### ISSUE TITLE
Extra Action Button Gone in 9.0.6 Beta

### ISSUE THREAD

**Issue by OdessaGrimaldus** [tullamods/Dominos#479]
Just as the title says, with this newest update I have no button movement option visible for the Extra Action Button to be moved through Dominos.

The only time this option does become visible for me is when the Extra Action Button itself is active in a zone/encounter. Aswell when it does become active, even with the setting enabled to remove the Blizzard Texture, with each no appearance of the Button this setting does not keep the Texture invisible.

**Comment by Tuller** [comment]
Can you verify that twitch didn’t give you the classic version?

**Comment by MaximusPM** [comment]
Mine is working perfectly:

![WoWScrnShot_102020_172452](https://user-images.githubusercontent.com/73047187/96640220-3e851d80-12f9-11eb-9f6b-f228a4f0ed37.jpg)

**Comment by Tairgire** [comment]
I'm having a similar/related problem with the 9.0.6 release.  When I click Configure, I do not see the draggable area for the extra button and it is reset to default (middle lower part of my screen).  I'm in Draenor so it's always visible right now.  I tried to find a setting that might control this but didn't see one.  I turn off Dominos_Cast, Progress, and Roll as I don't use those, in case that matters.  I reverted back to .05 and the button was both movable again and back at where I had placed it prior to upgrade.

**Comment by MaximusPM** [comment]
> 
> 
> I'm having a similar/related problem with the 9.0.6 release. When I click Configure, I do not see the draggable area for the extra button and it is reset to default (middle lower part of my screen). I'm in Draenor so it's always visible right now. I tried to find a setting that might control this but didn't see one. I turn off Dominos_Cast, Progress, and Roll as I don't use those, in case that matters. I reverted back to .05 and the button was both movable again and back at where I had placed it prior to upgrade.

The draenor garrison button is the Zone Ability Button, which is separate from the Extra Action Bar button

**Comment by Tuller** [comment]
That indicates to me you probably are running the classic release.

**Comment by Tairgire** [comment]
Indeed I was.  I will shake my fist at Twitch for giving me the wrong version again, though I should know to double-check by now.  Thanks for your patience!

**Comment by OdessaGrimaldus** [comment]
I did update to the current release and it is still an issue.

The issue of it jumping all around the screen with every reload still exists.. ..and if I do not go into the config for the Extra button everytime I reload, relog or anything of the like..the Blizzard Texture will appear for the button, even though it is disabled..and I must go in, enable and disable it again for it to be removed..but even then with the texture hidden, I will not be able to interact with anything that would be behind it..such as to put it next to my bars here on their left side..the texture that is hidden but extends out onto the stacks of bars of buttons I have here..will still impede me from being able to click any of them

![image](https://user-images.githubusercontent.com/67622191/96663828-80c15580-131f-11eb-9f59-f56430e6ff3c.png)

**Comment by Tuller** [comment]
If I recall, Titan panel is the culprit in that screenshot.

**Comment by OdessaGrimaldus** [comment]
> If I recall, Titan panel is the culprit in that screenshot.

I disabled all other addons besides Dominos, and the issue still persists. Even with the button texture hidden, it still retains it's blocking of anything that would be behind it, had it been enabled. Like this here screenshot before, all buttons to the left of the Kidney Shot I am moused over to show it's tooltip show no registration that they are moused over, show a tooltip for being moused over, and cannot be activated/clicked upon despite the texture being hidden.

![image](https://user-images.githubusercontent.com/67622191/96789221-c4b96680-13c2-11eb-98ad-9edc0d52c471.png)

**Comment by Tuller** [comment]
For the interactivity thing, try `/run ExtraActionBarFrame:EnableMouse(false)`. I'll roll that into the next update.

**Comment by OdessaGrimaldus** [comment]
> /run ExtraActionBarFrame:EnableMouse(false)

Tuller you are a SAINT!

That did it! I now have use of my action button and all buttons that it previously would have disabled!

Thank you so much for putting up with all these posts form me to fix this nitch issue, and I hope that in the end I have been atleast of some help to you to be sure that Dominos is only made just that small bit better for all whom have the joy of using it.

**Comment by Tuller** [comment]
Also for titan panel, `/run TitanMovable_AddonAdjust("ExtraActionBarFrame", true)`, They have some special case code for Elv and Bartender that should probably be applied for Dominos too.
