### ISSUE TITLE
can not switch to stealth bar

### ISSUE THREAD

**Issue by icekylinH** [tullamods/Dominos#481]
when the character switch between different stance, the car will not change , similar problems happened in Rogue and Druid.
**Addon Version**
9.0.6

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
Does this happen with just dominos enabled? Can you provide the info from /dom version?

**Comment by icekylinH** [comment]
Yes,Dominos only. Could be this one related with my language setting? I am not using English version client. 
![QQ图片20201021120455](https://user-images.githubusercontent.com/26866411/96666185-c6b90080-1395-11eb-83ad-da80f98b3340.png)

**Comment by icekylinH** [comment]
![屏幕截图 2020-10-21 120909](https://user-images.githubusercontent.com/26866411/96666730-e4d33080-1396-11eb-91c5-980fbb785c89.png)

[2020-10-21 12-13-11.zip](https://github.com/tullamods/Dominos/files/5412960/2020-10-21.12-13-11.zip)
As you can see in here. Even after I deleted my WTF folder and only have dominos in my Addons folder. All bar in the screen, none of them change along with my transformation. 
The zip file is my record

**Comment by icekylinH** [comment]
BTW: This also existed for 9.0.5 for me.not a new problem

**Comment by Tuller** [comment]
What does /run GetBuildInfo() give you? I assume your realm is running the Shadowlands pre patch?

It could be an non English client issue, but I would expect at least a failed to load error from Dominos in the chat log.

**Comment by icekylinH** [comment]
Yes , you are correct. My realm is running the Shadowlands pre patch
![无标题](https://user-images.githubusercontent.com/26866411/96756371-2acdda00-1413-11eb-839c-c05733b20ead.png)
The above is the output of GetBuildInfo. Could you tell me how to find this error log you need? I am not very familiar with this kind of thing

**Comment by Tuller** [comment]
That was mostly for me to confirm you're running on a 9.0 realm. As far as error messages go, if a bar fails to load in Dominos it prints an error message in chat. Otherwise you need to either enable lua errors or install BugSack/BugGrabber to figure out what lua error messages are coming through.

**Comment by kuletco** [comment]
This bug seems to be due to the improper OnLoadSettings working at bars/actionBar.lua:61. So you can temporarily resolve it by initializing the 'pages' variable by player class with 'mainbarOffsets.__index' in function ActionBar:GetDefaults().
