### ISSUE TITLE
Class bar with opacity 0 shows cooldown finishing pulse

### ISSUE THREAD

**Issue by neoxz04** [tullamods/Dominos#484]
**Addon Version**
9.0.7-Retail

**World of Warcraft Version**
Retail 9.0.1 36322 Oct 20 2020

Steps to reproduce: set Class Bar fade out opacity to 0, then cast a spell.
I would expect nothing happens on Class Bar, but its buttons show finishing pulse after 1 GCD. This is inconsistent with what I get when doing the same steps on an action bar.
 
Short video demonstrating the problem: https://i.gyazo.com/493b4db4c262be1da5eac29b62f1d8a6.mp4

**Comment by Tuller** [comment]
Yeah this is a rendering bug on Blizzard's side that I normally have to work around
