### ISSUE TITLE
Bags

### ISSUE THREAD

**Issue by Liylith** [tullamods/Dominos#485]
Since the last update the bags bar is not working properly. I made sure it wasn't hidden but still it is not showing.

**Comment by Sansaan** [comment]
Workaround: Pull up Dominos options, Configure Bars... Right-click the bags bar, uncheck "Show Bag Slots" then recheck it. Bags will be visible until reload.

**Comment by Anduviel** [comment]
I installed an older version to solve this problem,
 but this should not happen

**Comment by danielsawan** [comment]
same here
