### ISSUE TITLE
Updated to 9.0.9. Now missing Pet Bar and Pally Aura bar.

### ISSUE THREAD

**Issue by Sansaan** [tullamods/Dominos#486]
Classic. Reverting to 9.0.8 returns the pet bar and aura bar.

**Comment by WokenClick** [comment]
I can second this, it also has issues with Warrior, Druid, and Rogue "Stance" bars. Also, I get the error message "Failed to load StanceBar Interface\AddOns\Dominos\plugins\buttonthemer.lua:31: Wrong object type for function when I try to load a profile.

**Comment by luc2** [comment]
- Stance button in the middle of the screen
- Impossible to move it
- Resetting profile doesn't fix anything
- No stance bar
- Warrior, Rogue, Druid, Paladin

![dominos-bug](https://user-images.githubusercontent.com/2410567/97039308-85c71480-156c-11eb-9a21-8f6be0a4af77.jpg)

**Comment by Tuller** [comment]
My fault for only checking on the beta client, it looks like

**Comment by luc2** [comment]
It seems to work now. Thanks.
