### ISSUE TITLE
Config Menu does not open

### ISSUE THREAD

**Issue by LybrialsGit** [tullamods/Dominos#487]
**Addon Version**
9.0.10

**World of Warcraft Version**
Retail

**Steps to reproduce**
- Left-Clicking Minimap Icon to open the config does not open the config
- Typing /dominos config in chat does not open the config

**Comment by dajposkakac** [comment]
Has this been fixed? I'm having this issue on 9.0.12-Retail. Dominos isn't even showing up in Interface > AddOns. /dominos in chat shows the list of commands but /dominos config does nothing

**Comment by LybrialsGit** [comment]
In my case it was stupidity ;)
Dominios Options was disabled by default but needs to be enabled.
@Tuller I would recommend that in that case the Addon should print out a message that the options addon is missing.
I would also move the minimap icon to the options addon.

**Comment by dajposkakac** [comment]
Ah, of course, it was disabled for me too. Thank you

**Comment by Tuller** [comment]
The minimap button can’t be included in just the configuration part, as Dominos_Config is meant to be loaded dynamically to save a bit of memory. I can, however, check ahead of time to see if the Config add on is enabled and not load it if that’s the case
