### ISSUE TITLE
Separate Extra Action button and zone ability button

### ISSUE THREAD

**Issue by ColliderGX** [tullamods/Dominos#489]
The Extra Action button and zone ability button are currently linked together and separated by a large amount of pixels and can only move together.

It would be great to be able to move these around separately.

**Describe alternatives you've considered**
Alternative could be a slider the removes the distance between both items.

**Comment by Tuller** [comment]
This is how blizzard has implemented them in the new patch, and I would prefer to not need to make a completely custom implementation. The zone ability buttons, in particular may have issues even working in combat if I went that route

**Comment by ColliderGX** [comment]
Ok, thanks for hearing my request. I will just move them to a good spot then.
