### ISSUE TITLE
9.0.11-classic - Bag Count Issues - Soul Pouches

### ISSUE THREAD

**Issue by Sansaan** [tullamods/Dominos#490]
Free space count on Soul Pouches is being reported incorrectly... Dominos is reporting used spots instead of free spots. Normal bags and quivers are reporting normally. Unsure about other bag types.
![image](https://user-images.githubusercontent.com/67605814/97119439-90a5b480-16e6-11eb-98f8-332623c3af1c.png)

**Comment by Tuller** [comment]
What happens if you disable dominos? I don't really mess with the text on the backpack button

**Comment by Sansaan** [comment]
My bad... maybe that's normal, then, for Soul Pouches... reverted back a few releases and also disabled and it was the same result.
