### ISSUE TITLE
AP bar is missing

### ISSUE THREAD

**Issue by Ashna1** [tullamods/Dominos#492]
I am playing retail wow, using Dominos-9.0.11.  I just noticed today that the AP bar is missing.  I reloaded the UI after unchecking Dominos and the AP bar is there in the wow default UI.

**Comment by MaximusPM** [comment]
Didn't you download the Classic version by mistake?

**Comment by Ashna1** [comment]
No, it's the same one I've been using for quite a while, just updated it.  It's updated for game version 9.0.1

**Comment by Ashna1** [comment]
And I don't believe it's a conflict with another addon.  I only use Coordinates, Dominos, LiteBag, Numeration, Simulationcraft, and DejaCharacterStats

**Comment by Tuller** [comment]
Did you uncheck one bar mode? /dominos, then the progress panel

**Comment by Ashna1** [comment]
I never checked it.  Thanks.
