### ISSUE TITLE
"Eye of Kilrogg" warlock ability bar bug

### ISSUE THREAD

**Issue by addonaddict** [tullamods/Dominos#493]
Thank you for the amazing addon. Using it for years!

Noticed a bug that happened even before SL prepatch:
Using ability like eye of kilrogg shows part of a default blizz frame instead of being integrated with dominos
this happens with or without "use blizz override action bar" toggled in the options
is it possible to make it so this bar replaces the "override bar" selection?

Thank you!

![image](https://user-images.githubusercontent.com/73442541/97789634-6c3f5180-1b98-11eb-9503-280be1630d31.png)

**Comment by Tuller** [comment]
The possess bar frame is one I'll most likely just hide in the next update

**Comment by Tuller** [comment]
And it should be hidden in the 9.0.13 release
