### ISSUE TITLE
Exit taxi button (vehicle bar) does not show

### ISSUE THREAD

**Issue by madmaninabox75** [tullamods/Dominos#497]
Hello,
I recently switched back from ElvUI to the default interface and re-enabled all addons I used, including Dominos.
For some reason, the button to request the dropoff at next flight point does not show. I checked the vahicle bar multiple times and it is set to show and everything.
What can I do to have it shown? Even showing default Blizzard button instead of Dominos' would be fine, but I can't figure out how to do it.
Thank you very much,

**Comment by Tuller** [comment]
Can you replicate this with just Dominos enabled? Sometimes things like MoveAnything can mess with different parts of the UI

**Comment by Tuller** [comment]
I've still not reproduced, I'm calling this one an addon conflict
