### ISSUE TITLE
Unable to config Keybinds through Game Menu-Key Bindings-Dominos, vice versa.

### ISSUE THREAD

**Issue by baozilla** [tullamods/Dominos#501]
**Addons Enabled:** Dominos, Dominos Config, nothing else.
**Version:** 9.0.14-Retail
**WoW Version:** 9.0.1 (36577)(Release x64)

**Steps to Reproduce:**
1. Delete Cache and WTF folders for a fresh install
2. Download Dominos through WoWup.io
3. Enter game with only Dominos and Dominos Config enabled
4. Open Game Menu by pressing ESC, click Key Bindings, click Dominos
5. Select any Button (all should be "Not Bound"), bind selected Button with any key
6. Okay out of Key Bindings and Return to Game
7. Put any ability on previously selected Button
8. Press the ability, nothing will happen
9. Enable "Show Binding Text" under Dominos General configuration, none of the Buttons will show a key bind.

**In Reverse:**
10. Enter Dominos Binding Mode by Shift-Left Clicking on the minimap icon
11. Select any Button other than one selected in Step 5, bind selected Button with any key
12. Okay out of Binding Mode
13. Open Game Menu by pressing ESC, click Key Bindings, click Dominos
14. All Buttons, excluding one selected on step 5, will show "Not Bound"

**Workaround** is to obviously use Dominos Binding Mode at all times. However, Dominos Binding Mode does not recognize controller input, thus limiting controller players to the 5 Blizzard action bars. The above was tested with GamePad both enabled and disabled with no impact to the outcome.

Love this addon, hope this is an isolated case.

**Comment by Tuller** [comment]
This one was a typo in my bindings.xml file (CLICK:thing instead of CLICK thing)
