### ISSUE TITLE
Change bar anchoring point

### ISSUE THREAD

**Issue by addonaddict** [tullamods/Dominos#502]
**Is your feature request related to a problem? Please describe.**
When putting 2 horizontal bars together, there is no way (that i know of) to clamp them directly to middle of screen, see screenshot below

**Describe the solution you'd like**
Either allow clamping to middle of screen at both left and right sides of action bar by default, or enable option for each bar to change anchoring point from middle to maybe left and right which means u can center the 2 bars

**Describe alternatives you've considered**
n/a

**Additional context**

![image](https://user-images.githubusercontent.com/73442541/99194615-7ba0cc00-274e-11eb-8d9a-ef0905690a09.png)

**Comment by Tuller** [comment]
Yep, I plan on doing this.

**Comment by Tuller** [comment]
Along with the built in alignment grid in the latest releases, I have a branch that snaps bars to the nearest vertex on the grid
https://github.com/tullamods/Dominos/tree/snap-to-grid

I still need to apply auto centering and screen edge snapping again, though.

**Comment by addonaddict** [comment]
Just tried it and i am not able to snap right side of an actionbar to center of screen like in the image I added above
Am i missing something? 
Version 9.0.19
thx

**Comment by Tuller** [comment]
Try in 9.0.20
