### ISSUE TITLE
Show Alignment Grid does not appear when checked

### ISSUE THREAD

**Issue by karma12gaming** [tullamods/Dominos#505]
When configuring bars, "Show alignment grid" does not appear when checked. We've reinstalled / updated Dominos as well as disabled all other add-ons but it still doesn't appear. 

Edit: I forgot to mention this is 9.0.18 Retail 

![Dominos_grid_bug](https://user-images.githubusercontent.com/16180200/100261075-3c296b00-2f18-11eb-8882-dc1c1f834c92.jpg)

**Comment by Tuller** [comment]
Are you getting any error messages? You may need to install BugSack to see lua errors

**Comment by MaxXevious** [comment]
I am having this same issue, but then at times it will show the grid if I change the spacing but its not uniform, it feels like parts are missing.

on 64, 96, and 128
![12-29-2020 5-56-01 PM](https://user-images.githubusercontent.com/76759928/103325144-4818b900-49ff-11eb-853c-951045ba6b56.png)
![12-29-2020 5-56-26 PM](https://user-images.githubusercontent.com/76759928/103325145-48b14f80-49ff-11eb-96c6-8b6795b99427.png)

 density, no grid

on 80 its horizontal lines only, and odd spacing (its missing lines)

on 104, its missing more vertical lines.

**Comment by Tuller** [comment]
This is roughly due to using a 1pixel line size + UI scaling

**Comment by Altoholic** [comment]
Same problem here, on WoW classic. Fresh install of everything (including Windows and WoW classic) from today.
No lua error.

**Comment by Tuller** [comment]
This should be fixed in the latest version
