### ISSUE TITLE
Add action bars

### ISSUE THREAD

**Issue by Azurix78** [tullamods/Dominos#506]
Hi,

First of all thank you for your work. I've been using Dominos since my WoW debut and I think I'll continue to use it!
I just have a question about how many bars you can use.

Is there a limit on the number of bars that Blizzard allows?
I tried to modify the Dominos.lua file by changing the values of :

`Addon.ACTION_BUTTON_COUNT = 168`

```
ab = {
    count = 14,
    showgrid = true,
    rightClickUnit = 'player'
}
```

The bars appear well in game but unfortunately I can't add anything to them, I get an error when I try.

**Comment by Tuller** [comment]
There's a hard limit of 120 action slots on blizzard's end

**Comment by Azurix78** [comment]
Ohh ok thanks for your answer !
