### ISSUE TITLE
Azerite Power bar?

### ISSUE THREAD

**Issue by milioner1** [tullamods/Dominos#511]
I'm using the Shadowlands version of Dominos (fully updated), and yet the Azerite Power bar is still appearing in place of something more relevant such as Renown, Anima, Soul Ash or Stygia. Also, I can't find a way to edit the texture or font of that bar.

Are you guys working on something in that regard?

**Comment by Tuller** [comment]
Nothing yet, maybe on the weekend

**Comment by Tuller** [comment]
I don't know if I'll actually do anything for this. Its much less like an experience bar than previous progression systems were.

**Comment by milioner1** [comment]
Renown is capped weekly; perhaps it could set the full bar to the weekly cap and the empty bar to your current standing, so if for example you're at renown 6 and this week the cap is 9, every upgrade would increase the progression by 33%. Maybe that could just be one toggle-able mode of renown tracking and you could engineer another one. Besides that there are other currencies that should be added, like the ones I mentioned, while the AP bar at least should definitely be removed. Cheers 😛
