### ISSUE TITLE
castbar color (hunter)

### ISSUE THREAD

**Issue by h3LLgun** [tullamods/Dominos#512]
Hi, i have an issue with castbar color on hunters. All abilities (for example aimed shot/rapid fire) displayed in gray color, while other classes is fine, everything displayed in different colors. How can i customize color? 
![WoWScrnShot_120520_224605](https://user-images.githubusercontent.com/20191431/101263179-07a18480-374c-11eb-9356-730c1e521c45.jpg)

ver 9.0.2

**Comment by Tuller** [comment]
I think that’s the uninterruptible cast color. More options to customize that will come along eventually
