### ISSUE TITLE
bags bar disappeared; now stuck into menu bar

### ISSUE THREAD

**Issue by vincenthowland** [tullamods/Dominos#513]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.
![bags menu](https://user-images.githubusercontent.com/75549465/101267650-f5fab580-3728-11eb-82d4-9794dcaeb824.png)

**Addon Version**
You can get this via running `/dominos version` in game
9.0.19-Classic

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.
Classic

This happened while arranging things with Dominos, the two bars overlapped, then the bags became stuck within the menu bar.

**Comment by Tuller** [comment]
Are all other addons disabled when this happens?

**Comment by vincenthowland** [comment]
yes. Tried both with and without other add-ons.

**Comment by Tuller** [comment]
Weird. Try /run Dominos.do.profile.frames.bags = nil; ReloadUI()

**Comment by vincenthowland** [comment]
didn't work for me. I think the script didn't actually run anything bc I
didn't see the reload screen

**Comment by Tuller** [comment]
You may need to turn on scripts for that. Normally, that will reset the bag bar its default position

**Comment by Xpucmemo** [comment]
I know exactly how it happens -> when you use WASD to push the bag outside the borders of the screen (at least for me on bottom left it vanishes with S and D
