### ISSUE TITLE
Rogue stealth bar shows when not in stealth but in soul form (fae covenant)

### ISSUE THREAD

**Issue by Hauchka** [tullamods/Dominos#514]
Only Dominos Activated:

When I cast my soul form (fae covenant skill) bar 1 changes to stealth bar.

Addon Versión 9.0.19

Wow version: 9.0.2.X

Screens:

Stealth:
https://i.imgur.com/RAfN3tP.png
Not in stealth:
https://i.imgur.com/bDe8COt.png
Soul form:
https://i.imgur.com/DBUDnHk.png

Thank you so much :)

**Comment by Tuller** [comment]
What do your paging settings for the bar look like?

**Comment by Hauchka** [comment]
Like this:
https://i.imgur.com/DHdnpSa.png
https://i.imgur.com/sEQ3zTw.png
https://i.imgur.com/uSNXzCK.png

Translate:
Danza de las sombras -> Shadowdance
Sigilo -> Stealth
Página de acción X -> Action page X
Modificadores -> Modifiers
Tecla autohechizoc -> Autospell key

Changing shadowdance to "not active", the bar doesn't change, so It seems that the soul form and shadowdance triggers the same code.

**Comment by Tuller** [comment]
That makes sense. I wonder if shadowstate triggers something other than than [form:2] in this case.

**Comment by Hauchka** [comment]
Sorry for the delay, I was doing some tests in Outlaw and Sublety, with and without the option "shadowdance" activated in the castbar1 using "/script print(GetShapeshiftForm())"
In stealth returns always 1.
In shadowdance and soulform returns always 2 BUT with the shadowdance option not activated, the castbar change to stealth bar, so I think the game runs some other code to trigger the same as stealth when in shadowdance, so deactivating the option I got the spected behaviour.

It works for outlaw and sublety.

**Comment by Tuller** [comment]
Try this condition in a macro maybe [form:2,stealth]

**Comment by Tuller** [comment]
I've increased the specificity a bit more in 9.0.20. let me know if that helps

**Comment by Hauchka** [comment]
It works perfectly en 9.0.21 :)
Thank you so much Tuller <3 !!!

**Comment by Hauchka** [comment]
Solved 👍

**Comment by wutra4444** [comment]
Hello there, I am having the same issue now, when I use soulshape dominos activates shadowdance bar.

**Comment by wutra4444** [comment]
Sorry, stealth bar not the shadow dance.
