### ISSUE TITLE
Azerite power bar shows up even without azerite neck

### ISSUE THREAD

**Issue by addonaddict** [tullamods/Dominos#517]
Azerite bar should be disabled unless it is actually being tracked (while wearing the neck)
What is happening to me is i have nothing being tracked, so i want the bar to disappear (one bar mode, skip inactive)
Right now it defaults to azerite.
Any chance azerite tracking can be removed unless wearing the neck, and if nothing is being tracked, make the bar disappear?
Thanks

**Comment by Tuller** [comment]
This should be fixed in 9.0.20. You can also always get rid of the bar via putting progress into one bar mode (/dominos)

**Comment by Holleywood28** [comment]
My XP bar keeps changing to azerite power regardless of what I try and I have the new version. Any suggestions?

**Comment by addonaddict** [comment]
Same here. Constantly resets to azerite power (my toon is at max level)

**Comment by Tuller** [comment]
Do you have auto switch enabled by chance?

**Comment by addonaddict** [comment]
There seems to be something off about the azerite power bar, here's whats happening to me:

1. enable one bar mode
2. enable skip inactive modes
3. select any reputation to track (max level toon, no exp bar present)
4. rep bar gets replaced with azerite power bar after a /reload (azerite neck sitting in bank, unused)

perhaps if possible azerite bar should be disabled completely when neck not worn? currently addon is not finding it to be "inactive"
currently it kind of forces the user to use 2-bar mode which some, like me, dont really like

hope this helps
