### ISSUE TITLE
Extra Action Button Missing

### ISSUE THREAD

**Issue by OdessaGrimaldus** [tullamods/Dominos#518]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** 
Issue is that the Extra Action Button doesn't appear anymore, even when enabled. The square box of the button doesn't appear, nor does anything show even when the "show Blizzard details" option is enabled. 

Also, all bars, be they enabled or hidden now manifest as this screenshot here below shows. Until you click to set the bar to hidden and back to show again when configuring bars and buttons, all are just a solid color and nothing visible. Grey is hidden/disabled bars, and blue are enabled bars.

Solid Bars
https://imgur.com/a/D9p23oC

Bars After Being Clicked While Solid
https://imgur.com/a/u8KhGub

**Addon Version**
Dominos-9.0.19.zip

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
The opaque stuff should be resolved.  Where are you testing the extra bar for display?
