### ISSUE TITLE
I get error occasionally after 9.0.20 update.

### ISSUE THREAD

**Issue by zzipsa22** [tullamods/Dominos#521]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
You can get this via running `/dominos version` in game
9.0.20

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.
Retail

28x FrameXML\PetActionBarFrame.lua:247: attempt to perform arithmetic on a nil value
[string "@FrameXML\PetActionBarFrame.lua"]:247: in function `PetActionBar_UpdatePositionValues'
[string "@FrameXML\UIParent.lua"]:3312: in function `UIParentManageFramePositions'
[string "@FrameXML\UIParent.lua"]:2632: in function <FrameXML\UIParent.lua:2619>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3422: in function <FrameXML\UIParent.lua:3420>
[string "=[C]"]: ?
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@FrameXML\MainMenuBar.lua"]:160: in function <FrameXML\MainMenuBar.lua:137>
[string "=[C]"]: in function `MainMenuBarVehicleLeaveButton_Update'
[string "@FrameXML\MainMenuBar.lua"]:134: in function <FrameXML\MainMenuBar.lua:133>

Locals:
(*temporary) = nil
(*temporary) = MainMenuBarVehicleLeaveButton {
 0 = <userdata>
 Highlight = <unnamed> {
 }
}
(*temporary) = "attempt to perform arithmetic on a nil value"

it seems this is related exit vehicle button.

**Comment by Tuller** [comment]
Looks like I found a bug with the Blizzard UI, yay :) I've given the Blizzard possess bar and that seems to resolve it.
