### ISSUE TITLE
v9.0.20, new errors (posted below)

### ISSUE THREAD

**Issue by digitalmuze** [tullamods/Dominos#522]
with v9.0.20, new errors (posted below) ... reverted to v9.0.19 to remedy

10x FrameXML\PetActionBarFrame.lua:247: attempt to perform arithmetic on a nil value
[string "@FrameXML\PetActionBarFrame.lua"]:247: in function `PetActionBar_UpdatePositionValues'
[string "@FrameXML\UIParent.lua"]:3312: in function `UIParentManageFramePositions'
[string "@FrameXML\UIParent.lua"]:2632: in function <FrameXML\UIParent.lua:2619>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3422: in function `UIParent_ManageFramePositions'
[string "@FrameXML\MainMenuBar.lua"]:160: in function <FrameXML\MainMenuBar.lua:137>
[string "=[C]"]: in function `MainMenuBarVehicleLeaveButton_Update'
[string "@FrameXML\MainMenuBar.lua"]:134: in function <FrameXML\MainMenuBar.lua:133>

Locals:
(*temporary) = nil
(*temporary) = MainMenuBarVehicleLeaveButton {
0 = <userdata>
Highlight = <unnamed> {
}
}
(*temporary) = "attempt to perform arithmetic on a nil value"

**Comment by Tuller** [comment]
This should be fixed in 9.0.21
