### ISSUE TITLE
Talking head seems have more than one instance

### ISSUE THREAD

**Issue by yimgame** [tullamods/Dominos#524]
Hey, first of all, i love this addon, is just brilliant.

**Is your feature request related to a problem? Please describe.**

I see talking head in default and modify location one at a time y can't move one, the default one, just bring in default possition sometimes, i think is not the same frame as regular.

**Describe the solution you'd like**

Could be possible unifique all the position of talking head to just one location. i mean write booth coordinates together.

**Describe alternatives you've considered**

Just let move the second one to the same position as one, u will see one at time, but they are two frames and actually u can move one.

**Additional context**

Sorry i dont take any screenshoot, i will try to install moveanything and see if i can see the frame name.

**Comment by Tuller** [comment]
9.0.23 should resolve this.
