### ISSUE TITLE
bar positions keep resetting to unintended default location

### ISSUE THREAD

**Issue by Minuit-Monstre** [tullamods/Dominos#525]
it's inconsistent which bar/anchor does it between the exp bar, the loot roll bar, the class bar, the cast bar, the pet bar, but when i log out some (these specific ones i ran into) keep resetting to a default position that i have no control over after setting where i wanted them. 

**Addon Version**
9.0.21-Classic

**World of Warcraft Version**
WoW Classic

**Comment by Tuller** [comment]
Do you have screenshots of this?

**Comment by Minuit-Monstre** [comment]
Problem seems to have gone away with unchecking the “show grid” button and sticky bars.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Tuller** [comment]
That sounds like you're getting an error message that may be hidden. I would try installing BugSack + BugGrabber

**Comment by Goranaws** [comment]
Minuit-Monstre, seeing a copy of your saved variables for dominos, might help solve this error.


Tuller, this could be a bug in FlyPaper.

**Comment by lvangh** [comment]
I'm having the same problem on only one character with one bar. I suspect this may have something to do with profiles that have been updated over time? The issue for example is I made a 3x1 bar and I go to config mode to move it, I log out, log back in and it's back to the same initial spot. I think I will just manually edit the position in the \WTF folder.

**Comment by Altoholic** [comment]
I have the same problem on WoW classic, with a fresh install (including Windows and WoW classic) from today.
No lua error (i have bugsack an,d buggrabber).
