### ISSUE TITLE
Consumables sometimes stop updating on actionbars.

### ISSUE THREAD

**Issue by arcadepro** [tullamods/Dominos#526]
Retail WoW. Dominos 9.0.21 and earlier versions.

Sometimes, quite rarely, consumables on the actionbar just stop updating their amounts correctly. i.e. Potions do not show correct amount from bags, healthstones may indicate one use remaining when it's actually none. 

I have no idea what causes it yet and I realise this is a vague bug but it does happen. I wanted to see if anyone else has encountered this issue. (It also occurred in BFA but I was too lazy to post about it)

**Comment by Tuller** [comment]
The only modifications I make to the count display are:
* Allowing you to hide/show counts
* Providing counts for abilities that don't normally show them (only in classic)

So I'd be curious if this happens to you on the stock UI
