### ISSUE TITLE
Buffs/Debuffs control implementation (Dominos_Auras standalone addon replacement)

### ISSUE THREAD

**Issue by addonaddict** [tullamods/Dominos#527]
**Is your feature request related to a problem? Please describe.**
If a user wants to move buffs/debuffs, they need another addon like Move Anything. There are a few such addons out there, but they all make unnecessary changes to how the cooldown text looks on these auras.
Also, when using Masque, it affects dominos bars and everything else with exception of buffs and debuffs near the minimap.
Dominos_Auras addon (made by other author I think) does the same thing, but it is not updated and makes the cooldown text sit right on top of the buffs with no way to control it, which is ugly and makes it hard to see. On some auras, the text is same color as the background.....
Example:
![image](https://user-images.githubusercontent.com/73442541/102719122-2199a600-42ba-11eb-92e0-b281ea57e132.png)

how I want it to look, but with support for Masque and ability to move them around:
![image](https://user-images.githubusercontent.com/73442541/102719231-e481e380-42ba-11eb-8693-751cca84c4b3.png)

**Describe the solution you'd like**
I would like Dominos to implement a simple drag and drop to buffs/debuffs near minimap, without affecting how it displays cooldown text (or by choice, if others want). Preferably with similar basic fading controls and font changing + advanced show state + padding,size,scale,columns, etc. controls found on dominos bars.

This is just a suggestion - it's alright if you don't think it's necessary :)
Thank you for the wonderful addon

**Comment by Tuller** [comment]
It's something to consider for extras once module toggles are implemented in the UI

**Comment by Goranaws** [comment]
Tuller, if you chooses to add this yourself, my code is yours. Might help give you a head start. I'll post a copy of Auras here on GitHub.

**Comment by Swanarog** [comment]
https://github.com/Swanarog/Auras

Feel free to rewrite everything, as I know my code tends to be messy. Use it as reference, or reuse everything.

 I do plan to post one last update on Curse, just to have a working version available. Should you decide to implement your own version, i will remove mine from curse.

**Comment by Goranaws** [comment]
Or I can transfer ownership of it to you. I think curse allows for that.

**Comment by Swanarog** [comment]
I've done a partial rewrite, to help make it more legible. I had written this 2+ years ago, so it was needed.

I hope this will give a head start, when you are ready. And do let me know if you want me to transfer ownership on Curseforge to you!

**Comment by Goranaws** [comment]
Just want to share how popular this seems to be. I posted an update of Christmas, and it's had 1800 downloads since then.
![Screenshot_20210102-155648](https://user-images.githubusercontent.com/569473/103466448-4eff3e80-4d13-11eb-99db-a9186d863b5f.png)

**Comment by addonaddict** [comment]
If this is something that is well-liked, I wouldnt mind this idea expanded to other minor UI elements such as durability frame, vehicle seat frame, and boss frames. All of these are currently controlled via Move Anything addon on my end.
That addon does a pretty sloppy job of moving frames around as the anchoring positions are pretty buggy, which means if you change your UI scale, or just happen to log on different PC with different screen size, your windows will be all over the place.

I understand if the author wants to keep it to actionbars only, so im just throwing my 2 cents out there. Im sure a hell of a lot of people want to minimize their collection of 100 addons to do the job of 1 :D

Thank you

**Comment by Goranaws** [comment]
I'm actually working on something to cover the random other frames. Won't be dominos based, but will offer similar functionality when it's done. 

Core: https://github.com/Swanarog/sandCastle

Sample addon using it: https://github.com/Swanarog/sandQuest

**Comment by addonaddict** [comment]
is thit still being considered?
havent seen any updates whatsoever for nearly a month now

**Comment by Tuller** [comment]
Its still on my list to do.

**Comment by Goranaws** [comment]
Have you had a chance to look into this? I had done everything I could to make the code as "Tuller" as possible. It may not need many changes before you would be willing to release your own version. 

https://github.com/Swanarog/Auras

**Comment by Tuller** [comment]
No, not yet

**Comment by Tuller** [comment]
I've now actually looked at it :)

Will need to live with it for a bit.  A short todo

- [ ]  All user facing strings need to be moved to localization file
- [ ]  CPU usage is rather high - Would want to check how many things we can push to update on event instead of using an OnUpdate handler and refreshing every frame. At the very least have the parent container in charge of OnUpdates.
- [ ]  Maybe look at Cooldown:SetHideCountdownNumbers(false) for cooldown text.
- [ ]  I really need to implement the enable/disable modules UI
- [ ]  I really need to implement default layouts.

**Comment by Goranaws** [comment]
I will see what I can do about the first three to do's.

**Comment by Goranaws** [comment]
You cannot use the built-in cooldown text, if you want to allow the text to be moved. There is no means by which I can see to access the built-in cooldown text for that purpose. In order to meet the requests above, I had to recreate the cooldown text so that it could be moved.

**Comment by Tuller** [comment]
The code is now in the core repo

**Comment by Goranaws** [comment]
Since you are rolling it into the core, should I take down my page on curse? Or wait till you tell me it's time?

**Comment by Tuller** [comment]
It’ll probably be in a beta form for a bit. After that you. An archive the project on curse if you want

**Comment by Goranaws** [comment]
Ok. I'm honestly quite excited to see what you will do with it. :-)
