### ISSUE TITLE
Advanced Show States menu

### ISSUE THREAD

**Issue by Swanarog** [tullamods/Dominos#528]
Took me a bit, but I've managed to get this working. Feel free to edit: https://github.com/Swanarog/Dominos

Based on the paging options, I've created a Show States panel, separate from the Advanced Panel. You get two dropdowns, one to select to the show state condition, one for the display state. There is also an edit box to see the changes. Once both dropdowns are set, it updates the edit box accordingly. This should be a much easier way for beginners to get stated with show states. You can still manually type/edit show states.

**Comment by Tuller** [comment]
I don't think this one is quite what I'm looking for. I'm mucking about with some different things
![image](https://user-images.githubusercontent.com/191239/111920187-09295b00-8a64-11eb-8992-12090cd8574b.png)
