### ISSUE TITLE
Talking head is moveable, but is still anchored to other windows

### ISSUE THREAD

**Issue by addonaddict** [tullamods/Dominos#530]
When moving talking head to top of screen, you notice after doing world quests that the rewards preview is hidden as it is anchored to the talking head
This severely limits the areas you can place it
Not sure how to fix - perhaps not having them anchored and allow moving both separately

top of the image below is actual top of screen:
![image](https://user-images.githubusercontent.com/73442541/103161983-1d88ef00-47b8-11eb-9362-eca69f650a80.png)

thank you

**Comment by Tuller** [comment]
I've added in a hack to reposition the talking head and group loot frames whenever the AlertFrame calls UpdateAnchors. This should hopefully resolve this one.

(PS, I really dislike the AlertFrame stuff in Blizzard's code)
