### ISSUE TITLE
Show Macro Text

### ISSUE THREAD

**Issue by R0bd4wg** [tullamods/Dominos#531]
![WoWScrnShot_123120_135826](https://user-images.githubusercontent.com/50415605/103430934-c7cc9200-4b7d-11eb-931a-3677907491fa.jpg)
Show macro text has to be clicked off every restart for macro text to go away.

**Comment by h3LLgun** [comment]
Same problem for me. Show binding text as well.

**Comment by Tuller** [comment]
What theme are you using in Masque?

**Comment by R0bd4wg** [comment]
> What theme are you using for your action buttons?

Lorti UI

**Comment by Tuller** [comment]
Check that addon's config settings for showing/hiding macro and binding text.
