### ISSUE TITLE
Nudge frames with keyboard not working since 9.0.21-retail

### ISSUE THREAD

**Issue by catthou** [tullamods/Dominos#532]
**Addon Version**
9.0.21-retail

I can't nudge frames anymore since this update! The arrow keys still seem to just go through to my default ui - in this case, paging my primary action bar. Nudging was very useful for putting two frames next to each other. You could dock them, then nudge it one away and one closer to have them next to each other while keeping "share opacity states" enabled for other bars.

I tested this with only dominos and dominos_config enabled.

**Comment by Tuller** [comment]
Have you unbound your movement keys by chance? The one change I made was to use those for moving bars around.

**Comment by catthou** [comment]
Those work. I had no idea anything was changed, so I never thought to use my character movement keys. I've never really associated them with UI actions before.
