### ISSUE TITLE
Rogue shadowdance bar shows while in soulshape form (fae covenant)

### ISSUE THREAD

**Issue by wutra4444** [tullamods/Dominos#536]
When I cast soul shape my bar is recognizing shadowdance mode. 

https://prnt.sc/wm83j0

https://prnt.sc/wm84u0

https://prnt.sc/wm8589

https://prnt.sc/wm85ci

**Addon Version**
9.0.21

**World of Warcraft Version**
Shadowlands latest version

**Comment by Tuller** [comment]
Can you create a macro with [bonusbar:1,form:2] to test?

**Comment by wutra4444** [comment]
Hello, sorry I am not so experienced with macros, could you give me a full example of how it should look? Also is it possible for you to help me remotely if needed.

**Comment by wutra4444** [comment]
Now, for some reason, when shadow dance action bar is disabled, soulshape doesn't affect the main bar, also if I cast shadow dance it changes to stealth bar even if it's disabled...funny but it works xD

**Comment by Tuller** [comment]
I think that's about the best we can do for now
