### ISSUE TITLE
Castbar does not appear when using the Blizzard Override for vehicles with casted abilities

### ISSUE THREAD

**Issue by HaraiUlfsark** [tullamods/Dominos#537]
Hello

When using the blizzard override UI for vehicles and such the cast bar disappears, so you can not see the cast bar for vehicles with casted abilities like the nightsong ardenmoth from "A dangerous harvest" ardenweald world quest, when unchecking the blizzard override bar it appears again, as well as the other bars behind the vehicle frame. I know that for most bars and frames affected by dominos we have the option to allow them with the blizzard override, but specifically the cast bar frame is missing that option

Thank you for your time

**Comment by Tuller** [comment]
This should be resolved in the latest release (I had the cast bar auto hidden in the override UI)
