### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Altoholic** [tullamods/Dominos#539]
**Addon Version**
9.0.21-classic

**World of Warcraft Version**
Classic

1x Dominos\bars\actionButtonMixin.lua:45: bad argument #1 to 'bnot' (number expected, got nil)
[C]: in function `bnot'
Dominos\bars\actionButtonMixin.lua:45: in function `func'
Dominos\core\buttonBar.lua:257: in function `ForButtons'
Dominos\bars\actionBar.lua:232: in function <Dominos\bars\actionBar.lua:227>
(tail call): ?
Dominos\bars\actionBarModule.lua:76: in function `ForAll'
Dominos\bars\actionBarModule.lua:48: in function `?'
...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...ceBagSync\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...ceBagSync\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `PickupPetAction'
FrameXML\PetActionBarFrame.lua:381: in function `PetActionButton_OnReceiveDrag'
[string "*:OnReceiveDrag"]:1: in function <[string "*:OnReceiveDrag"]:1>

**Comment by Tuller** [comment]
This should be resolved in the latest release.

**Comment by Altoholic** [comment]
It is.
TY!
