### ISSUE TITLE
Can I change Dominos' frame to background?

### ISSUE THREAD

**Issue by 2HyeokJun** [tullamods/Dominos#543]
hi, i love dominos so i place it to my centerbar...
but it's frame priority is so high and i can't click my keystone's start button
can i change dominos' frame to background?
thank you for your support.
![dominos](https://user-images.githubusercontent.com/46053007/108613401-028fcf80-7435-11eb-975b-e91a697b92ee.png)

**Comment by Tuller** [comment]
There's nothing in the addon for this at the moment, but its on the list.

Its a bit annoying, because this is more a bug with Blizzard's stuff in that those menus should be on a higher strata :)

**Comment by 2HyeokJun** [comment]
thank you for your support :)

**Comment by 2HyeokJun** [comment]
so thank you:) it's great function!
