### ISSUE TITLE
Grid gaps on multi-monitor setup

### ISSUE THREAD

**Issue by MuTLY** [tullamods/Dominos#544]
The grid shows gaps between lines, as demonstrated on the image:

![image](https://user-images.githubusercontent.com/777006/108885335-70c7c400-75e6-11eb-8f28-af5575082421.png)

These gaps can vary, depending on the "steps" on the addon control slider. Unless that's intended?

**Addon Version**
9.0.23-Retail

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
Its not intentional, but is kindof a weird artifact of how the wow ui draws single pixel lines at various screen resolution + UI scale settings.

**Comment by Tuller** [comment]
This should be fixed in the latest version. I'm using a two pixel line with as @Goranaws was earlier, as well as some PixelUtil stuff that Blizzard has built into the retail client (that will eventually make it into the classic clients)
