### ISSUE TITLE
Hotkey Color Problem

### ISSUE THREAD

**Issue by nukuge** [tullamods/Dominos#545]
**Addon Version**
9.0.23 (Not even before)

**World of Warcraft Version**
Classic

![dominos](https://user-images.githubusercontent.com/79773942/109404740-4e4df600-79ac-11eb-9169-abd0b07ebb1f.png)

i am using a hotkey custumization addon, that is CleanHotkey
pet bar, stance bar are applied, but action bar is not applied.
Font applied Color not applied.

**Comment by Tuller** [comment]
This is to be expected, as the standard UI uses hot keys to indicate range.

**Comment by nukuge** [comment]
i see. thank you
