### ISSUE TITLE
Invalid Target With Prismatic Crystal

### ISSUE THREAD

**Issue by AdmiralWombat** [tullamods/Dominos#547]
Using the https://www.wowhead.com/object=330194/prismatic-crystal, I get an "Invalid Target" when trying to use on any critter in Nazjatar. Disabling Dominos fixed it. Having _only_ Dominos for an addon also caused the bug.

Version 9.0.24-Retail

**Comment by Tuller** [comment]
How are you activating the button? A hotkey or mouse click?

**Comment by AdmiralWombat** [comment]
Mouse click

**Comment by Tuller** [comment]
Are you right clicking with a self cast key set in /dominos?

**Comment by AdmiralWombat** [comment]
No, I'm not.

**Comment by Tuller** [comment]
I’m at a loss for this one. Are you using just dominos + dominos_config? You may also want to see I’d something like Bartender exhibits a similar issue
