### ISSUE TITLE
Additional button layouts

### ISSUE THREAD

**Issue by Goranaws** [tullamods/Dominos#549]
I've written some concept code that would allow buttons to be rotated around a frame's center and/or be displayed on an angle and/or an arc. Initial button positions would still based on rows and columns, but with additional options...

screenshots: https://imgur.com/a/NP5AtFb
code: https://github.com/Goranaws/Dominos

**Comment by Tuller** [comment]
This is neat, but I also don’t think it would work well with sticky bars etc.

**Comment by Goranaws** [comment]
I wrote this mostly mostly out of curiosity. No issue if you don't want to include it, but if I could make the frame resize with the rotation and arc, would you want to include it?

**Comment by Tuller** [comment]
I don't think I'll include it for now.
