### ISSUE TITLE
Talking Heads is always in the bottom left of the screen and can not be moved

### ISSUE THREAD

**Issue by mrCorbyn** [tullamods/Dominos#550]
This issue appears sporadically (not always a talking head on the screen) but often it is moved to the bottom left of the screen since the 9.0.5 update

**Addon Version**
9.0.24 Retail

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
Are you using anything like MoveAnything?

**Comment by mrCorbyn** [comment]
No

**Comment by BigBont** [comment]
After 9.0.5 I got the same problem.
Not use MoveAnything.
The day before 9 0 5 it worked fine.

**Comment by Tuller** [comment]
Thus might work a bit better now. I do normal testing with the void elf intro quest

**Comment by BigBont** [comment]
9.0.25  still broken   =(((

https://snipboard.io/4UhVp6.jpg

https://snipboard.io/7rS1Ev.jpg

https://snipboard.io/gZBHPz.jpg

https://snipboard.io/ntI7jH.jpg

**Comment by Tuller** [comment]
Can you use /framestack and take a screenshot of that?

**Comment by BigBont** [comment]
Ofcourse! But Iam not sure what it is? Its chat command?

**Comment by Tuller** [comment]
Yes that's a chat command

**Comment by BigBont** [comment]
https://snipboard.io/tvNzKB.jpg

https://snipboard.io/IGhmVu.jpg

https://snipboard.io/CdevYW.jpg

https://snipboard.io/2yCI8S.jpg

**Comment by BigBont** [comment]
https://snipboard.io/TIaGuN.jpg

**Comment by Tuller** [comment]
One more thing to try `/dump TalkingHeadFrame:GetPoint()`

That'll display a bunch of stuff in your chat log, like this
![image](https://user-images.githubusercontent.com/191239/111227198-95490780-85b8-11eb-96d8-808043aef088.png)

**Comment by BigBont** [comment]
https://snipboard.io/tljMsT.jpg

https://snipboard.io/8UvkH0.jpg

And When I try move it with my mouse, its stuck and I cant:

https://snipboard.io/9MqETf.jpg

https://snipboard.io/09cNsK.jpg

**Comment by barmelinda** [comment]
There seems to be some incompatibility with the bigwigs addon, when I turn it off the problem ends.

**Comment by BigBont** [comment]
BigWigs
v. 216
Plugins/BossBlock: Add the ability to block the "Talking Head" frame, which is mainly targetted at mythic+ but can be expanded to where it's required.

And then they start working with it. Maybe the problem is here.

**Comment by Tuller** [comment]
That's more than likely it.

**Comment by Tuller** [comment]
Yep, confirmed its BigWigs as the culprit. It appears to take over the frame, even outside of raids.

**Comment by BigBont** [comment]
Cool! Our investigation is done! ^_^
Can you fix it? or BigWigs have to do it?

**Comment by Tuller** [comment]
More for BigWigs to fix than anything I think. At the very least, if something sets `TalkingHeadFrame.ignoreFramePositionManager = true` then BigWigs shouldn't mess with it.

**Comment by BigBont** [comment]
Can I disabel this BigWigs funcion somehow? Delete some file or change it in the BigWigs folder?

**Comment by Tuller** [comment]
I don’t see anything in the options for bigwigs to do it.

**Comment by BigBont** [comment]
Are you going to discuss this with the BigWigs creator? Or should I create a Bug report for BigWigs?

**Comment by Tuller** [comment]
I’d request creating a bug report for them

**Comment by Justw8** [comment]
I dont think we do anything special, all that's being done is registred an event then then do something when that happens:
https://github.com/BigWigsMods/BigWigs/blob/master/Plugins/BossBlock.lua#L363-L411

Are you only checking ADDON_LOADED and not checking if the Addon is already loaded? I dont see you checking if the addon is already loaded.
It's an OptionalDeps for us, so it's loaded as we load BigWigs. Your codde wouldn't trigger as you will never recieve the 'ADDON_LOADED' event and trigger this.
https://github.com/tullamods/Dominos/blob/ffaf8e0efc8bcdfcbc96b6f467aa9d26c366b872/Dominos_Encounter/talkingHeadBar.lua#L108-L114

glhf

**Comment by Tuller** [comment]
Yeah that looks to be the issue. I never thought to think about OptionalDeps loading the module ahead of time
