### ISSUE TITLE
Action buttons some time dont press

### ISSUE THREAD

**Issue by neowest1990** [tullamods/Dominos#554]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
9.0.25

**World of Warcraft Version**
Retail

Very often, buttons on panels located just below the center of the screen stop clicking with the mouse. Even hovering is not highlighted as if there is a hidden element on top of them. The same is in the other modification of the bartender4. How to fix it already tired. It seems that this is something from the standard interface of the game because disabling other modifications does not fix

**Comment by Goranaws** [comment]
Next time this happens, type /framestack into chat. This will make a tooltip appear that will tell you the names of anything under the mouse cursor. Move your mouse over the area you can't click, and take a screenshot of what the tooltip says, then post that here.

**Comment by Goranaws** [comment]
I have encountered this bug myself, recently. maybe an eighth down from center of the screen, is where it tends to happen for me. Usually when I am trying to use my mouse to turn my view.
