### ISSUE TITLE
Target frames

### ISSUE THREAD

**Issue by Zaralissa** [tullamods/Dominos#555]
Since the last update my UI has been painful to use.  When I click on a target now I get target, target of target, target of target's target, a focus target and since I'm a hunter I get pet target, target of pet's target, etc.  I end up with something like 6 target windows across my screen with buff bars everywhere.  The target's cast bars are impossible to read which makes effective interrupts extremely difficult.  It's virtually impossible to raid or do mythics.  I also cannot right click my profile to trade, leave group, change instance from heroic to mythic.  When I right click, nothing happens.  When I disable Dominos it works fine.  I love the addon, it used to do everything I wanted.  Now I can't function.

**Comment by Tuller** [comment]
Dominos doesn’t provide unit frames, so not me :)

**Comment by Goranaws** [comment]
This is an issue with Dominos_Units. Not supported by Tuller, the Author of Dominos. Please visit: https://github.com/Goranaws/Dominos_Units

**Comment by Goranaws** [comment]
This is an issue with Dominos_Units. Not supported by Tuller, the Author of Dominos. Please visit: https://github.com/Goranaws/Dominos_Units
