### ISSUE TITLE
Pet Action Bar still shows glow with opacity set to zero

### ISSUE THREAD

**Issue by raethkcj** [tullamods/Dominos#557]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.**
The clip I recorded shows other addons running, but I was still able to reproduce this with only Dominos and Dominos_Config.

**Addon Version**
9.0.25-Classic

**World of Warcraft Version**
Classic

https://www.youtube.com/watch?v=uBmCKH-4kqc

Abilities on the Pet Action Bar show a faint blue glow when they come off cooldown. It's not very noticeable with action bars at full opacity. However, when I set a bar to zero opacity, the glow still shows up with its regular opacity. I'd expect this glow to inherit the opacity of the Action Bar.

**Comment by raethkcj** [comment]
Sorry I see this is probably a duplicate of #484

**Comment by Tuller** [comment]
Yeah it’s the shine texture for cooldowns. When at 0% opacity, I need to hide cooldowns and show them otherwise. This is because the shine animation doesn’t inherit opacity levels

**Comment by BigBont** [comment]
Can we disable the shine animation btw?
