### ISSUE TITLE
Progress Bar Text is behind the progress bar(s)

### ISSUE THREAD

**Issue by focalpointld** [tullamods/Dominos#558]
**Addon Version**
Dominos 9.0.26-Classic

**World of Warcraft Version**
Classic 1.13.6 b37497

Progress Bar Text is framed behind the colored bar and its segments itself. I have not been able to produce the Progress Bar Text on top of the colored segments. The only way I have been able to view the text is by turning down the Opacity of the progress bar colors.
I have disabled all other addons, and have adjusted Frame Strata and Frame Level of the progress bar with no change.
This problem exists with Segmented or Unsegmented. Changing the overall opacity of the bar does not help either. 

Is there a fix for this?

**Comment by Vikirnoff** [comment]
I'm having the same issue as well but in Dominos 9.0.26 in WoW Version Shadowlands. I have included a screenshot as well.  Thanks! 

![WoWScrnShot_032321_050736](https://user-images.githubusercontent.com/11279387/112121557-c23b8280-8b95-11eb-9d15-8addd63c4eef.jpg)

**Comment by Sneedle** [comment]
Same problem here :) WoW Retail (9.0.5) & Dominos (9.0.26)
![Wow_DLeGUojKms](https://user-images.githubusercontent.com/2368600/112149619-77465d00-8bdf-11eb-9d0e-aacaa82097e0.png)

**Comment by Tuller** [comment]
Yeah I likely broke it with the new frame strata and level sliders
