### ISSUE TITLE
Force bar drawing in PVP only

### ISSUE THREAD

**Issue by hkud3** [tullamods/Dominos#559]
Is there functionality already in the mod that shows a bar only when in PVP/War Mode/Battleground/Arena and otherwise hides it? Or changes from one bar to another (i.e., similar to the Stealth only state)? I did some Google searches, checked the UI and config, but didn't find it.

Sorry if this is something obvious with the States form. I didn't find documentation for this feature.

**Comment by Tuller** [comment]
There's nothing that I can see for a macro for this (see https://wowpedia.fandom.com/wiki/Macro_conditionals). So your best bet is probably to use a different profile for PVP.
