### ISSUE TITLE
A way to disable Dominos taking over the talking head frame

### ISSUE THREAD

**Issue by Diagonet** [tullamods/Dominos#560]
Is your feature request related to a problem? Please describe.
I love dominos for the action bars but I would really prefer to have other addons take over the talking head. Trying to use other addons to move that frame is blocked by dominos.

Describe the solution you'd like
Just having the option to have another addon take over the talking head.

Describe alternatives you've considered
Only alternative here seems to be to stop using dominos? I would rather not though, really like it.

**Comment by Tuller** [comment]
Two options at the moment:
1. Disable Dominos Extras in the addons menu
2. /run Dominos.db.profile.modules.TalkingHeadBar = false; ReloadUI()

**Comment by Diagonet** [comment]
Oh that's perfect, thanks!
