### ISSUE TITLE
Paging preferences don’t load from profile

### ISSUE THREAD

**Issue by LwsBtlr** [tullamods/Dominos#562]
**Addon Version**
9/0/27-Retail

**World of Warcraft Version**
Retail

I have a setup on a character that swaps the bar based on pressing control, option, or command. When I load that profile on another toon, the swap settings do not load in the new profile.

Specifically: action bar 4 is my “main” bar, shown as 3x4 to match my numpad. if I press alt, dominos swaps to bar 3, if I press control, it swaps to bar 5, if I press CMD, it switches to Bar 1.

Works great, but not when I load the profile on another character, I have to specifically set the paging preferences for each toon.

**Comment by Tuller** [comment]
Paging is actually class specific within a profile right now
