### ISSUE TITLE
Group bars

### ISSUE THREAD

**Issue by blaadje** [tullamods/Dominos#563]
Hey! Thanks for your very nice addon!

I'm frustrated when I group bars by context and have to move these bars one by one.

=> It could be nice to have option to group bars together so we could change both positions, sizes etc. from 1 option ?

_(I'm on classic wow)_

**Comment by blaadje** [comment]
Well it seems to be possible to move groups by pulling the bar above 🤔

**Comment by jason-greer** [comment]
You can also hold shift while scaling to adjust scale at the same time. The linked bars inherit opacity option in the main menu is there too

**Comment by Tuller** [comment]
You can use the linked bars inherit opacity option, and hold shift to scale docked bars at the same time from the parent one

**Comment by blaadje** [comment]
Alright this is awesome, thank you guys!
