### ISSUE TITLE
I can't put spells in action bars 5-10

### ISSUE THREAD

**Issue by mikeith** [tullamods/Dominos#565]
Dominos is the only addon I have.  
I'm hoping this is a user error, and is just me.  I can't put spells in action bars 5-10.  I was adding spells in 1-4 just fine, but the other action bars don't even show the spell block.  It's just clear.  I can't find any setting that would differentiate 1-4 from 5-10.  Is there one, or am I doing something wrong?  Please help me enable action bars 5-10.

9.0.28-retail

Retail version of WoW, just bought Shadowlands.

**Comment by Tuller** [comment]
Two things to check:
1. Do you have lua errors enabled? You may need to install BugSack + BugGrabber
2. Can you try with just Dominos + Dominos_Config loaded?

**Comment by mikeith** [comment]
I have no idea how to answer your questions, so i looked it up and i found:

/console scriptErrors 1

to enable Lua errors.  However, it didn't do anything.

I loaded up Dominos from Curseforge.  I don't see anything that would
let me load Dominos with _Config, just says Dominos.

Let me know how to do that, and I'll try it.

Dominos is all I have loaded atm.

Thank you very much

**Comment by Tuller** [comment]
Check the addons menu (Escape when in game, then addons).

**Comment by mikeith** [comment]
Jason,
I have a new pc, and just found an issue with it, and so I must work on
that first.  I'll get back to you when I can, thank you.
