### ISSUE TITLE
Reputation Bar creating UI artifacts

### ISSUE THREAD

**Issue by boktai1000** [tullamods/Dominos#569]
**Addon Version**
9.0.28-beta2-BCC

**World of Warcraft Version**
Burning Crusade Classic

When I was tracking nothing, and went to track a reputation in BC Classic, I got this odd line showing up. I am using Masque with Dominos, so I'm not entirely clear how the two may be interacting to create this.

Edit: I tried it without Masque just to verify, and it still happens. This shows up if I unselect a reputation, and then reselect it to watch as an XP bar.

To Reproduce: Set a reputation to watch as your experience bar

To Temporarily Resolve: do a /reload UI and the artifact/graphical elemental protruding on your screen will go away

See below

![image](https://user-images.githubusercontent.com/9054563/121546506-f40ff880-c9d0-11eb-9288-07ab46e2a390.png)

![image](https://user-images.githubusercontent.com/9054563/121546437-e6f30980-c9d0-11eb-9b36-7f543ec624ba.png)

![image](https://user-images.githubusercontent.com/9054563/121546472-eeb2ae00-c9d0-11eb-8ef0-4c19574d949f.png)

**Comment by Tuller** [comment]
Have you tried with just Dominos enabled (and no other addons)?

**Comment by boktai1000** [comment]
Yes, I just tried with all addons Disabled except for the Dominos addons to confirm. Please see below

![image](https://user-images.githubusercontent.com/9054563/121566714-65f13d80-c9e3-11eb-85d3-2200f1328146.png)

**Comment by Tuller** [comment]
I still haven't reproduced this one, unfortunately.

**Comment by boktai1000** [comment]
I did some testing on this again today, the only addon I had enabled from a clean startup was Dominos and I still had the issue occur. I unfortunately didn't see anything in my taint.log file - as well as no Lua errors (there never were though). Here's another screenshot, clean UI and no mods at all.

Reproducing this again for me is simply spamming the "Show as Experience Bar" option, like click/cycle through it multiple times (I do this like 3 times and it happens, but I can spam it after that and reproduce it every time I click it on and off again)

![image](https://user-images.githubusercontent.com/9054563/122263391-fd4f0880-ce9b-11eb-8576-449bfe56ec3f.png)

**Comment by boktai1000** [comment]
I do have another toon that I test this on and I cannot reproduce it for what it's worth. The toon is not Level 70 though, and has an XP bar. I even copied the profile from my Toon that is experiencing this (70 Warrior) to my Level 61 Mage by doing the Copy Profile, and that's really one of the only things related to said bar that I can think of. Maybe this helps, I dunno when that toon will hit 70 but if he hits it and the bug becomes present on it, I'll be sure to follow up if it's still on-going (that may be weeks or months from now though unfortunately!)

**Comment by boktai1000** [comment]
I also wanted to record some of my associated Dominos settings in-case they can help reproduce the issue and document what I have

**Comment by boktai1000** [comment]
Believe it or not, I was actually able to reproduce this on Classic Era. Pardon the UI.. but for the sake of the test, I just had my regular Classic Era addons running and a completely fresh Dominos install (I deleted all saved options in the WTF folder)

![image](https://user-images.githubusercontent.com/9054563/122281995-85d7a400-ceb0-11eb-96f7-1a8c58fc0288.png)

**Comment by Tuller** [comment]
Never reproduced, but guessed correctly that it is the MainMenuBarMaxLevelBar. This is now hidden in 9.0.29

**Comment by boktai1000** [comment]
I can confirm that this is now fixed in 9.0.29 - thanks!
