### ISSUE TITLE
Warrior bar swapping doesn't work in TBC

### ISSUE THREAD

**Issue by lukemundy** [tullamods/Dominos#570]
Have loaded just dominos and dominos config. As a warrior, switching stance doesn't change the active action bar to the bar for that stance.

From what I understand, action bar 7 is the "main" bar or the bar for battle stance and action bar 8 is for defensive stance (i assume 9 is for zerker stance but i haven't unlocked that yet). I expected either action bar 1 or 7 to change to 8 when i move to defensive stance but that doesn't occur. all bars (all 10, i enabled them all to check) remain the same. Screenshots below:

![image](https://user-images.githubusercontent.com/346520/122041335-6c305100-ce0b-11eb-8201-41f537ce125e.png)

here's my config
![image](https://user-images.githubusercontent.com/346520/122041376-79e5d680-ce0b-11eb-99de-12857c56558d.png)

If it helps, i'd be happy to submit a PR for this myself if you can point me in the right direction.

**Addon Version**: 9.0.28-BCC

**World of Warcraft Version**: Burning Crusade Classic

**Comment by Tuller** [comment]
Check the paging settings you have for Bar 1 in its right click menu.

**Comment by lukemundy** [comment]
ahh, they were all disabled... my bad man, once I set those to the relevant bars everything is working fan.

thanks for your time
