### ISSUE TITLE
Vertical "Menu" Bar - Button Press Graphic Issue

### ISSUE THREAD

**Issue by boktai1000** [tullamods/Dominos#571]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
9.0.28-beta2-BCC

**World of Warcraft Version**
Burning Crusade Classic

To Reproduce - Configure your Menu Settings > Layout to "1" Column so that it is completely vertical. Pressing the Buttons or using Keybinds to open them, you will notice a small graphical issue when doing so. It goes away once the pressing sequence is completed, so I can't really record or post a screenshot unless it was a GIF or Video, so the best I can do is show how my configuration looks as well as my options I have configured. Any more questions just let me know - thanks again for the great addon!

In particular, it seems mostly prevalent with the Quest Log button, and happens when I press every button including the Quest Log button or any of the associated hotkeys.

![image](https://user-images.githubusercontent.com/9054563/122264431-2623cd80-ce9d-11eb-973d-b93cc233131f.png)

![image](https://user-images.githubusercontent.com/9054563/122264548-4784b980-ce9d-11eb-90a0-5dae4c5a206a.png)

**Comment by Tuller** [comment]
I've reduced the refresh time on my end for that. Its a weird artifact of how the Blizzard UI refreshes the talent/quest button ordering whenever you press a button.

**Comment by boktai1000** [comment]
With 9.0.29 it looks a bit better, but now it has introduced what I would consider as "flicker" when clicking the buttons or pressing the keybinds, and the issue is still present - but happens "faster"

**Comment by Tuller** [comment]
For now, I think this is the best I can do.
