### ISSUE TITLE
Extra Action Button not shown during Step Into the Light quest

### ISSUE THREAD

**Issue by Sipollo** [tullamods/Dominos#575]
When doing the campaign quest "Step Into the Light" you are in a vehicle; whilst the vehicle UI is shown correctly, the quest also has an extra action button which Dominos suppresses from being shown.

**Addon Version**
9.1.0-Retail

**World of Warcraft Version**
Retail

**Comment by Swordart25** [comment]
Yup Extra action bar went missing.

**Comment by Tuller** [comment]
Are these two options checked?
![image](https://user-images.githubusercontent.com/191239/158064511-584d24b7-e8d3-4e27-971e-cbc489480863.png)
