### ISSUE TITLE
Stance menu Warrior TBC

### ISSUE THREAD

**Issue by Goldmoon29** [tullamods/Dominos#577]
Hello, When I configure the class bar on 1 column the icons remain on 3 columns.

**Addon Version**
9.1.0-BCC

**World of Warcraft Version**
Classic TBC

![2021-08-19_10h24_00](https://user-images.githubusercontent.com/68126821/130035749-6c6af059-a1dd-4222-890c-5665f8434135.png)

**Comment by Tuller** [comment]
When you see something like this, where Dominos appears a bit disconnected from the bar, its usually related to another addon taking control of that too.
