### ISSUE TITLE
Zone abilities still not showing up

### ISSUE THREAD

**Issue by CodingLeon** [tullamods/Dominos#579]
Zone abilities are still not showing up. Have to disable addon to get it done, and then re-enable to get dominos back..

**Comment by Alexej32** [comment]
Had/have the same issue zone ability not showing up, have to disable Dominos every time i have a quest with extra ability button then enable it when I'm done. Is this gonna get fixed or need to look after a replacement addon :(

**Comment by CodingLeon** [comment]
Still having the issue after installing again last night and having a go with it. Am I doing something wrong in my settings? Or is it a bug?
