### ISSUE TITLE
Problem when you register Hero's way(M+ 20 reward, teleport to enterance of SL dungeons) to dominos slot

### ISSUE THREAD

**Issue by hobulian** [tullamods/Dominos#584]
**I tried to reproduce the issue with just Dominos and Dominos_Config running.
Although screenshot isn't but result was same
https://imgur.com/a/Hq22nVl

when you mouseover registered folderable menu of SL hero's way. It changes alphas of every hidden frames of dominos 

**Addon Version**
9.1.2 I updated today.

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
Mouseover related flyout bug I forgot to close
