### ISSUE TITLE
StanceBar/PetBar wrong object type for function at /Dominos/plugins/buttonThemer.lua:64

### ISSUE THREAD

**Issue by AuwersK** [tullamods/Dominos#585]
I can't adjust pet or stance bars in classic_era

![Screenshot from 2021-09-21 13-22-17](https://user-images.githubusercontent.com/39767592/134162785-199dddae-e1fc-46fd-bec1-5499e2f101f1.png)
![Screenshot from 2021-09-21 13-21-43](https://user-images.githubusercontent.com/39767592/134162716-c853839f-1630-408d-9f82-1f2790f3e271.png)
![Screenshot from 2021-09-21 13-21-54](https://user-images.githubusercontent.com/39767592/134162720-981421db-1068-418c-bbc9-f5c0ca172d8b.png)

**Addon Version**
9.1.2-Classic

**World of Warcraft Version**
Classic Era

**Comment by DKNurs** [comment]
A simple workaround/fix is in the buttomTheme.lua line 63 and 64 edit the Normal.Texture to normal.Texture
