### ISSUE TITLE
Pet Bar is not there!

### ISSUE THREAD

**Issue by jfive87** [tullamods/Dominos#587]
I recently started playing classic era wow coming over form tbc i set up my bar exactly how i had it in TBC however for some reason my pet bar is not there. i have reloaded uninstalled and updated the addon and have no idea why its not showing up. i have recently had to download bartender until this issue is resolved. 
**Addon Version**
9.1.3

**World of Warcraft Version**
Classic

**Comment by jfive87** [comment]
So a brief fix i have had to download an older version 9.0.28 and my pet bar is there. the issue is kinda weird i looked at older streams and my pet bar was there just fine then i updated it and the pet bar dissapeared

**Comment by Tuller** [comment]
I've not reproduced this one.
