### ISSUE TITLE
TBC Priest request: disable automatic stance-swap on Spirit of Redemption

### ISSUE THREAD

**Issue by Zautix** [tullamods/Dominos#589]
If you respec between Shadow and Holy as a Priest in TBC era, Shadowform and Spirit of Redemption (the post-dead healing form) share the same stance flag, resulting in your Spirit of Redemption having your shadow DPS action bar when you die.

Ideally, Dominos would check to see if the Spirit of Redemption talent (or ability) is learned and disable the Shadowform stance option automatically (this is the current manual workaround.) 

While this suggestion may be beyond the scope of what Dominos is intended to provide, it would be very helpful to be able to automatically adjust settings based on learned skills (similar to how WeakAuras uses them as load conditions.) It could be used to replicate an automatic "dual spec"-style action bar swap using paging without any user intervention beyond the initial setup.

**Comment by Tuller** [comment]
Yes, this should be something that I can likely detect and at least give you two paging options (Spirit and Shadow) in the UI.

**Comment by Tuller** [comment]
Late followup, I don't think I can reliably detect this one in combat.
