### ISSUE TITLE
More action bars and specific keybindings on profiles

### ISSUE THREAD

**Issue by Zammuu** [tullamods/Dominos#590]
Hi,

I recently found this issue by playing druid that I run out of action bars because some of the action bars are made to be druids forms bars. I recommend to add feature that will give you chance to add more action bars like others addons do. I have like 3 to 4 action bars which I use for spells and 2 row of stuff I want to be easily available. So in this case I have used around 6 action bar and now I wanted 1 more action bar for other purposes but then I realised that all the others 4 action bars were used on my forms. So if I put there something else than form skills I would be in trouble at using those forms.

I wish to get more action bars or option to add more action bars to avoid this kind of things.

**Comment by Tuller** [comment]
There's a hard limit of 120 action buttons imposed by Blizzard unfortunately.
