### ISSUE TITLE
Main Bar not paging only page 1,2

### ISSUE THREAD

**Issue by 40P3** [tullamods/Dominos#594]
Hi, Updated to latest version 9.1.3 (shadowlands)
Just noticed that paging doesn't work.
I got mouse scroll+Shift up/down for next/previous main page bar cycling.
Dominos set up for standard mainbar, 1-6 paging enabled.
But only page 1,2 repeating constantly. Something is blocking the addon to actually page through all the main bar pages from 1-6.
No extra button/keyboard modification enabled on the bar, nothing. I'm using macros on the main page 1, but other than that, I would use page 2,3,4 for standard buttons/skills/items.
![dominons_mainbar_setup](https://user-images.githubusercontent.com/20872247/146806807-26b42f20-d8c1-452e-9630-ffc0de21be35.jpg)

**Comment by Tuller** [comment]
In the standard blizzard action bars menu, uncheck the extra action bars.

**Comment by 40P3** [comment]
OMG!
That is a weird new feature.
Thanks for helping Tuller I prob. would never have found it alone /facepalm!
THANKS! MERRY CHRISTMAS YOU WOW ADDON GOD! :)
