### ISSUE TITLE
TBC: Possible to Set Paging for "Possess" bar?

### ISSUE THREAD

**Issue by crespire** [tullamods/Dominos#598]
**Problem**
I am having a heck of a time figuring out how to configure my bars for the Teron Gorefiend fight in TBC Classic. Currently, the ghost possess bar ends up paging over my pet bar. As a priest, I don't typically have my pet bar bound, as I control my shadowfiend via macros.

I say "Possess" bar, as I understand this is a specific type of bar.

**Suggestion**
What would be lovely is the ability to set a special page for "Possess" like I can with Shadowform or Spirit of Redemption. Ideally, I would like for my possess to page to Action Bar 1, so I can easily use my main keybinds for the ghost skills.

**Alternatives**
As far as I can tell, there is actually no option for me to redirect or otherwise control how the "Possess bar" pages. I am unsure if this is an API limitation, but having the ability to page any of my main action bars to "Possess" would be sufficient.

**Additional context**
I've been using the Steam Tonk Controller to try to configure my buttons, so I am wondering if that might help with your testing.

For what it is worth, I do have "override bar" in the settings set to Action Bar 1, but not sure if this is the same setting as what I am requesting.

**Comment by Tuller** [comment]
The possess bar changed a bit in implementation over time. 

[bonusbar:5] should be the right macro conditional for it in TBC, but I'll double-check.

**Comment by crespire** [comment]
Thanks. I'm still pretty new to WoW addons in terms of programming side, are you able to provide some information how I might utilize the macro conditional to achieve what I'm looking for? Would that be something you'd have to update on the LUA side as an option in terms of paging?

Thanks for the work you put in on this addon!

**Comment by Tuller** [comment]
Worth trying with 9.2.0. BCC classic now uses some different possess bar logic and should let you swap between the action bars and pet bar.

**Comment by crespire** [comment]
> Worth trying with 9.2.0. BCC classic now uses some different possess bar logic and should let you swap between the action bars and pet bar.

Thank you, I see that the "Override" Bar option now lets me select "Action Bar 1" so I will see how it goes this week. Haven't been put into ghosty form since week 1, so haven't had a chance to test run.

Do you know if there are any other mechanics in TBC that have the same trigger? It seems the Steam Tonk controller does not have the same trigger.

**Comment by Tuller** [comment]
I think most of the mechanics in early TBC will use the pet bar for possess type actions.

**Comment by crespire** [comment]
After some weeks, it seems that I'm stuck using the pet bar for this encounter. Thanks!
