### ISSUE TITLE
Dominos does not go away after pet battle starts in 9.2

### ISSUE THREAD

**Issue by BigFire321** [tullamods/Dominos#599]
Start pet battle.  Dominos bars does not withdraw to show pet battle bar.

**Addon Version**
Dominos 9.2.1

**World of Warcraft Version**
Retail 9.2.0.42423

**Comment by Tuller** [comment]
I've not replicated this one. Can you doublecheck your version using /dom version?

**Comment by Veyska** [comment]
![WoWScrnShot_022322_100238](https://user-images.githubusercontent.com/2243477/155380321-8a0a5f7a-7292-4427-be76-af1b3729c549.jpg)

**Comment by Aideenwolf** [comment]
Veyska beat me to it.. I'm having the same issue - am a warrior too - don't see why that would matter but there you are.

**Comment by Veyska** [comment]
I was seeing the bars on non-warriors too, just double-checked on a shaman since I had one parked in the garrison.

**Comment by BigFire321** [comment]
Please note, version 9.2.0 works.

**Comment by Veyska** [comment]
9.2.2-Retail appears to have fixed whatever was being peculiar in 9.2.1-Retail, huzzah!

**Comment by tflo** [comment]
Just was about to post that Dominos 9.2.2 doesn't change anything for me, as I realized that my toc file still says "9.2.1" while the WoWUp app says "9.2.2" (via Wago).

Are there any packaging issues?

BTW, the manually downloaded 9.2.2 indeed fixes the pet battle issue. Many thanks.

**Comment by Tuller** [comment]
No packing issues I know of.

**Comment by tflo** [comment]
WoWUp has just released an [update](https://github.com/WowUp/WowUp/releases/tag/v2.6.2) saying “Fixed an issue with Wago addons updating incorrectly”. 

Maybe it was that.
