### ISSUE TITLE
WoW 9.2 Blizzard override bar doesn't show on latest Dominos version 9.2.1

### ISSUE THREAD

**Issue by m4xc4v413r4** [tullamods/Dominos#600]
I noticed it right at the very start of the new quests for the new zone, they have us flying on an enemy mount before we go through the portal to the new zone and I couldn't see the abilities for the quest, only saw my own Warrior abilities.

After that, and thinking it was just a one time thing, everything was fine, but just now I went to do a WQ in Ardenweald where we transform into a bear, and again, the abilities bar for the bear didn't show up, I only saw my own Warrior abilities.

I've done that quest before and it worked fine, this only happened with the update I did today before getting in WoW for 9.2.

**Comment by Swordart25** [comment]
Okay so why do i see another bars ? 
![image](https://user-images.githubusercontent.com/98956396/155849343-d44074a0-f398-4757-b838-af014167d768.png)

**Comment by m4xc4v413r4** [comment]
Because you have "Use Blizzard Override Action Bar" turned on, which defeats the point of having an action bar addon.
If you turn it off, the spells should appear on dominos bars instead of a dedicated bar filled with pretty textures around like the one in that picture.

**Comment by Tuller** [comment]
Can you verify you're still getting this with 9.2.2?

**Comment by Swordart25** [comment]
well i did it yesterday and had it with Uther i have blizzard override and on another vehicle for example doing Venthyr Daily quest where you play as Stoneborn "Darkwing Drills" It doe snot showed other bars.

**Comment by m4xc4v413r4** [comment]
> Can you verify you're still getting this with 9.2.2?

Sorry, haven't tested it yet, I turned on the blizzard ones as a temporary fix and haven't been on much since. When i get home I'll test it If I can find a place to do it on like an active world quest that uses it, and I'll let you know.

**Comment by m4xc4v413r4** [comment]
> Can you verify you're still getting this with 9.2.2?

ok, I managed to find a WQ that uses the temporary bar and it is working well on 9.2.2.
I'm trying to find another or something else that uses it to confirm but seems like it is fixed.

**Comment by Swordart25** [comment]
niceeeeee  had no issue only happened with uther quest.
