### ISSUE TITLE
Strange button placement when you have two "extra" buttons

### ISSUE THREAD

**Issue by Hofflerand2** [tullamods/Dominos#601]
Hi, this is not a big deal, just a small suggestion. Occasionally we are given two separate abilities that go to the Extra Bar. Here's where my bar is positioned when I have _one_ extra button:

![WoWScrnShot_031322_083648](https://user-images.githubusercontent.com/30275556/158059729-c50c69fa-36c6-4dc7-b35f-f5239ed9e969.jpg)

And this is what happens when I get a second extra button:

![WoWScrnShot_030822_134422](https://user-images.githubusercontent.com/30275556/158059764-e75ca5f1-9920-4a49-b3a5-59ce090a1d73.jpg)

I was wondering if Dominos could place these buttons side by side instead of spreading them out in such a weird fashion. But perhaps this is how the default UI does it too - I wouldn't know, as I have been using Dominos for so long.

Thanks for reading my suggestion.

**Comment by Tuller** [comment]
Dominos makes the container that those buttons are a part of movable, but doesn't actually make the buttons themselves movable (this is a workaround to prevent issues in combat). So it is most likely how the default UI handles it.
