### ISSUE TITLE
Zereth Mortis: "Cosmic Energy" bar is positioned very strangely

### ISSUE THREAD

**Issue by Hofflerand2** [tullamods/Dominos#602]
Hello. This is another rather small issue that I am experiencing. In the new zone, Zereth Mortis, there is this odd bar that you cannot move with Dominos. It positions itself in the strangest places.

Example 1:

![WoWScrnShot_030822_143230](https://user-images.githubusercontent.com/30275556/158060014-ad9f049b-017a-41d2-856b-5be37e74ce15.jpg)

Example 2:

![WoWScrnShot_031122_030429](https://user-images.githubusercontent.com/30275556/158060019-99cb0e99-89b8-4d10-a65e-60e7b514f7ba.jpg)

It would be great if we could move or hide this bar. If not, it's really not a big deal. Thanks.

**Comment by Tuller** [comment]
Try running /fstack and then hovering over the bar to see what name it has.

**Comment by Hofflerand2** [comment]
![WoWScrnShot_031422_123117](https://user-images.githubusercontent.com/30275556/158218196-edc70612-9160-4b43-a670-aa70112a2c84.jpg)

![WoWScrnShot_031422_123122](https://user-images.githubusercontent.com/30275556/158218206-06a0fe46-c635-420a-9470-cf0e093d6830.jpg)

**Comment by tflo** [comment]
Same issue here. It's overlapping exactly with my Dominos main action bars.

Provisionally, I could make it moveable via [BlizzMove](https://www.wowinterface.com/downloads/info23875-BlizzMove.html#info) > Default disabled frames > Blizzard_UIWidgets

![WoWScrnShot_031622_152408](https://user-images.githubusercontent.com/1410282/158613658-78f79029-a3e4-4d98-b411-929aad2f65f0.jpg)

**Comment by Tuller** [comment]
I'll investigate this a bit more, but I'm leaning towards wanting to send people over to something like BlizMove to handle that specific UI element.

**Comment by tflo** [comment]
FYI:

Just found out that [Leatrix Plus](https://www.leatrix.com/plus) now has an option to permanently move (and resize) this widget:

![WoWScrnShot_051822_123728-pty](https://user-images.githubusercontent.com/1410282/169022324-78c71e9a-bcf3-4862-a641-2bbbf844b9f6.png)

Unlike BilzzMove, this doesn’t throw errors.

**Comment by Hofflerand2** [comment]
Thanks! I use LTP so this fix will work great for me.
