### ISSUE TITLE
Some bars are resetting their positions.

### ISSUE THREAD

**Issue by BigBont** [tullamods/Dominos#603]
When trying to move bars and bags with arrows, they reset their position and cannot be moved with arrows. This happens when bars or bags are on the right side of the screen.

**Comment by Tuller** [comment]
Have you noticed this with other addons disabled?

**Comment by BigBont** [comment]
No, but I don't use many addons. ShadowedIF, HandyNotes, BigWigs, Skada and its all.

**Comment by BigBont** [comment]
It's  Action Bar 4  problem

**Comment by BigBont** [comment]
Retail 9.2
