### ISSUE TITLE
Rework/addition of exp bar that matches blizz UI

### ISSUE THREAD

**Issue by addonaddict** [tullamods/Dominos#604]
Hello,

I've tried Dominos so many times over the years, and I love it for everything except 1 thing (which is big enough for me to delete the addon)
The exp bar does not match the blizz UI and is very clunky to use / move around / scale / snap to things / etc
Is there any possibility you could add a literal copy/paste of the blizzard exp bar as an option?
It would be the smaller exp bar (not the wider one) without any side art work
The only options you would need for this bar is to move it around, snap, and scale. Nothing else is needed

Bartender is another alternative I tried that does this, but for whatever reason they just take the lazy way out by grabbing the long exp bar and scaling it so it's literally unusable on big resolutions. (even 1080p....)

Hope you consider this... thank you

Example of exp bar:
![image](https://user-images.githubusercontent.com/73442541/159290935-a94086a9-e998-4de4-a35a-d42d8e9e0ab1.png)

**Comment by Tuller** [comment]
The current implementation is mostly my best effort at trying to replicate the Blizzard bar, while avoiding the scaling issues you noted. There's a bit more work on the border that I could do to make it closer in appearance.

**Comment by addonaddict** [comment]
If you could make it match blizzard UI a bit more I would LOVE that! The outside border of exp and rep bars in the screenshot would look nice on the dominos exp bar imo. Or something similar.
In terms of function - my only gripe right now is the snapping issues.
I try to center my exp bar at bottom center of my screen, then snap rest bars on top. (Matching the blizz UI i screenshotted above)
For some reason, as of recent updates, snapping is very hard to do. Almost as if too much precision is required. This was not the case about 1 or 2 years back.
With all other frames, I tend to spend a lot of time trying to center things on the screen. For some reason they just refuse to snap unless i'm literally within the 1-3 pixel range.

Hope this makes sense
Thanks for your work!!!

**Comment by Tuller** [comment]
The grid is probably the reason for snapping being a bit weirder.

**Comment by addonaddict** [comment]
Hi, its been about 4 months since i commented about this but just wanted to let you know that i ended up deleting the addon all together out of sheer frustrations with more recent changes (last year or two). The snapping is not functional, i wouldnt call it just weird. I gave up trying. Just my 2 cents. It may work for your layout, but it needs to be reworked before i reconsider.
