### ISSUE TITLE
Mouse over flyout button causes every faded out buttons to fade in

### ISSUE THREAD

**Issue by hobulian** [tullamods/Dominos#606]
When mouse over flyout button(Warlock's summon pet or M+ dungeon portal) causes this.
I've waited from the beginning of SL but this wouldn't fixed till now.

**Addon Version**
9.2.2

**World of Warcraft Version**
Retail

**Comment by hobulian** [comment]
https://imgur.com/a/VHkGyUT

**Comment by Tuller** [comment]
This is finally fixed in 10.0.14
