### ISSUE TITLE
Not able to bind "Shift+Leftclick" and "Shift+Rightclick" in Action Bar 8 in Dominos (WoW Retail)

### ISSUE THREAD

**Issue by atrionix** [tullamods/Dominos#610]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**: 9.2.2
You can get this via running `/dominos version` in game

**World of Warcraft Version**: Retail (Shadowlands)

**Issue**:
I am using Dominos and Elvui for my interface.
However, I cannot get my keybinds "shift+click" and "shift+rightclick" to work, which I use for my skills.
I have tried binding the keys in Elvui - which simply do not work and I have also tried binding them in Dominos which used to work, but now it does not.

It's action bar 8 that needs those two keys bound to "shift+click" and "shift+rightclick" but they just simply do not bind, not even when Elvui is disabled.
I also tried "alt+click" and "alt+rightclick" but that also doesn't seem to work, it just doesn't bind the keys, lol!
A friend of mine is using a similar setup, and it works for him. Anyone else having that issue or something similar?

![unknown](https://user-images.githubusercontent.com/107123236/172623601-c06f116f-6ce2-42d5-b27c-0de931a3034f.png)
![dwed](https://user-images.githubusercontent.com/107123236/172623759-f92da2e1-5952-42b7-810a-d083a5ff8539.png)

Thanks in advance,

**Comment by Tuller** [comment]
Usually shift + click is used for picking up buttons when bars are locked.
