### ISSUE TITLE
Will Dominos need to exist?

### ISSUE THREAD

**Issue by Tuller** [tullamods/Dominos#613]
Blizzard is revamping the user interface in the next expansion. It'll feature things like movable action bars, and the ability to turn off UI elements (like the gryphons) This covers the biggest thing that Dominos does. At the present time, I believe that Dominos will not be needed, and that I can discontinue the addon.

Odds are, the best approach to the new UI for the expansion may be a series (or one big) "HUD enhancements" add-on doing things like:
* Out of range coloring (ex, tullaRange)
* Cooldown text coloring (ex tullaCTC)
* Custom paging
* Scaling/opacity settings
* Snapping

**Comment by Goranaws** [comment]
I doubt blizzard will ever allow more than a few bars to be visible, and I highly doubt we will be able to hide/resize buttons from actions bar. I think Dominos will still have a place, perhaps just not as robust of a tool as it is now.

**Comment by kMeillet** [comment]
Dominos need to exist because outside of Retail, there's WOTLK Classic.

Also, Bartender is broken since eternity (see Bartender curseforge page and all complain about micro stutter and lag).

Dominos is the defacto action bar addon for most of Classic player now.

**Comment by Naros** [comment]
So I took a look at the UI revamp on the Beta today and my opinion is yes Dominos or any other bar mod will continue to be required if you really want to have full control over your bars.

The new Blizzard UI takes an opinionated perspective based on FFXIV where you have 3 core action bars in the middle of your screen at the bottom max, stacked on top of one another.  While you can control whether you have 1, 2, or all 3 bars visible, and control their size and scale, I have yet to find a way to lay out those 3 bars outside of them being stacked this way.

I think there is value in being able to add more than 3 bars on the bottom part of your screen, whether you enjoy having 2 rows of 24 buttons with keys bound to your liking or what, you simply don't have the customization available to you out of the box in terms of overall layout that mods as Dominos or others provide.

**Comment by Tuller** [comment]
The approach I want to take is to experiment with extending that new UI, and seeing how much of a pain it is to do.

**Comment by boomboo** [comment]
The current beta UI is substantially more restrictive than Dominos both in terms of options for opacity / show / hide and the number of separate button groups it allows.

You also can't use a part of a bar in some place and other buttons from it in another location.

**Comment by kayti-wow** [comment]
If it helps with the decision, Bartender4 is being updated for Dragonflight (it almost all works now) so they clearly think there's still a need for a bar addon.  I do prefer Dominos, though.

**Comment by 0xjc** [comment]
Agreed, I'm in the same spot where I have to use Bartender for DF beta, it works alright but the UX isn't as good as Dominos. The fact alone that the Blizzard default bars don't support up to 10 bars is a deal-breaker. Custom show/hide conditionals are a close second.

**Comment by Tuller** [comment]
My [dragonflight branch](https://github.com/tullamods/Dominos/tree/dragonflight) has a good chunk of it working now. There's a lot more "if something happens, reposition everything" logic on Blizzard's end to deal with than I would like.

**Comment by Naros** [comment]
That's great news @Tuller, I can't wait to battle test this on beta when you're got a preview build.

**Comment by Tuller** [comment]
The new edit mode, by and large, causes the built in action bars (and others, like the stance bar, pet bar, possess bar) to not be reusable on my end without layout issues. Various different events trigger full layout on Blizzard's end. This causes any of those action buttons to move away from Dominos. This is similar to behavior to conflicts I've encountered with other addons. The frequency of this behavior is largely dependent on the bar. For the multi action bars, this mainly occurs if you open the spell book. For the pet and stance bars, this occurs whenever those bars receive an update event. For the main action bar, this appears to only occur when entering quick binding mode.

The best resolution to this, I think, is to build custom versions of the action, pet, possess, and stance bars.

**Comment by Goranaws** [comment]
I wish I had access to the beta! If you have to go the full custom route, you will lose the ability to rearrange action bars in combat. That has been one of the benefits that Dominos has had over the competition.

**Comment by kayti-wow** [comment]
@Goranaws the new UI is also on the Pre-Patch PTR which is open to everyone.

**Comment by Tuller** [comment]
> I wish I had access to the beta! If you have to go the full custom route, you will lose the ability to rearrange action bars in combat. That has been one of the benefits that Dominos has had over the competition.

Using the `ActionBarButtonTemplate` should be doable. I just don't think I can reuse the existing main action bar and multi action bar buttons in Dragonflight due to the aforementioned layout issues.

**Comment by Tuller** [comment]
There's now eight action bars in the latest PTR build for the stock UI, and some form of snap to grid.

**Comment by Aideenwolf** [comment]
It's still a far cry from what Dominos is/was. To be honest it's driving me slightly batty that if they stay in "default" position that their UI elements collapse on themselves. IE, The Stance bar is attached to the Pet bar, which  is attached to Bar 3, which is attached to bar 2 which is attached to bar 1. If there's no buttons they collapse down. Default UI no strings attached. As SOON as you move anything all this attach and collapse coding is just gone. Snapping is still pretty bad too

**Comment by Goranaws** [comment]
I've been trying to comprehend how they have achieved their snapping code, but it seems to be rather convoluted. I'm not fond of the default snapping style at all. Does anyone happen to know which you I file contains the actual snapping logic code?

**Comment by Tuller** [comment]
> I've been trying to comprehend how they have achieved their snapping code, but it seems to be rather convoluted. I'm not fond of the default snapping style at all. Does anyone happen to know which you file contains the actual snapping logic code?

https://github.com/Gethe/wow-ui-source/blob/ptr/Interface/FrameXML/EditModeUtil.lua#L278

and 

https://github.com/Gethe/wow-ui-source/blob/ptr/Interface/FrameXML/EditModeSystemTemplates.lua#L398

**Comment by Tuller** [comment]
I’ve opted to not support dragonflight for now.

**Comment by Goranaws** [comment]
I had been working on a new navigation add-on for the past year, but due to issues/bugs I've experienced on the public beta, I've decided not to continue. It's likely I'll be leaving World of Warcraft.. a lot has changed, and it would be a steep hill to reconstruct most of my work. It seems likely that you will have to start nearly from scratch, in order to support dragonflight. Good luck with Dominos. 

Ps. I've removed all of my add-ons from curse, so no need to worry about any remnants of my work in the future.

**Comment by exxy** [comment]
Is anyone planning to fork this project?  If the original creator is not going to maintain it, the community can.  It's still 100% required.

**Comment by Tuller** [comment]
I’ve not heard anyone offer to update it for Dragonflight

**Comment by StormFX** [comment]
I mean, I could take a look at it, but I need to get my stuff updated first. That out of the way, I was going to ask: Do you mind if I throw together a stand-alone Dominos skin? Credit will be given, of course. Had a few requests, so thought I'd ask. :P

**Comment by Tuller** [comment]
That seems fine

**Comment by StormFX** [comment]
Just wondering, what would you think of adding a stand-alone Dominos skin as a sub-module, that way it's included with Dominos but removes it from `buttonThemer.lua` and makes it a bit easier for me to update it whenever I change something relevant in Masque?

**Comment by Tuller** [comment]
A git submodule, or a dominos addon? I tend to not like submodules unless they're shared between quite a few repos.

**Comment by StormFX** [comment]
I was just thinking of something that could be downloaded separately, but also could be included in Dominos by default, without having to update separate repos.

**Comment by Tuller** [comment]
That seems fine

**Comment by StormFX** [comment]
So if I throw together a stand-alone skin, you can set it up on Dominos side to grab it? Just trying to make it a bit easier for both us. Also, once I get it set up, would prefer a pull request or just info on what needs to be updated in the buttonThemer file?

**Comment by Tuller** [comment]
A PR would be preferable

**Comment by StormFX** [comment]
Waiting on the CF project approval to push a tag. Only one other question: Is there a particular license you'd prefer it to use? I can use the BSD (Copied from Dominos), if that's what you'd prefer.

**Comment by Tuller** [comment]
BSD is probably easiest

**Comment by sod** [comment]
You are a legend @Tuller. I thought hope was lost seeing this issue a month ago. Also seeing bartender not supporting the new hold-to-cast feature. Grinded my teeth out trying to get modifier paging to work by my own with native dragonflight bars.

Now I log on and see you actually updated it, and even hold-to-cast works. Thank you so much ❤️.
