### ISSUE TITLE
Enable vehicle Bar for wotlk classic

### ISSUE THREAD

**Issue by david-driscoll** [tullamods/Dominos#614]
**Is your feature request related to a problem? Please describe.**
It would be wonderful for the "blizzard override bar" to be enabled for wotlk classic, currently we get the pet bar experience.

**Describe the solution you'd like**
It would be great to be able to hop into the vehicle of choice and get a nicer bar experience 😄 

PS: Thanks for the wonderful addon, I've used it for decades I think.

**Comment by Tuller** [comment]
I’ve turned on the bar in the latest beta
