### ISSUE TITLE
[Wrath] Shadow Dance

### ISSUE THREAD

**Issue by XyzKangUI** [tullamods/Dominos#615]
Hi, I've tried your latest public beta build and can report that shadow dance is not swapping bars as it should. 

The solution is as follow:

`core/barStates.lua:`

`addState('class', 'shadowdance', '[form:3]', GetSpellInfo(51713))` has to be `addState('class', 'shadowdance', '[bonusbar:2,form:2]', GetSpellInfo(51713))`

**Comment by Tuller** [comment]
I believe all we need is:
```lua
addState('class', 'shadowdance', '[bonusbar:2]', GetSpellInfo(51713))
```

The `[form:3]` stuff came from me reviewing the last WotLK version of Dominos.
