### ISSUE TITLE
[WotLK PTR] The shaman totem bar displays in in 9.3.0-beta3, but it is not movable nor congifurable as the changelog suggests.

### ISSUE THREAD

**Issue by SheerAwesomeness** [tullamods/Dominos#616]
The shaman totem bar displays in this version, but it is not movable nor congifurable as the changelog suggests.

**Addon Version**
9.3.0-beta3-Retail

**World of Warcraft Version**
Classic WotLK PTR

![image](https://user-images.githubusercontent.com/4459267/185228218-40efc629-4561-4c0e-944f-4884a3307cb0.png)

**Comment by Tuller** [comment]
Can you try without other addons?

**Comment by SheerAwesomeness** [comment]
Sorted, thank you. Wrong version was loaded - retail 9.3.0-beta rather than Wrath. Somehow clicked wrong thing like a dumbdumb.
