### ISSUE TITLE
Bar change on talent switch in WoTLK Classic Pre Patch

### ISSUE THREAD

**Issue by OnceWasPerfect** [tullamods/Dominos#619]
**Is your feature request related to a problem? Please describe.**
With the introduction of dual spec in WoTLK Classic Pre Patch every bar changes when you switch talents.  I really only want maybe the main bar, if that, to change.  I have a bar with just consumes on it for example and if i move stuff around or change it on spec 1, when I go to spec 2 I have to change it again.  This is especially problematic on hidden bars because I have to unhide them, make the change, and hide it again. 

**Describe the solution you'd like**
Best case would be a paging option per bar for talents.  I would also like for the bars to simply not change.

**Describe alternatives you've considered**
I don't really see any outside of changing bars in each talent.

**Comment by Tuller** [comment]
This is actually a Blizzard thing, not a Dominos one. If you can find an action sets mod, it should be able to save your buttons to a profile.
