### ISSUE TITLE
[Lua Error] 1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'UNKNOWN()'.

### ISSUE THREAD

**Issue by boktai1000** [tullamods/Dominos#620]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
9.3.4-wrath

**World of Warcraft Version**
Wrath of the Lich King Classic
3.4.0.45327

Got a Lua Error with Dominos today while setting keybinds in an instance. Just wanted to pass it along.
https://www.curseforge.com/wow/addons/dominos?comment=8962

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBinding'
[string "@Blizzard_BindingUI\Blizzard_BindingUI.lua"]:348: in function `KeyBindingFrame_UnbindKey'
[string "@Blizzard_BindingUI\Blizzard_BindingUI.lua"]:402: in function <...aceBlizzard_BindingUI\Blizzard_BindingUI.lua:380>
[string "=(tail call)"]: ?
```

![image](https://user-images.githubusercontent.com/9054563/188035000-f3e896ad-3afd-4b9b-915d-559b37c0f8a1.png)

**Comment by Tuller** [comment]
Can you try with just Dominos enabled? I think another addon is causing that particular issue.
