### ISSUE TITLE
Enable SpellFlash on DominosActionButton 

### ISSUE THREAD

**Issue by jaychang85** [tullamods/Dominos#621]
FrameNames.Action = {
	"VFLButton", -- OpenRDX
	**"DominosActionButton", -- Dominos**
}

I just added above line into Hekili\Libs\SpellFlashCore\SpellFlashCore.lua to enable SpellFlash on Dominos Action bar.  See if you could update and release.

**Comment by Tuller** [comment]
Did you mean to note this on the SpellFlash library?

**Comment by jaychang85** [comment]
correct.  After adding Dominos line, I can have SpellFlash working with Dominos action bar.

**Comment by jaychang85** [comment]
For instance, I got the name of one of Dominos action button name by following command.

/print GetMouseFocus():GetName()
DominosActionButton13

**Comment by jaychang85** [comment]
Just realized this is for Dominos addon.  Sorry for the confusion.
