### ISSUE TITLE
menu bar not showing

### ISSUE THREAD

**Issue by thekaiserfranz** [tullamods/Dominos#625]
Hi, my menu bar is not showing even tough the opacity is turned on. Its weirdly grey instead of blueish. Can you help me? Thanks in advance!

![grafik](https://user-images.githubusercontent.com/113668435/190582323-e88f1af5-63af-429c-8a46-32a055857789.png)

**Comment by Tuller** [comment]
It looks like you've hidden the menu bar. Try middle clicking or shift right clicking it.
