### ISSUE TITLE
totem bar on wotlk classic out of order

### ISSUE THREAD

**Issue by sogybritches** [tullamods/Dominos#626]
the Totem bar is displaying the wrong keybind text, it is swapping the fire totem bar button keybind and the earth totem bar button keybind text on the bar display. no way to turn off the keybind text for the totem bar either.

9.3.5- wrath

wotlk classic

**Comment by Tuller** [comment]
Does this happen with the stock UI? I actually don't touch most of the totem bar other than making it movable.

**Comment by sogybritches** [comment]
No stock ui has all the keybinds listed correctly, it functions fine just the text is listed wrong so like my earth totem will show A2 as the text but will cast when I hit Alt 1 as set in the keybind menu
