### ISSUE TITLE
Shadow Priest stance swaping.

### ISSUE THREAD

**Issue by deadmage** [tullamods/Dominos#632]
Whenever you switch from disc/holy to shadow and enter Shadowform the main bar does not work read key bind actions from the keyboard, spells are clickable. Please advise on how to fix this issue.
Reproduce:
1. Log in
2. Switch to Shadow spec (from disc or holy)
3. Enter Shadow form
4. Main bar (action bar 1) spells do not trigger from keybinds.

**Addon Version**
9.3.5

**World of Warcraft Version**
WOTLK Classic

**Comment by Tuller** [comment]
I've still not reproduced this one. Have you setup paging for shadowform in configuration mode for the main action bar?
