### ISSUE TITLE
Dragonflight limited feature

### ISSUE THREAD

**Issue by boomboo** [tullamods/Dominos#633]
Given that at least for now dominos is not supported for DF, would you be interested in providing a simple state machine for the default bars, ie. an ability to change their opacity/visibility based on macro conditionals?

**Comment by Tuller** [comment]
I expect to be able to implement some settings for paging and visibility in a separate add-on.

**Comment by speedwaystar** [comment]
help is on the way: https://github.com/tullamods/Dominos/tree/dragonflight

**Comment by Tuller** [comment]
> help is on the way: https://github.com/tullamods/Dominos/tree/dragonflight

Yes, that’s my branch. Action bars mostly work (need to redirect bindings and handle the override bar case), as well as the stance bar. The menu and bag bars are movable.

I’ve not implemented a new pet bar. That one will require the most rework and not work as well as the stock one in combat.
