### ISSUE TITLE
Losing feature

### ISSUE THREAD

**Issue by lisandraaax** [tullamods/Dominos#635]
I am sad that dominos is not updated for dragonflight, blizzard's new ui does not have a lot of the freedom and functionality that dominos had, for example- I would configure 2 bars to only show 3 buttons vertically for my bars and place them apart but with blizzard they only let you reduce the amount of buttons on a bar to 6? It totally messes up the design I had created with dominos. Please bring the addon to dragonflight! The base ui is nowhere near as good

**Comment by lisandraaax** [comment]
Also the background inside the buttons are dark whereas in dominos they were clear... ugh I wish dominos would come back so badly

**Comment by melinerunen** [comment]
The min button padding of 2px form base wow :(

**Comment by Tuller** [comment]
Having checked, these actually aren't fixable with the stock action bars.
