### ISSUE TITLE
Selectively disable Dominos frames

### ISSUE THREAD

**Issue by Soromeister** [tullamods/Dominos#637]
**Is your feature request related to a problem? Please describe.**
Cosmetic problem: Want to have the default Blizzard Cast Bar instead of the Dominos one.

**Describe the solution you'd like**
Option to use the Blizzard frame instead of the Dominos one, effectively disabling the features of Dominos for that particular frame.

**Describe alternatives you've considered**
Bartender doesn't skin the cast bar, so that would be an alternative.

**Additional context**
N/A

**Comment by Tuller** [comment]
Have you tried disabling Dominos_Cast?

**Comment by Soromeister** [comment]
I'm blind. That did the trick. Thanks.
