### ISSUE TITLE
I really miss the paging feature :(

### ISSUE THREAD

**Issue by melinerunen** [tullamods/Dominos#638]
First, thank you for this awesome add-on that served me well for years :D 

I really loved your add-on since mid BFA. Mid nyalotha prog I was using bartender and I found it was kind of slow with my old pc. Specially with ~200ms under lust and with crazy high haste, the buttons stopped registering the click and i was missing a lot of GCD's. When I switched to Dominos with it's "reuse the most we can from default" all my problems were gone, and I was able to proper react to procs and GCD's again. 

That being said, I really miss the hold key to page feature. It made soo much easier to assign buttons to shift modifier that made the ui compact, usable and intuitive to use.  I know blizzard includes almost all the features that Dominos had (the min padding of 2px of wow is awful) the one I miss the most is the paging. Can it be transferred to a small add-on to "enhance" the current base?  Similar to what was posted on #613 ? I really loved the "HUD enhancement" idea :D

Unless you come to rescue us and develop the "HUD enhancement" add-on, my alternative's is either use bartender again T.T or have to have all the bars showing up to replace the shift modifiers T.T

**Comment by Tuller** [comment]
Customizable paging settings are something that is possible to implement with the stock action bars. Messing with the minimum padding value, weirdly, is not.
