### ISSUE TITLE
10.0 Alpha 2 Errors

### ISSUE THREAD

**Issue by MetalHeadSeven** [tullamods/Dominos#640]
Thanks so much for updating Dominos!!

10.0.0-alpha2

Retail

1x Interface/AddOns/Dominos_Encounter/encounterBar.lua:59: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'EncounterBar' already exists.
[string "=[C]"]: ?
[string "@Interface/AddOns/CanIMogIt/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:235: in function `NewModule'
[string "@Interface/AddOns/Dominos_Encounter/encounterBar.lua"]:59: in main chunk

Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'EncounterBar' already exists."

1x ...nterface/AddOns/Dominos_Encounter/talkingHeadBar.lua:96: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'TalkingHeadBar' already exists.
[string "=[C]"]: ?
[string "@Interface/AddOns/CanIMogIt/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:235: in function `NewModule'
[string "@Interface/AddOns/Dominos_Encounter/talkingHeadBar.lua"]:96: in main chunk

Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'TalkingHeadBar' already exists."

1x ...nterface/AddOns/Dominos_Encounter/talkingHeadBar.lua:96: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'TalkingHeadBar' already exists.
[string "=[C]"]: ?
[string "@Interface/AddOns/CanIMogIt/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:235: in function `NewModule'
[string "@Interface/AddOns/Dominos_Encounter/talkingHeadBar.lua"]:96: in main chunk

Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'TalkingHeadBar' already exists."

1x Interface/AddOns/Dominos_Encounter/talkingHeadBar.lua:1 (null)

1x FrameXML\Bindings.xml:1 Interface/AddOns/Dominos_Encounter/encounterBar.lua:1 (null)

1x FrameXML\Bindings.xml:1 Interface/AddOns/Dominos_Encounter/talkingHeadBar.lua:1 (null)

**Comment by MetalHeadSeven** [comment]
Disregard this report I forgot to remove the version posted earlier by EnemyHere before installing 10.0 Alpha 2.  No errors with 10.0 Alpha 2.

**Comment by Tuller** [comment]
This  is because I’ve moved the Dominos Extras/Encounter into the main addon folder. I probably should check and disable on load
