### ISSUE TITLE
[Dragonflight] Flyout Menus (pets, mage portals) do not work

### ISSUE THREAD

**Issue by VerstandInvictus** [tullamods/Dominos#641]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
10.0.0-alpha2-retail

**World of Warcraft Version**
Retail (Dragonflight prepatch)

The built-in click-to-menu button types, e.g. hunter pet commands, mage portal/teleport buttons, do not appear to be working in this build yet - just wanted to call that out in case you hadn't caught it yet. The buttons appear to activate, but no menu buttons appear.

Let me know if there's any diag info I can provide that would help narrow it down. It does happen with only Dominos and Dominos_Config enabled.

**Comment by Tuller** [comment]
This one is an issue on Blizzard's end:
https://github.com/Stanzilla/WoWUIBugs/issues/302

**Comment by symmetriq** [comment]
Until the latest release, I had a workaround for this — Blizzard action bar 8 still showed up even with Dominos loaded, so I was using that for all my flyouts. Now it seems Blizzard bar 8 is captured as Dominos bar 14 so this workaround no longer works.

**Comment by artazika** [comment]
elvui panels got fixed
should we expect a fix for dominos panels soon?

**Comment by jlschuncke** [comment]
The ElvUI "fix" was writing custom code to replace the lua methods Blizzard blocked. A lot of work, and time-consuming for a small team. And perhaps not worth it for the developer.

**Comment by Tuller** [comment]
More specifically, Elv and Bartender use LibActionButton, and Nev implemented a custom flyout for it. My recommendation is to use the addon Select
https://www.curseforge.com/wow/addons/select

I’ve considered implementing my own workaround, but haven’t yet spent the time doing so.

**Comment by artazika** [comment]
In search of a temporary solution to the problem, I found a Select, but opted for oPie as more nice solution for mage portals

Thank you for the answer and explanation, will be waiting, cheers

**Comment by Tuller** [comment]
I've implemented a workaround in 10.0.13. The main drawback with the workaround is that it doesn't work for Blizzard keybindings.
