### ISSUE TITLE
No bars, no settings

### ISSUE THREAD

**Issue by CiiLK** [tullamods/Dominos#644]
Addon Version: 9.3.5-retail. Curse says it was updated 17 hours ago.

World of Warcraft Version: Dragonflight 10.0.0.46366

When enabling Dominos, there are no action bars. There is an error in chat: "Failed to load ActionBars Interface/Addons/bars/actionButtonMixin.lua:57: attempt to call global 'ActionButton_UpdateFlyout' a nil value)". When trying to do /dominos, nothing happens as I can't hit enter in chat. Options > Addons > Dominos just has a blank screen. Tried to delete Dominos from addons folder and reinstall but same issue.

**Comment by Tuller** [comment]
https://github.com/tullamods/Dominos/releases/tag/10.0.0-alpha2
