### ISSUE TITLE
Can't use any buttons by hotkeys

### ISSUE THREAD

**Issue by artazika** [tullamods/Dominos#646]
I can't use any buttons from my panels by any hotkey, I'm getting this error and wow sugestion to turn off Dominos

1x [ADDON_ACTION_FORBIDDEN] Модификация 'Dominos' пыталась вызвать защищенную функцию 'UseAction()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR1BUTTON7"]:2: in function <[string "MULTIACTIONBAR1BUTTON7"]:1>

**Addon Version**
Dominos: 10.0.0-alpha4-retail

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
Is this a persistent error you’re getting, or just only under certain conditions?

**Comment by Magikh42** [comment]
Got this issue too
It happen sometimes after being teleported loading screen (such as portals or mythic+ starting)
Doing a /reload temporarily fix the issue until the next loading screen

**Comment by artazika** [comment]
As much as I get this error, I can't clearly tell after what it's happens. Probably the comment above is right, after the loading screen.
/rl temporarily fix the issue

**Comment by Magikh42** [comment]
I forgot to mention that I don't get any lua errors related to Dominos
Even with the current beta update available on Curse the issue is still present
