### ISSUE TITLE
Dragonriding

### ISSUE THREAD

**Issue by boomboo** [tullamods/Dominos#647]
I'm not certain but I think dragonriding UI is implemented via `[bonusbar:5]` as in when it shows up and probably needs to be in posses/override or it's own category.

**Comment by Tuller** [comment]
I don’t yet have beta access to test. [bonusbar:5] should be in set already at least.

**Comment by boomboo** [comment]
It didn't work out of the box for me, so I had to modify `overridebar='[overridebar][bonusbar:5]1;0'` for it to work (in overrideController.lua)

**Comment by boomboo** [comment]
#f3be523d612560dab64c492dec73d2b3f5617c0f fixes it
