### ISSUE TITLE
XML Issues 2 errors on reload or login

### ISSUE THREAD

**Issue by rmtaft** [tullamods/Dominos#648]
confirmed this is with or without other addons

1x FrameXML\Bindings.xml:1 Couldn't open Interface/AddOns/Dominos/Bindings.xml

1x FrameXML\Bindings.xml:1 FrameXML\Bindings.xml:1 Couldn't open Interface/AddOns/Dominos/Bindings.xml

**Comment by Tuller** [comment]
Try removing all dominos folders and reinstalling the AddOn

**Comment by rmtaft** [comment]
did this, no change, could this be because of an errant settings file in the WTF saved variable?

**Comment by rmtaft** [comment]
pulled those files from the old Version and it seemed to take care of the issue. just placed them in the master Dominos Directory

**Comment by Tuller** [comment]
Weird. I had removed the file because of potential taint issues

**Comment by domi1294** [comment]
Same issue here, tested it on retail with the latest beta version of dominos. I tried deleting everything and reinstalling but didn't fix itself, copying the file from the master branch removed the lua error for me too.
