### ISSUE TITLE
Dragonfligh's Beta/Alpha versions not working for me

### ISSUE THREAD

**Issue by Faugus** [tullamods/Dominos#649]
I'm trying to use the beta/alpha versions, I activate it on addon's list, it's showing loaded on the memory usage thing, but it doesn't work.
There's no config menu, no minimap button, any chat commands works, bars are still blizzard's default...
I deleted the WTF folder.
I disabled all the other addons aswell.

**Addon Version**
Beta, alpha4, alpha3...

**World of Warcraft Version**
Dragonflight 10.0.0 (46336)

**Comment by Tuller** [comment]
What does /dominos version show?

**Comment by Faugus** [comment]
/dominos version shows nothing

![chat](https://user-images.githubusercontent.com/112667550/199628595-bee5e75d-e8a2-4435-9b8c-505e54468a63.jpg)
![addons](https://user-images.githubusercontent.com/112667550/199628605-e105eb7d-002e-464f-b3c1-ea930e2f9ebb.jpg)
![memory](https://user-images.githubusercontent.com/112667550/199628613-98cb4fdf-5fec-4c4d-a9ef-51ca189ff055.jpg)

**Comment by Faugus** [comment]
There's no Dominos Extras

![image](https://user-images.githubusercontent.com/112667550/199820749-00472d77-05e7-4eea-b238-a893dbaef251.png)

**Comment by Faugus** [comment]
I just found the beta version on Curse Forge and it's working.
Looks like I was using the wrong files.
I'm sorry for that.
Great addon! Thank you very much for updating it.
