### ISSUE TITLE
Stance bar

### ISSUE THREAD

**Issue by artazika** [tullamods/Dominos#651]
Stance bar in Dominos does not support Masque
![image](https://user-images.githubusercontent.com/39316666/199541191-6f828cb4-2bd2-4d9c-847c-9e5e76bbbd7e.png)

https://github.com/SFX-WoW/Masque/issues/272
![image](https://user-images.githubusercontent.com/39316666/199541238-627ac326-2bf2-4f9b-badc-1e4b4e4e4b60.png)

**Addon Version**
10.0.0-beta2-retail

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
It appeared to be working for me with the latest version of masque

**Comment by tmgsca** [comment]
It works fine on mine. Using latest version of Masque + latest alpha of Dominos.

**Comment by artazika** [comment]
Hm, idk what happend, but with Dominos-10.0.0-beta3 everything is fine. sorry
