### ISSUE TITLE
CollectionsJournal error on leaving combat

### ISSUE THREAD

**Issue by boomboo** [tullamods/Dominos#653]
Message: Interface/AddOns/Dominos/plugins/showGridFixes.lua:40: attempt to index global 'CollectionsJournal' (a nil value)
Count: 1
Stack: Interface/AddOns/Dominos/plugins/showGridFixes.lua:40: attempt to index global 'CollectionsJournal' (a nil value)
[string "@Interface/AddOns/Dominos/plugins/showGridFixes.lua"]:40: in function `?'
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...ils/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ils/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Dominos/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ce/AddOns/Dominos/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>

**Comment by koolman007** [comment]
similar issue:

7x Interface/AddOns/Dominos/plugins/showGridFixes.lua:40: attempt to index global 'CollectionsJournal' (a nil value)
[string "@Interface/AddOns/Dominos/plugins/showGridFixes.lua"]:40: in function `?'
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Dominos/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ce/AddOns/Dominos/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by Tuller** [comment]
The current beta (4) should resolve this

**Comment by boomboo** [comment]
Works
