### ISSUE TITLE
/click actionbutton1 not working in 10.0.0 on wotlk classic client

### ISSUE THREAD

**Issue by Hedjman** [tullamods/Dominos#656]
Just updated to 10.0.0 (Release) and my macros that include /click actionbuttonX lines in macros no longer work. I reverted to 9.3.5 (Release) and functionality returned.

**Comment by Tuller** [comment]
How are you triggering the macro? Does it happen to be via a shift key combo?

**Comment by rainecheck** [comment]
Likely relates to the lua error `Couldn't open Dominos\Bindings.xml`. Generates twice on every character login.

**Comment by Tuller** [comment]
The current workaround for this is to remind your keys.

**Comment by Hedjman** [comment]
> How are you triggering the macro? Does it happen to be via a shift key combo?

I have a /click actionbutton1 on nearly all my shots as a hunter to handle my pet actions. So I am triggering the macro through hotkeys, some without a modifier (1-4) some using shift, alt, or ctrl. It failed in all scenarios.

**Comment by Tuller** [comment]
This may be resolved in the latest release (10.0.1)
