### ISSUE TITLE
Dominoes Config

### ISSUE THREAD

**Issue by peterpaul69** [tullamods/Dominos#657]
I am getting errors Dominoes_Config has been blocked from an action only available to the blizard ui.
I am getting this when right clicking on several things on my action bar (hearth stone, astral recall, ancestral spirit

**Comment by Tuller** [comment]
This one is likely an execution path taint issue. To isolate, does it work with just Dominos enabled, or after a reload of your interface?

**Comment by peterpaul69** [comment]
It did't do it last night until after I reloaded, then it would do it every time I right clicked some actions, but left click didn't do it.. Also, the call pet popout isn't working when I have it on an action bar. It works fine within the spell book and also with dominoes disabled.

________________________________

**Comment by Tuller** [comment]
This may be resolved in the latest release (10.0.1)

**Comment by peterpaul69** [comment]
Is there a way to make the action bar numbers match the blizzard action bar numbers? Right now blizzard numbers 6, 1, 2, 3, 8 match dominoes 12. 1, 6, 5, 14. Not sure about the rest of them. I can figure out which bars match up completely if you need me to. Just personally trying to get the bars with dominoes on or off to be as close as possible. Also, is there a way to link or save the dominoes layout so you can have the exact same layout on every toon, like the new option with blizzards?

________________________________

**Comment by peterpaul69** [comment]
Never mind on the last part of my other message. I found the profiles option in the dominoes main menu.
________________________________
