### ISSUE TITLE
[ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'MultiBarRightButton7:SetAttribute()'

### ISSUE THREAD

**Issue by ciphersimian** [tullamods/Dominos#658]
Reproduced with just Dominos, Dominos_Config, BugSack, and BugGrabber running.

**Addon Version**
```
Dominos: 10.0.0-retail
```

**World of Warcraft Version**
```
version = 10.0.0, build = 46455, date = 'Nov  1 2022', tocversion = 100000.
```

This happens pretty quickly just attacking from being mounted with a macro on Action Bar 1 and/or trying to mount from the Summon Random Favorite Mount ability, in both cases by pressing a keybind.

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'MultiBarRightButton7:SetAttribute()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/ActionButton.lua"]:355: in function `UpdatePressAndHoldAction'
[string "@Interface/FrameXML/ActionButton.lua"]:415: in function `Update'
[string "@Interface/FrameXML/ActionButton.lua"]:892: in function `OnEvent'
[string "@Interface/FrameXML/ActionButton.lua"]:264: in function <Interface/FrameXML/ActionButton.lua:256>
```

**Comment by Tuller** [comment]
I expect that this is resolved in the latest version.

**Comment by ciphersimian** [comment]
Similar but different issue with the latest version:

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'OverrideActionBarButton3:SetAttribute()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/ActionButton.lua"]:355: in function `UpdatePressAndHoldAction'
[string "@Interface/FrameXML/ActionButton.lua"]:415: in function `Update'
[string "@Interface/FrameXML/ActionButton.lua"]:892: in function `OnEvent'
[string "@Interface/FrameXML/ActionButton.lua"]:264: in function <Interface/FrameXML/ActionButton.lua:256>
```

```
Dominos: 10.0.3-retail
```

**Comment by ciphersimian** [comment]
I'm trying out `10.0.4-retail` but I had some general questions about the best way to set things up for the best chance of things working.

I'm curious if all Dominos Action Bars are created equal?

I started by redoing my UI for 10.0 with the new Edit Mode and e.g. put:
Action Bar 1
Action Bar 2
Action Bar 3
Action Bar 4
down at the bottom center of my screen.

Once there was a Dominos version for 10.0 I loaded it up and found those same action bars were:
Action Bar 1
Action Bar 6
Action Bar 5
Action Bar 3

which seemed very odd.

The complete mapping from Dominos action bars to Blizzard action bars seems to be:

Dominos Action Bar 1 = Blizzard Action Bar 1
Dominos Action Bar 2 = N/A
Dominos Action Bar 3 = Blizzard Action Bar 4
Dominos Action Bar 4 = Blizzard Action Bar 5
Dominos Action Bar 5 = Blizzard Action Bar 3
Dominos Action Bar 6 = Blizzard Action Bar 2
Dominos Action Bar 7 = N/A
Dominos Action Bar 8 = N/A
Dominos Action Bar 9 = N/A
Dominos Action Bar 10 = N/A
Dominos Action Bar 11 = N/A
Dominos Action Bar 12 = Blizzard Action Bar 6
Dominos Action Bar 13 = Blizzard Action Bar 7
Dominos Action Bar 14 = Blizzard Action Bar 8

So I'm wondering if there is any reason I might see better or worse behavior if I switched to predominantly using say Dominos Action Bar's 2, 7, 8, 9, 10, 11 which are not linked to the Blizzard ones in any way?

**Comment by Tuller** [comment]
At the moment, bars linked to blizzard ones should provide hold to cast and press on key press capabilities, the bars not should not.

**Comment by ciphersimian** [comment]
From:
```
Dominos: 10.0.4-retail
```

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton66:SetAttribute()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/ActionButton.lua"]:355: in function `UpdatePressAndHoldAction'
[string "@Interface/FrameXML/ActionButton.lua"]:415: in function `Update'
[string "@Interface/FrameXML/ActionButton.lua"]:367: in function `UpdateAction'
[string "@Interface/FrameXML/ActionButton.lua"]:1185: in function <Interface/FrameXML/ActionButton.lua:1182>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:266: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:322: in function <Interface/FrameXML/SecureHandlers.lua:306>
[string "=(tail call)"]: ?
```

**Comment by ciphersimian** [comment]
```
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'MultiBarRightButton12:SetAttribute()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/ActionButton.lua"]:355: in function `UpdatePressAndHoldAction'
[string "@Interface/FrameXML/ActionButton.lua"]:415: in function `Update'
[string "@Interface/FrameXML/ActionButton.lua"]:892: in function `OnEvent'
[string "@Interface/FrameXML/ActionButton.lua"]:264: in function <Interface/FrameXML/ActionButton.lua:256>
```

**Comment by Tuller** [comment]
10.0.11 should have a few more workarounds related to taint issues to mitigate this a bit more.

**Comment by jonjbm** [comment]
Still getting the followering on 10.0.11:

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton14:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:412: in function <FrameXML/ActionButton.lua:373>
[string "=[C]"]: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>
```

It's the type of error that causes a small error window to pop up in the middle of my screen and renders my keybinds unusable until I reload the UI. It's pretty disastrous because I don't realize it's going to happen until I run into combat, then I have no choice but to reload _while in combat_, which as you can imagine is really not good.

**Comment by Venkx** [comment]
Just wanted to point out that this issue still exists. Almost every time I hearth into valdrakken I have to reload, because I cant use any buttons.
