### ISSUE TITLE
Keybinds dissappear after I relog 

### ISSUE THREAD

**Issue by Seridion** [tullamods/Dominos#659]
After the latest update, my keybinds just dissappear between relogs. 

I've tried to delete Cache folder.

**Comment by Tuller** [comment]
What does /dominos version show?

**Comment by Seridion** [comment]
> 

Hey, it shows 10.0.0-wrath

**Comment by Seridion** [comment]
I downloaded a version now that says 9.3.0-beta3-Wrath  and it does the same thing, keybinds dissappear everytime i restart game

**Comment by Seridion** [comment]
But it seems to only be some actionbars that reset, not all the keybinds. It's really annoying

**Comment by Tuller** [comment]
This should be resolved in the latest release.
