### ISSUE TITLE
MOD Macros + Shift Key Not Working

### ISSUE THREAD

**Issue by avarath2022** [tullamods/Dominos#661]
Latest version for WOTLK any mod macro does not work when SHIFT key is held.

**Comment by Toffelcore** [comment]
It seems Keybinds set by Dominos and Keybinds set through "Standard" functionality work different. When setting Keybinds through Dominos the modifiers in Macros stopped working. Also the Keybinds on the Actionbars are only shown, when set through Dominos.

**Comment by avarath2022** [comment]
Issue just started to happen with latest version.

**Comment by Zurandis** [comment]
I'm having this same issue, after doing a bit more testing, any of the action buttons labeled "DominosActionButton"# don't seem to work with shift macros, but the bars/buttons without that in it do allow shift macros to work.

**Comment by markhagemann** [comment]
> I'm having this same issue, after doing a bit more testing, any of the action buttons labeled "DominosActionButton"# don't seem to work with shift macros, but the bars/buttons without that in it do allow shift macros to work.

That makes sense for me now, was working on one character but not the other, the one that did work had it in the standard action buttons.

**Comment by Tuller** [comment]
This should be resolved in the latest release.
