### ISSUE TITLE
Feature Request: Parity Between Blizzard Bars and Dominos Bars

### ISSUE THREAD

**Issue by StormFX** [tullamods/Dominos#662]
It would be amazing to see better parity between the default action bars and Dominos' bars. As it is now, according to my testing, it's set up like this:

| Dominos | Blizzard |
| --- | --- |
| Action Bar 1 | Action Bar 1 |
| Action Bar 2 | Class Bar 2 (AB 1 Page 2) |
| Action Bar 3 | Action Bar 4 |
| Action Bar 4 | Action Bar 5 |
| Action Bar 5 | Action Bar 3 |
| Action Bar 6 | Action Bar 2 |
| Action Bar 7 | Class Bar 1 (Cat/Stealth) |
| Action Bar 8 | ? (Treant) |
| Action Bar 9 | Class Bar 3 (Bear) |
| Action Bar 10 | Class Bar 4 (Moonkin) |
| Action Bar 11 | Extra? |
| Action Bar 12 | Action Bar 6 |
| Action Bar 13 | Action Bar 7 |
| Action Bar 14 | Action Bar 8 |

While this works, it can be frustrating in the event having to disable Dominos temporarily due to unforeseen issues, etc. Obviously, there's no correlation between how a user sets up their Dominos bars and how they set up the default bars, but still. I imagine this could probably _mostly_ be covered with just renaming the bars (excluding any internal shenanigans). That said, here's my suggestion for better parity:

| Dominos | Blizzard |
| --- | --- |
| Action Bar 1 | Action Bar 1 |
| Action Bar 2 | Action Bar 2 |
| Action Bar 3 | Action Bar 3 |
| Action Bar 4 | Action Bar 4 |
| Action Bar 5 | Action Bar 5 |
| Action Bar 6 | Action Bar 6 |
| Action Bar 7 | Action Bar 7 |
| Action Bar 8 | Action Bar 8 |
| ~~Action~~ Class Bar 1 | Class Bar 1 (Cat/Stealth) |
| ~~Action~~ Class Bar 2 | Class Bar 2 (AB 1 Page 2) |
| ~~Action~~ Class Bar 3 | Class Bar 3 (Bear) |
| ~~Action~~ Class Bar 4 | Class Bar 4 (Moonkin) |
| ~~Action~~ Extra Bar 1/Class Bar 5 | ? (Treant) |
| ~~Action~~ Extra Bar 1/2 | Extra? |

Feel free to take this with as much of a grain of salt as you prefer. I'm just throwing the idea out there. And I apologize if I've got some of the bar assignments incorrect. Thanks! :)

**Comment by Tuller** [comment]
Aka "implement the bartender labeling for consistency 😄

The primary conflict with that naming convention is that dominos supports a variable number of bars via /dom numbars|numbuttons.

**Comment by StormFX** [comment]
> Aka "implement the bartender labeling for consistency

Well, BT4 uses the "Class Bar", etc, naming, but its bar layout/order is very similar to Dominos, in that it also uses the older bar order.

> The primary conflict with that naming convention is that dominos supports a variable number of bars via /dom numbars|numbuttons.

So the issue with that is the "Class Bar" and "Extra Bar", not so much the order? I'm OK with "Bar x", etc, but the order is a bit "meh". I actually had to make a macro with a name for each bar and drag them out just to figure out which bar was which in both Dominos _and_ Bartender. :P

**Comment by Tuller** [comment]
Also, here's the full mapping:

| Action Page | Start Action ID | Dominos Bar ID | Blizzard Frame | Dragonflight Name | Notes |
| --- | --- | ---  | --- | --- | --- |
| 1 |     1 |    1 | MainActionBar | Action Bar 1 | |
| 2 |   13 |    2 | [actionpage:2]  | | 
| 3 |   25 |    3 | MultiBarRight | Action Bar 4 | |
| 4 |   37 |    4 | MultiBarLeft | Action Bar 5 | |
| 5 |   49 |    5 | MultiBarBottomRight | Action Bar 3 | |
| 6 |   61 |    6 | MultiBarBottomLeft | Action Bar 2 | | 
| 7 |   73 |    7 |  [bonusbar:1]  | | 
| 8 |   85 |    8 |  [bonusbar:2]  | | 
| 9 |   97 |    9 |  [bonusbar:3]  | | 
| 10 | 109 |  10 |  [bonusbar:4]  | |
| 11 | 121 |  11 |  | Likely originally [bonusbar:5] |
| 12 | 133 | | MultiCastActionPage1 | Still usable by shamans for totems in Dragonflight |
| 12 | 137 | | MultiCastActionPage2 | |
| 12 | 141 | | MultiCastActionPage3 | |
| 13 | 145 |  12 | MultiBar5 | Action Bar 6 |
| 14 | 157 |  13 | MultiBar6 | Action Bar 7 |
| 15 | 169 |  14 | MultiBar7 | Action Bar 8 |
| 16 | 181 |   | GetVehicleBarIndex() | |
| 17 | 193 |   | GetTempShapeshiftBarIndex() | |
| 18 | 205 |   | GetOverrideBarIndex() | |
| 19 | 217 |   | GetExtraBarIndex() | |

**Comment by StormFX** [comment]
Thanks for the mapping! I guess I should have checked the button IDs in the default UI. Had I done that, I'd have seen the logic of Dominos' current implementation. It seems Blizzard's implementation is the root of the proverbial "evil". Not sure why I expected anything different. 😛 

I suppose it's not that big of a deal. I've already set up my Dominos bars to match that of my default set up in the event of needing to disable Dominos for some reason. The proposed change would be mostly aesthetic on the front-end, so nothing to be overly concerned with. 🤷‍♂️

**Comment by StormFX** [comment]
Sorry to bug you on this, but I figured I'd ask before posting another issue. There seems to be something weird going on where in Dominos, Dragon Riding triggers Action Bar 5 (MultiBarBottomRight) instead of Action Bar 11 ([bonusbar:5]).

**Comment by srhinos** [comment]
I'm also encountering this and found its because blizzard made `GetBonusBarOffset()` return 5 instead of anything else. unsure if this has changed at all but I fixed it by changing line 94 in `core/overrideController.lua` from `newPage = GetBonusBarOffset() or 0` to `newPage = 11`. Seems to have fixed the behavior but I know this isn't a good long term fix so not submitting a PR for it lol

**Comment by Tuller** [comment]
Forgot to actually add in the base offset (6) for bonusbar for that one.
