### ISSUE TITLE
Alt and numpad key combos stopped working - found a fix???

### ISSUE THREAD

**Issue by CMMauddib** [tullamods/Dominos#663]
Playing WOTLK Classic, and I use a Logitech g600.  I dedicated two action bars for my side buttons, with one of the action bars working when I hold ALT.  While the action bar was still switching, my mouse buttons (num pad buttons) were not working for it.  

The fix I found was to add another keybinding, holding ALT with the proper mouse button, and then saving. THEN, I removed all bindings,  and simply rebound the numpad buttons as it was originally. Now, it works like before.  Strange.

**Comment by Tuller** [comment]
This should be resolved now.
