### ISSUE TITLE
Call Pet Error

### ISSUE THREAD

**Issue by Invarix** [tullamods/Dominos#665]
Retail
Dominos 10.0.0-Retail:

Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Count: 2
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SpellFlyout.lua"]:240: in function `Toggle'
[string "@Interface/FrameXML/SecureTemplates.lua"]:361: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:1157: in function <Interface/FrameXML/ActionButton.lua:1127>
[string "=[C]"]: ?

Locals: self = SpellFlyout {
 0 = <userdata>
 direction = "RIGHT"
 isActionBar = true
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:90
 eventsRegistered = false
 MarkClean = <function> defined @Interface/SharedXML/LayoutFrame.lua:105
 OnCleaned = <function> defined @Interface/SharedXML/LayoutFrame.lua:114
 Toggle = <function> defined @Interface/FrameXML/SpellFlyout.lua:206
 GetLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:64
 OnUpdate = <function> defined @Interface/SharedXML/LayoutFrame.lua:84
 GetAdditionalRegions = <function> defined @Interface/SharedXML/LayoutFrame.lua:76
 IsDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:110
 SetBorderSize = <function> defined @Interface/FrameXML/SpellFlyout.lua:442
 Layout = <function> defined @Interface/SharedXML/LayoutFrame.lua:333
 SetBorderColor = <function> defined @Interface/FrameXML/SpellFlyout.lua:435
 dirty = false
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 OnShow = <function> defined @Interface/SharedXML/LayoutFrame.lua:32
 Background = Frame {
 }
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 IgnoreLayoutIndex = <function> defined @Interface/SharedXML/LayoutFrame.lua:329
}
flyoutID = 9
parent = DominosActionButton10 {
 CalculateAction = <function> defined @Interface/FrameXML/SecureTemplates.lua:609
 QuickKeybindButtonOnHide = <function> defined @Interface/FrameXML/QuickKeybind.lua:11
 FlyoutArrowContainer = Frame {
 }
 NewActionTexture = Texture {
 }
 RightDivider = Frame {
 }
 UpdateButtonArt = <function> defined @Interface/FrameXML/ActionButton.lua:1227
 QuickKeybindButtonOnLeave = <function> defined @Interface/FrameXML/QuickKeybind.lua:33
 OnDragStart = <function> defined @Interface/FrameXML/ActionButton.lua:1164
 OnReceiveDrag = <function> defined @Interface/FrameXML/ActionButton.lua:1176
 icon = DominosActionButton10Icon {
 }
 SlotArt = Texture {
 }
 AutoCastable = Texture {
 }
 UpdateState = <function> defined @Interface/FrameXML/ActionButton.lua:497
 SetShowCooldowns = <function> defined @Interface/AddOns/Dominos/bars/actionBar/button.lua:82
 UpdatePressAndHoldAction = <function> defined @Interface/FrameXML/ActionButton.lua:340
 HotKey = DominosActionButton10HotKey {
 }
 HighlightTexture = Texture {
 }
 UpdateOverlayGlow = <function> defined @Interface/FrameXML/ActionButton.lua:682
 GetPagedID = <function> defined @Interface/FrameXML/ActionButton.lua:987
 Update = <function> defined @Interface/FrameXML/ActionButton.lua:378
 UpdateShownInsecure = <function> defined @Interface/AddOns/Dominos/bars/actionBar/button.lua:35
 IconMask = MaskTexture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 OnLoad = <function> defined @Interface/FrameXML/ActionButton.lua:279
 PushedTexture = Texture {
 }
 SetTooltip = <function> defined @Interface/FrameXML/ActionButton.lua:896
 AutoCastShine = DominosActionButton10Shine {
 }
 UpdateUsable = <function> defined @Interface/FrameXML/ActionButton.lua:503
 UpdateFlash = <function> defined @Interface/FrameXML/ActionButton.lua:991
 GetShowGrid = <function> defined @I

**Comment by Tuller** [comment]
This is a bug in blizzard's end that I cannot fix. My suggestion is to try the select addon as a workaround:

https://www.wowinterface.com/downloads/info11607-Select.html

**Comment by Invarix** [comment]
Thank you for continuing to work on Dominos.
