### ISSUE TITLE
Exit vehicle button does not work

### ISSUE THREAD

**Issue by Kristofer25** [tullamods/Dominos#667]
Version: 10.0.1 

Exit vehicle button shows up when inside a vehicle but clicking it does not do anything. Also in edit mode it says im moving the posses bar when im actually moving the exit vehicle button.

**Comment by Tuller** [comment]
I merged the possess and vehicle bars into a single bar (possess)

**Comment by Tuller** [comment]
I've not reproduced the button doing anything from my testing. What version of wow are you running? (/dom version will tell me enough for this)

**Comment by artazika** [comment]
For me exit vehicle button doesn't work either
10.0.3-retail , fully disabled addons

**Comment by MisterUIltimo** [comment]
Hi,
to go further in that:
The exit vehicle button does work, but not in all situations.
For example: If i mount an necrolord npc(abomination factory) the button works and let me dismount.
If i mount an toy,like the darkmoon seeshaw, or other objects like the "food war" tables in ember court or Air Supremacy worldquest in Bastion the button does nothing and i need to exit via /leavevehicle.
My conclusion is that the button works on all npc/vehicles where i can freely control the movement.
But not on all mountable stationary objects.

Dominos: 10.0.4-retail

**Comment by Tuller** [comment]
Thank you for the detailed report.

**Comment by Tuller** [comment]
This should be resolved in the latest release (I've removed the UnitControllingVehicle check)

**Comment by MisterUIltimo** [comment]
Tested on controllable npcs and on stationary worldquest npcs. Also on the Darkmoon Seeshaw Toy. Button works on all of them.
Should be working everywhere else.

Thanks Tuller
