### ISSUE TITLE
PossesBar not working correctly in classic era

### ISSUE THREAD

**Issue by deplex** [tullamods/Dominos#669]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

The PossesBar not working correctly in classic era.

4x Dominos\bars\possessBar.lua:136: Usage: GetPossessInfo(index)
[string "=[C]"]: in function `GetPossessInfo'
[string "@Dominos\bars\possessBar.lua"]:136: in function `Update'
[string "@Dominos\bars\possessBar.lua"]:199: in function <Dominos\bars\possessBar.lua:197>
[string "@Dominos\core\helpers.lua"]:176: in function <Dominos\core\helpers.lua:175>

Locals:
(*temporary) = 0

If you change line 136 to `local texture-- = (GetPossessInfo(button:GetID()))` then it will fail the if statement in line 139 with 
1x Dominos\bars\possessBar.lua:139: attempt to call global 'UnitControllingVehicle' (a nil value). Seems that 
`UnitControllingVehicle` and `CanExitVehicle` does not exists in classic era api.

**Addon Version**
10.0.2-classic

**World of Warcraft Version**
Classic Era

**Comment by Tuller** [comment]
10.0.3 should resolve this one.

**Comment by deplex** [comment]
yes, ty :-)
