### ISSUE TITLE
Action bar locked during combat, cannot drag abilities onto

### ISSUE THREAD

**Issue by Falaenx** [tullamods/Dominos#672]
The action bars lock down when in combat and you can only drag abilities on/off of currently occupied spaces.  The blizzard default bars do not do this.  Is there a setting feature to unlock the bars during combat beyond the standard in game settings which I already have overridden locked action bars?  Mostly a problem while leveling where you get a new ability in the heat of combat but cannot apply it to you bars until you have left combat.

**Addon Version**
10.0.4

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
This should be resolved in the latest release.

My intention with Dragonflight was to use the `[cursor]` macro conditional to figure out when to show/hide buttons. However, that condition doesn't work for all cursor types (pet actions, mounts, and battlepets specifically don't trigger it) AND it does not work in combat.

So instead, I've implemented a thing to track ActionButton1's showgrid attribute (which I can do now that I'm not reusing them), and send that information over to the rest of Dominos action bars. This seems to work fine, and has the benefit of eliminating the need of a workaround for the aforementioned issue with [cursor] and specific action types.
