### ISSUE TITLE
DK Presences not showing yellow activation border when active on normal action bars

### ISSUE THREAD

**Issue by Speaker1264** [tullamods/Dominos#676]
Dominos doesn't show the yellow activation border for DK presences such as Blood Presence when you have the ability on a normal action bar.  It does show the border for the class bar, just not the action bars.  For rogues and warriors, abilities like Stealth and Battle Stance show the yellow activation borders on both the action bars as well as the class bar.  It seems like DK presences should also show the yellow border on the action bars as well since presences are considered stances like Stealth and Battle Stance.

**Addon Version**
10.0.7-wrath

**World of Warcraft Version**
Classic

**Comment by Tuller** [comment]
Dominos does not handle this particular thing, so its likely an issue on the stock UI's end.
