### ISSUE TITLE
Action Bar 12 Empty

### ISSUE THREAD

**Issue by gz2k2** [tullamods/Dominos#677]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
1.0.0.6 and 1.0.0.7

**World of Warcraft Version**
Retail

My "Dominos" Bar 12 is now emtpy since v1.0.0.6. if i disable Dominos, "Blizzard" Bar 6 is filled with my Spells. 1.0.0.5 works fine

**Comment by Tuller** [comment]
This should be fixed in 10.0.8
