### ISSUE TITLE
zhTW localizations

### ISSUE THREAD

**Issue by class2u** [tullamods/Dominos#680]
Hi, Here are the [updated zhTW localizations](https://drive.google.com/file/d/1gNaCuXHr8MMuDPm8sLw3-bajcyNnLlSP/view?usp=share_link) for Dominos 10.0.9. Please feel free to use them. Thank you.

**Comment by class2u** [comment]
Thank you for using the localizations. There are still two issue:
1. Dominos_Cast\localization.xml does not have localization.tw.lua included.
2. Dominos_Progress\localization\localization.tw.lua does not been replaced with the new one.

**Comment by Tuller** [comment]
This should be resolved in 10.0.11
