### ISSUE TITLE
extra action bar sometimes not handled by dominos

### ISSUE THREAD

**Issue by Neischa** [tullamods/Dominos#681]
Hi, I have a problem that extra action button is sometimes not handled by dominos, but by blizz UI = it is displayed in the middle of the screen in default style. When I reload UI or relog, dominos usually takes it over properly and renders it in correct position and style (smaller, no graphic on sides).

I have latest version of Dominos, playing Retail.

I know this description sux, but I am facing this issue for couple of weeks already and its happening like 3-4* per day only and I was unable to identify the root cause, but it seems like there is higher chance this happenes when I change specialization.
Btw. I dont't have any other addon which is able to manipulate with button frames.

**Comment by Neischa** [comment]
Ok, I just verified it does always when I change spec, but when I reloadui after it fixes it (until I change spec again).
And I tested it with dominos only, just to be sure.

**Comment by Tuller** [comment]
10.0.11 implements some more workarounds for this.

**Comment by hollo6** [comment]
It's still happening with 10.0.11, at seemingly random times, without changing specs.

**Comment by justinkb** [comment]
still happening in 10.2.5, without changing specs (happened during gilneas reclamation scenario with the tunnel torch)

**Comment by Tuller** [comment]
Are you still seeing this with 10.2.15?
