### ISSUE TITLE
Action Button Glows/Swipes ignoring opacity settings

### ISSUE THREAD

**Issue by ZINK-ZINK** [tullamods/Dominos#684]
Version 10.0.11-retail

When using the Fader settings to set Bars to 0 Opacity Glows and Swipes still show up over the "invisible" action bars. 

To recreate the bug Unholy DK Ghoul Pet's auto-cast abilities and Paladin's Aura Bar GCD consistently show it.

**Comment by Tuller** [comment]
Is the bar set at exactly 0% opacity? At 1% the shine will likely show up (because it ignores your bar's opacity setting).
