### ISSUE TITLE
Vehicle Bar doesn't move 'Help Request' from Micro Menu

### ISSUE THREAD

**Issue by boktai1000** [tullamods/Dominos#685]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

When entering a vehicle (in this case, Pilgrims Bounty) the Micro Menu buttons all move to the new Vehicle UI except for the Help Request button. Inserted in a screenshot below to showcase this.

**Addon Version**
Dominos: 10.0.11-Wrath

**World of Warcraft Version**
Classic Wrath

![image](https://user-images.githubusercontent.com/9054563/204150154-fdd939c1-48d7-4a5e-b5de-1ee07c2d3dfb.png)

**Comment by Tuller** [comment]
This might be a bit better in 10.0.15
