### ISSUE TITLE
Action bars do not save when swapping specs

### ISSUE THREAD

**Issue by kevgwang** [tullamods/Dominos#689]
Character in question is a shaman.

One day, I zoned out of a dungeon, and my bars were replaced by the bars of the spec that I had used inside the dungeon but was different from what I went in with and exited with.  I.E   I was in elemental spec, queued as resto, was swapped by the game to be resto as I zoned into the dungeon, and upon leaving the instance, I was put back into elemental spec, but my bars were replaced with my restoration ones.

Since that day, my bars no longer save their buttons after swapping specs.

Previously, I've never used spec profiles, but after having this issue, I have tried to use different profiles for different specs.  Unfortunately, the issue still occurs where my bars remain the same.

I have tried deleting both the generic shaman profile as well as the newly created spec profiles.

The issue only happens to one specific character.

**Addon Version**
10.0.11-retail

**World of Warcraft Version**
 Retai

**Comment by kevgwang** [comment]
This issue only happens when swapping between resto and elemental as well, regardless of whether I have different profiles set for each spec or am using the same profile for this shaman.

When swapping to or from enhancement, the enhancement bars remain separate from the resto/elemental.

This issue hasn't occurred on any other character.

**Comment by Tuller** [comment]
Action button _contents_ are not stored by Dominos, only bar positions.

**Comment by kevgwang** [comment]
Thank you for the response.

I've verified that this is an issue on Blizzard's end that a number of other players are experiencing on the official forums.
