### ISSUE TITLE
Dragonriding Paging

### ISSUE THREAD

**Issue by Guycicle** [tullamods/Dominos#691]
It is nice to have a seperate action bar when we're flying for Surge Forward and Ascend. 
The new patch sorta messed this up. 

Please add paging for Dragonriding for anyone who wants actionbar to change when mounted.

**Comment by Tuller** [comment]
This should already be implemented. Your override bar should page to bar 11 currently.

**Comment by vioray** [comment]
doesn't work correctly on Evokers, the bar doesn't change. possibly due to how the bar pages for the racial Soar?

**Comment by Tuller** [comment]
Dragonriding has been moved to a bar's right click context menu.
