### ISSUE TITLE
Pagination does not work when override bar is set to bar 1 during dragonriding

### ISSUE THREAD

**Issue by thefowles1** [tullamods/Dominos#697]
**Addon Version**
10.0.12-retail

**World of Warcraft Version**
Retail

Issue: When override bar is set to action bar 1, the action bar will not change pages while on my dragonflight mount, locking me to only the dragonriding abilities. I cannot cycle through my action bars by using the 1-6 numbers on my numpad, like how action bars function otherwise. This is especially annoying with dragonriding, as I have my dragonflight mount hotkey on a different action bar (5), and I cannot cycle to the action bar to press the hotkey to dismount and am instead forced to right click the buff to dismount. Verified this only occurs with override bar set to 1 (anything other than 1, the dragonriding abilities do not show while mounted, since they are not on any of my 1-6 bars, thus rendering anything other than 1 being useless for dragonriding -- however, cycling pages _does_ work if it is set to anything other than 1), as well as only happens with dominos (with all dominos addons disabled & only using vanilla action bars, pressing 1-6 on numpad _does_ cycle action bars while dragonriding, as expected).

**Comment by Tuller** [comment]
In 10.0.13, I've moved dragon riding configuration into the standard spot for paging.

**Comment by thefowles1** [comment]
@Tuller I see beta2 has been pushed and is preconfigured to override bar 1 - behavior now operates like vanilla bars. Thank you so much for the quick work.
