### ISSUE TITLE
unusable spells

### ISSUE THREAD

**Issue by Mordello** [tullamods/Dominos#698]
Hey so i'm getting this issue quite often where i cannot use certain spells untill i reload. i cant figure out when this happens either cause its pretty random. also i can never use my teleport or portal spells. i always have to go through my spellbook to be able to cast it. i cannot cast it thru my dominos bars.

I can click on the spells on the dominos but i cannot use my keyboard bindings to use them.
I've tried to disable certain addons, deleted some weakauras but dunno. hopefully someone can help me thank you.

3x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton9:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:412: in function <FrameXML/ActionButton.lua:373>
[string "=[C]"]: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>

**Comment by calummitchell** [comment]
This is happening to me semi-regularly. It seems to happen when I switch specs/talents and possibly only with macro keybinds. /reload fixes it.

1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton27:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:330: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:392: in function `Update'
[string "@FrameXML/ActionButton.lua"]:890: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:244: in function <FrameXML/ActionButton.lua:236>

1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'OverrideActionBarButton5:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:330: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:392: in function `Update'
[string "@FrameXML/ActionButton.lua"]:890: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:244: in function <FrameXML/ActionButton.lua:236>

1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton17:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:330: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:392: in function `Update'
[string "@FrameXML/ActionButton.lua"]:890: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:244: in function <FrameXML/ActionButton.lua:236>

1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton11:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:330: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:392: in function `Update'
[string "@FrameXML/ActionButton.lua"]:890: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:244: in function <FrameXML/ActionButton.lua:236>
