### ISSUE TITLE
Dragonriding bar override not working

### ISSUE THREAD

**Issue by Falaenx** [tullamods/Dominos#702]
The dragonriding bar that was on bar 11 used to override bar one when mounted in a dragonride.  This no longer works in this version or a setting has been changed and not documented.

**Addon Version**
10.0.13-beta1

**World of Warcraft Version**
Retail

**Comment by speedwaystar** [comment]
you can edit your bar settings and enable the dragonriding override (it uses bar 11). this works, for a while. however, after a period it suddenly stopped working for no apparent reason+, although the override is still active. quitting wow and restarting caused it to begin working again. no errors were thrown during the period it wasn't working.

**Comment by speedwaystar** [comment]
regarding dragonflight override not working after a period: it's because i use macros with /swapactionbar x y, and only the initial actionbar supports paging, apparently, even if i set all the other bars to also use dragonriding with ab 11.

**Comment by MrDragon** [comment]
I had 10.0.13 non-beta installed, I see the "Paging Dragonriding" option, it is set to bar 11, and bar 11 does contain the dragonriding buttons.
However, when I'm mounted, actionbar 1 doesn't change to 11. Maybe I'm doing something wrong?
I reverted back to 10.0.12 for now.
If it matters: I'm an Orc Arms Warrior.

**Comment by Tuller** [comment]
10.0.15 should fix this
