### ISSUE TITLE
Keybinds are not Talent Specific ANYMORE

### ISSUE THREAD

**Issue by knoxnetic** [tullamods/Dominos#704]
So, I'm using the latest 10.0.02 version

Basically I used to have different Keybinds and spells location based on the spec. (Mage)

Now If I change spec between fire and frost. Same keybinds share the same locations on the bars on every talent specialization

Before, in simple terms keybinds where not shared inbetween all specs... Now I'm forced to same keybinds like on blizzard UI on every action bar on every SPEC... Basically Character specific, not Talent Spec :( 

Please fix

**Comment by Tuller** [comment]
Domino's bindings are stored on Blizzard's end, and are not part of any Dominos profile.
