### ISSUE TITLE
Vehicle Bar

### ISSUE THREAD

**Issue by ForzaInter135** [tullamods/Dominos#705]
I am a new player so please keep my noobness in mind...Whenever I have a quest that involves a WOW vehicle, I cannot see the bar I need to utilize. Is there a way to see this bar somehow?  FYI- I did not see a "vehicle bar" so I assume it overrides another bar?

Any help is much appreciated!

**Comment by HolgerDKz** [comment]
> > I am a new player so please keep my noobness in mind...Whenever I have a quest that involves a WOW vehicle, I cannot see the bar I need to utilize. Is there a way to see this bar somehow? FYI- I did not see a "vehicle bar" so I assume it overrides another bar?
> 
> Any help is much appreciated!

It looks like yesterdays (for NA) or todays (for EU) WoW update broke something in how WoW/Dominos handles bars as the dragongliding bar does not appear for me as of today (2022/12/14)

**Comment by Tuller** [comment]
10.0.15 should fix this
