### ISSUE TITLE
Error with fresh install

### ISSUE THREAD

**Issue by Sythr4l** [tullamods/Dominos#706]
This error appears when loading into the game with Dominos v 10.0.13

1x Dominos/Dominos.lua:70: attempt to compare nil with number
[string "@Dominos/Dominos.lua"]:70: in function `OnUpgradeDatabase'
[string "@Dominos/Dominos.lua"]:264: in function `UpgradeDatabase'
[string "@Dominos/Dominos.lua"]:30: in function <Dominos/Dominos.lua:27>
[string "=[C]"]: ?
[string "@Bazooka/libs/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...dOns/Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Bazooka/libs/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Bazooka/libs/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...dOns/Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by Tuller** [comment]
Thanks, this should be resolved in 10.0.14

**Comment by Sythr4l** [comment]
Thank you!
