### ISSUE TITLE
Flyout buttons not working

### ISSUE THREAD

**Issue by Makyura3** [tullamods/Dominos#712]
Using Dominos version 10.0.14 on retail servers.

Flyout menus work but when I press on a mage portal, warlock pet, etc., they do not work.

**Comment by rmtaft** [comment]
after update i believe , my mage portals and teleports also stopped working, no errors just no action on click

**Comment by Tuller** [comment]
What button are you using to toggle the fly-outs?

**Comment by Makyura3** [comment]
> What button are you using to toggle the fly-outs?

None. If I put it on a keybind, nothing happens but that's fine. I click the teleport or portal button then click on a teleport or portal and nothing happens.

**Comment by vioray** [comment]
not only does clicking the buttons not work, the flyout menus do not go in front of other elements of the UI making them very easily hidden

**Comment by leonbaineann** [comment]
I'm having this issue as well, just want to add that when I click on a portal icon from the flyout bar, the bar closes but the icon glows like when it casts and stays glowing when I open the bar again.  it just doesn't actually start the cast

**Comment by Tuller** [comment]
This should be fixed in the 10.2.5 beta
