### ISSUE TITLE
[Wrath] Death Knight presence paging options

### ISSUE THREAD

**Issue by Road-block** [tullamods/Dominos#714]
**Is your feature request related to a problem? Please describe.**
I'd like presences to show up as paging options for bar configuration.

**Describe the solution you'd like**
Blood/Frost/Unholy register with GetShapeshiftForm* and [form:N] macro conditionals and they also fire the relevant `UPDATE_SHAPESHIFT_FORM` event.
The addition should be as simple as adding this snippet to barStates.lua in the class section.
```lua
elseif class == 'DEATHKNIGHT' then
    if Addon:IsBuild('wrath') then
        addFormState('class', 'blood', 48266)
        addFormState('class', 'frost', 48263)
        addFormState('class', 'unholy', 48265)
    end
```

**Describe alternatives you've considered**
The alternative is replacing the presence class buttons with regular macro buttons like
```
#showtooltip
/use Blood Presence
/changeactionbar [nobar:1] 1
``` 
etc

**Additional context**
Leveraging Dominos paging seems by far the cleaner solution and having them set to `Disable` by default makes this zero impact for players that have no use for paging but gives the option to enable for those that do 😃

**Comment by Tuller** [comment]
Thank you, this should be implemented in the beta version.

**Comment by Road-block** [comment]
Latest beta package seems to have disappeared the micromenu bar on Wrath Classic. 
There are no Lua errors. I checked to make sure it didn't revert to hidden. I did a full exit of the client and started up again.

**Comment by Road-block** [comment]
Presence paging works great on the latest beta so I'll close this one and make a separate ticket for the micromenu bug.
