### ISSUE TITLE
[Wrath] Micromenu buttons invisible (no Lua errors)

### ISSUE THREAD

**Issue by Road-block** [tullamods/Dominos#716]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
You can get this via running `/dominos version` in game
`10.0.15-beta1-wrath`

**World of Warcraft Version**
Classic Wrath Live (3.4.0.47168 enUS)

There are no Lua errors, the Micromenu bar overlay shows in config mode, clicking individual buttons on and off adjusts the size but the buttons do not draw (also not clickable, they're just "not there")

Reverting to release version `10.0.14` Micromenu works without any addon / configuration changes.

**Comment by Road-block** [comment]
Did all the typical troubleshooting stuff

- Fully exit client in case a new file was added
- Reload
- Check show states (default/empty)

**Comment by Tuller** [comment]
Move the bar up, and you'll see the problem :)

**Comment by Tuller** [comment]
10.0.15 should fix this
