### ISSUE TITLE
Pet grid always showing empty buttons

### ISSUE THREAD

**Issue by Daenarys** [tullamods/Dominos#718]
The pet grid is always showing empty buttons, should be hidden when no buttons attached to that slot.

![Screenshot 2022-12-30 204800](https://user-images.githubusercontent.com/4172453/210107104-efc36c38-c9fc-440c-8bc0-d85750495b3f.png)

**Addon Version**
10.0.15

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
Try this:
1. Enter Blizzard's edit mode
2. Select the pet bar
3. Uncheck Always Show Buttons

**Comment by Daenarys** [comment]
Thanks!
