### ISSUE TITLE
Stance Bar Anchor Point

### ISSUE THREAD

**Issue by gz2k2** [tullamods/Dominos#719]
**Is your feature request related to a problem? Please describe.**
Is it possible, to change the Anchor Point of Stance Bar?
My Stance Bar is on the right side, and grows to the right side.
I have placed the Bar on my Druid, and on my Warrior, the Bar is moved a little to the left. (look at Screenshots)

**Additional context**
Warrior
![grafik](https://user-images.githubusercontent.com/77876301/210136375-c668964f-e1c9-400f-b3ec-ad2e25ff51cf.png)

Druid
![grafik](https://user-images.githubusercontent.com/77876301/210136533-54c17eb7-6e59-419e-aaf5-0da0cd801a75.png)

**Comment by Tuller** [comment]
Do you have sticky bars enabled?

**Comment by gz2k2** [comment]
yes, sticky Bars are enabled

**Comment by Tuller** [comment]
I think in this case, it may have been snapped to the grid and not to the bar. What do the bars look like in configuration mode?

**Comment by gz2k2** [comment]
it works now. my problem was Masque. With sticky bars, the stance bar was misplaced by 2 pixels. i've moved the stancebar with the movement keys. i think, this "unstick" the bars. i've changed the scaling at Masque. now, the stance bar is at the same place with warrior and druid.

Thank you for your help :)

Masque Scaling 1.0
![grafik](https://user-images.githubusercontent.com/77876301/210180228-d612c62f-5b9e-41a8-9266-6059fb8d3e62.png)

Masque Scaling 0.92
![grafik](https://user-images.githubusercontent.com/77876301/210180256-bb67a3a7-27bd-4df1-b148-8648503f9a04.png)
