### ISSUE TITLE
When Dragonflight override is set to Bar 1, but the command /swapactionbar is used to show a different page, the override doesn't work

### ISSUE THREAD

**Issue by speedwaystar** [tullamods/Dominos#721]
to recreate:
- set Action Bar 1 Dragonriding override to Action Bar 11

![example 1](https://i.imgur.com/wWnhnUX.png)

- for argument's sake, since it won't actually do anything, set Action Bar 2 Dragonriding override to Action Bar 11
-create a macro with includes the command /swapactionbar 1 2

![example 2](https://i.imgur.com/T0dTSrO.png)

- drag the example macro to a slot on Action Bar 1

![example 3](https://i.imgur.com/JinI58j.png)

- verify that the Dragonflying override works by mounting your dragon
dismount

- click the example macro. Action Bar 1 now shows Action Bar 2. however, if you left-click Dominos and enter configuration mode, you'll see that Dominos still considers it to be Action Bar 1

- mount Dragon and note that the override doesn't work, even though both Bar 1 and 2 have been set to use overide.

**Comment by Tuller** [comment]
This is intentional. Dominos evaluates paging in the following order:
1. Modifiers
2. Quick paging (You're triggering the [actionpage:2] condition via the `swapactionbar` command)
3. Class specific paging (which includes dragon riding)

**Comment by speedwaystar** [comment]
is there a workaround that I can use to cause the override to work when the
quick page is displayed?

**Comment by Tuller** [comment]
You can edit barStates.lua, but that's about it. The I've set the priority is so that you can be in a stance (or flying), and then use a quick page or modifier to switch to a different bar temporarily, and then switch back once more when you're done.

**Comment by speedwaystar** [comment]
fair enough. i guess then my workaround is to make a macro for dragonriding
that does
/swapactionbar 1 1
/use <dragon>

cheers
