### ISSUE TITLE
Dominos bars disappear after dungeons and crafting orders

### ISSUE THREAD

**Issue by alliepet** [tullamods/Dominos#722]
**Addon Version**
10.0.12-retail

**World of Warcraft Version**
Retail

My bars will disappear seemingly randomly but I notice it most after a dungeon, sometimes after combat and a lot after I do some crafting orders. I see this error:

`23x Dominos/core/frame.lua:422: calling 'GetParent' on bad self (Usage: local parent = self:GetParent())
[string "=[C]"]: in function `GetParent'
[string "@Dominos/core/frame.lua"]:422: in function <Dominos/core/frame.lua:413>
[string "@Dominos/core/frame.lua"]:452: in function <Dominos/core/frame.lua:433>
[string "@Dominos/core/frame.lua"]:457: in function `IsFocus'
[string "@Dominos/core/fadeManager.lua"]:21: in function `Update'
[string "@Dominos/core/fadeManager.lua"]:43: in function <Dominos/core/fadeManager.lua:41>

Locals:
(*temporary) = SecureTransferDialog {
 Button2 = Button {
 }
 Button1 = Button {
 }
 Text = FontString {
 }
 Border = Frame {
 }
 MoneyLabel = FontString {
 }
 CautionIcon = Texture {
 }
 ticker = <userdata>
 0 = <userdata>
 acceptTimeLeft = 3
}`

**Comment by alliepet** [comment]
This seems to happen randomly when getting out of combat too.

**Comment by alliepet** [comment]
Same error, but it happens even when I'm doing crafting or like, randomly. :O

**Comment by Tuller** [comment]
This should be fixed in the latest one at least.
