### ISSUE TITLE
button grid slow response

### ISSUE THREAD

**Issue by Daenarys** [tullamods/Dominos#725]
The button grid has a slight delay in showing up when picking up action buttons from it, With Bartender4 it shows instantly (same as blizz default) and sometimes when you drag buttons to other slots you have to actually click the slot to place the button in it. I know you've tried fixing that before, but its still not working correctly.

**Addon Version**
10.0.16

**World of Warcraft Version**
Retail

**Comment by Daenarys** [comment]
@Tuller I have tinkered with the code myself a bit since i have some dev experience myself, and i managed to make it work blizzlike by handling the ACTIONBAR_SHOWGRID and ACTIONBAR_HIDEGRID events in the action bar module. This also removes the requirements of "_childupdate-showgrid" and "UpdateShown" in ActionButtons, the LoadShowGridController in ActionBar and the secureEnv.lua. I did have to use the ACTIONBAR_SLOT_CHANGED event or the buttons would hide after dragging them to other slots.

**Comment by Daenarys** [comment]
@Tuller been experimenting a bit with adding the ACTIONBAR_SHOWGRID and ACTIONBAR_HIDEGRID events to the action bar and calling SetShowGridInsecure, out of combat its as quick as bt4 and blizz, while in combat it doesnt work, so still have to use loadshowgridcontroller/secureenv which it luckily falls back to!

**Comment by Tuller** [comment]
Yeah the reason I had to use the secure stuff was to work around not being able to use the events in combat 😃 

In classic, we are able to use that logic.

**Comment by Daenarys** [comment]
Got it, but atleast it works as 'normal' out of combat using the event thing ^^
Also I tried it on BT4 and they have it working in combat with the events? how does that work? xD

**Comment by Tuller** [comment]
LibActionButton (which is what bartender uses internally) makes the buttons transparent instead of hiding them.  It works visually, but you may notice that the area where empty buttons are isn’t clickable

**Comment by Daenarys** [comment]
Interesting! thanks for the info :)

**Comment by Tuller** [comment]
It's something to play around with. Typically, I'd want to avoid two code paths for the same thing.

**Comment by Tuller** [comment]
This should be faster in the 10.2.5 implementation
