### ISSUE TITLE
Player Bar / Stance Bar

### ISSUE THREAD

**Issue by kafciu** [tullamods/Dominos#726]
After last update Player Bar disappeared. I dont have Auras bar on my Paladin and Forms bar on my Druid. Can u check it?

**Addon Version**
10.0.16 - wrath

**World of Warcraft Version**
WoTLK Classic

**Comment by kafciu** [comment]
![image](https://user-images.githubusercontent.com/122321527/211609471-9b8456a6-f30d-4cb4-af5d-57c046bc3635.png)

**Comment by Tuller** [comment]
Are you running any other addons? That particular file shouldn’t even be loaded in classic.

**Comment by Xanpop** [comment]
MoveAndImprove

Was having the exact same problem and disabling MoveAndImprove fixed it.

**Comment by mattk926** [comment]
Same issue here. Disabled MoveAndImprove for now. but this wasn't an issue before the update to dominoes... would be good to have a fix besides disabling other addons.

**Comment by kafciu** [comment]
> Are you running any other addons? That particular file shouldn’t even be loaded in classic.

As Xanpop and mattk926 wrote disabling MoveAndImprove addon fixed it.  But all was good before last update. Today MoveAndImprove has update but stance bar still not working

**Comment by mattk926** [comment]
> 

The "update" was merely adding !!! to a line that stated: "This addon was only a prototype!!!" Looks like the author decomissioned this addon and replaced it with two different addons below:

2 New Addons that replaces this one:
• https://www.curseforge.com/wow/addons/moveany

• https://www.curseforge.com/wow/addons/improveany

this two are the new ones, this one was just a prototype
