### ISSUE TITLE
Keys firing on key up instead of key down

### ISSUE THREAD

**Issue by ShadowSingularity** [tullamods/Dominos#730]
Abilities firing on key up even though the cvar is set to use them on key down.

**Addon Version**
10.0.16

**World of Warcraft Version**
Retail.

**Comment by Tuller** [comment]
Which action bars are you using?

**Comment by ShadowSingularity** [comment]
1,2 and 3, the strange thing is that for example cobra shot fires off instantly, but disengage i can hold until release.

**Comment by aname23** [comment]
Hi Tuller

Just popping in to say that I also have the same problem.

For me, bars 1, 3, 4, 5, 6 and 12 work fine. Abilities activate on keypress down.

But bars 2, 7, 8, 9, 10 and 11 only activate on key up.

Not sure if that helps out at all or what other info I could provide to assist, let me know if needs.

Thanks
Seb

**Comment by ShadowSingularity** [comment]
Ah that would explain why cobra shot (bar 1) does work but my disengage (bar 2) doesnt.

**Comment by Tuller** [comment]
2, 7, 8, 9, 10, and 11 are additional buttons provided by Dominos. They can't implement cast on keypress in the Dragonflight expansion.
