### ISSUE TITLE
Action Bar 3 is invisible

### ISSUE THREAD

**Issue by Ceejaikae** [tullamods/Dominos#734]
A recent update has made Action Bar 3 invisible in WotLK Classic. You can't see what buttons are on the bar, even if it's "visible", nor can you drag abilities to the bar. When picking up an ability the outlines on the bar don't even show up. The hotkeys and abilities on AB3 still work and fire properly, but otherwise the bar can't be interacted with, outside of moving it.

Thank you.

**Comment by lath** [comment]
I'm having the same issue, changing the opacity under fading to less than 100 and then back to 100 fixes it - for a while. Seems to reset itself sometimes after you hearthstone or logout/login.

**Comment by Tuller** [comment]
Do you have screenshots of this? Both with and without configuration mode (/dom config) open.

**Comment by lath** [comment]
Without /dom config
![image](https://user-images.githubusercontent.com/733989/215287978-7e7db1bd-2edb-4b3e-b7c7-ddbe88aacdca.png)

With /dom config
![image](https://user-images.githubusercontent.com/733989/215288006-e3a0672d-dd0e-411e-b02a-936f8e092880.png)

Fading view of AB3
![image](https://user-images.githubusercontent.com/733989/215288075-03af5126-9a2c-422f-985f-38e9eee54f0b.png)

Please let me know if you want any more information I can provide :)

**Comment by bendltd** [comment]
not sure if it might help but in my case the Bar3 just got stuck on the right side:
![WoWScrnShot_013123_111504](https://user-images.githubusercontent.com/5522102/215736573-f91af857-df10-42f9-951b-83076de2f3af.jpg)

and the Bar3 should be at the bottom:
![WoWScrnShot_013123_111526](https://user-images.githubusercontent.com/5522102/215736887-88d570aa-2418-4885-b09b-03085e1e4897.jpg)

**Comment by Knightstrike66** [comment]
Hello, I had a similar issue as shown with this screenshot: 
![image](https://user-images.githubusercontent.com/124203758/216150471-71c13108-59d3-46bd-9a48-57d20f909923.png)
I was using the addon MoveAny, in it's settings i unchecked "Actionbars 3 (Right Bar)" and my dominos bars returned to normal.
<img width="700" alt="image2" src="https://user-images.githubusercontent.com/124203758/216150930-2ca63818-4335-490b-b418-6ca302401fd5.png">
I hope this helps!

**Comment by lath** [comment]
I also have MoveAny, and Actionbars 3 was checked for me too. Most likely this was the cause!

**Comment by Ceejaikae** [comment]
> Do you have screenshots of this? Both with and without configuration mode (/dom config) open.

I can get some today. I am also going to check for any conflicts with MA, though I do not think I have that installed in WotLK Classic.

Also, a small update: I was able to get the bar into the right place by right-clicking on the Action Bar 3 "shadow" in config mode (oddly the "shadow" was in the correct place, but the actual bar went up the right side of the screen, clipping into another one), but I have not re-logged since to see if it was a permanent or temporary fix.

**Comment by bendltd** [comment]
> I also have MoveAny, and Actionbars 3 was checked for me too. Most likely this was the cause!

Thank you so much. I've MoveAny as well but I only use it for the QuestLog and for whatever reason it activated Bar3:
![image](https://user-images.githubusercontent.com/5522102/216292658-94b103dd-8bd1-46bf-9169-10fb1444f2cf.png)

Removing this solved it for me.

**Comment by Ceejaikae** [comment]
Well, yeah, apparently it was just a weird bug with MA, not dominos. You can close this ticket, as I was having the same issue described earlier in this thread (MoveAnything had checked Action Bar 3 on it's own and had put it in the default position on the right side of the screen).

Thanks again to everyone helping to fix this issue.
