### ISSUE TITLE
[10.0.7] Pet and Stance Bar Errors

### ISSUE THREAD

**Issue by Tuller** [tullamods/Dominos#736]
In 10.0.7, Blizzard changed the behavior of the PetActionBar to no longer use the buttonsAndSpacers table. Need to revisit the implementation

**Comment by Daenarys** [comment]
I saw your commit earlier and was thinking, can't we just remove the buttons and spacers and add the bars to the blizz hider? I tried it on the PTR with old modules and it seemed to work fine. Off topic, they also semi fixed the spell flyouts but they only work on the blizz bars so we still have to use the custom implementation. 🙃

**Comment by red7silence** [comment]
The pet bar (warlock) is completely gone while using dominos with 10.0.7 release.

**Comment by ThatJeffGuy** [comment]
Can also confirm completely gone for Druid stance bar, as well as Hunter pet bar.

I'd assume everything calling the PetActionBar is busted.
