### ISSUE TITLE
(REQUEST) Cast action keybinds on key down

### ISSUE THREAD

**Issue by Comettii** [tullamods/Dominos#737]
Hi,

I recently switched to Dominos from Bartender4 and I really like the addon, especially with the page feature.

However, one thing that I really missed is the possibility to change the behavior of the key action and launch it when it is pressed instead of when it is released. Searching a little on Google, I found that the cvar used was `actionButtonUseKeyDown 1`, but this does not work for a long time and many addons that used this to change the behavior, stopped working (advance interface options for example).

If it's not too much to ask, would it be possible to insert this functionality into the addon please? I'm sure it would make it even bigger!

Thank you very much for your work!

**Comment by XyzKangUI** [comment]
May I ask what the 'addCastOnKeyPressSupport' function is used for in wrath classic? The CVar works in classic.

**Comment by ivancuric** [comment]
I noticed that all of my bars except action bar 2 respect this setting.
I also noticed that there is quite a bit more delay when pressing down (and releasing) compared to vanilla bars.

**Comment by Tuller** [comment]
This should be fixed in the 10.2.5 beta
