### ISSUE TITLE
[Wrath Classic] 10.0.20-beta

### ISSUE THREAD

**Issue by Road-block** [tullamods/Dominos#739]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
You can get this via running `/dominos version` in game

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.

```lua
2x Dominos/core/frame.lua:430: attempt to call method 'IsVisible' (a nil value)
[string "@Dominos/core/frame.lua"]:430: in function <Dominos/core/frame.lua:429>
[string "@Dominos/core/frame.lua"]:455: in function <Dominos/core/frame.lua:437>
[string "@Dominos/core/frame.lua"]:465: in function `IsFocus'
[string "@Dominos/core/fadeManager.lua"]:21: in function `Update'
[string "@Dominos/core/fadeManager.lua"]:43: in function <Dominos/core/fadeManager.lua:41>
```
Locals in attachment
[errorstack.txt](https://github.com/tullamods/Dominos/files/11026526/errorstack.txt)

**Comment by Road-block** [comment]
This happens on login/reload.

**Comment by Tuller** [comment]
This is now resolved
