### ISSUE TITLE
Menu Bar Opacity Fading Issue

### ISSUE THREAD

**Issue by fapmilk** [tullamods/Dominos#741]
I set my menu bar to 0% opacity and then have it fade back in to 100% upon mouseover. Since the 10.0.7 patch my menu bar has been bugging out and getting stuck at 0% opacity. Reloading fixes it temporarily.

**Addon Version**
10.0.21-retail

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
Have not replicated this one.
