### ISSUE TITLE
Dominos has been blocked from an action

### ISSUE THREAD

**Issue by Sythr4l** [tullamods/Dominos#744]
**Addon Version**
10.0.22-retail

I have a mount macro on my bars.  Occasionally the macro is blocked due to "Dominos has been blocked from an action only available tot he Blizzard UI."  The macro is as follows:

#showtooltip
/cast [advflyable] Cliffside Wylderdrake; [flyable] Cartel Master's Gearglider; Magmashell

This typically happens after finished a mythic+ and teleporting to Valdrakken. Reloading the UI resolves the issue.

**Comment by rukk1** [comment]
I get this constantly after a load screen, any time I push a macro it throws an error and I have to reload.

**Comment by Tuller** [comment]
Closing 701 related issues to cleanup my list
