### ISSUE TITLE
Problem with Blizzard glow abilities - much bigger than they should be

### ISSUE THREAD

**Issue by ned406** [tullamods/Dominos#749]
Happens with glow abilities like execute/victory rush/hammer of wrath etc. The "Useable" glow frame is huge and I can't get it to go away when it its active.

![image](https://user-images.githubusercontent.com/41378787/234700830-87e0f950-882d-442e-9153-e89fb1ae01a7.png)

This doesn't happen all the time and I'm not sure what causes it, or if its even dominos or masque.

**Comment by Tuller** [comment]
Can you doublecheck without masque enabled?

**Comment by Makyura3** [comment]
I can vouch that it's just Dominos. I don't use masque and have this happen to me also. Either using the spell to get rid of the glow or taking the button off the bar and putting it back fixes it.

**Comment by ned406** [comment]
It seems that other people are reporting the same issue, but it might just be with blizzard bars in general rather than dominos

**Comment by ned406** [comment]
It seems that the problem is with Dominos itself Tuller
