### ISSUE TITLE
Bag opening

### ISSUE THREAD

**Issue by colhanf** [tullamods/Dominos#750]
Addon Version : 10.1.0

World of Warcraft Version : Retail Dragonflight

I have a problem with opening the bags, they are over the side action bars even when trying to activate or not the different action bars in the options. I only use the two sidebars by default, nothing else.

No problem before 10.1.0, and I use the last release version. I tried to reset the interface, deleted the wtf folder, nothing works. No problem with just the Blizzard default UI.

Thanks for the help !

**Comment by symmetriq** [comment]
Same issue here. Until 10.1.0, if I had action bars 4 and 5 enabled in the Blizzard interface options, that would push all the right-edge frames over — open bags, quest tracker, arena and boss frames, and the default tooltip anchor. As of 10.1.0 that gap is now gone when Dominos is enabled, so bags cover up the right action bars, and all those other frames are underneath the action bars. If I disable Dominos, everything is back where it should be, but will reset back to the right edge (with no gap) once Dominos is re-enabled.

**Comment by AutolycusWolf** [comment]
Just wanted to say that this is still a bug as of the latest version. I don't want to sound impatient or anything and I'm grateful for having dominos, an action bar replacement I really can't do without, but this little thing is a bit annoying and wanted to know if it is being worked on or if there's nothing that can't be done about it. Adding a picture for reference.


![WoWScrnShot_071823_102353](https://github.com/tullamods/Dominos/assets/102288746/3c062ad4-9661-4cc5-a939-824b89f4fb60)

**Comment by Tuller** [comment]
This isn't likely fixable by me, at least not without causing the Blizzard action bars to appear in edit mode still.

**Comment by AutolycusWolf** [comment]
> This isn't likely fixable by me, at least not without causing the Blizzard action bars to appear in edit mode still.

I think the blizzard action bars appear when in edit mode already, or at least I think they do. Or do you mean in Dominos edit mode? Regardless this wasn't happening in older versions of Dominos and I'm guessing Blizzard messed up things again. Still if this can be fixed even with bars appearing in edit mode I reckon it is a minor inconvenience compared to having things the way they used to. 
Anyway, I'm posting some pictures for reference from my hunter alt if this can be of any help.

This is what I see with Dominos enabled and in Dominos edit mode:
![WoWScrnShot_072123_171151](https://github.com/tullamods/Dominos/assets/102288746/7735ec70-745c-42b6-ac66-5457923c7701)

This is what I see with Dominos enabled and in Blizzard edit mode:
![WoWScrnShot_072123_171230](https://github.com/tullamods/Dominos/assets/102288746/ae3813ea-6be9-4331-b61d-c83922786442)

This is what I see with Dominos disabled and in Blizzard edit mode:
![WoWScrnShot_072123_171345](https://github.com/tullamods/Dominos/assets/102288746/2b6a0ae6-7ea4-4908-8995-bfb376859346)
