### ISSUE TITLE
Feature Request: use blizzard cast bar & experience bars

### ISSUE THREAD

**Issue by Rezy942** [tullamods/Dominos#751]
Hello,

Thank you SO much for maintaining this amazing addon that ive been using for years!!!
I've always had a bit of annoyance though:

1. I want to be able to use blizzard cast bar. I just dont enjoy the looks of dominos cast bar, especially now.
**Is that possible without deleting game folders or manually turning off Dominos Cast?**
The reason I want to avoid that is because i frequently use "turn on all addons" as i toggle many addons at once. So i just make sure ALL of them are always on (as im sure many others are).

2. Same thing for dominos experience bars:
Can we have option to use blizard default exp bar now that it's in a convenient location and somewhat matches Dominos look? :)

Hope you will consider this ... thank you so much!! :)

**Comment by von-get** [comment]
In the meant time, I recommend using something like Addon Control Panel, or Simple Addon Manager.  Both allow you to save addon configurations, so instead of enable all, you could load a preset that has both of those disabled.

**Comment by Rezy942** [comment]
> In the meant time, I recommend using something like Addon Control Panel, or Simple Addon Manager. Both allow you to save addon configurations, so instead of enable all, you could load a preset that has both of those disabled.

Thank you but I just opt into not using the addon all together if i have to micro-manage my addons on top of everything else. I ended up deleting dominos, but keep checking if this feature is added. I know it was asked many times over the years, hoping author can consider eventually. It should be a very simple thing to do.. basically a module toggle. But only author knows best.

**Comment by Tuller** [comment]
This is the intended way to disable modules on a per Dominos profile basis:
`/run Dominos.db.profile.modules.CastBar = false`
`/run Dominos.db.profile.modules.MirrorTimer = false`
`/run Dominos.db.profile.modules.ProgressBars = false`

**Comment by Rezy942** [comment]
> This is the intended way to disable modules on a per Dominos profile basis: `/run Dominos.db.profile.modules.CastBar = false` `/run Dominos.db.profile.modules.MirrorTimer = false` `/run Dominos.db.profile.modules.ProgressBars = false`

Thanks for the reply! Do these commands persist when logging on an alt? Or is this basically same as disabling the addon via addons menu?
A lot of the times I want to disable ALL my addons to see what is causing issues. Then I re-enable everything later. Having to manually go back and disable modules via addons menu would suck, which is why I dont use it.

Any chance to add these commands as a toggle in the addon options menu?
Disabling the module would disable it for the profile entirely - not just "manually" disabled in addons list, which is a bad way of doing it imo.

Hope it makes sense
Thanks

**Comment by Tuller** [comment]
Those commands set settings within your Dominos profile. This just tells Dominos "don't call the Load function for these".  Disabling the modules within the addons menu is still preferable, as none of the code form them will be loaded.

As [von-get](https://github.com/von-get) mentioned, using something like Addon Control panel is something that may be better for your specific use case. You can define sets of addons to turn on/off.

**Comment by Rezy942** [comment]
> Those commands set settings within your Dominos profile. This just tells Dominos "don't call the Load function for these". Disabling the modules within the addons menu is still preferable, as none of the code form them will be loaded.
> 
> As [von-get](https://github.com/von-get) mentioned, using something like Addon Control panel is something that may be better for your specific use case. You can define sets of addons to turn on/off.

I see, thanks.  :) Also i tend to install and delete addons regularly, and move between 2 different computers. I try my best to get away from micro-management addons like these that rely on tinkering with profiles, so i wont be using it. Its just too much work to keep track of.
