### ISSUE TITLE
Duplicated actionbars (actionbar 1 & 7 are the same)

### ISSUE THREAD

**Issue by simsekb** [tullamods/Dominos#753]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

Nothing else than just having the actionbars filled with spells & macros.

**Addon Version**
You can get this via running `/dominos version` in game

10.0.22-classic

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.

Classic

**Comment by Tuller** [comment]
This is a feature, not a bug :) In the case of warriors, by default, your main action bar is displaying the actions from bar 7 (and will switch to others when you switch to other stances). This mirrors the behavior of the default UI. To work around this, you can edit the paging settings for the bar by right clicking it in configuration mode.
