### ISSUE TITLE
Dominos causes huge freeze when another wow account on same b.net account logs in

### ISSUE THREAD

**Issue by Neischa** [tullamods/Dominos#754]
Hey, I recently returned to wow and found out when I have Dominos addon installed and enabled whenever I log into my second account while I am already online on my first account (2 wow accounts, 1 b.net account) my first wow account freezes for like half minute and when I accidentally click on anything when its frozen wow completely crash.
This "issue" exists for very long time, many years, but until now it froze for like 1 second only.
To make sure it is caused by Dominos I deleted my addons and wtf folder, then tested it - no issue, no freeze at all. Then I installed Dominos only, didnt set it up at all, just tested it and it froze for almost 30 seconds. Its definitely caused by Dominos, but there is no error reported (I have errors on).
Also it negatively affects performance, fps is noticably lower when Dominos is installed and in combat.

I was on latest stable Dominos version and on retail.

I know I didn't provide much so if you have any idea let me know, happy to help!

Thanks in advance for checking!

**Comment by Fetu56** [comment]
Encountered same issue at retail with last build of Dominos

**Comment by Neischa** [comment]
Still an issue, almost 30s freeze when character on second wow account on same b.net account enters world. Please fix it, this is a blocker:(
