### ISSUE TITLE
Action Bar 2 does not respect ActionButtonUseKeyDown CVar

### ISSUE THREAD

**Issue by domi1294** [tullamods/Dominos#755]
As the title says, all action bars except action bar 2 change their behavior when I change the CVar via Advance Interface Options. I tried it with only Dominos enabled and the issue persists.
Something I noticed while testing is when I disable Dominos I lose my action bar 2, so the default UI's action bar 2 is different from Dominos' action bar 2 for some reason, maybe that's somehow related to the issue?

**Addon Version**
10.1.0-retail

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
This should be fixed in the latest beta version (10.2.5)
