### ISSUE TITLE
[Bug] Disconnect (or very big lag) when logged in with the second account

### ISSUE THREAD

**Issue by ai-shibo** [tullamods/Dominos#773]
I had Dominos + Dominos_Config running only.
The verion is 10.1.3-retail.

I logged in with the 1st account. Then I loggen in with the 2nd account. This way the 1st character is lagged. If I Alt+Tab to the 1st client it may unlagged (or may not). If I stay focused on the 2nd account then the 1st one is 100% kicked offline. This started to happen since about 10.1.0 Game Patch (Retail).

Fix it please. Ty.

**Comment by Tuller** [comment]
Multiboxing isn't something I test for.

**Comment by ai-shibo** [comment]
Sad news. But thank you for your attention and supporting anyway!
