### ISSUE TITLE
When playing as a rogue/druid, if caught by a mob at the same moment stealth is pressed.: action bars stuck in stealth paging even in combat.

### ISSUE THREAD

**Issue by Superpositionals** [tullamods/Dominos#775]
If I press "stealth" at the exact moment a mob notices me, I am of course pulled out of stealth immediately from the mob attacking and yet my action bars are stuck in the action bar page that is my stealth set. In hardcore this is especially frustrating as I cannot attack aside from auto attack unless I manually go into my spellbook and find an attack ability. How to fix it is simple, either a /reload or simply killing the mob then going back into stealth, where it resets. 

**Addon Version**
10.1.3-classic

**World of Warcraft Version**
Classic Hardcore

**Comment by Tuller** [comment]
I extremely vaguely recall this one being something tied to the actual game code for classic.

**Comment by Superpositionals** [comment]
Hmm, well it has only happened with this specific version of classic dominos for me, and never before on anything else- for what it's worth. I switched addons and the problem went away.

**Comment by Tuller** [comment]
Is this happening for you?

**Comment by Tuller** [comment]
Closing as I’ve not reproduced it

**Comment by Superpositionals** [comment]
I'm not sure if it still does this, as I switched to Bartender and no longer experience the issue.
