### ISSUE TITLE
Dominos Causing Long Load Times & Blizzard Voice Chat Errors

### ISSUE THREAD

**Issue by inabohx** [tullamods/Dominos#776]
This took a while to track down to Dominos, but for most of Dragonflight I've been experiencing large hangtimes on full blue bar loading from the character screen. Upon getting logged in, the chat window has this error:

"Can't connect to a voice chat server right now. Please try again. (VoiceError: 16)"

Some notes from my own investigating:

- It only happens if loading in from the character screen. If I log in without Dominos enabled, and enable it in-game, the reload happens just fine.
- Once I finally get logged in and deal with the large hang time, the game and addon run fine.
- I've gone so far as to disable voice communications on my blizzard account via parental controls, but that didn't help.
- I've reproduced this with no addon but Dominos running.

No idea how an action bar mod is interacting with in-game voice chat, but here we are! Best of luck... just wanted to get my issue documented somewhere.

**Addon Version**
10.1.4-retail

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
For long loading times, can you make sure something like BugSack and BugGrabber are installed? I suspect you're getting lua errors when loading.

**Comment by inabohx** [comment]
Ahh yeah I didn't think to check those -- unfortunately my login test with just those 2 + Dominos enabled didn't seem to provide anything. It really does baffle me... I don't even want voice chat enabled, so I'm not sure why it tries to connect to it anywhere and only with Dominos on.

**Comment by inabohx** [comment]
Hmm that or the other way around? It always connects and Dominos prevents it somehow?  Either way still weird :(

**Comment by ChrisDev-io** [comment]
I ran into the same issues. I was running BugGrabber and BugSack, no LUA errors were caught on login or during gameplay. The delay in logging in is upwards of 30+ seconds compared to turning off Dominos. If there are any kind of logs or system information I can provide, I'm more than happy to help provide what data I can to figure out the cause of this issue.

When I found out it was Dominos causing my slow logins, I disabled all addons and started turning them on in batches and 1 at a time. It appears that Dominos would cause the slow login regardless of what other addons were on, but happy to test that theory further for confirmation.

**Comment by arkayenro** [comment]
seeing the same 30s load times, 8 of which are normal.
buggrabber and backsack showed nothing

used the taintlog to see what it was doing and it looks like the libs load in the first second, theres a 5 second gap, then the domains action buttons get created in the next second, then theres a 25ish second gap of nothing

the 25 seconds includes me manually typing in /dom (it triggers taint so can be used to see roughly when i was loaded in) and then logging out.

its a little bit more data but doesnt appear to be overly helpful

**Comment by arkayenro** [comment]
its this line 342 in ...\Dominos\bars\menuBar.lua

`hooksecurefunc("UpdateMicroButtons", layout)`

if you comment it out theres no delay - not sure why yet

**Comment by Tuller** [comment]
Try with 10.2.1 as I debounced that particular call.
