### ISSUE TITLE
[Classic Era] Keybinding in profiles not working since patch 1.14.4

### ISSUE THREAD

**Issue by Mcaruano** [tullamods/Dominos#781]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.**
Confirmed. Tested this on a character with absolutely no other addons loaded apart from Dominos and Dominos_Config

**Addon Version**
10.1.5-classic (but have seen this issue since the "big" Classic Era patch 1.14.4 on August 22 that introduced the new Era ranking system and broke all addons)

**World of Warcraft Version**
Classic Era

**Description of Problem**
Since the "big" Classic Era 1.14.4 patch on August 22, Keybinds in Dominos has been severely misbehaving on the Era client. I knew something was wrong after the patch because when I logged in (after updating Dominos) I saw that my keybindings for **Action Bar 1 and Action Bar 2** were reset to defaults on all of my characters while the remainder of my keybindings on all of the other Action Bars were unchanged (i.e. set to what I had them set as prior to the patch). I'll break up this description into two separate issues for clarity, however I suspect that the underlying bug is likely the same across both.

**First Issue**
The specific issue I'm reporting here is that keybinds are not being properly saved to individual profiles; any changes you make to keybinds on one profile affect all other profiles.

Steps to Repro:
1. Create a character on Classic Era and load only the Dominos and Dominos_Config addons from the 10.1.5-classic release of Dominos (or any release version since August 22)
2. Create a new Profile called "TestA" and open Keybindings. Make sure the "Character Specific Key Bindings" box is unchecked and change some keybindings. Click "Okay" to confirm the changes.
3. Create a new Profile called "TestB", and open Keybindings. Make sure the "Character Specific Key Bindings" box is unchecked and change some keybindings of the same keys. Click "Okay" to confirm the changes.
4. Swap profiles back to "TestA", and observe the Dominos chatlog confirm 'Dominos: Set profile to "TestA"'
5. Take a look at your bars, notice that the keybindings in "TestA" are now mapped to whatever you had set in profile "TestB"

Essentially, any Profile you attempt to make will keep UI elements stored independently as expected, but will share keybinding state globally.

**Second Issue**
The other issue observed is current character keybinds for Action Bar 1 and Action Bar 2 being reset to game default randomly upon logging in (just as they did when patch 1.14.4 first hit).

I use Profiles **a lot** in my various addons, so once I learned of this misbehavior I decided to distance myself from Dominos Profiles until a fix is put in place. What I did was I created a singular standard template profile that matches *most* of my keybinds across my various characters called "Standard Setup" and I went through my characters and moved some spells around to adhere to this new universal template. I figured even with the bug descripted in the First Issue above, as long as I stick to just a single template I should be safe. I went through all of my characters and made sure everything was setup properly, and all appeared to be well. Then when I logged into raid last night on one of my characters I noticed my Action Bar 1 and Action Bar 2 were yet again set to default.

I opened Dominos keybindings and "Character Specific Key Bindings" was unchecked, as I expected it to be. I checked it and unchecked it and that resolved the issue, setting my keybindings up to match the "Standard Setup" profile once more. This was still extremely worrisome as it was completely unexpected, and I only discovered it right before we were about to pull.

Unfortunately I can't reproduce this one myself, so I can't offer any steps. I'm just adding this information to this issue report in the hopes that it aids in the triaging of the underlying bug.

It's important to note that it is only Keybinds that are being affected in this way. If you move or modify UI elements, those do get properly saved uniquely per each profile.

**Comment by Mcaruano** [comment]
This issue has been persistent for 2 months, so apologies for not reporting it sooner. I fell for the "bystander syndrome" trap by assuming someone else had already and so I never put forth the effort.

**Comment by Tuller** [comment]
Key bindings aren’t actually associated with a Dominos profile, which may be the issue here.

**Comment by Mcaruano** [comment]
Oh really? I swear I've used this feature for a long long time to set up keybindings in a profile such that I could rapidly setup new characters and it was as simple as selecting the profile from the drop-down to get both my UI and keybindings online. Maybe I'm just grossly misremembering something? I believe my action bars 1 and 2 being reset to default when first updating after the 1.14.4 patch and on random occasion since then has to do with Dominos though as I do not have any other UI addons that muck with keybindings.
