### ISSUE TITLE
Blizzard mirror timer not overridden (retail) in version 10.2.0

### ISSUE THREAD

**Issue by TallerAndBlueOnline** [tullamods/Dominos#786]
**Addon Version**
10.2.0

**World of Warcraft Version**
Retail

Basically what it says on the label: the Blizzard mirror timer (or at least the breath bar) is not overridden, and I can't seem to find any way to change that. I'm sure it'll turn out that I'm making a silly error somewhere; even so.  Thanks in advance.

**Comment by Tuller** [comment]
This should be fixed with 10.2.1
