### ISSUE TITLE
Pet Bar covers Flyout menu

### ISSUE THREAD

**Issue by Makyura3** [tullamods/Dominos#789]
Got a new computer, set up my bars on my characters and I notice this happen on my hunter.

![WoWScrnShot_011124_011343](https://github.com/tullamods/Dominos/assets/121463525/ea80b6ed-5f9a-494d-accd-cc9181793a20)

This is with Dominos 10.2.1 and on retail WoW.

Is there something I need to do to stop this?

**Comment by Tuller** [comment]
Try setting the Pet Bar's frame strata to Low.

**Comment by Makyura3** [comment]
> Try setting the Pet Bar's frame strata to Low.

Awesome. That worked. Thanks.
