### ISSUE TITLE
10.2.5-beta1 broke button text

### ISSUE THREAD

**Issue by hollo6** [tullamods/Dominos#790]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.**
Reproduced with everything else disabed.

**Addon Version**
10.2.5-beta1 and 10.2.0-retail

**World of Warcraft Version**
Retail

I have updated to 10.2.5-beta1 and realized that all the button text got HUGE and not wrapped anymore so everything was out of place and could not find any way to revert that so I decided to roll back to 10.2.5 (restored the WTF file from backup as well).
Now the binding text (but not the macro names) is missing from half my bars.
I did not do anything else that might have caused this and now I can't find a way to get them back.

**Comment by Tuller** [comment]
Do you have a screenshot?

**Comment by hollo6** [comment]
before:
![image](https://github.com/tullamods/Dominos/assets/365584/bb5a45e1-13ff-4912-9d11-0684e2fdd1ac)
after:
![image](https://github.com/tullamods/Dominos/assets/365584/761df4fe-d04c-4939-80e7-4d69d0bea3ad)

So far I have seen this on 1 character and it affect action bars 2 and 10.

**Comment by hollo6** [comment]
So it seems beta modified the bindings-cache.wtf file.
After restoring that one from my backup, it seems to be fine again.
But it was only partially broken and makes me wonder what else I will find missing or broken at the most inconvenient times. :/

Also, since this topic is already open, is there a way to get the old font size and wrapped macro text (so it won't cover 3 buttons) back?

**Comment by Tuller** [comment]
I’ll revisit the new button template. I tend to run with macro text off, which is a reason I missed it.

**Comment by Tuller** [comment]
beta2 should resolve the text issue.

**Comment by hollo6** [comment]
Indeed it looks good now, thank you!
