### ISSUE TITLE
beta2 switched action bar bindings

### ISSUE THREAD

**Issue by hollo6** [tullamods/Dominos#791]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.**
Reproduced with everything else disabled.

**Addon Version**
10.2.5-beta2

**World of Warcraft Version**
Retail

Beta2 switched the bindings of action bars 11 and 12.
10.2.0:
![image](https://github.com/tullamods/Dominos/assets/365584/d32dee98-a80d-4716-bf67-5dba496a322d)
10.2.5-beta2:
![image](https://github.com/tullamods/Dominos/assets/365584/2ce601ee-63f4-402e-a039-6b9bd18bd509)

Rolling back to 10.2.0 fixes it with nothing else changed (except restoring the bindings-cache.wtf that beta versions tend to break).

**Comment by Tuller** [comment]
This should be resolved in the 10.2.5-beta4 release.

**Comment by hollo6** [comment]
Thanks! I will test it as soon as the button glow solution is in.

**Comment by hollo6** [comment]
Tested with Beta5, this appears to be fixed. Thanks!
