### ISSUE TITLE
beta breaks all button animation revert solutions

### ISSUE THREAD

**Issue by hollo6** [tullamods/Dominos#792]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.**
Reproduced with everything else disabled.

**Addon Version**
10.2.5-beta2

**World of Warcraft Version**
Retail

Cannot find anything now to hide or alter the hideous 10.1.5 button animations. Tried:
[HideActionBarAnimations](https://legacy.curseforge.com/wow/addons/hideactionbaranimations) - this is what I was using until now
[RemoveActionAnimations](https://github.com/Tuller/RemoveActionAnimations)
[HideButtonGlow](https://github.com/dekallo/HideButtonGlow)
[DisableActionButtonSpellCastEffects WA](https://wago.io/vToRxC78V)

Reverting back to 10.2.0 would fix this but with that version, it is no longer possible to add anything into the action bars so it's a deadlock.

**Comment by Tuller** [comment]
The beta shouldn’t have any of the spell cast animations. Are there particular ones that you’re seeing?

**Comment by hollo6** [comment]
Every single one of them.

**Comment by hollo6** [comment]
For example:
![image](https://github.com/tullamods/Dominos/assets/365584/34b7c0d1-b7a4-4a41-b540-7eb5a060bd64)

**Comment by mbattersby** [comment]
I have a somewhat related request, as I am also integrating with Dominos in an addon I author (LiteButtonAuras) and need to be able to iterate the action bar buttons and hook when a new button is created.

With the previous release it seems all the buttons were pre-created before `LAYOUT_LOADED` fired so my integration looked like this:
```lua
local function DominosInitCallback()
    for _, actionButton in pairs(Dominos.ActionButtons) do
       GenericInitButton(actionButton)
    end
end

function LBA.BarIntegrations:DominosInit()
    if Dominos then
        Dominos.RegisterCallback(self, 'LAYOUT_LOADED', DominosInitCallback)
    end
end
```

I'll admit I didn't test it much (I'm not a Dominos user) but it seemed to work and nobody complained.

With the beta version `LAYOUT_LOADED` seems to be fired the first time before I can register it, and buttons can be dynamically made.

This is my best attempt at peeking at the internals and creating a new integration. Do you have a better suggestion? This is not at all urgent, obviously you are very busy trying to get all this over the line.

```lua
function LBA.BarIntegrations:DominosInit()
    if Dominos then
        for actionButton in pairs(Dominos.ActionButtons.buttons) do
            GenericInitButton(actionButton)
        end
        hooksecurefunc(Dominos.ActionBar, 'OnAttachButton', function (bar, button) GenericInitButton(button) end)
    end
end
```

**Comment by Tuller** [comment]
This should work:

```lua
hooksecurefunc(Dominos.ActionButton, "OnCreate", function(button, id)
    -- do stuff
end)
```

**Comment by mbattersby** [comment]
It this a reasonable way to iterate the existing buttons?
```
        for actionButton in pairs(Dominos.ActionButtons.buttons) do
            GenericInitButton(actionButton)
        end
```

**Comment by Tuller** [comment]
That’s probably the easiest for the moment. I’ll add a GetAll

**Comment by Tuller** [comment]
Over the weekend I'll be implementing options to hide the glow, and revert the loss of control cooldown behavior to earlier versions.

**Comment by Tuller** [comment]
Beta5 implements an option to disable the spell activation glows, and should use an older behavior for loss of control cooldowns.

**Comment by hollo6** [comment]
I have tested this version and it removes the glows entirely, but I still need to see them, just not in the supernova format.
Would it be possible to have an option to use the old ones or let other addons do it?

**Comment by Tuller** [comment]
I’ve dimmed the glow and dropped the initial flash

**Comment by hollo6** [comment]
This looks better, although it was too dim for me but looked ok after increasing the alpha manually in SetVertexColor. Any chance this could be a setting?
I also miss the proc flash, it should still be a bit more evident when the proc happens.

**Comment by hollo6** [comment]
Does this mean we were not going to get a solution for this?

**Comment by Tuller** [comment]
I’ve kept the completely turn off option but I reverted the dimimg of the flash after you and a few others noted it was too hard to see

**Comment by hollo6** [comment]
How about adding the (old) proc flash? It's still very needed.
