### ISSUE TITLE
Retail 10.2.5 breaks dragging to empty button

### ISSUE THREAD

**Issue by Jahfry** [tullamods/Dominos#793]
**Addon Version**
10.2.1-retail (latest available on CurseForge)

**World of Warcraft Version**
Retail 10.2.5

**Issue**

When a bar has "Show Empty Buttons" checked ON all dragging works as expected. 

When "Show Empty Buttons" is off, dragging to an empty button slot no longer works. 

Turning on "Show Empty Buttons" globally allows dragging. Turning on per bar works to fix individual bars. 

Behavior changed in 10.2.5. 

PS. Note that this is after manually disabling all other addons and doing a reload to make sure there was no cross-contamination of the test.

**Comment by Tuller** [comment]
To resolve this for the moment with the 10.2.1 version 
1. Disable Dominos
2. Open edit mode
3. Right click the main action bar.
4. Uncheck always show buttons
5. Save your settings 
6. Enable dominos
7. Reload your UI

**Comment by Jahfry** [comment]
> To resolve this for the moment with the 10.2.1 version

Confirmed workaround, thanks :)
