### ISSUE TITLE
Does not show layers

### ISSUE THREAD

**Issue by nanjuekaien1** [tullamods/Dominos#799]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** 
Found out when using Dominos
Demon Hunter's vengeance talent Spirit Bomb does not show the number of Soul Fragments.
As you can see in the screenshot, it is displayed on Blizzard's original action bar.
marked by the red box
![炸弹](https://github.com/tullamods/Dominos/assets/2303601/b9a4033d-5348-4b1f-b4ea-f16197869896)

**Addon Version**
Dominos-10.2.5-beta4

**World of Warcraft Version**
 Retail

**Comment by Tuller** [comment]
Check beta5 when you can.

**Comment by nanjuekaien1** [comment]
Fixed.
Thank you

**Comment by nanjuekaien1** [comment]
Dominos-10.2.6
Potions, Enhancement Runes and Sharpening Stones quality levels are not shown. (Red boxes are original action bars; yellow boxes are Dominos)
Red boxes are original action bars
![原版](https://github.com/tullamods/Dominos/assets/2303601/591b37cc-514e-4bb6-b3db-3f3b0bcd75f3)
yellow boxes are Dominos

![Dominos-10 2 6](https://github.com/tullamods/Dominos/assets/2303601/6b7cf99c-27df-4da3-9c83-836e0ade6400)

**Comment by nanjuekaien1** [comment]
tullamods Can you add an option to enable or disable it?

**Comment by Tuller** [comment]
Yes, it’ll be an easy update
