### ISSUE TITLE
Extra Ability Disappearing

### ISSUE THREAD

**Issue by SajuukCor** [tullamods/Dominos#800]
The Extra Ability buttons are disappearing during combat. For example the Covenant abilities in Shadowlands.

5x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'ExtraAbilityContainer:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPointBase'
[string "@Dominos/bars/extraAbilityBar.lua"]:78: in function `RepositionExtraAbilityContainer'
[string "@Dominos/bars/extraAbilityBar.lua"]:179: in function `RepositionExtraAbilityContainer'
[string "@Dominos/bars/extraAbilityBar.lua"]:169: in function <Dominos/bars/extraAbilityBar.lua:168>
[string "=[C]"]: in function `ApplySystemAnchor'
[string "@FrameXML/EditModeSystemTemplates.lua"]:339: in function `UpdateSystem'
[string "@FrameXML/EditModeManager.lua"]:1185: in function `UpdateSystem'
[string "@FrameXML/EditModeManager.lua"]:1173: in function <FrameXML/EditModeManager.lua:1172>
[string "=[C]"]: in function `secureexecuterange'
[string "@FrameXML/EditModeManager.lua"]:1175: in function `UpdateSystems'
[string "@FrameXML/EditModeManager.lua"]:964: in function `UpdateLayoutInfo'
[string "@FrameXML/EditModeManager.lua"]:258: in function <FrameXML/EditModeManager.lua:250>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Addon Version**
10.2.5-beta4

**World of Warcraft Version**
10.2.5 Retail

**Comment by Tuller** [comment]
I've added a combat check to prevent this error in beta5

**Comment by hayatofujii** [comment]
Careful: with
```
Dump: value=Dominos.db.profile.modules.ExtraAbilityBar
[1]=false
```
[Alchemical Fire](https://www.wowhead.com/spell=266198/alchemical-fire) on Gorak Tul's fight doesn't show up
