### ISSUE TITLE
Taint issue with 10.2.7 in retail

### ISSUE THREAD

**Issue by Gaviin1242** [tullamods/Dominos#807]
I posted a comment about this on the curseforge comments, and you asked for a taint.log to see what's going on.  Attached is what was produced during a half hour m+ rise run.  I had to break it into two files to allow to upload.

It didn't get to the point of actually preventing me from using my action bars (which did happen the other day), but a few errors were thrown in BugSack.

[taint.log](https://github.com/tullamods/Dominos/files/14018105/taint.log)
[taint-2.log](https://github.com/tullamods/Dominos/files/14018108/taint-2.log)

**Comment by Tuller** [comment]
I've made one minor change which might minimize this a bit.
Does this happen when you're running just Dominos?

**Comment by Gaviin1242** [comment]
I haven't tried running just Dominos.  I wouldn't know what to do without my other addons.  :)  But I can say for sure this issue never occurred before v10.2.5.  I reverted back to 10.2.1 and have been without any errors since then.  Assuming 10.2.9 is the one with the change you mentioned, I can try that and see what happens.

Appreciate the help!

**Comment by Gaviin1242** [comment]
I updated to 10.2.9, and sadly still getting the same taint errors occasionally.  :(  Thanks for trying though.

**Comment by EmElw** [comment]
Had only dominos running and still got the same sort of taint. Provided taint.log .

[dominos only taint.log](https://github.com/tullamods/Dominos/files/14108739/dominos.only.taint.log)

I'm using paging actionbars for dragonriding.
