### ISSUE TITLE
Calling protected function

### ISSUE THREAD

**Issue by Caza4** [tullamods/Dominos#808]
This happens every session the first time I press something.

5x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'ActionButton8:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function `Update'
[string "@FrameXML/ActionButton.lua"]:503: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:981: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:207: in function <FrameXML/ActionButton.lua:204>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Addon Version**
10.2.7-retail

**World of Warcraft Version**
Retail
![WoWScrnShot_012324_124312](https://github.com/tullamods/Dominos/assets/43317711/5a6a0d9e-3468-409c-89d2-25f9f3caff17)

**Comment by calummitchell** [comment]
Also been getting a few of these recently.

1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'ActionButton6:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function `Update'
[string "@FrameXML/ActionButton.lua"]:503: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:981: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:207: in function <FrameXML/ActionButton.lua:204>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
 
 
 
 
 1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'MultiBarRightButton1:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetShown'
[string "@FrameXML/ActionBar.lua"]:195: in function `UpdateShownButtons'
[string "@FrameXML/ActionButton.lua"]:507: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:981: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:207: in function <FrameXML/ActionButton.lua:204>

Locals:
Skipped (In Encounter)




1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'ActionButton9:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function `Update'
[string "@FrameXML/ActionButton.lua"]:503: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:981: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:207: in function <FrameXML/ActionButton.lua:204>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by calummitchell** [comment]
Got this error again last evening while I was recording my gameplay. The error is the same as before and happened when I pressed Shadow Dance which changes my stance, so might be related to paging. My Shadow Dance button is on Action Bar 1 and my paging settings for Action Bar 1 is Shadow Dance Action Bar 1 i.e. don't change which action bar is shown when I Shadow Dance.

My Shadow Dance button is also a macro which only casts Shadow Dance the second time I press it. So I didn't get an error the first time I pressed the key, but did the second time.

#show
/castsequence reset=15 Shiv, Shadow Dance, Shiv
/use 13
/cast Kingsbane


1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'ActionButton6:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function Update'
[string "@FrameXML/ActionButton.lua"]:503: in function UpdateAction'
[string "@FrameXML/ActionButton.lua"]:981: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:207: in function <FrameXML/ActionButton.lua:204>

**Comment by calummitchell** [comment]
This appears to be reproducable on my Assassination Rogue just doing the regular opener. Although the error doesn't always occur at exactly the same place. I recorded a taint.log file of one example.
[taint.log](https://github.com/tullamods/Dominos/files/14101166/taint.log)

**Comment by calummitchell** [comment]
If there's any testing you want me to do just ask.

**Comment by calummitchell** [comment]
I disabled all addons except Dominos and reproduced this problem with taintLog "2".
[taint.log](https://github.com/tullamods/Dominos/files/14101742/taint.log)

**Comment by calummitchell** [comment]
After a little more testing. This issue reproduces 100% of the time with version 10.2.11 by doing the standard Assassination Rogue opener https://www.wowhead.com/guide/classes/rogue/assassination/rotation-cooldowns-pve-dps which involves two stance changes (Shadow Dance and Vanish). 10.2.10 doesn't have this problem.

So something in https://github.com/tullamods/Dominos/compare/10.2.10...10.2.11 doesn't play nice with stance changes.

**Comment by calummitchell** [comment]
Just finished a dungeon playing outlaw rogue using 10.2.10 and did trigger the same lua error but it didn't popup an error dialog and didn't prevent me pressing any keys, which is what was happening with 10.2.11 on Assassination rogue.

1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'ActionButton11:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function `Update'
[string "@FrameXML/ActionButton.lua"]:1068: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:302: in function <FrameXML/ActionButton.lua:279>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by calummitchell** [comment]
No errors with 12.1.3 during 3 hour raid.
