### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by itsSinba** [tullamods/Dominos#810]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.**
Error (400+) on login, on 2 characters only (Monk and Evoker). It happens on any existing or new profile on those characters. Also disabled all mods except dominos.

> 408x Dominos/bars/actionBar/button.lua:265: invalid option in `format'
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@FrameXML/RestrictedFrames.lua"]:674: in function <FrameXML/RestrictedFrames.lua:673>
[string "@FrameXML/RestrictedFrames.lua"]:812: in function `CallMethod'
[string "        if name == "action" then
            self:RunAttribute("UpdateShown")
            self:CallMethod("OnActionChanged", value)
        end
    "]:3: in function <[string "        if name == "action" then..."]:1>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@FrameXML/RestrictedExecution.lua"]:484: in function <FrameXML/RestrictedExecution.lua:447>
[string "=(tail call)"]: ?
[string "@FrameXML/SecureHandlers.lua"]:128: in function <FrameXML/SecureHandlers.lua:121>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
...
[string "@FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:781: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

**Addon Version**
10.2.7-retail

**World of Warcraft Version**
10.2.5.53040

**Comment by itsSinba** [comment]
Update: I found the issue by looking at line 265 in button.lua. I have a consumable in my bars that I have more than 999 of (1493 to be exact) that is causing this error. Removing it from the action bar and reloading gives no more errors.

**Comment by Tuller** [comment]
Yes, this was a typo in my end
