### ISSUE TITLE
Error on version :  10.2.8 - retail  : Paging - Dragonriding

### ISSUE THREAD

**Issue by Sanchopelota** [tullamods/Dominos#811]
Getting this error when clicking on the combo for Dragonriding on setup/paging : 

21x ..._Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1512: attempt to index field 'NewFeature' (a nil value)
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1512: in function `UIDropDownMenu_Refresh'
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1580: in function `UIDropDownMenu_SetSelectedValue'
[string "@Dominos_Config/widgets/dropdown.lua"]:83: in function `ShowMenu'
[string "@Dominos_Config/widgets/dropdown.lua"]:42: in function `initFunction'
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:771: in function `UIDropDownMenu_Initialize'
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1781: in function `ToggleDropDownMenu'
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:686: in function <..._Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:683>

Locals:
self = <table> {
 UIDropDownMenu_SetButtonText = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2085

**Comment by Tuller** [comment]
I've updated the library again, which should resolve this one.
