### ISSUE TITLE
10.2.9 broke button text

### ISSUE THREAD

**Issue by hollo6** [tullamods/Dominos#812]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.**
Reproduced with everything else disabled.

**Addon Version**
10.2.9

**World of Warcraft Version**
Retail

Looks the same as in [beta1](https://github.com/tullamods/Dominos/issues/790) but this time it happened after upgrading to 10.2.9 and none of the bindings-cache.wtf files were modified so there is no way to restore them either.
The bindings are still working but they are not being shown on action bars 2, 8, 10 and 12.

**Comment by Tuller** [comment]
What version did you upgrade from?

**Comment by hollo6** [comment]
10.2.1

**Comment by hollo6** [comment]
I just realized I might not have worded this clearly enough.
The binding text is now missing while using the new version.
Still exists in 10.2.9.

**Comment by Tuller** [comment]
I've not yet replicated this one.

**Comment by hollo6** [comment]
Anythig I can do to help tracking the issue down? I can reproduce it any time by updating to 10.2.9 or 10.2.10 and doing absolutely nothing else.

**Comment by Tuller** [comment]
Are you seeing it with only Dominos + Dominos_Config enabled?

**Comment by hollo6** [comment]
Yes.

**Comment by hollo6** [comment]
Not sure how relevant this is, but it looks exactly the same as the previous issue, but then it happened after rolling back from a beta version to 10.2.1 and I could fix it by restoring the bindings-cache.wtf that beta versions altered during update.
But these versions (10.2.9 and 10.2.10) don't alter that file at all.

**Comment by Tuller** [comment]
What are your bindings in those cases?

**Comment by hollo6** [comment]
bar 2: F5, F10, D0, SF3
bar 8: S2, S1, S4, S3
bar 10: AWD, AWU, SB5, B5, SE, E, WU, AF1, AF2, SF1
bar 12: A` A1

Unaffected bars have totally similar bindings and combinations so I'm pretty sure that the actual bindings don't matter.

**Comment by Tuller** [comment]
Were you binding directly to the buttons? That is DominosActionButton<Number>?

**Comment by hollo6** [comment]
Might be onto something there.
bind UP MULTIACTIONBAR1BUTTON4 - OK
bind DOWN CLICK DominosActionButton16:LeftButton - NOK

But I haven't changed my bindings in a decade.

**Comment by Tuller** [comment]
That may be the issue here. Dominos bindings should use `:HOTKEY` instead of `:LeftButton`. Both can work, but only HOTKEY really supports cast on keypress

**Comment by hollo6** [comment]
But the bindings work, they are just not being shown on the buttons.

**Comment by Tuller** [comment]
Yes, that makes sense, because I only display the binding associated with the HOTKEY entry. If you run `/run Dominos.db.global.bindingsVersion = nil; ReloadUI()` then the migration code for global bindings should be run again.

**Comment by hollo6** [comment]
Right, this did the trick.
So the problem here is that this code is not being run in 10.2.9 and 10.2.10. I'm not sure about versions between beta4 and 10.2.8 because those had bigger issues so I haven't checked if bindings-cache.wtf changed, but it did definitely run in beta versions.

**Comment by Tuller** [comment]
10.2.5 is when I bumped the bindings version number. You reverted your bindings to a prior version, if I recall.

**Comment by hollo6** [comment]
Yes, I kept rolling back to 10.2.1.
