### ISSUE TITLE
Action button block after mounting 

### ISSUE THREAD

**Issue by Vebren** [tullamods/Dominos#815]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

Tested with just Dominos + Config, just used bug grabber and bug sack after to grab the error.
This happens after leaving combat and then mounting from what i can tell, i thought it was a dragonflying mount at first but after leaving a dungeon to repair on the yak it also happened.

**Addon Version**
10.2.11-retail
**World of Warcraft Version**
Retail

2x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'OverrideActionBarButton3:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function `Update'
[string "@FrameXML/ActionButton.lua"]:1068: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:302: in function <FrameXML/ActionButton.lua:279>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by Tuller** [comment]
Versions 10.2.13 and later should resolve this.
