### ISSUE TITLE
Using Whirling Surge whilst Dragonriding causes this and main ability bar to throw errors

### ISSUE THREAD

**Issue by Maschieftain** [tullamods/Dominos#819]
When using dragonriding quite often Dominos will fail when I use my keybind (3) for Whirling Surge. After I do and dismount it then also fail on certain abilities on my main bar as well (not the same keybind). If I click the buttons manually then they're still usable. If I reload it goes away until the next time I mount up on my dragonriding mount, or if I'm riding the mount then potentially a new zone (unsure exactly when it can be triggered again).
This has only happened in the latest version, with the version previous having separate issues with using keybinds in other areas
Bug Grabber:
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Dominos' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:100: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:148: in function `ActionButtonUp'
[string "ACTIONBUTTON3"]:4: in function <[string "ACTIONBUTTON3"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Addon Version**
10.2.11-retail

**World of Warcraft Version**
Retail

**Comment by Maschieftain** [comment]
Using the action bars after the initial trigger throws this error:
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'SpellFlyout:Hide()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Hide'
[string "@FrameXML/SecureTemplates.lua"]:363: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:100: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:148: in function `ActionButtonUp'
[string "ACTIONBUTTON5"]:4: in function <[string "ACTIONBUTTON5"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by Maschieftain** [comment]
Looks to be related to https://github.com/tullamods/Dominos/issues/817 going by the second stacktrace

**Comment by Maschieftain** [comment]
Seems I can trigger the second stacktrade without the first by dragonriding and not using Whirling Surge, so there may be two separate issues related to dragonriding involved

**Comment by bylzz** [comment]
Have the same issue, also able to trigger it without dragonriding. It triggers for me quite often after latest patch.
