### ISSUE TITLE
Keybinds triggering wrong buttons in druid forms

### ISSUE THREAD

**Issue by Irame** [tullamods/Dominos#820]
With version 10.2.11 on retail (10.2.5.53040) I have a strange issue.
If I am in a form as a druid and try to cast any of the first 6 abilities of my main action bar (bar 1) by key bind it triggers the corresponding ability from bar 10. This happens regardless of the paging setting, the bug occurs with paging off and with paging set to another bar. It is also important to note, that everything works fine if I am not in a shapeshift form.

For example, if I try to use the second ability on my main bar (Wrath im my case) it will trigger the second ability on bar 10 (Mark of the Wild in my case).

The layout of my bars looks like this:
![image](https://github.com/tullamods/Dominos/assets/4299716/da8833d3-5f34-420b-b8a0-58e3e86485de)

This bug does not occur with 10.2.10 or lower.

**Comment by Tuller** [comment]
This should be resolved now and was due to some problems with the override bar detection.
