### ISSUE TITLE
Keybinds triggering a restricted UI error

### ISSUE THREAD

**Issue by thecosmicdrake** [tullamods/Dominos#821]
Currently since the maintenance today whenever I am using my keybinds any time I switch zones or dungeons immediately the first time I use a keybind I get an error telling me that Dominos has requested a restricted function and I have to reload.

![WoWScrnShot_013024_161102](https://github.com/tullamods/Dominos/assets/485486/5c7682d6-518d-4904-91ce-9e1bf35bf654)

**Addon Version**
10.2.11-retail

**World of Warcraft Version**
Retail

**Comment by thecosmicdrake** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'OverrideActionBarButton1:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function `Update'
[string "@FrameXML/ActionButton.lua"]:1068: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:302: in function <FrameXML/ActionButton.lua:279>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrab1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'OverrideActionBarButton1:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function `Update'
[string "@FrameXML/ActionButton.lua"]:1068: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:302: in function <FrameXML/ActionButton.lua:279>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
er.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by thecosmicdrake** [comment]
1x Dominos_BuffTimes/main.lua:628: hooksecurefunc(): ActionButton_UpdateState is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Dominos_BuffTimes/main.lua"]:628: in main chunk

Locals:

**Comment by Tuller** [comment]
Dominos_BuffTimes specifically isn't actually a Dominos addon.

**Comment by thecosmicdrake** [comment]
> Dominos_BuffTimes specifically isn't actually a Dominos addon.

Thank you. I'll disable it and see what happens

**Comment by thecosmicdrake** [comment]
Disabled Dominos_BuffTimes and still getting this bug error

2x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'ActionButton3:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:485: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:551: in function `Update'
[string "@FrameXML/ActionButton.lua"]:1068: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:302: in function <FrameXML/ActionButton.lua:279>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by thisisu** [comment]
Related I think @ https://github.com/tullamods/Dominos/issues/827
