### ISSUE TITLE
10.2.12b icons blank

### ISSUE THREAD

**Issue by thefowles1** [tullamods/Dominos#823]
It seems with the reverted version updated today, a new bug appears where changing bars causes ability icons to vanish.

**Addon Version**
10.2.12b

**World of Warcraft Version**
Retail

Example:
![Recording 2024-01-31 at 00 53 33](https://github.com/tullamods/Dominos/assets/1276319/405a6a14-4886-443d-aca9-013f451b4bb1)

**Comment by Maschieftain** [comment]
Same happens for me where if I dragon ride, the abilities that aren't set on the dragon ride bar are blank when I dismount

**Comment by hollo6** [comment]
Same happens with druid forms. This was already a problem with dragonriding in beta versions but wasn't present in 10.2.11 and a few versions before that.

**Comment by kirkwor** [comment]
Can confirm as well, only the first 5 buttons seem to always appear/display when mounting a Dragonriding mount (usually you have 6 dragon abilities with full talents) and after dismounting the action bar first 5 buttons appear/display, the rest only after you highlight them with the mouse or actually use them (they're still there but blank), similar case to #795 issue.

**Comment by Tuller** [comment]
This may be a bit better in 10.2.14
