### ISSUE TITLE
10.2.12b actions activate on key release instead of keypress

### ISSUE THREAD

**Issue by thefowles1** [tullamods/Dominos#825]
With today's reverted change update, action bar buttons now activate upon key release instead of keypress, even after using "/console ActionButtonUseKeyDown 1".

**Addon Version**
10.2.12b

**World of Warcraft Version**
Retail

**Comment by Jahfry** [comment]
Probably related: 

https://github.com/tullamods/Dominos/issues/824

**Comment by thefowles1** [comment]
> Probably related:
> 
> #824

Given the desrcibed issue, I think I can agree.

10.2.13 appears to resolve.
