### ISSUE TITLE
Key press down functionality broken

### ISSUE THREAD

**Issue by asfadd** [tullamods/Dominos#826]
As of 10.2.12 button use on key press down no longer functions for any action bar. Disabling Dominos resolves this issue, as does reverting Dominos to 10.2.11. Additionally even prior to 10.2.12 (at least 10.2.11, not sure about prior versions) Dominos would sporadically revert to key press release and I would need to manually change the setting with a command. This would work for a time until it would again reset. Again, disabling Dominos would resolve this. I have not been able to determine a reason for this. This is no longer the case for 10.2.12 as Dominos is simply ignoring the CVars setting now. I know certain bars do not work with keypressdown but I don't use those bars. 

**Addon Version**
10.2.12 and 10.2.12b

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
This should be resolved in 10.2.13+
