### ISSUE TITLE
error spam due to stagger monk

### ISSUE THREAD

**Issue by artazika** [tullamods/Dominos#830]
144x ...ceShadowedUnitFrames/modules/monkstagger.lua:44: attempt to compare number with nil
[string "@ShadowedUnitFrames/modules/monkstagger.lua"]:44: in function `Update'
[string "@ShadowedUnitFrames/modules/monkstagger.lua"]:34: in function `?'
[string "@ShadowedUnitFrames/modules/units.lua"]:36: in function `FullUpdate'
[string "@ShadowedUnitFrames/modules/units.lua"]:375: in function `CheckUnitStatus'
[string "@ShadowedUnitFrames/modules/units.lua"]:614: in function <ShadowedUnitFrames/modules/units.lua:440>
[string "=[C]"]: in function `SetAttribute'
[string "@ShadowedUnitFrames/modules/units.lua"]:964: in function `LoadUnit'
[string "@ShadowedUnitFrames/modules/units.lua"]:1337: in function `InitializeFrame'
[string "@ShadowedUnitFrames/ShadowedUnitFrames.lua"]:274: in function `LoadUnits'
[string "@ShadowedUnitFrames/ShadowedUnitFrames.lua"]:86: in function `OnInitialize'
[string "@ShadowedUnitFrames/ShadowedUnitFrames.lua"]:932: in function <...aceShadowedUnitFrames/ShadowedUnitFrames.lua:930>

Locals:
self = <table> {
 moduleClass = "MONK"
 moduleHasBar = true
 Update = <function> defined @ShadowedUnitFrames/modules/monkstagger.lua:37
 UpdateMinMax = <function> defined @ShadowedUnitFrames/modules/monkstagger.lua:30
 OnEnable = <function> defined @ShadowedUnitFrames/modules/monkstagger.lua:4
 OnLayoutApplied = <function> defined @ShadowedUnitFrames/modules/monkstagger.lua:24
 moduleKey = "staggerBar"
 moduleSpec = <table> {
 }
 moduleName = "Stagger bar"
 OnDisable = <function> defined @ShadowedUnitFrames/modules/monkstagger.lua:20
}
frame = SUFUnitplayer {
 0 = <userdata>
 OnEnter = <function> defined @ShadowedUnitFrames/modules/units.lua:670
 UnregisterAll = <function> defined @ShadowedUnitFrames/modules/units.lua:145
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 auras = <table> {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 powerBar = StatusBar {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 unitType = "player"
 staggerBar = StatusBar {
 }
 indicators = Frame {
 }
 unitInitialized = true
 unit = "player"
 ReregisterUnitEvents = <function> defined @ShadowedUnitFrames/modules/units.lua:41
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 RegisterUnitEvent = <function> defined @ShadowedUnitFrames/modules/units.lua:112
 fontStrings = <table> {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 TopEdge = Texture {
 }
 unitOwner = "player"
 fullUpdates = <table> {
 }
 UnregisterUpdateFunc = <function> defined @ShadowedUnitFrames/modules/units.lua:135
 combatText = Frame {
 }
 incHeal = StatusBar {
 }
 FullUpdate = <function> defined @ShadowedUnitFrames/modules/units.lua:33
 portraitModel = PlayerModel {
 }
 portrait = PlayerModel {
 }
 registeredEvents = <table> {
 }
 UnitClassToken = <function> defined @ShadowedUnitFrames/modules/units.lua:685
 TopLeftCorner = Texture {
 }
 RegisterNormalEvent = <function> defined @ShadowedUnitFrames/modules/units.lua:62
 SetVisibility = <function> defined @ShadowedUnitFrames/modules/units.lua:246
 topFrameLevel = 5
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 SetRangeAlpha = <function> defined @ShadowedUnitFrames/modules/units.lua:179
 visibility = <table> {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 isDead = false
 unitGUID = "Player-1615-08E56303"
 Center = Texture {
 }
 unitRealType = "player"
 RightEdge = Texture {
 }
 LeftEdge = Texture {
 }
 BottomEdge = Texture {
 }
 highFrame = Frame {
 }
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 OnLeave = <function> defined @ShadowedUnitFrames/modules/units.lua:678
 incAbsorb = StatusBar {
 }
 comboPoints = Frame {
 }
 vehicleUnit = "vehicle"
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 healthBar = StatusBar {
 }
 TopRightCorner = Texture {
 }
 UnregisterSingleEvent = <function> defined @ShadowedUnitFrames/modules/units.lua:95
 DisableRangeAlpha = <function> defined @ShadowedUnitFrames/modules/units.lua:171
 RegisterUpdateFunc = <function> defined @ShadowedUnitFrames/modules/units.lua:118
 SetBlockColor = <function> defined @ShadowedUnitFrames/modules/units.lua:191
 SetBarColor = <function> defined @AddOn

Dominos: 10.2.15-retail

Retail

**Comment by Tuller** [comment]
I don't see anything specific to Dominos here. It looks more like its related to ShadowedUnitFrames?
