### ISSUE TITLE
10.2.15 macros disappear from bars

### ISSUE THREAD

**Issue by hollo6** [tullamods/Dominos#831]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.**
Reproduced with everything else disabled.

**Addon Version**
10.2.15-beta1 and 10.2.15 both have this issue.

**World of Warcraft Version**
Retail

Upon changing specialization, and some other events that I couldn't yet identify (probably taking portals but that alone is not a reliable way to reproduce this), macros disappear from action bars and only a blank button is displayed. Can be temporarily "fixed" by grabbing an ability or macro. Mainly action bars 4, 5, 10 and 14 are affected as far as I can see.

**Comment by Tuller** [comment]
I likely just need to force an icon update on SPELLS_CHANGED.

**Comment by hollo6** [comment]
Not sure what changed on this front, this wasn't an issue in previous addon versions.
Also I probably didn't describe the problem well enough, the place for the missing macros is almost invisible, I can only see the border around that empty slot because I know to look for it.

**Comment by Tuller** [comment]
Its a regression from me refactoring the code base a bit.

**Comment by hollo6** [comment]
All use cases look good now, thanks!
