### ISSUE TITLE
Cannot use buttons on hidden action bar slots

### ISSUE THREAD

**Issue by asfadd** [tullamods/Dominos#832]
Getting this BugSack dump when attempting to use an ability that's on an action bar slot I have hidden. Using abilities on the same action bar but on slots that aren't hidden works normally. Disabling Dominos and using the default UI bars with the bar hidden works normally. Reverting to version 10.2.14b resolves this issue. 
 Additionally, casted abilities such as flash of light are not triggering the global cooldown animation on the icon of the casted ability. It will display on other icons but not the one that was used. 

40x FrameXML/MultiActionBars.lua:29: attempt to index local 'button' (a nil value)
[string "@FrameXML/MultiActionBars.lua"]:29: in function `MultiActionButtonUp'
[string "MULTIACTIONBAR2BUTTON8"]:4: in function <[string "MULTIACTIONBAR2BUTTON8"]:1>

Locals:
bar = "MultiBarBottomRight"
id = 8
bar = MultiBarBottomRight {
 0 = <userdata>
 buttonPadding = 2
 GetShowAllButtons = <function> defined @FrameXML/ActionBar.lua:179
 UpdateSystemSettingAlwaysShowButtons = <function> defined @FrameXML/EditModeSystemTemplates.lua:994
 UpdateMagnetismRegistration = <function> defined @FrameXML/EditModeSystemTemplates.lua:731
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:609
 UpdateFrameStrata = <function> defined @FrameXML/ActionBar.lua:183
 IsFrameAnchoredToMe = <function> defined @FrameXML/EditModeSystemTemplates.lua:694
 TrySetCompositeNumberSettingValue = <function> defined @FrameXML/EditModeSystemTemplates.lua:212
 downKeys = <table> {
 }
 GetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:156
 buttonTemplate = "MultiBar2ButtonTemplate"
 GetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:148
 useDefaultAnchors = false
 GetSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:540
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:254
 oldGridSettings = <table> {
 }
 GetScaledSelectionSides = <function> defined @FrameXML/EditModeSystemTemplates.lua:532
 SelectSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:763
 SetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:135
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:714
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:499
 UpdateSystemSettingIconSize = <function> defined @FrameXML/EditModeSystemTemplates.lua:933
 SetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:143
 HasActiveChanges = <function> defined @FrameXML/EditModeSystemTemplates.lua:381
 GetScaledCenter = <function> defined @FrameXML/EditModeSystemTemplates.lua:525
 DoesSettingDisplayValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:445
 UpdateDisplayInfoOptions = <function> defined @FrameXML/EditModeSystemTemplates.lua:456
 GetSystemName = <function> defined @FrameXML/EditModeSystemTemplates.lua:822
 ProcessMovementKey = <function> defined @FrameXML/EditModeSystemTemplates.lua:39
 GetSettingValueBool = <function> defined @FrameXML/EditModeSystemTemplates.lua:436
 HasCompositeNumberSetting = <function> defined @FrameXML/EditModeSystemTemplates.lua:385
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:440
 dividersDirty = false
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 ShouldResetSettingsDialogAnchors = <function> defined @FrameXML/EditModeSystemTemplates.lua:168
 dirtySettings = <table> {
 }
 UpdateGridLayout = <function> defined @FrameXML/EditModeSystemTemplates.lua:870
 IsToTheLeftOfFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:481
 GetSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:465
 hasActiveChanges = false
 OnSystemLoad = <function> defined @FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @FrameXML/EditModeSystemTemplates.lua:653
 GetCombinedCenterOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:596
 SetupSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:369
 IsShownOverride = <function> defined @FrameXML/ActionBar.lua:282
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:833
 CacheGridSettings = <function> defined @FrameXML/ActionBar.lua:65
 UpdateDirtySettin

**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** 
Done

**Addon Version**
10.2.15-retail

**World of Warcraft Version**
Retail

**Comment by Tuller** [comment]
When you say hidden, have you happened to have shrunk the bar to one button too?

**Comment by asfadd** [comment]
The bar is shrunk to 4 buttons showing. I didn't test it with other configurations except all 8 showing which behaved normally. But yes, that's what I mean by hidden.

**Comment by Tuller** [comment]
Yep, that makes sense then for the cause.
