### ISSUE TITLE
Shadowform auto-paging

### ISSUE THREAD

**Issue by Piripippeli** [tullamods/Dominos#833]
Shadowform auto-paging isn't working. 
Tried all 14 actionbars, but it won't work.

**Addon Version**
Dominos
Version: 10.2.18-Classic

**World of Warcraft Version**
Classic, (SOD).
Version: 1.15.1.53247

**Comment by Tuller** [comment]
Does a form:1 macro work for you? That’s what Dominos is using for in classic

**Comment by Piripippeli** [comment]
Yes [form:x] macro works but that autopaging would be nice
