### ISSUE TITLE
Action bar 1 completely disappears when I go into Shadowform

### ISSUE THREAD

**Issue by vintage143** [tullamods/Dominos#837]
When I go into shadowform my Action Bar 1 completely disappears and I can't cast spells using any keybinds for that action bar either.

**Addon Version**
Feb 18 2024 version onwards. After downgrading back to the Feb 11 2024 version the issue is resovled

**World of Warcraft Version**
Classic SOD

**Comment by Tuller** [comment]
What do your paging settings look like when you right click the bar in config mode?
