### ISSUE TITLE
Hide keybind text not working

### ISSUE THREAD

**Issue by callmeaxx** [tullamods/Dominos#838]
Hi, I am using the latest updated version 10.2.21 for WoW Classic SoD. 
Noticed the following bullet: 
"Fix hotkey display issues"

Not sure if related, but the hide key bind feature no longer works for my client. 
I tried reinstalling the addon and displaying all other addons that could have possibly interfered.

**Comment by Tuller** [comment]
Are hotkeys set to be visible  in /dom config ?

**Comment by callmeaxx** [comment]
> Are hotkeys set to be visible in /dom config ?

No, they are not. I'll post a screen shot once servers are back up.

**Comment by callmeaxx** [comment]
![dominos error example](https://github.com/tullamods/Dominos/assets/160622693/476bee66-cfe6-423e-9d8e-6a278634e075)

**Comment by callmeaxx** [comment]
![dominos error example](https://github.com/tullamods/Dominos/assets/160622693/78c6632a-cc3e-4f66-ad93-d7091a7dca8c)

**Comment by callmeaxx** [comment]
OK, I think I found the problem with another conflicting UI addon. 
RougeUI seemed to be causing the issue. Going to reach out to that developer

**Comment by Tuller** [comment]
So the change I made was to make hotkeys transparent when you set them to hidden.  I bet that addon is doing the same thing

**Comment by callmeaxx** [comment]
![image](https://github.com/tullamods/Dominos/assets/160622693/32a52100-3ac0-49b9-884d-21c1b387acc1)
The addon is Rouge UI
