### ISSUE TITLE
"Show Binding Text" won't disable properly

### ISSUE THREAD

**Issue by wwbrandon** [tullamods/Dominos#839]
Hey, I love that your addon can hide binding text... but the recent update broke it. The text won't hide.

**Comment by Tuller** [comment]
Do you experience this with just Dominos + Dominos_Config enabled? Other addons may also mess with binding text.

**Comment by wwbrandon** [comment]
All I did was update the addon one day and the settings check box will turn them off, but 1 second later they re-enable.

**Comment by wwbrandon** [comment]
Hello,

wanted to follow up- the show binding text seems to be broken for me. I have no conflicting addons and tried for another solution. The toggle will turn off the text, but when you close the option window they reappear. D:

**Comment by Tuller** [comment]
That's exceptionally weird, as there shouldn't be anything that really fires off of closing the options window.

**Comment by wwbrandon** [comment]
I don't believe I have any conflicting addons forcing the text... here is a video showing it.

https://github.com/tullamods/Dominos/assets/107085170/a06b4e12-f054-4b77-aeb3-1022d5302280

**Comment by wwbrandon** [comment]
This give any insight??

**Comment by Tuller** [comment]
I'm still thinking it might be an addon from that clip

**Comment by wwbrandon** [comment]
Whatever you did in your latest update corrected the break! <3
