### ISSUE TITLE
Show Empty Buttons not working

### ISSUE THREAD

**Issue by vioray** [tullamods/Dominos#840]
**Addon Version**
10.2.21-retail
You can get this via running `/dominos version` in game

**World of Warcraft Version**
retail

when I log into any character the empty action bar buttons are hidden. I have to go into options, untick "Show Empty Buttons" and retick it. this happens every time I log into any character

**Comment by Tuller** [comment]
Do you get this with just Dominos + Dominos Config enabled? One possibility is you have show empty buttons checked globally, but have it unchecked in your bar's context/right click menu.

**Comment by vioray** [comment]
I have both. I haven't changed anything but now it's remembering when I change it and relog
