### ISSUE TITLE
Patch day errors

### ISSUE THREAD

**Issue by thisisu** [tullamods/Dominos#845]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
Dominos: 10.2.22-retail

**World of Warcraft Version**
Retail

243x FrameXML/MainMenuBarMicroButtons.lua:1623: attempt to compare two nil values
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1623: in function `GetEdgeButton'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1651: in function `UpdateHelpTicketButtonAnchor'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1710: in function `Layout'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1759: in function `Layout'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:413: in function <FrameXML/MainMenuBarMicroButtons.lua:412>
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@Dominos/bars/menuBar.lua"]:168: in function `Layout'
[string "@Dominos/core/buttonBar.lua"]:89: in function `ReloadButtons'
[string "@Dominos/bars/menuBar.lua"]:133: in function `ReloadButtons'
[string "@Dominos/core/buttonBar.lua"]:16: in function <Dominos/core/buttonBar.lua:15>
[string "=(tail call)"]: ?
...
[string "@FrameXML/UIParent.lua"]:777: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
self = MicroMenu {
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 GetEdgeButton = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1600
 ShouldUpdateLayout = <function> defined @SharedXML/LayoutFrame.lua:483
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 SetHeightPadding = <function> defined @SharedXML/LayoutFrame.lua:160
 layoutFramesGoingRight = true
 OnCleaned = <function> defined @SharedXML/LayoutFrame.lua:131
 isHorizontal = true
 OnUpdate = <function> defined @SharedXML/LayoutFrame.lua:93
 GetAdditionalRegions = <function> defined @SharedXML/LayoutFrame.lua:85
 GetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:156
 OnShow = <function> defined @SharedXML/LayoutFrame.lua:32
 GetHeightPadding = <function> defined @SharedXML/LayoutFrame.lua:164
 UpdateFramerateFrameAnchor = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1666
 GetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:148
 dirty = false
 stride = 12
 GetWidthPadding = <function> defined @SharedXML/LayoutFrame.lua:168
 childYPadding = -5
 SetScaleAdjustment = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1713
 layoutFramesGoingUp = false
 UpdateQueueStatusAnchors = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1656
 SetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:135
 InitializeButtons = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1565
 GetFixedHeight = <function> defined @SharedXML/LayoutFrame.lua:152
 MarkClean = <function> defined @SharedXML/LayoutFrame.lua:117
 CacheLayoutSettings = <function> defined @SharedXML/LayoutFrame.lua:471
 SetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:143
 GetLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:73
 numButtons = 12
 IsDirty = <function> defined @SharedXML/LayoutFrame.lua:127
 OnLoad = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1560
 oldGridSettings = <table> {
 }
 Layout = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1703
 SetFixedHeight = <function> defined @SharedXML/LayoutFrame.lua:139
 AnchorToMenuContainer = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1674
 SetQueueStatusScale = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1695
 0 = <userdata>
 UpdateHelpTicketButtonAnchor = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1634
 AddButton = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1591
 MarkIgnoreInLayout = <function> defined @SharedXML/LayoutFrame.lua:44
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 childXPadding = -5
 IgnoreLayoutIndex = <function> defined @SharedXML/LayoutFrame.lua:515
}
rightMost = false
topMost = true
firstButton = HelpMicroButton {
 0 = <userdata>
 OnEnter = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:353
 FlashBorder = Texture {
 }
 QuickKeybindButtonOnShow = <function> defined @FrameXML/QuickKeybind.lua:4
 QuickKeybindButtonOnEnter = <function> defined @FrameXML/QuickKeybind.lua:22
 DoModeChange = <function> defined @FrameXML/QuickKeybind.lua:95
 QuickKeybindButtonOnUpdate = <function> defined @FrameXML/QuickKeybind.lua:75
 tooltipText = "Customer Support"
 QuickKeybindButtonOnLeave = <function> defined @FrameXML/QuickKeybind.lua:33
 OnMouseDown = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:416
 Background = Texture {
 }
 PushedBackground = Texture {
 }
 QuickKeybindButtonSetTooltip = <function> defined @FrameXML/QuickKeybind.lua:52
 layoutIndex = 10
 OnShow = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:408
 OnLoad = <function> defined @FrameXML/MainMenuBarMicroButtons.l

**Comment by Geekly** [comment]
I only have Dominos and Dominos_config and Buggrabber/Bugsack running. Wow doesn't like what Dominos is doing to the Menu Bar Buttons element. 
**Addon Version**
Dominos: 10.2.22-retail
**World of Warcraft Version**
Retail

I get an error similar to this whenever I activate one of the menu items, either by clicking the button or by using a hotkey.

138x FrameXML/MainMenuBarMicroButtons.lua:1623: attempt to compare number with nil
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1623: in function `GetEdgeButton'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1651: in function `UpdateHelpTicketButtonAnchor'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1710: in function `Layout'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1759: in function `Layout'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:413: in function <FrameXML/MainMenuBarMicroButtons.lua:412>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetParent'
[string "@Dominos/core/buttonBar.lua"]:53: in function `AttachButton'
[string "@Dominos/core/buttonBar.lua"]:86: in function `ReloadButtons'
[string "@Dominos/bars/menuBar.lua"]:133: in function `ReloadButtons'
[string "@Dominos/core/buttonBar.lua"]:16: in function <Dominos/core/buttonBar.lua:15>
...
[string "@FrameXML/UIParent.lua"]:572: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:777: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
self = MicroMenu {
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 GetEdgeButton = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1600
 ShouldUpdateLayout = <function> defined @SharedXML/LayoutFrame.lua:483
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 SetHeightPadding = <function> defined @SharedXML/LayoutFrame.lua:160
 layoutFramesGoingRight = true
 OnCleaned = <function> defined @SharedXML/LayoutFrame.lua:131
 isHorizontal = true
 OnUpdate = <function> defined @SharedXML/LayoutFrame.lua:93
 GetAdditionalRegions = <function> defined @SharedXML/LayoutFrame.lua:85
 GetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:156
 OnShow = <function> defined @SharedXML/LayoutFrame.lua:32
 GetHeightPadding = <function> defined @SharedXML/LayoutFrame.lua:164
 UpdateFramerateFrameAnchor = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1666
 GetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:148
 dirty = false
 stride = 12
 GetWidthPadding = <function> defined @SharedXML/LayoutFrame.lua:168
 childYPadding = -5
 SetScaleAdjustment = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1713
 layoutFramesGoingUp = false
 UpdateQueueStatusAnchors = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1656
 SetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:135
 InitializeButtons = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1565
 GetFixedHeight = <function> defined @SharedXML/LayoutFrame.lua:152
 MarkClean = <function> defined @SharedXML/LayoutFrame.lua:117
 CacheLayoutSettings = <function> defined @SharedXML/LayoutFrame.lua:471
 SetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:143
 GetLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:73
 numButtons = 12
 IsDirty = <function> defined @SharedXML/LayoutFrame.lua:127
 OnLoad = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1560
 oldGridSettings = <table> {
 }
 Layout = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1703
 SetFixedHeight = <function> defined @SharedXML/LayoutFrame.lua:139
 AnchorToMenuContainer = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1674
 SetQueueStatusScale = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1695
 0 = <userdata>
 UpdateHelpTicketButtonAnchor = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1634
 AddButton = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:1591
 MarkIgnoreInLayout = <function> defined @SharedXML/LayoutFrame.lua:44
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 childXPadding = -5
 IgnoreLayoutIndex = <function> defined @SharedXML/LayoutFrame.lua:515
}
rightMost = false
topMost = true
firstButton = QuestLogMicroButton {
 0 = <userdata>
 OnLeave = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:379
 FlashBorder = Texture {
 }
 DoModeChange = <function> defined @FrameXML/QuickKeybind.lua:95
 QuickKeybindButtonOnLeave = <function> defined @FrameXML/QuickKeybind.lua:33
 OnClick = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:780
 QuickKeybindButtonSetTooltip = <function> defined @FrameXML/QuickKeybind.lua:52
 OnShow = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:408
 QuickKeybindHighlightTexture = Texture {
 }
 SetPushed = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:387
 UpdateMouseWheelHandler = <function> defined @FrameXML/QuickKeybind.lua:86
 QuickKeybindButtonOnMouseWheel = <function> defined @FrameXML/QuickKeybind.lua:46
 UpdateTooltipText = <function> defined @FrameXML/MainMenuBarMicroButtons.lua:775
 QuickKeybindButtonOnShow = <function> defined @I

**Comment by Geekly** [comment]
If I disable the Domino's menu button bar (simply hiding it), the errors go away (but then I don't have a menu button bar).

**Comment by Tuller** [comment]
The latest version lets the stock UI control the menu bar for now (and the bag and queue status, too) as a temporary workaround. I think I may need to just write my own implementation of the bar as a longer term fix.

**Comment by hollo6** [comment]
The new version always forces the bag and menu bars to appear and now there's no way to hide them.
I have tried commenting them out in Dominos.toc as well to no avail.
I'm able to move/resize the LFG status icon with MoveAny after this update, but if Dominos is enabled, it somehow takes precedence and I'm unable to hide the menu and bag bars - there is no such option in Edit Mode and MA cannot get a handle on them.
Is there something I can do to prevent this?

**Comment by Tuller** [comment]
A more permanent fix should now be in place.

**Comment by thisisu** [comment]
Ty Tuller
