### ISSUE TITLE
ADDON_ACTION_BLOCKED

### ISSUE THREAD

**Issue by Neokub** [tullamods/Dominos#846]
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'MultiBarBottomLeftButton1:Hide()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Hide'
[string "@FrameXML/ActionButton.lua"]:498: in function `ActionButton_HideGrid'
[string "@FrameXML/MultiActionBars.lua"]:130: in function `MultiActionBar_UpdateGrid'
[string "@FrameXML/MultiActionBars.lua"]:111: in function `MultiActionBar_ShowAllGrids'
[string "@FrameXML/SpellBookFrame.lua"]:105: in function <FrameXML/SpellBookFrame.lua:96>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2168: in function `SetUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2013: in function `ShowUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:1881: in function <Interface_Vanilla/FrameXML/UIParent.lua:1877>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2660: in function `ShowUIPanel'
[string "@FrameXML/SpellBookFrame.lua"]:46: in function `ToggleSpellBook'
[string "TOGGLESPELLBOOK"]:1: in function <[string "TOGGLESPELLBOOK"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511

**Comment by Tuller** [comment]
Are you able to reproduce this with just Dominos + Dominos_Config enabled? Are you playing on retail or classic?
