### ISSUE TITLE
GM ticket status icon is not linked to Menu

### ISSUE THREAD

**Issue by SlayksWood** [tullamods/Dominos#847]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
Dominos: 10.2.24-retail

**World of Warcraft Version**
Retail

So it locates in center of screen and there are no way to move it anywhere:
![image](https://github.com/tullamods/Dominos/assets/45708377/398067d0-863e-4050-a71f-8d5e9420240e)

**Comment by Avanor1212** [comment]
Even after the recent update it's not working properly for me. 
On some characters the support-icon is still placed in the center of the screen. Changing profiles, reloading the interface and reinstalling the addon didn't fix it.
On one of my characters the icon actually reattached to the menu at some point while playing, but after logging in between characters it's back to the bugged positioning in the center.

**Comment by Tuller** [comment]
This should be a bit better now, I hope.
