### ISSUE TITLE
Cataclysm Beta Stands/Classbar

### ISSUE THREAD

**Issue by Necro87** [tullamods/Dominos#848]
**Addon Version**
10.2.24

**World of Warcraft Version**
Cataclysm Beta

Stands/Classbar missing. 

Other then default profile also tried import my wotlk save variables to see if it was there then but it isnt, it is also not hidden unless somehow even default is of screen. otherwise seems to work no issues

**Comment by Tuller** [comment]
I don't currently have access to the beta, so its going to be hard for me to resolve issues like this until then. Can you install bugsack and errors from that?

**Comment by Necro87** [comment]
only bugsack error i get is one unrelated to any addons. i also for fun tried to install bartender4 to see if same issue was happening there, but no.. the stand/classbar is still intact there. anyway here is the one bugsack error that is in bugsack.

---------------
19x ...ddOns/Blizzard_UIPanels_Game/Cata/SpellBookFrame.lua:970: IsPassiveSpell(): Invalid spell slot
[string "=[C]"]: in function `IsPassiveSpell'
[string "@Blizzard_UIPanels_Game/Cata/SpellBookFrame.lua"]:970: in function `UpdateProfessionButton'
[string "@Blizzard_UIPanels_Game/Cata/SpellBookFrame.lua"]:1082: in function `FormatProfession'
[string "@Blizzard_UIPanels_Game/Cata/SpellBookFrame.lua"]:1121: in function `SpellBook_UpdateProfTab'
[string "@Blizzard_UIPanels_Game/Cata/SpellBookFrame.lua"]:120: in function <...ddOns/Blizzard_UIPanels_Game/Cata/SpellBookFrame.lua:99>

Locals:
(*temporary) = 57
(*temporary) = "spell"
-----------------

**Comment by Necro87** [comment]
well ill be damd.. i made a new copied paladin to test if issue still there and it wasnt. the issue might be spesificly to copied characters somehow.... weird

**Comment by grantlerdt** [comment]
The problem for Stance/Classbar not showing can be found in stanceBar.classic.lua line 14 to 25 where it states for example line 14
DEATHKNIGHT = Addon:IsBuild('wrath'),

When changing this to
DEATHKNIGHT = Addon:IsBuild('wrath', 'cata'),
and adding 
elseif l == LE_EXPANSION_CATACLYSM then
WOW_BUILD = 'cata'
to Dominos.lua at line 27 the Stancebar for Deathknights is showing.

Hope this helps :)

**Comment by Tuller** [comment]
I think this is already fixed in the beta release.
