### ISSUE TITLE
[Classic] Dominos bars 12-14

### ISSUE THREAD

**Issue by XyzKangUI** [tullamods/Dominos#850]
It was brought to my attention (no idea why) that Dominos has enabled the extra bars (MultiBar5-7) in classic. However you cannot bind keys to these bars because the bindings don't exist.

Dominos can add the missing bindings by uncommenting in Bindings.xml and editing button.classic.lua to not use MULTIACTIONBAR5BUTTON, MULTIACTIONBAR6BUTTON, MULTIACTIONBAR7BUTTON

**Comment by Tuller** [comment]
For now, you can use quick binding on these (/kb). I added them because I noticed that they were usable in classic.

**Comment by XyzKangUI** [comment]
> For now, you can use quick binding on these (/kb). I added them because I noticed that they were usable in classic.

The bars exist, however you cannot bind anything at all.
