### ISSUE TITLE
Cata Pre Patch Shadow Dance Broken

### ISSUE THREAD

**Issue by YOLTS** [tullamods/Dominos#853]
Reporting an issue following Cata Pre-Patch:  Rogue shadow dance ability no longer changes the main action bar (as it did before the pre patch).  Disabling Dominos, the main action bar changes to "Action Bar 8"(as labeled in Dominos).  Hoping we receive fix soon.  Thanks :)

**Comment by Nekura-Neko** [comment]
I'm thinking this one is circa line 177 of dominos/core/barStates.lua where it version-checks for Wrath, but the call for GetSpellInfo by ID seems a bit risky given how many skills got squirreled up in the Cata release.

    -- wrath shadowdance
    if Addon:IsBuild('wrath') then -- Prime culprit right here!
        addState('class', 'shadowdance', '[bonusbar:2]', GetSpellInfo(51713)) --but is the spell ID still correct?

**Comment by Tuller** [comment]
This one was already fixed in the cata branch, which is now merged into the main release.
In terms of the spell ID check - That's there to provide the name of ability in the paging section of the bar's context menu.
