### ISSUE TITLE
Versions Higher Than 10.2.29 Not Loading in Cataclysm Classic

### ISSUE THREAD

**Issue by chynes-re** [tullamods/Dominos#856]
**World of Warcraft Version**
Cata Classic

Dominos version 10.2.29 and 10.2.30 install fine using Curseforge but they do not appear in the game client addon listing. I have rolled back to 10.2.28 and verified that the addon still appears in the load list and loads fine in game. I see that Curse reports 10.2.29 was when Dominos changed their manifest removing support for 3.4.3. Given that we are still in pre-patch I'm wondering if that is the issue.

**Comment by vertx66** [comment]
Second this, rolled back and 10.2.28 and everything is functioning again.

**Comment by Tuller** [comment]
I've confirmed that the addon loads for me. Do you see the addon in the `_classic_` addons folder after it is installed?

**Comment by holypalaswe** [comment]
Updating the addon through curseforge while I had game running and doing a /reload made Dominos disappear from ingame addon list and not work. It was fixed by a simple restart of wow.

**Comment by chynes-re** [comment]
Weirdly enough, after having repeated the same steps I tried multiple times yesterday the current version 10.2.30 is now loading fine for me. I tried reinstalling the addon through Curseforge, uninstalling 10.2.30 and installing it again, and installing the lesser versions manually. It didn't work until I installed 10.2.28. 

All I did to upgrade from 10.2.28 tonight was upgrading _before_ I launched the game. Confirmed working without error for me now though.

**Comment by Francoporto** [comment]
Hello, same for me, the 10.2.29 and 30 are not showing in the addon list in the game

**Comment by Tuller** [comment]
Is this working better now?  I changed the the TOC file generation bit to only generate a separate one for Vanilla, instead of Classic.

**Comment by Francoporto** [comment]
> Is this working better now? I changed the the TOC file generation bit to only generate a separate one for Vanilla, instead of Classic.

Personaly i have no issue
