### ISSUE TITLE
[Cata Classic] Enounter Bar saved location not respected

### ISSUE THREAD

**Issue by Road-block** [tullamods/Dominos#858]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
You can get this via running `/dominos version` in game
**10.2.30-cata**

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.
**Cataclysm Classic**

The Encounter Bar (shows Alt PowerBar from what I can tell? for when it shows up) 
I have saved to a specific location (center bottom closer to my actionbars)
The move overlay at that location with /dominos config so it doesn't seem to be a persistence issue.

**Unexpected behavior.**
Regardless where it is saved _it pops up at the default location when it shows up during fights_.

**Comment by Road-block** [comment]
I restored a line that was commented out - in my local copy - and that seems to have fixed the issue (alt power bar showed at the saved location on Chogul with corruption mechanic)

The line in question being [Dominos/bars/encounterBar.lua#L78](https://github.com/tullamods/Dominos/blob/c60b1f3b0e573d6330b3fce052aa8c26c0c21210/Dominos/bars/encounterBar.lua#L78)

I have no idea if there needs to be conditional code for other client versions as I don't play mainline.

**Comment by Tuller** [comment]
Thanks. I've put the setting behind a client check because it isn't necessary in retail

**Comment by kbinz** [comment]
The fix don't work for me after a death. /rl helps
![dominos_encounter_bar](https://github.com/tullamods/Dominos/assets/50100372/25972f52-6038-4093-8442-a3696c6d7b2a)

**Comment by Road-block** [comment]
I noticed the same after some pull on Atramedes. 
I don't know if it was due to wipe or Blizzard changed something in one of the recent Cata classic patches.

**Comment by kbinz** [comment]
Also noticed it today while doing dmf dailys

**Comment by Road-block** [comment]
> Also noticed it today while doing dmf dailys

This is real interesting. Which daily shows an alternate power bar. Having a way to troubleshoot outside of a raid would be really helpful.

**Comment by kbinz** [comment]
Okay sorry for my previous too imprecise describtion.
I hope this clearfies it better :)

My Encounter bar is first at the position i defined.
After a death in a fight with an encounter bar, the position is in the middle of the screen. 

Ways to reproduce I recognized at dmf:
Exite the vehicle manually at the tonk challenge, be destroyed or let the timer expire (daily: "Tonk Commander").
Let the timer expire at the shooting range (daily: "He Shoots, He Scores!").

Tomorow I'll check other dailys there

Cheers!

**Comment by kbinz** [comment]
tyvm <3
I'll see next week thursday if it fixed the problem =)
