### ISSUE TITLE
Action bar 3 and Action bar 4 have bugs in configuration mode

### ISSUE THREAD

**Issue by zhxxkeke** [tullamods/Dominos#860]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
10.2.31-retail

**World of Warcraft Version**
Retail

Action bar 3 and Action bar 4 have bugs in configuration mode
I moved Action bar 3 or Action bar 4 to the right side of the screen, just like Blizzard's default position, if I use the arrow keys to control the position of the action bar, they can't be moved or reset to the middle of the screen

scale affects the position, is this a BUG? Action bar 4 x I set 54, the actual value is 36 54*0.68=36.72
（I want to set the value of x to 36 and by my calculations I have to set it to 54）

**Comment by Tuller** [comment]
This actually was an issue with any frame that was scaled. This should be fixed with v10.2.32 

Additionally, I adjusted the nudge increments that they correspond more closely to screen pixels.
