### ISSUE TITLE
When i click right mouse button on bars it shows a conflict with Blizz UI

### ISSUE THREAD

**Issue by omkara452** [tullamods/Dominos#861]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
10.2.32

**World of Warcraft Version**
Retail

2x [ADDONACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'MultiBar7ActionButton9:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function SetAttribute'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:488: in function UpdatePressAndHoldAction'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:554: in function Update'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:1074: in function OnEvent'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:302: in function <Blizzard_ActionBar/Mainline/ActionButton.lua:279>

Locals:
 = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by Tuller** [comment]
Are you able to produce this one with just Dominos and Dominos Config loaded?
