### ISSUE TITLE
The maximum value of rowoffset should be added with the value of Space.

### ISSUE THREAD

**Issue by WhisperWindE** [tullamods/Dominos#863]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
This is the only way to achieve vertical alignment when staggered rows.
![image](https://github.com/tullamods/Dominos/assets/41589655/10c61c1c-8803-404a-a277-b6aeb9c2c600)

**Comment by Tuller** [comment]
I never actually considered this particular bar configuration before

**Comment by WhisperWindE** [comment]
`function ButtonBar:SetRowOffset(rowOffset)
    self.sets.rowOffset = rowOffset           **+ self.sets.spacing**
    self:Layout()
end`
I simply modified the function to temporarily implement this offset, but there is a problem. Every time I switch to modify, this offset will be automatically added.
Which one should I modify correctly?

**Comment by Tuller** [comment]
I think you want to ,ossify the layout function directly

**Comment by WhisperWindE** [comment]
Bar-RowOffset  range (0-36)
36 is the width of the button
How to add the width of Spaceing
For example, the default Space=2
The range of offset should be 0----38 (36+2)

**Comment by Tuller** [comment]
This is implemented now - The min and max values of the slider will include spacing. You can also type in a value to bypass the limits that are in place.

**Comment by WhisperWindE** [comment]
Which file was changed? I used it WotLK Classic

**Comment by Tuller** [comment]
I updated Dominos Config’s slider defaults 

https://github.com/tullamods/Dominos/commit/08509946a13ffd1d4ccdb3536e68b497cfe79a56
