### ISSUE TITLE
TWW Beta Error

### ISSUE THREAD

**Issue by TallerAndBlueOnline** [tullamods/Dominos#865]
I'm currently in the TWW beta, and I've been getting the following error with version 10.2.35:
Message: Interface/AddOns/Dominos_Cast/castBar.lua:72: attempt to call upvalue 'IsHelpfulSpell' (a nil value)
Time: Tue Jun 25 22:49:55 2024
Count: 2
Stack: Interface/AddOns/Dominos_Cast/castBar.lua:72: attempt to call upvalue 'IsHelpfulSpell' (a nil value)
[string "@Interface/AddOns/Dominos_Cast/castBar.lua"]:72: in function <Interface/AddOns/Dominos_Cast/castBar.lua:68>
[string "@Interface/AddOns/Dominos_Cast/castBar.lua"]:329: in function `func'
[string "@Interface/AddOns/Dominos_Cast/castBar.lua"]:358: in function `SetProperty'
[string "@Interface/AddOns/Dominos_Cast/castBar.lua"]:417: in function `UpdateCasting'
[string "@Interface/AddOns/Dominos_Cast/castBar.lua"]:250: in function `func'
[string "@Interface/AddOns/Dominos_Cast/castBar.lua"]:154: in function <Interface/AddOns/Dominos_Cast/castBar.lua:150>

Locals: spellID = 28700
name = "Disperse Neutralizing Agent"
(*temporary) = nil
(*temporary) = "Disperse Neutralizing Agent"
(*temporary) = "attempt to call upvalue 'IsHelpfulSpell' (a nil value)"
IsHelpfulSpell = nil
IsHarmfulSpell = nil

Thanks in advance.

**Comment by Tuller** [comment]
This is fixed in the latest commit, but I’ve not yet pushed it out
