### ISSUE TITLE
Feature request: Separate UIWidgetPowerBarContainerFrame from the Encounter Bar

### ISSUE THREAD

**Issue by jungheeMW** [tullamods/Dominos#870]
**Is your feature request related to a problem? Please describe.**
In the most recent update (10.2.37), UIWidgetPowerBarContainerFrame was attached to the Encounter Bar. UIWidgetPowerBarContainerFrame includes the dragonriding/skyriding vigor bar. By default, this bar is located in the center of the screen, and can be hidden or modified by WeakAuras (dragonriding WAs will often hide the Blizzard default bar). Now it appears in the location where the Encounter Bar is, and WeakAuras cannot interact with it. The Power Bar can no longer be separated from the Encounter Bar if Dominos is active.

**Describe the solution you'd like**
If possible, this change should be reverted, or the Power Bar should be separated from the Encounter Bar.

**Describe alternatives you've considered**
Currently, I have gone back to an older build (10.2.36).

**Comment by Tuller** [comment]
For context, I made this change to to be a bit more consistent with the Blizzard UI, which also [parents the element to the EncounterBar](https://github.com/Gethe/wow-ui-source/blob/6b65c2922baca3db5a28fb39b69c95cef1047bec/Interface/AddOns/Blizzard_UIWidgets/Mainline/Blizzard_UIWidgetPowerBarFrame.xml). I think WeakAuras would want to do something like this:
```lua
UIWidgetPowerBarContainer:UnregisterForWidgetSet(C_UIWidgetManager.GetPowerBarWidgetSetID())
```

**Comment by jungheeMW** [comment]
Should I forward this to [WeakAuras2](https://github.com/WeakAuras/WeakAuras2), or to the the people who write the dragonriding WeakAuras? It's unlikely that the latter will account for addon usage.

**Comment by jungheeMW** [comment]
I looked into the dragonriding WeakAuras. This is the main LUA code most dragonriding weakauras are based off of: https://wago.io/dmui-dragonriding

Currently, it seems to hide the Encounter Bar when it is visible. The WeakAura works normally when Dominos is disabled, or when using 10.2.36 and older.

**Comment by Tuller** [comment]
Right, so that element should really be controlling the visibility of UIWidgetPowerBarContainer.

If you want to disable Dominos from handling the encounter bar, you can also use something like this:
`/run Dominos.db.profile.modules.encounter = false; ReloadUI()`

**Comment by Darianopolis** [comment]
Dragonriding aura dev here - I use Dominos anyway, so I can just fix the aura to be more compatible :)
Need to push an update for prepatch anyway

**Comment by jungheeMW** [comment]
Thank you both for the quick response and fix!
