### ISSUE TITLE
1x ...ack/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua:20: script ran too long

### ISSUE THREAD

**Issue by 4t0msk** [tullamods/Dominos#871]
1x ...ack/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua:20: script ran too long
[string "@BugSack/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:20: in function <...ack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BugSack/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Dominos/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ceDominos/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
Skipped (In Encounter)

**Comment by Tuller** [comment]
This is likely not Dominos. Can you test with the rest of your addons disabled?
