### ISSUE TITLE
error when mooving my shaman totem bar

### ISSUE THREAD

**Issue by SuperCrishna** [tullamods/Dominos#872]
Date: 2024-07-23 17:27:12
ID: 1
Error occured in: Global
Count: 1
Message: ...Ons/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua line 50:
   attempt to perform arithmetic on local 'l' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:50: ?()
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:168:
      ...Ons/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua:155
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:220:
      ...Ons/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua:212
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:243:
      ...Ons/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua:234
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:299: GetBestAnchor()
   [string "@Interface/AddOns/Dominos/core/frame.lua"]:893: StickToFrame()
   [string "@Interface/AddOns/Dominos/core/frame.lua"]:881: Stick()
   [string "@Interface/AddOns/Dominos_Config/overlay/dragFrame.lua"]:311: OnMovingChanged()
   [string "@Interface/AddOns/Dominos_Config/overlay/dragFrame.lua"]:371: SetMoving()
   [string "@Interface/AddOns/Dominos_Config/overlay/dragFrame.lua"]:293: OnMouseUp()
   [string "@Interface/AddOns/Dominos_Config/overlay/dragFrame.lua"]:172:
      ...nterface/AddOns/Dominos_Config/overlay/dragFrame.lua:172
Locals:
(*temporary) = "LeftButton"
(*temporary) = true
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v4.4.6991 (SwimmingSeadragon)
  AucAdvanced, v4.4.6991 (SwimmingSeadragon)
  AucFilterBasic, v4.4.6991 (SwimmingSeadragon)
  AucScanData, v4.4.6991 (SwimmingSeadragon)
  AucStatHistogram, v4.4.6991 (SwimmingSeadragon)
  AucStatiLevel, v4.4.6991 (SwimmingSeadragon)
  AucStatPurchased, v4.4.6991 (SwimmingSeadragon)
  AucStatSimple, v4.4.6991 (SwimmingSeadragon)
  AucStatStdDev, v4.4.6991 (SwimmingSeadragon)
  AucUtilFixAH, v4.4.6991 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v10.2.31
  BeanCounter, v4.4.6991 (SwimmingSeadragon)
  BlizzMove, vv3.5.33
  Carbonite, vv4.4.0-00016
  CarboniteNotes, vv4.4.0-00016
  CarboniteQuests, vv4.4.0-00016
  DBMCore, v11.0.0
  DBMStatusBarTimers, v11.0.0
  DBMVPVEM, veeae112
  Dominos, v10.2.37
  DominosCast, v
  DominosConfig, v
  DominosProgress, v
  DominosRoll, v
  ElkBuffBars, v2.7.3-211
  Enchantrix, v4.4.6991 (SwimmingSeadragon)
  EnchantrixBarker, v4.4.6991 (SwimmingSeadragon)
  EnhancedFlightMap, v4.1.2-Classic/Cata
  ErrorMonster, vv10.2.6
  Informant, v4.4.6991 (SwimmingSeadragon)
  Masque, v10.2.11
  MasqueDominos, v10.2.10
  MobInfo2, v10.1.24
  OmniCC, v10.2.9
  Pawn, v2.9.13
  Plater, vPlater-v583-Cata
  Prat30, v3.9.55
  Quartz, v3.7.11
  Recount, vv4.4.0a
  RXPGuides, vv4.6.30
  SexyMap, vv10.2.10
  SlideBar, v4.4.6991 (SwimmingSeadragon)
  Stubby, v4.4.6991 (SwimmingSeadragon)
  TipTac, v24.05.26
  TipTacItemRef, v24.05.26
  TipTacTalents, v24.05.26
  TitanAmmo, v8.0.15
  TitanBag, v8.0.15
  TitanClassic, v8.0.15
  TitanClock, v8.0.15
  TitanGold, v8.0.15
  TitanLocation, v8.0.15
  TitanLootType, v8.0.15
  TitanPerformance, v8.0.15
  TitanRegen, v8.0.15
  TitanRepair, v8.0.15
  TitanVolume, v8.0.15
  TitanXP, v8.0.15
  TradeSkillMaster, vv4.14
  VuhDo, v3.170-catac
  VuhDoOptions, v3.170-catac
  WIM, v3.11.2
  ZPerl, v7.2.5
  ZPerlArcaneBar, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib v4.4.0.55639(US) <enUS>
  (ck=7ba)

**Addon Version**
10.2.37-cata

**World of Warcraft Version**
cataclysm classic 4.4.0

**Comment by Kilmatar** [comment]
Actually, this happens on moving of ANY element.

Date: 2024-07-24 18:09:06
ID: 2
Error occured in: Global
Count: 1
Message: ...Ons/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua line 50:
   attempt to perform arithmetic on local 'l' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:50: ?()
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:168:
      ...Ons/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua:155
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:220:
      ...Ons/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua:212
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:243:
      ...Ons/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua:234
   [string "@Interface/AddOns/Dominos/libs/LibFlyPaper-2.0/LibFlyPaper-2.0.lua"]:299: GetBestAnchor()
   [string "@Interface/AddOns/Dominos/core/frame.lua"]:893: StickToFrame()
   [string "@Interface/AddOns/Dominos/core/frame.lua"]:881: Stick()
   [string "@Interface/AddOns/Dominos_Config/overlay/dragFrame.lua"]:311: OnMovingChanged()
   [string "@Interface/AddOns/Dominos_Config/overlay/dragFrame.lua"]:371: SetMoving()
   [string "@Interface/AddOns/Dominos_Config/overlay/dragFrame.lua"]:293: OnMouseUp()
   [string "@Interface/AddOns/Dominos_Config/overlay/dragFrame.lua"]:172:
      ...nterface/AddOns/Dominos_Config/overlay/dragFrame.lua:172
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v4.4.6991 (SwimmingSeadragon)
  WowheadLooter, v40400
  AdvancedInterfaceOptions, v1.9.0-3-gc90c107
  AlreadyKnown, v1.73
  Altoholic, v4.4.005
  AtlasLootClassic, vv4.0.1
  AtlasLootClassicData, vv4.0.1
  AtlasLootClassicDungeonsAndRaids, vv4.0.1
  AucAdvanced, v4.4.6991 (SwimmingSeadragon)
  AucFilterBasic, v4.4.6991 (SwimmingSeadragon)
  AucStatHistogram, v4.4.6991 (SwimmingSeadragon)
  AucStatiLevel, v4.4.6991 (SwimmingSeadragon)
  AucStatPurchased, v4.4.6991 (SwimmingSeadragon)
  AucStatSimple, v4.4.6991 (SwimmingSeadragon)
  AucStatStdDev, v4.4.6991 (SwimmingSeadragon)
  AucUtilFixAH, v4.4.6991 (SwimmingSeadragon)
  BeanCounter, v4.4.6991 (SwimmingSeadragon)
  Bistooltip, v8.09
  ChatBarClassic, v3.4-Cataclysm
  DataStore, v2024.06.26
  DataStoreAchievements, v2024.06.27
  DataStoreAgenda, v2024.06.23
  DataStoreAuctions, v2024.06.23
  DataStoreCharacters, v2024.06.27
  DataStoreContainers, v2024.06.26
  DataStoreCrafts, v2024.06.26
  DataStoreCurrencies, v2024.06.23
  DataStoreInventory, v2024.06.23
  DataStoreMails, v2024.06.23
  DataStoreQuests, v2024.06.26
  DataStoreReputations, v2024.06.24
  DataStoreSpells, v2024.06.23
  DataStoreTalents, v2024.06.27
  DBMCore, v11.0.0-6-ga104c01
  DBMSpellTimers, vr157-2-gbb7767a
  DBMStatusBarTimers, v11.0.0-6-ga104c01
  DBMVPVEM, veeae112
  Decursive, v2.7.20
  Dominos, v10.2.37
  DominosCast, v
  DominosConfig, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v4.4.6991 (SwimmingSeadragon)
  EnchantrixBarker, v4.4.6991 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.5
  GatherMate2, v1.47.5-classic
  GatherMate2GasClouds, v2.4
  HandyNotes, vv1.6.20
  HandyNotesDungeonLocationsClassic, v1.08b
  HandyNotesNPCsClassic, v1.34h
  HandyNotesTravelGuide, vv1.6
  HealBot, v4.4.0.24
  HealBotData, v
  HealBotOptions, v
  HealBotPluginCombatProt, v4.4.0.1
  HealBotPluginManaWatch, v4.4.0.3
  HealBotPluginPerformance, v4.4.0.2
  HealBotPluginThreat, v4.4.0.5
  HealBotTips, v
  HealerProtection, v1.2.30
  Informant, v4.4.6991 (SwimmingSeadragon)
  KrowiAchievementFilter, v74.2
  KrowiAchievementFilterTooltipData, v2.0
  LeatrixMaps, v4.0.16
  LeatrixPlus, v4.0.16
  LibSharedMedia30, v3.0-152
  Pawn, v2.9.13
  Postal, vv4.1.7
  Prat30, v3.9.55
  Questie, v10.3.7
  SexyMap, vv10.2.10
  SpellActivationOverlay, v2.3.0
  Stubby, v4.4.6991 (SwimmingSeadragon)
  TacoTip, v0.4.5
  TellMeWhen, v11.0.0
  TomTom, vv4.0.0-release
  VendorPrice, v1.8.0
  WeakAuras, v5.15.2
  WeakAurasArchive, v5.15.2
  WhereToGatherClassic, v4.0
  WIM, v3.11.1-1-g18c69d4
  ZPerl, v7.2.5
  ZPerlArcaneBar, v
  ZPerlCustomHighlight, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidFrames, v
  ZPerlRaidMonitor, v
  ZPerlTarget, v
  BlizRuntimeLib v4.4.0.55639(EU) <ruRU>
  (ck=aed)

**Comment by Tuller** [comment]
Fixed in the last update. Source was not setting a size on the encounter bar in Classic.
