### ISSUE TITLE
Dragonriding/Skyriding Vigor bar not appearing anymore

### ISSUE THREAD

**Issue by alliepet** [tullamods/Dominos#873]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.
^^ I had just those two running, and I dont have Move Anything. The issue persisted

**Addon Version**
10.2.37-retail

**World of Warcraft Version**
Retail

The issue is that the vigor bar for dragonriding/skyriding does not show up anymore. I actually noticed this the day BEFORE prepatch when I logged in for raid. On my other computer I'm running an older version and logged into prepatch, and I saw my vigor bar fine. On the computer it has an issue on, I disabled Dominos and the vigor bar returned. I didn't see anything in the BugSack for Dominos but I might have missed it.

**Comment by Tuller** [comment]
Is your encounter bar visible?

**Comment by alliepet** [comment]
Yeah, looks like it. I went into Edit Mode and see my Encounter Bar. I am currently mounted up in that screenshot.
![Encounter Bar visible](https://github.com/user-attachments/assets/38cc0fe2-dd57-4e0c-928b-4be489455eef)

**Comment by alliepet** [comment]
The version on my other computer where everything works fine is Dominos 10.2.32-retail

**Comment by Tuller** [comment]
Check the Dominos encounter bar, not the edit mode one

**Comment by alliepet** [comment]
I just updated my dominos after reverting to an older version, and the issue popped up again.

![dominosbars](https://github.com/user-attachments/assets/dc542bc1-2284-4ee7-af79-8b5c3dc735b1)
This is what my edit mode looks like in dominos, I havent changed or moved anything around.

**Comment by sliceandice** [comment]
The main issue I see is that the encounter bar now stays on top of any window that is up. for instance if your mounted and open up your spell book the encounter bar will be on top of the spell book instead of behind it like it used to do.

**Comment by Tuller** [comment]
You might want to adjust the strata in that case.

**Comment by alliepet** [comment]
I feel so dumb now, I just updated Dominos and went to Encounter Bar and chose the Fade IN opacity to 100 and now the skyriding stuff shows. I thought it was the fade out that needed to be 100 lol.

**Comment by MsLestrange** [comment]
I have this same issue, ive tried everything I cannot get it to work. For some reason in EDIT mode, I do have an encounter bar. But in DOMINOS edit mode it just doesn't exist anymore, it's no where to be found. Can anyone help? It is visible in blizzard edit mode and the moment I disable Dominos, the vigor bar shows. Adding screenshot to show Encounter bar is gone on dominos. 
![image](https://github.com/user-attachments/assets/275a9da7-209b-4e2f-97ea-a09cfe1aca70)
