### ISSUE TITLE
Can't disable Spell Overlay Glow (yellow border)

### ISSUE THREAD

**Issue by Aur0r4** [tullamods/Dominos#876]
Hello,

I can't get rid of the Spell-Overlay-Glow even when I disable it in the Dominos configuration. I've disabled all other AddOns to test it, but as you can see on the screenshot, the glowing border effect is still showing.

Also the effect does not fade out after time, I have to mouse over it, to make it disappear.

**Addon Version**
Dominos 11.0.0-retail

**World of Warcraft Version**
Retail

![image](https://github.com/user-attachments/assets/bdcc3d39-fb7e-48c6-a680-f0140f97cc1a)

**Comment by Aur0r4** [comment]
As a workaround I'm using this now:
https://www.curseforge.com/wow/addons/hideactionbaranimations

**Comment by Tuller** [comment]
Confirmed. The root cause is that Blizzard calls UpdateOverlayGlow from its main Update method, which happens irrespective of the events being registered. Dominos will need to hook that method, (or ActionButton_ShowOverlayGlow) and hide if the setting is enabled.

**Comment by Aur0r4** [comment]
Thank you that you have fixed it so fast. This is working as expected now.

Closing ticket as it is resolved.
