### ISSUE TITLE
XP bar doesn't seem to work

### ISSUE THREAD

**Issue by hyperdefined** [tullamods/Dominos#879]
My XP bar seems to be stuck at 0/1 (see at the top). I have only Dominos enabled in the screenshot below. Swapping profiles doesn't seem to fix it.

![screenshot](https://safe.canine.tools/ApyuQ1e29K69.jpg)

If I disable Dominos and look at my real XP bar, I can see my level progress just fine.

![screenshot](https://safe.canine.tools/VkAXOrYFtjtM.png)

**Addon Version**
11.0.1-retail

**World of Warcraft Version**
Retail 11.0.2 (56313)

**Comment by Tuller** [comment]
Have you tried clicking on the display to switch modes?  Based on the coloring, I don’t think you’re currently showing experience

**Comment by hyperdefined** [comment]
That did it, no idea I could swap what it displays on there.
