### ISSUE TITLE
Bars not hiding with Blizzard Vehicle UI

### ISSUE THREAD

**Issue by Aur0r4** [tullamods/Dominos#881]
**Tested with only Dominos and Dominos_Config enabled:**
When Vehicle UI is showing up, Dominos bars are still showing, even if "Show with Override UI" is enabled.
Tested with this Quest:
https://www.wowhead.com/de/quest=82226

**Addon Version**
11.0.1 Retail

**World of Warcraft Version**
Retail

![image](https://github.com/user-attachments/assets/9c92889b-726e-49cc-ac95-024cd07621bd)
![image](https://github.com/user-attachments/assets/487cbe0f-61c9-4155-91af-fcb9ffb867bf)

**Comment by Tuller** [comment]
This should be fixed in the latest version
