### ISSUE TITLE
Undesirable outcome with Skyriding and Action Bar paging

### ISSUE THREAD

**Issue by geomattsson** [tullamods/Dominos#884]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.**
Issue is reproducible with only Dominos and Dominos_Config active

**Addon Version**
Dominos: 11.0.2-retail

**World of Warcraft Version**
Retail

**Issue**
Using shift-scroll for pagination of Action Bar 1 results in undesirable behaviour when in combination with skyriding. I have tried two variants to get my desired outcome, see attached screenshots. However, both ways have drawbacks. Using disabled action pages makes it so that skyriding hijacks Action Bar 1, and I have to perform shift+mousewheel scroll 5 times to reach Action Bar 2. Using alternating pages of Action Bar 1 and Action Bar 2 makes the scrolling correct, but skyriding only hijacks page 1, and not the other pages with Action Bar 1.

**Desired outcome**
1. Each shift+scroll of the mousewheel should switch between Action Bar 1 and Action Bar 2
2. Skyriding shall hijack Action Bar 1

**Suggested fix**
Make it so that when the pages 3-6 are disabled, they are not included in the scrolling. 

![on_sky_mount_disabled](https://github.com/user-attachments/assets/66706659-290f-4c0f-afd0-6de85de5b30e)

![on_sky_mount](https://github.com/user-attachments/assets/bf2cd7e3-f427-4e69-a2d1-2b872529499e)

**Comment by Tuller** [comment]
Silly alternative: you could bind mouse wheel up and down directly to quick page 1 and 2

**Comment by geomattsson** [comment]
I could, except I have Cone of Cold or dragons breath for that. So that would destroy my muscle memory.
From what I can recall, this has worked before with dominos, at least I never noticed this issue before.

**Comment by Tuller** [comment]
Largely, paging on Blizzard's is dependent on which bars you have "enabled" in edit mode. The more you have, the less pages are available for paging. Enabling all of the action bars here should reduce the list that you have available via mouswheel paging:

![image](https://github.com/user-attachments/assets/946128a6-b31b-4d9d-b0ae-965adfe93e2a)

**Comment by geomattsson** [comment]
That is a neat and quite weird workaround. Enabling all action bars there allowed Dominos to only scroll through action bar1 and 2 only, meaning that the skyrding override worked as inteded (at least as intended for me). 

From my point of view this ticket can be closed, I have my desired use-case. Or if you feel like this workaround should not be required you can keep it open.

Thanks a lot for your help! Hope you have a fun expansion!
