### ISSUE TITLE
Dominos moves tooltip from lower-right to lower-left. Cannot move or edit tooltip location

### ISSUE THREAD

**Issue by ghubrebel** [tullamods/Dominos#891]
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.
Dominos moves tooltip from lower-right to lower-left. Cannot move or edit tooltip location
I've tried using Move Anything to counter this, but Dominos reverts to lower-left, right over the chat window, and it's annoying to deal with in that location.

Is there a slash command to move this? Fix for this?

**Addon Version**
You can get this via running `/dominos version` in game
11.0.4, for game version 1.15.4

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.
Classic SOD

**Comment by Tuller** [comment]
Which tooltip in particular are you speaking of?

**Comment by Tuller** [comment]
This should be fixed in the next release.

**Comment by ghubrebel** [comment]
The native tooltip when hovering over nameplates, spells, bags, items in the environment.
Screens below to explain. These normally are left to the lower right, but Dominos places the tooltip to the lower left??

Hoving character shows tooltip in the lower right.

[cid:add63e03-e653-4d94-bb11-93822926d022]

Hovering another character.

[cid:00a69157-7c22-423d-b7e6-5680f13719b9]


________________________________
