### ISSUE TITLE
Dominos bug on SOD - bags not showing when all action bars are enabled in wow config

### ISSUE THREAD

**Issue by JefersonPrad** [tullamods/Dominos#892]
When all action bars are enabled in main wow config, when trying to open my bags, the bags doesn't show up. Then I need to untick the action bars display in wow config, for it to show again. (which is bad because then the bags cover the action bars in the right side of the screen). 
*This started happening only with the last Dominos version.*

Edit: First this was happening only in my druid when I was on Bear Form, but this also is happening with my hunter.

**Addon Version**
11.0.4-classic

**World of Warcraft Version**
SOD

**Comment by brookesb91** [comment]
![WoWScrnShot_093024_194021](https://github.com/user-attachments/assets/2e9c94ef-b251-4b7d-b763-50315e68d307)

Confirmed. If you enable all action bars and reload, the bags stop displaying and the tooltip has moved. Fixed by unchecking the additional action bars.
