### ISSUE TITLE
Show Spell Animations broken

### ISSUE THREAD

**Issue by Aarali** [tullamods/Dominos#896]
Show Spell Animations doesn't hide the spell animations introduced in patch 10.1.5 anymore as of today. Toggling it on and off only temporarily works until you get in combat again then the spell animations appear despite the setting being unchecked. Running Dominos v.11.0.5 on the Retail Version of WoW

**Comment by Aur0r4** [comment]
If anyone else is having this issue, see my solution here:
https://github.com/tullamods/Dominos/issues/897
